### ISSUE TITLE
Add discovered catalog refresh functionality

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#1000]
See #996 for context

In the scheduler, add a process which runs discovery then performs one of the following actions:

* If the catalog was amended: move the connection to a new state DEFUNCT_CATALOG_AMENDED in the backend. Connections whose source is in this state do not sync data.
* If the catalog has expanded/contracted and not amended, we update the source's catalog selection by adding any new streams/fields without selecting them. If any streams/fields were removed by the contraction, remove them from the catalog (even if they were selected).

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368198267421) by [Unito](https://www.unito.io)

**Comment by ChristopheDuong** [comment]
Small question: to detect that catalogs changed (amended/expanded or contracted), are they going to be persisted/stored somewhere? if yes, where?

**Comment by ChristopheDuong** [comment]
As a side note for the future, it would be really great, if we can send notifications (slack, email, etc) when such changes happen to the catalogs...

So that user can decide to go select or un-select new fields/streams or be aware that the Analytics pipelines downstream may get affected (if streams/fields were removed, then some expected data could stop being replicated/refreshed).

**Comment by sherifnada** [comment]
@ChristopheDuong love the notifications idea! the infrastructure for that would also get us closer to having an "audit log" of schema changes for debuggability

FWIW this issue is getting bumped out of the next release, see #996 for more context

**Comment by evantahler** [comment]
Closing in favor of the epic https://github.com/airbytehq/airbyte/issues/14278
