### ISSUE TITLE
Expose detailed Attempt stats and failure information in the UI

### ISSUE THREAD

**Issue by pmossman** [airbytehq/airbyte#10110]
## Overview
The Airbyte API now returns new fields on the `AttemptRead` containing detailed information about sync stats and failures.

These new fields are:
- `AttemptRead.totalStats`
- `AttemptRead.syncStats`
- `AttemptRead.failureSummary`

In airbyte-api's `config.yaml` spec, you can now find the following types:

---

#### AttemptStats
`AttemptStats` replaces `recordsSynced` and `bytesSynced` with better-named `recordsEmitted` and `bytesEmitted`, and also introduces `recordsCommitted`, a crucial stat for users to understand the data that was actually persisted in the destination.

- The `AttemptRead.totalStats` field uses this type.

<details>
<summary>AttemptStats schema</summary>
<pre>
AttemptStats:
      type: object
      properties:
        recordsEmitted:
          type: integer
          format: int64
        bytesEmitted:
          type: integer
          format: int64
        stateMessagesEmitted:
          type: integer
          format: int64
        recordsCommitted:
          type: integer
          format: int64
</pre>
</details>

---

#### AttemptStreamStats
`AttemptStreamStats` contains `AttemptStats` for each individual stream in the sync.

- The `AttemptRead.syncStats` field uses this type.

<details>
<summary>AttemptStreamStats schema</summary>
<pre>
AttemptStreamStats:
      type: object
      required:
        - streamName
        - stats
      properties:
        streamName:
          type: string
        stats:
          $ref: "#/components/schemas/AttemptStats"
</pre>
</details>

---

#### AttemptFailureSummary
`AttemptFailureSummary` includes information about any failures that occurred over the course of the sync. It includes a list of `failures`, and a `partialSuccess` boolean that indicates whether or not any records were committed to the destination before the stream failed.

- The `AttemptRead.failureSummary` field uses this type.

<details>
<summary>AttemptFailureSummary schema</summary>
<pre>
AttemptFailureSummary:
      type: object
      required:
        - failures
      properties:
        failures:
          type: array
          items:
            $ref: "#/components/schemas/AttemptFailureReason"
        partialSuccess:
          description: True if the number of committed records for this attempt was greater than 0. False if 0 records were committed. If not set, the number of committed records is unknown.
          type: boolean
    AttemptFailureReason:
      type: object
      required:
        - timestamp
      properties:
        failureOrigin:
          $ref: "#/components/schemas/AttemptFailureOrigin"
        failureType:
          $ref: "#/components/schemas/AttemptFailureType"
        externalMessage:
          type: string
        stacktrace:
          type: string
        retryable:
          description: True if it is known that retrying may succeed, e.g. for a transient failure. False if it is known that a retry will not succeed, e.g. for a configuration issue. If not set, retryable status is not well known.
          type: boolean
        timestamp:
          type: integer
          format: int64
    AttemptFailureOrigin:
      description: Indicates where the error originated. If not set, the origin of error is not well known.
      type: string
      enum:
        - source
        - destination
        - replication
        - persistence
        - normalization
        - dbt
    AttemptFailureType:
      description: Categorizes well known errors into types for programmatic handling. If not set, the type of error is not well known.
      type: string
      enum:
        - config_error
        - system_error
        - manual_cancellation
</pre>     
</details>

---

## Frontend Changes

We want users to benefit from the new Attempt information described above. Modifications will take place in the Sync History view. I put together a very rough idea of what these changes could look like:

![image](https://user-images.githubusercontent.com/7798112/152579707-7c0cdd0c-10cf-4fd6-9857-b9eebc7fb449.png)

**Comment by cgardens** [comment]
I think the design work for the per-stream counts may be underspecified. I tried to mock something up [here](https://www.figma.com/file/etaOkOsnXMoKwbfhCD71kw/Web-app?node-id=32209%3A146809) and what I did is bad enough that I think we should get the designer to look at.

I think adding failure reason and partial success is somewhat straight forward and we could fast track. It would be very high value to get it out quickly. I'm going to split that into a [separate issue](https://github.com/airbytehq/airbyte/issues/10110) here for Harshith to tackle, and then we can have the rest of this go through design.

**Comment by cgardens** [comment]
Context:
* committed record counts - previously a job only exposed a single record count. this count was misleading because it only tells you how many records we pulled from the source ("emitted records"). we now also can expose "committed records" which is the number of records taht we actually save in the destination. these numbers are different when there is a partial success. a partial success is when a non-zero number of records make it to the destination. we cannot always calculate the committed records, so in cases where we can't, we need to degrade gracefully, either hide it or say "unavailable". this is also tracked at the attempt level. this is a weird concept and so we want to have a link / tooltip to our docs for users to go to understand it.
* failure reason - when attempts fail we want to expose additional information about why they failed. the two things we want to expose now are failure origin, which tells us if the failure happened in : source, destination, platform, or unknown. when possible we will also expose a human readable error message. this won't always be available.
* per-stream record counts - previously that we only exposed the total record count for a replication job. so it was the total records replicated across all tables. now we can can break it out at the stream level as well, and we'd like a way to expose that per attempt.
* partial success - i explained the concept above. but basically in addition to succeeded, failed, and cancelled, we want to expose partial success to a user. it's a kinda weird concept, so we should allow a tooltip / link to our docs. in terms of severity it is somewhere between green and red.

Mock ups:
[job list](https://www.figma.com/file/etaOkOsnXMoKwbfhCD71kw/Web-app?node-id=32218%3A154643)
[job expanded success](https://www.figma.com/file/etaOkOsnXMoKwbfhCD71kw/Web-app?node-id=32218%3A156577)
[job expanded failure](https://www.figma.com/file/etaOkOsnXMoKwbfhCD71kw/Web-app?node-id=32217%3A147755)
[job expanded partial success](https://www.figma.com/file/etaOkOsnXMoKwbfhCD71kw/Web-app?node-id=32218%3A155515)
[record counts expanded failure](https://www.figma.com/file/etaOkOsnXMoKwbfhCD71kw/Web-app?node-id=32253%3A149794)
[record counts expanded partial success](https://www.figma.com/file/etaOkOsnXMoKwbfhCD71kw/Web-app?node-id=32253%3A150728)

@timroes I put all the context and mocks into this issue. Do you think it is clear enough to be worked on. Since we have all of this info in the UI already, this one is _not_ the highest priority. It will present the info much better than we are presenting it already 😄

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by edmundito** [comment]
@andyjih Can you review the mocks and follow up with @timroes ?

**Comment by andyjih** [comment]
@edmundito @timroes Took a look at the designs. Overall looks good. I have a few nits that I commented in the Figma for Nico. None of those are blocking work from starting though! 🙌🏽

**Comment by edmundito** [comment]
@andyjih this issue has been open for a while. Could you re-review and see if this is something that is ready to implement?

**Comment by evantahler** [comment]
We've added failure summaries to the UI: https://github.com/airbytehq/airbyte/pull/12896
We've added additional summary data to the logs: https://github.com/airbytehq/airbyte/pull/16314 

I'll close this and we can re-visit each section of the UI later
