### ISSUE TITLE
Source Salesforce: support for custom domain

### ISSUE THREAD

**Issue by harshithmullapudi** [airbytehq/airbyte#10236]
## Tell us about the problem you're trying to solve
Need custom domain support for salesforce source connector
https://airbytehq-team.slack.com/archives/C01MFR03D5W/p1643798513607949

**Comment by duncanphillips** [comment]
I originally ran into this problem, but it seems to have been my fault. I think I was using a refresh token instead of a an access key, or something to that effect. Once all the keys were correct, the login returned the url for our custom domain and the sync worked as expected. Perhaps a suggestion here would be for an improvement to the docs on how custom domains work for the connector, and how to get the right keys required (as this was not obvious).

**Comment by ihommani** [comment]
Hi @duncanphillips, I think I get the same need than yours. However looking at the source code of the salesforce connector I see not way to override the login URL used with the refresh token. It's hard coded: https://github.com/airbytehq/airbyte/blob/94e3e0ea27ab84c13d1283d1078f2f7735285ae5/airbyte-integrations/connectors/source-salesforce/source_salesforce/api.py#L266
 
Did you really managed to set a custom saleforce domain in the connector ? 

Thx!
