### ISSUE TITLE
Documentation link: Support both domains: OLD `docs.airbyte.io`, NEW `docs.airbyte.com`

### ISSUE THREAD

**Issue by grubberr** [airbytehq/airbyte#10412]
## Current Behavior
Docs pre-loading feature works only for OLD urls which starts with `docs.airbyte.io` domain.
`https://docs.airbyte.io/integrations/sources/zendesk_sunshine`

but for NEW correct domain `docs.airbyte.com` it fails like on picture

<img width="862" alt="Screenshot 2022-02-17 at 18 17 25" src="https://user-images.githubusercontent.com/195743/154523653-39ab058a-8c19-40d4-a6c6-441536439b1f.png">

it happens because we support only OLD domain
https://github.com/airbytehq/airbyte/blob/fe1eb8dd003067b7ce617ec6dd367a6f2763791c/airbyte-webapp/src/hooks/services/useDocumentation.ts#L12

## Expected Behavior
I think we need to support both domains: `docs.airbyte.io, docs.airbyte.com` until all doc urls updated.

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by timroes** [comment]
Can someone explain me what's the difference between those two domains? Which one is the one we're using for actually publishing docs?

**Comment by jrhizor** [comment]
We redirect from .io to .com now. However, the issue here is that we're packaging the doc .md files into the webapp build, but referencing their file paths based off of the `documentationUrl` provided in the connector definition. 

Some of the more recent ones are specified with .com:
```
airbyte-integrations/connectors/source-quickbooks-singer/source_quickbooks_singer/spec.json
2:  "documentationUrl": "https://docs.airbyte.com/integrations/sources/quickbooks",
```

While others use .io:
```
airbyte-integrations/connectors/source-tiktok-marketing/integration_tests/spec.json
2:  "documentationUrl": "https://docs.airbyte.io/integrations/sources/tiktok-marketing",
```

Others still use invalid domains:
```
airbyte-integrations/connectors/source-azure-table/source_azure_table/spec.json
2:  "documentationUrl": "https://docsurl.com",
```

or helpful but non-internal domains (not related to the md files at all):
```
airbyte-integrations/connectors/source-shortio/source_shortio/spec.json
2:  "documentationUrl": "https://developers.short.io/reference",
```

So I suppose for some of these you'll need to reach out to the connector team to improve these. However, I agree with @grubberr that we could fix the hacky mapping here to accept either prefix.

**Comment by timroes** [comment]
I've created https://github.com/airbytehq/airbyte/issues/10622 for the connectors team to fix all invalid scaffolded domains.
