### ISSUE TITLE
Extract (base) sizes into theme

### ISSUE THREAD

**Issue by timroes** [airbytehq/airbyte#10457]
We currently use a lot of styles and specifically pixel sizes hard-coded in styled component all around the UI codebase. This leads us to e.g. use all font-sizes between 8px and 22px (excluding 19px) somewhere in the code base. Similar for padding/margins. We should extract some common font sizes e.g. using t-shirt sizes (S, M, L, etc.) into the theme and limit usage to them.

For padding/margin we should define some common base shirt-sizes as well and make sure we're using those or multiple of those for the padding/margin.

**Comment by timroes** [comment]
@edmundito could we try to handle font-size extraction into variables soonish? While we've migrated to SASS, we already introduced many arbitrary font-size parameters in individual components and we have nearly all font-sizes between 10px and 22px used somewhere. I think we should try to prioritize making sure we're using a set of defined font-sizes and align all components to them.

**Comment by josephkmh** [comment]
I'd like to add here that we should not be using `px` values for font sizes, rather `rem`. `px` values for font sizes is an accessibility issue because they do not resize according to browser preferences. Should be a pretty easy fix, but it would make sense to do while extracting all font sizes into variables.

**Comment by josephkmh** [comment]
Refining notes:
- The CSS has inconsistent sizes but they should be matching the CSS sizes
- We should create CSS variables for text sizes so that can be applied to design cases where the text components should not match
- Update the PX to rem, calculate based on: https://nekocalc.com/px-to-rem-converter
- Replace all equivalent px values to SASS variables (e.g. any instance of `font-size: 14px;` becomes `font-size: fontSizes.$size-lg`)

Second Step:
- Go through codebase and adjust any font sizes that do _not_ match our font size variables. If changing the font size breaks the design, consult with @Upmitt 
- Add stylelint rule to prevent explicit px values for font sizes (variables should be used instead)
