### ISSUE TITLE
Create a notion of streams which are "selected by default" 

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#10872]
## Tell us about the problem you're trying to solve
A connector like JIRA may have 100 streams. Most users typically care about 20 of those. But since all streams are selected by default, a user has to specifically opt out of the streams they don't care about. Since the path of least resistance is do nothing/keep all streams selected, user syncs often end up with way more data than they care about or need. 

The downside for this is: 
1. Increased sync times, sometimes significantly e.g: nested REST resources which may take a long time may be unnecessarily slowing down the sync.
2. More API quota usage for the user

## Describe the solution you’d like
When setting up a connection, expose a way to display the streams which are included by default in the sync, and have all others deselected. 

Thus, when a user goes to setup a connector in a connection, some streams are selected by default and others need to be opted into by the user. 

This could be implemented at the protocol/connector level (e.g adding a `selected_by_default` keyword in the catalog output from discovery) or it could be at the server level. Not sure

**Comment by evantahler** [comment]
From https://github.com/airbytehq/airbyte/issues/21418

Not all streams are created equal.  Especially in API sources, the performance and likelihood of being consumed varies dramatically between sources.  

Take `soruce-github` for example (inspired by [this](https://github.com/airbytehq/oncall/issues/1303#issuecomment-1381772903) OC issue).  The average user probably wants the "repos", "issues" and "pull_requests" streams.  However, there are over 20 additional streams the connector offers, which is great, but in order to provide a fast and simple first sync, we probably shouldn't enable them all by default.  In this case, due to limitations in the Github API, we need to make a network request for every item in the "issue_reactions" stream, which rapidly consumes the available rate limit, throttling all other streams.

Proposal:
* Modify the result of the DISCOVER command such that streams can provide a boolean "suggested" property.  
* In the UI, if suggested is true, pre-check it.  if suggested is false, leave it unchecked.
* Of course, users can change their stream selection like they can today.
