### ISSUE TITLE
Notify users of auto-disabled connections

### ISSUE THREAD

**Issue by terencecho** [airbytehq/airbyte#10929]
## Tell us about the problem you're trying to solve
With the additional feature of adding an option to auto-disable failing connections from this [issue](https://github.com/airbytehq/airbyte/issues/9715), we want to clearly define how the notification of a connection being auto-disabled should be surfaced.

For example, do we want an email or a pop-up? Do we want to confirm that the user has acknowledged this automated disablement of a connection? etc.

**Comment by cgardens** [comment]
we do _not_ currently have a way to send emails to users as far as i'm aware. @davinchia am I wrong on this? do we have sendgrid set up somewhere?

**Comment by cgardens** [comment]
@terencecho if you take a look at `NotificationClient`, we have some stuff in place to push information to users. The idea here was that a user could plug in different types of notification clients. Right now we just support slack, but adding email makes sense (for cloud). 

Sending emails from OSS is hard because it requires having the user set up a mail server or using ours (which is very dangerous). We should skip supporting it in OSS for now.

Based on Davin's response about our email setup, you could set up an email `NotificationClient` and we could use that to send this ifnormation.

**Comment by michel-tricot** [comment]
@nataliekwong should probably be involved in that conversation

**Comment by nataliekwong** [comment]
We can use customer.io as a way to send emails to Cloud users, as all Cloud users are already in customer.io today.  I agree on not sending emails to OSS users. Here is what I sent Terence, in a follow-up message:
> As far as implementation, the in-app message would need to be done within product. For the emails, we can use Segment to generate calls that trigger emails (we can use our email tool [customer.io](http://customer.io/) for the actual sending of the emails).

For the initial implementation, I suggest we send this as a transactional email as it's a product-triggered notification and should not be able to be opted out from. We could allow for opt-out of connector turnoff notifications in the future (as you suggested, a toggle in the UI), but to start it would be mandatory. 

Outside of this particular issue, I have gotten a few requests for an email notification feature as users don't want to go through the hurdle of setting up a webhook. If we were to develop that feature, we could continue to use customer.io to send those emails, or move all product-triggered emails to Sendgrid. Ideally we consolidate so that we have clear delineations on what kinds of emails are being sent and from where.

**Comment by davinchia** [comment]
We do use Sendgrid today to send the new user invite and workspace invite emails. See https://github.com/airbytehq/airbyte-cloud/blob/master/cloud-server/src/main/java/io/airbyte/cloud/server/email/Sendgrid.java. Log in is in lastpass.

I don't have an opinion on customer.io vs Sendgrid.

**Comment by terencecho** [comment]
I don't have enough context to have an opinion between customer.io vs sendgrid. But I think it makes sense to create an email implementation of `NotificationClient` and link it to either customer.io or sendgrid, which could be re-used for other email notifications for the future.

**Comment by cgardens** [comment]
Let's use customer.io then. Better to consolidate towards a single tool. Sounds like we have a clear owner of customer.io and buy in from GTM. Sendgrid is a bit of an orphan in our stack right now.

**Comment by terencecho** [comment]
Going to leave this issue open until the feature flag is turned on in cloud

**Comment by terencecho** [comment]
This has been deployed to production as of 5/2/22.
