### ISSUE TITLE
Source Amplitude Feature/Bug Hub

### ISSUE THREAD

**Issue by avaidyanatha** [airbytehq/airbyte#10942]
The centralized hub for all feature requests and bugs associated with the [Amplitude Source](https://docs.airbyte.com/integrations/sources/amplitude) has been moved to the [Maintainer Github Project](https://github.com/orgs/airbytehq/projects/13/views/14).

The table of issues that was previously on this issue is now deprecated but is left in the collapsed section below.
<details>
  <summary>Deprecated Issue Hub</summary>

**Feature Checklist**

| Feature |  Comments | Related Issue(s) | Related PR | Claimed By | Merged | Bounty |
|---|---|---|---|---|---|---|
| Full Stream Coverage | Triage necessary. | | | | ❓ | - |
| Incremental Sync | | | | | ✔️ | - |
| Pagination | | | | | ❌ | $200 |
| Test Coverage | [Unit Test Files](https://github.com/airbytehq/airbyte/tree/master/airbyte-integrations/connectors/source-amplitude/unit_tests) | | | | ✔️ | - |
| Sandbox Account | | | | | ✔️ | - |
| Docs Formatting | This connector doc does not follow our new standard format. | | | | ❌ | $50 |
| Getting Started Guide | | | | | ❌ | $100 |

**Bug Checklist**

| Bug Description | Other Notes | Related Issue(s) | Related PR | Claimed By | Merged | Bounty |
|---|---|---|---|---|---|---|
| Reduce duplication of User IDs to Emails |  | [Issue](https://github.com/airbytehq/airbyte/issues/4409) | | | ❌ | $100 |
| Add better error response messages to file size errors |  | [Issue](https://github.com/airbytehq/airbyte/issues/7900) | | | ❌ | $100 |
</details>

**Comment by itaseskii** [comment]
Hey @avaidyanatha I have done some analysis of what can and can't be done from the above requirements and these are my findings.

1. **Incremental Sync:**
* Cohorts -> Not supported but contains 'lastMod' and 'lastComputed' properties which most likely can be used for incremental sync
* Annotations -> Not supported most likely because the 'date' field in the response is the date to which the annotation was added and not when the annotation was created or updated.
2. **Pagination:**
* None of the implemented streams support pagination which means that nothing can be done here

**Comment by itaseskii** [comment]
I have claimed the issue for adding better error response messages to file size errors

**Comment by aharelick** [comment]
Closing this issue as this will all be managed by the [Maintainer Github Project](https://github.com/orgs/airbytehq/projects/13).
