### ISSUE TITLE
Generalize configProvider

### ISSUE THREAD

**Issue by timroes** [airbytehq/airbyte#10955]
Currently the config provider in the FE does mix it's configuration from build time environment variables (`REACT_APP_`), variables assigned to `window` and a file loaded from `config.json`. 

We want to narrow this down to two different providers with different priority, i.e. `window` or `config.json` should exist and be able to overwrite the build time environment variables. The code should be generic to be able to overwrite any part of the configuration without requiring hard-coded references for each individual variable.

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by timroes** [comment]
After some brainstorming with Teal, Topher and Davin, we decided to change how we're handling environment variables. In the future we only want to except all environment variables via build time environment variables (i.e. `REACT_APP_...`). We'd instead build the code for each staging/dev environment separately (we anyway do that for the docker images). Therefore we'll remove any configuration via the `window` object or (the not yet enabled) `config.json` file. This will significantly decrease the complexity of our configProviders code and offload the efforts to the build time.

This will require https://github.com/airbytehq/airbyte/issues/15648 to be solved, since the demo instance at the moment still requires to set the `IS_DEMO` variable on `window`.

**Comment by josephkmh** [comment]
Adding the description from !21297:

ConfigProvider is used to provide app-wide configuration - largely environment variables - in a React context. The current implementation is abstracted into different layers of “config providers”, which makes it hard to reason about and confusing to extend:

There are many config providers that have overlapping config values. They overwrite each others’ configurations from left to right:
OSS: defaultConfigProvider > envConfigProvider > windowConfigProvider
Cloud: defaultConfig > cloudEnvConfigProvider > cloudWindowConfigProvider > envConfigProvider > windowConfigProvider
Configuration resolves asynchronously to support fileConfigProvider, although it is currently not used
This can be improved:

fileConfigProvider can be removed, since it is not used (it’s also the only async config provider)
All config can be contained in a single synchronous config object
We can still use injected window properties via nginx for the interim
Although this means we could get rid of the ConfigProvider React context entirely, we should keep it around to avoid refactoring its consumers.
