### ISSUE TITLE
Retry failed build steps.

### ISSUE THREAD

**Issue by davinchia** [airbytehq/airbyte#10958]
## Tell us about the problem you're trying to solve
An easy way to get over transient errors is to retry steps where we know this happens.

Steps where this happens in:
* all kubernetes test builds
* frontend tests

### Retries for flaky e2e tests
- [x] https://github.com/airbytehq/airbyte/pull/11816
- [x] https://github.com/airbytehq/airbyte/pull/11818

### Followup
- [ ] https://github.com/airbytehq/airbyte/issues/11819

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by supertopher** [comment]
## Supporting material for this project:

[GitHub Actions code in airbyte](https://github.com/airbytehq/airbyte/tree/master/.github/actions)
[Github recent actions to scan for transient errors in airbyte](https://github.com/airbytehq/airbyte/actions)

* It may be helpful to talk to frequent contributors to understand what errors are transient and which failures are real.  
* You may even game this system by finding a known good branch, making an empty commit and looking for errors in that.  
* Remember that the pipelines we are most concerned for in OSS are frontend tests and the Kubernetes test builds 

should you identify a common component of failure that could be addressed more directly than a retry loop please create a task for that action or discuss it with the team

**Comment by git-phu** [comment]
Some quick notes:
- Retry logic at the step level is not a feature out of the box for github actions, though a simplistic approach could be to write our run commands to try multiple times like [this example](https://github.community/t/how-to-retry-a-failed-step-in-github-actions-workflow/125880/4)
- someone has written a github action specifically for retrying steps [here](https://github.com/marketplace/actions/retry-step)
    - for example, using this action we could wrap the run command for frontend tests here https://github.com/airbytehq/airbyte/blob/77eca9f63029b9ebc58d330153a9c9e7bc65cb50/.github/workflows/gradle.yml#L407 with retry logic on failure
    - example:
      ```yaml
      uses: nick-fields/retry@v2
      with:
        timeout_seconds: 15
        max_attempts: 3
        retry_on: error
      command: ./tools/bin/e2e_test.sh 
      ```

**Comment by davinchia** [comment]
I like using the already written action so we avoid reinventing the wheel.

**Comment by git-phu** [comment]
Currently trying out the github action for retrying steps [here](https://github.com/airbytehq/airbyte/compare/peter/test-new-actions?expand=1)

Looks like it doesn't play well with bash scripts that have a `trap`, but it otherwise seems to work as advertised.  Will continue testing this out.

**Comment by git-phu** [comment]
Trying out Cypress retries [here](https://github.com/airbytehq/airbyte/compare/peter/test-test-retries?expand=1)

I think I prefer this to simply using the retry step github action.
It's quite easy to configure, and with retries enabled the Cypress dashboard also shows you which tests are flaky (require more than one try to pass).
It also currently adds a check to the build that will fail if there are any flaky tests (but this can be disabled through the Cypress dashboard project settings).

Only caveat is that if we are modifying any kind of state per test run and not also cleaning it up per run, each retry attempt won't be starting from a clean state.

**Comment by git-phu** [comment]
Ideally I'd like to:
- modify the existing frontend/kube tests steps to pull out the setup steps (e.x. docker-compose up) from the gradle task running the tests
- use retry steps for the setup steps
- implement test retries through cypress/junit

This way we can retry the setup steps separately from retrying flaky tests, since both can transiently fail.  I'd prefer this to retrying the whole step because right now some of these steps can take close to 30 minutes even on a successful run, so retrying the whole step would make the full pipeline extremely slow if if it ultimately succeeds.

Also I'm not too interested in trying to get retry steps to work with `trap`, so I'd rather split the existing scripts into different steps. 😄 

The downside with this approach is that currently the `bin` scripts can be run both locally and in github actions, but splitting up the script in github actions means we can't run the same single script in both scenarios anymore.  
However, it's not clear how useful these scripts actually are for local testing (I asked @jrhizor and it sounds like in practice you'd want to spin up the airbyte components and run the tests separately so that you can iterate on changes and rerun the tests, instead of trying to do everything in one monolithic script).

**Comment by davinchia** [comment]
Agree we should push retries into the native layer as much as possible. @timroes do you have any preferences on setting retries on the frontend. Should we use Cypress?

@git-phu iirc, most of the retry failures on the kube integration tests are test related. On the set up side, I think the only failure I've seen is the images failing to load into KinD. That feels like something we can deterministically get rid of by switching to Minikube. Because of this, I think we want to put retries on the tests only for now.

As for whether we want to do retries over the entire step vs the individual test - I think the former is more convenient, but the latter is more visible and will force us to deal with each transient test as they come up, which is a good thing. @jrhizor what do you think?

**Comment by pmossman** [comment]
TODO: implement individual retries, or create follow up tickets to split out that work

**Comment by git-phu** [comment]
@davinchia here's an example of a test run that fails because the `Run End-to-end Acceptance Tests` step is waiting forever for the health api to return healthy after docker-compose up
https://github.com/airbytehq/airbyte/runs/5858262127?check_suite_focus=true

This kind of problem wouldn't be addressed by retries on the test level.
I'll split out a separate ticket for dealing with the setup steps and leave this ticket for pushing retries into the native layer.

**Comment by davinchia** [comment]
Nice catch. Thanks @git-phu 

Should we correct that instead of retrying? I said the same thing in the PR - I don't want us to be too reliant on retrying. Or do you think we should still have this on the set up phase?

**Comment by git-phu** [comment]
Good point @davinchia , in general I think of retries as a bandaid for stuff that doesn't work reliably, so I do think it's worth fixing the setup steps so that they do not sometimes fail. I haven't looked into why these are failing though, so I currently don't really know how difficult/possible it is to fix. Retries on the other hand are just a generic bandaid until we get around to investigating this more deeply.

**Comment by timroes** [comment]
> Agree we should push retries into the native layer as much as possible. @timroes do you have any preferences on setting retries on the frontend. Should we use Cypress?

Yes, I think having it within cypress (as now has already been done) is the best approach. I don't think we need to enable retry on the FE build in general, since I have so far not seen any flakyness in the unit tests (and would also find that rather rare) that are included in the build step. Thus I would rather suggest not retrying the whole FE build step.

**Comment by davinchia** [comment]
@git-phu sounds good! Should we create an issue to make sure we don't forget to come back and fix before we close this? Apologies if you already mentioned and I forgot.

**Comment by git-phu** [comment]
@davinchia yup, I created https://github.com/airbytehq/airbyte/issues/11819 for retrying certain setup steps. 
 Currently I'm thinking of adding retries for just the `docker-compose up` and the `kind` plus `kubectl apply` steps.  I haven't seen other setup related steps fail randomly.

**Comment by davinchia** [comment]
Thanks @git-phu !
