### ISSUE TITLE
Source Mixpanel Feature/Bug Hub

### ISSUE THREAD

**Issue by avaidyanatha** [airbytehq/airbyte#11008]
The centralized hub for all feature requests and bugs associated with the [Mixpanel Source](https://docs.airbyte.com/integrations/sources/mixpanel) has been moved to the [Maintainer Github Project](https://github.com/orgs/airbytehq/projects/13/views/17).

The table of issues that was previously on this issue is now deprecated but is left in the collapsed section below.
<details>
  <summary>Deprecated Issue Hub</summary>

**Feature Checklist**

| Feature |  Comments | Related Issue(s) | Related PR | Claimed By | Merged | Bounty |
|---|---|---|---|---|---|---|
| Full Stream Coverage | All endpoints have associated streams. | | | | ✔️ | - |
| Incremental Sync| Not currently implemented for the `Engage`, `Annotations`, `Cohorts` and `Cohort Members` streams | | [PR](https://github.com/airbytehq/airbyte/pull/11501) | @itaseskii | ❌ | $300 |
| Pagination | | | | | ❌ | $200 |
| Test Coverage | [Unit Test Files](https://github.com/airbytehq/airbyte/tree/master/airbyte-integrations/connectors/source-mixpanel/unit_tests) - Some testing, but more is likely required. | | | @itaseskii | ❌ | $300 |
| Sandbox Account | | | | | ✔️ | - |
| Docs Formatting | This connector doc does not follow our new standard format. | | | | ❌ | $50 |
| Getting Started Guide | Very stubbed currently. | | | | ❌ | $100 |

**Bug Checklist**

| Bug Description | Other Notes | Related Issue(s) | Related PR | Claimed By | Merged | Bounty |
|---|---|---|---|---|---|---|
| Sync failure with high volume |  | [Issue](https://github.com/airbytehq/airbyte/issues/8427) | | | ❌ | $200 |
| Basic normalization fails with duplicate field names | | [Issue](https://github.com/airbytehq/airbyte/issues/5355) | | | ❌ | $200 |
| 429 Status Code is not handled |  | [Issue](https://github.com/airbytehq/airbyte/issues/9410) | | | ❌ | $200 |
</details>

**Comment by itaseskii** [comment]
Hey @avaidyanatha I have done some analysis of what can and can't be done from the above requirements and these are my findings.

1. **Incremental Sync:**

- **Engage** -> Investigate if 'created' property is present by default, if it is custom property stream will require user-defined cursor. ***might require dynamic schema creation for custom user defined properties**
- **Annotations** -> Date field present but connector note says 'annotation date - is the date for which annotation was added, this is not the date when annotation was added That's why stream does not support incremental sync.'
- **Cohorts** -> contains 'created' field which can be used for incremental sync
- **Cohorts Members** ->  Investigate if 'created' property is present by default, if it is custom property stream will require user-defined cursor. ***might require dynamic schema creation for custom user defined properties**

2. **Pagination**:

- From already present streams only Engage and Cohort Members support pagination which already have it implemented and leaves nothing to be done here

3. **Full Stream Coverage:**
- Missing: /insights, /retention (requires from to), /schemas, /pipeline, /connectors and maybe more

**Comment by itaseskii** [comment]
Hey @avaidyanatha I would like to tackle the **_Incremental Sync_** issue next. I have already written an explanation in the comment above on how I am planning to add incremental sync for each of the streams.

**Comment by itaseskii** [comment]
I have claimed the **_429 Status Code is not handled_** issue

**Comment by aharelick** [comment]
Closing this issue as this will all be managed by the [Maintainer Github Project](https://github.com/orgs/airbytehq/projects/13).
