### ISSUE TITLE
[EPIC] Destination-Bigquery: Data type gaps: Numeric, Bignumeric, Bytes, etc

### ISSUE THREAD

**Issue by etsybaev** [airbytehq/airbyte#11090]
Perform final review. Make sure existing types are mapped correct and add support for missed data-types:

<b style="font-weight:normal;" id="docs-internal-guid-bdd7babb-7fff-f3a2-d6cb-b418a21b53d5"><div dir="ltr" style="margin-left:-48pt;" align="left">

BigQuery type | Airbyte Type
-- | --
BOOLEAN | BOOLEAN
INTEGER | INTEGER (INT64)
FLOAT | NUMBER (FLOAT64)
NUMERIC | -
BIGNUMERIC | -
DATE | DATE
TIMESTAMP | TIMESTAMP
DATETIME | DATETIME
STRING | STRING
BYTES | -
ARRAY | ARRAY
RECORD | OBJECT

</div></b>

**Comment by misteryeo** [comment]
**Issue was linked to Harvestr Discovery:**  [Improve DB/DW data mappings](https://app.harvestr.io/components/0/list/wOUds4X9B)

**Comment by yurii-bidiuk** [comment]
I made some research to verify mapping Airbyte type to destination-bigquery type. The result of this research is quite different from the table above:
1. The Airbyte OBJECT type is mapped as STRING on the BigQuery side. 
2. All date-time fields are mapped as TIMESTAMP. 
 
Airbyte type | BigQuery type
-- | --
DATE | DATE 
STRING (BASE64) | STRING   
NUMBER | FLOAT   
OBJECT | STRING   
STRING | STRING  
BOOLEAN | BOOLEAN  
INTEGER | INTEGER  
STRING (BIG_NUMBER) | STRING  
STRING (BIG_INTEGER) | STRING  
ARRAY | REPEATED
STRING (TIMESTAMP_WITH_TIMEZONE) | TIMESTAMP   
STRING (TIMESTAMP_WITHOUT_TIMEZONE) | TIMESTAMP

**Comment by grishick** [comment]
@yurii-bidiuk I don't think it is OK that some types are mapped differently to BigQuery and BigQuery denormalized. Since there are several type gaps that may require different amount of work, let's consider this issue a "research" and as such, the acceptance criteria for this ticket would be opening GitHub issues for type mappings that need to be added or corrected.
So please open issues for mapping:

- STRING (TIMESTAMP_WITH_TIMEZONE) to TIMESTAMP in BigQuery denormalized
- STRING(TIMESTAMP_WITHOUT_TIMEZONE) to TIMESTAMP in BigQuery denormalized
- STRING (BIG_NUMBER) to BIGNUMERIC in BigQuery denormalized and in BigQuery
- STRING (BIG_INTEGER) to INT64 in BigQuery denormalized and in BigQuery

@edgao does the list above make sense?

**Comment by edgao** [comment]
I think timestamp_without_timezone should be datetime, which is bigquery's "time without timestamp" type. Otherwise LGTM.

I'm a bit confused about objects turning into strings in destination-bigquery - shouldn't normalization be unnesting those into their own tables?

**Comment by yurii-bidiuk** [comment]
@edgao you're right. Normalization creates its own tables for objects in destination-bigquery

**Comment by yurii-bidiuk** [comment]
@grishick @edgao thank you for your feedback.
I created follow-up tickets:
#12652 Destination BigQuery denormalized: add support for timestamp with/without timezone
#12655 Destination BigQuery: map "airbyte_type": "big_integer" to INT64
#12656 Destination BigQuery denormalized: map "airbyte_type": "big_integer" to INT64
#12657 Destination BigQuery denormalized: map "airbyte_type": "big_number" to BIGNUMERIC
#12658 Destination BigQuery: map "airbyte_type": "big_number" to BIGNUMERIC
#12660 Destination BigQuery: timestamps without timezone should be mapped to DATETIME
cc: @alexandr-shegeda

**Comment by grishick** [comment]
@edgao should `"airbyte_type: big_integer"` be mapped to `BIGNUMERIC` in BigQuery instead of being mapped to`STRING`? And similarly, should Airbyte's `big_number` be mapped to `BIGNUMERIC`?

**Comment by grishick** [comment]
Closing this Epic. Remaining issues are tracked in #17637
