### ISSUE TITLE
[SPIKE] Spring (dependency injection)

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#11133]
## Tell us about the problem you're trying to solve
We have had multiple members of our team advocate for using a dependency injection framework (and whatever other wins we can get). Spring has bubbled to the top.

## Describe the solution you’d like
Spike on implementing Spring for dependency injection in the cloud billing module. It is well contained so it should be decent for a POC. Goal is to get developer leverage.

## Acceptance Criteria
* PR that uses Spring dependency injection that demonstrates what it would look like.
* If we like it, we should merge it.

**Comment by michel-tricot** [comment]
We should be careful going into this one. DI frameworks lead to a lot of downstream complexities including steeper learning curves for newcomers.

**Comment by pmossman** [comment]
Grooming notes:
- Only real open question is 'do we want to go this route?'
- Any big concerns that the team hopes will be addressed as the outcome of the Spike.

Jonathan already tried this, thinks it can be a pretty small task. Used Sprint built-in for scheduling tasks in a few places in code. Couldn't complete it because of the uberjar issue and classpath clutter, might have used the wrong guinnea pig project, need one that doesn't inherit uberjars. Hasn't given up, Jonathan will continue to poke at billing.

Want to make sure we find a guinnae pig that actually demonstrates the benefits of Spring, which may be at odds with choosing a module that has few dependencies.

Davin wants to understand best practices and use the bare minimum. Keep depenedencies at a minimum, keep scope as tight as possible.

Question: How do we think about OSS contributions and Spring? Does this help or hurt OSS contribution friction? A lot of Java developers have Spring experience, so it might help? Is learning curve actually steep? Adding '@autowired' is pretty straightforward. Davin: if we just use autowired and beans, all good, but pulling in all of the features, services, etc is where it gets scary.

Instrumenting a library on its own doesn't really do anything unless it's being used in an application that starts the Spring boot context. 

Billing app sounds like the right app if we can unblock it with the uberjar solution.

Davin: could be cool to do a proof-of-concept across OSS/Cloud. Getting that working would feel like a silver bullet. Might be hard to get here as a POC but would demonstrate a ton of value.
