### ISSUE TITLE
connector definitions should allow customizing step timeouts for custom connectors

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#11236]
We should allow connector-definition level (perhaps with connector-level override) timeouts for custom connectors so cloud users can cap the downside from bugs and limit their runs to a few hours.

Ideally failing this timeout would move the job into some kind of quarantined state instead of retrying.

**Comment by grishick** [comment]
More context on this. A related issue came up during on call (cc @ChristopheDuong ). A source connector was continuing to pump out data, as the time went by, the rate was slowing down, but the connector was still working (not hung, just waiting for source API rate limits). After more than 3 days of running, the source connector got killed. I think, we need timeout settings that allow us to kill a connector gracefully, meaning that the connector instance will be notified that it is about to be killed, so that it can wrap up and shutdown cleanly. We should also make connectors aware of what the timeout settings are, so that internally, the connector can avoid hitting the timeouts.

**Comment by evantahler** [comment]
Closing this issue in favor of https://github.com/airbytehq/airbyte/issues/13664
