### ISSUE TITLE
Cron String: API and Server changes.

### ISSUE THREAD

**Issue by davinchia** [airbytehq/airbyte#11431]
## Tell us about the problem you're trying to solve
Part of #2170. Follow up to #11419 .

Modify the external api endpoint to accept and return the new object that supports cronstring.

This change needs to be coordinated with FE, since the FE needs to make changes to consume the modified endpoint.

We cannot do a release before the FE is also updated to use this modified endpoint.

## Describe the solution you’d like
Modify the ConnectionSchedule object in [config.yml](https://github.com/airbytehq/airbyte/blob/master/airbyte-api/src/main/openapi/config.yaml#L3320) to be an enum similar to the enum stated in the [issue](https://github.com/airbytehq/airbyte/issues/2170#issuecomment-1051065420). This part needs to be coordinated with FE. There might be more routes we need to support.

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by timroes** [comment]
One additional API that we'd need is an API that returns us all allowed time zones for the cronjob (since JavaScript and Java libraries tend to support different time zones), i.e. that API should return an array of strings with allowed time zone names.

We should also make sure we're limit the API to create/edit a schedule to only accept those time zone names and fail with a 400 when a different time zone is used.

Working with time zones a bit in the past, I'd suggest we're filtering out the available time zones a bit, that Java will support by default. I'd suggest filtering out all time zones beginning with `Etc/`. Those are most often confusing to the user, since they are non intuitive, e.g. `Etc/GMT-4` is `UTC+4`, while most users would expect it to be UTC-4.

**Comment by davinchia** [comment]
@timroes how will the api to return the supported timezones be used?

**Comment by mfsiega-airbyte** [comment]
Some brainstorming:

I was imagining that the frontend would call the API and populate a dropdown/some form component with the available choices.

From the Connection API perspective - I think we're tied to a tzdata version (see https://www.iana.org/time-zones) since this is already packaged with Java (https://www.oracle.com/java/technologies/tzdata-versions.html) and Quartz scheduler depends on it.

From the perspective of making the tz list available to the frontend: I could imagine adding a server API that dumps the list (via something like https://docs.oracle.com/javase/7/docs/api/java/util/TimeZone.html#getAvailableIDs()). This guarantees that it stays in sync. An alternative: store the relevant version of the tzdata db as a static asset, and just fetch that. This avoids the work of adding a dedicated API, but is slightly more prone to falling out of sync (static asset needs to be updated if we bump the server tz db version).

Or maybe Tim had something totally different in mind, and I'm way off base :)

**Comment by timroes** [comment]
@mfsiega-airbyte that sums it up pretty much what we'll need in the FE. We'll have a selectbox for the timezones and need to know which ones are available, since different libraries have support for different timezones, we should not just ask our data library in JS to dump us a list of timezones, but fetch it from the backend API, so that you can ensure you're only giving us timezones that will also work later on.

Just to raise awareness for my comment above again:

Working with time zones a bit in the past, I'd suggest we're filtering out the available time zones a bit, that Java would support. I'd suggest filtering out all time zones beginning with Etc/. Those are most often confusing to the user, since they are non intuitive, e.g. Etc/GMT-4 is UTC+4, while most users would expect it to be UTC-4.

**Comment by mfsiega-airbyte** [comment]
Notes from offline chat with @timroes:
- We will initially filter out the `Etc/` timezones in the backend
- We probably do want to add a server API to return the list of supported timezones to avoid tz db inconsistencies
- Make sure we populate both old and new schemas in the read operation a la https://github.com/airbytehq/airbyte/pull/15039

**Comment by davinchia** [comment]
My thought is it would be easier to bundle the asset for now. Both OSS and Cloud are deployed as a whole so version inconsistencies is low risk, and I don't really see us updating this list often (though I might be wrong). I'm usually fair game for stuff except when it comes to adding new api routes, since they are usually hard to remove/modify. We would also add more traffic as part of creating a connection, and since there isn't an immediate benefit, I would rather not do so yet.

Just some thoughts, so take with a grain of salt.

**Comment by mfsiega-airbyte** [comment]
I'm inclined to agree with https://github.com/airbytehq/airbyte/issues/11431#issuecomment-1202800212 that it's worth at least trying this without adding a new API (this sort of thing seems reasonably-well supported nowadays, whereas it wasn't in the past). If the frontend work gets underway and it's clear that it's a non-starter we can always revisit.

WDYT?

**Comment by timroes** [comment]
I am not sure I fully understand what you mean by "bundling the asset" here? You'd add something into the CI that would generate a JSON file with all available time zones that will then be bundled with the FE code? It sounds for me harder to maintain as a special CI thing, than just adding a new API for it?

**Comment by davinchia** [comment]
Yes. The file can be manually updated for now to keep things simple. Something along the lines of placing this list in a folder so react includes the file as an asset when it's compiled (maybe the 'src' folder?), and parsing it on the FE. We can make automatically generating this file as a separate task.

Work-wise it's roughly equal, and maybe just slightly simpler. The main thing here is there is lower overall system complexity i.e. no additional api routes on the interface, no new api routes in our load balancers, less unnecessary networking calls ('unnecessary' since this will almost always return the same thing) etc. Generally less places for this to go wrong in production. The trade off is less flexibility in the deploy, which seems less important since this shouldn't change often.

I see this as a half step towards turning this into an api call, and as Mike pointed out, we can do so if we discover this doesn't work well while working on this.

**Comment by timroes** [comment]
@davinchia JSON files inside `src` we can simply import and use, so that should be the place (we can still figure out the specific folder). So if the BE either manually updates or automatically generate that file, this would be fine. If we automatic generate it, we must make sure it's running as part of `npm start`/`npm run build`, since the FE team doesn't use gradle to run the project. I am happy to assist with that.

My only question would be: since we plan to filter out some timezones, would we then just duplicate that code? Since we need to make sure the backend doesn't accept those as well as not have them in the JSON? An API would have the advantage, that we could just have some Java method for that, that we can call in both APIs.
