### ISSUE TITLE
Make it possible to see who is on call

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#11479]
## Tell us about the problem you're trying to solve
Currently we update the description in the #oncall channel to keep track of who is on call. This is error prone (easy to forget). The reason we do this is because our source of truth for the on call rotation is in PagerDuty. This means that only people with PagerDuty accounts can look at the rotation (even if they are using the Slack - Pager Duty app).

## Describe the solution you’d like
* In slack, as someone who does not have a PagerDuty account, I want to be able to see who the current on call is.
* This process should read directly from the source of truth (PagerDuty) and not rely on someone remember to update something.
* It should be easy. 1 command in slack.

**Comment by pmossman** [comment]
Grooming notes:
- Let's say Adam (head of sales) wants to page the OC person. He doesn't have a pagerduty account. But if we had an OC bot that can read the pagerduty schedule, that might get us there.
- Topher: in the past has used an email address that sends to the current OC person
- We have a strong Slack culture, want to be able to Slack message the OC person. OC email alias not a bad idea regardless
- Next step: try to get this working with the PagerDuty app itself, if we can't, use something like https://www.easyaslinux.com/tutorials/devops/notify-your-pagerduty-oncall-by-mentioning-oncall-in-slack-with-help-of-hubot/

**Comment by davinchia** [comment]
The default pagerduty app supports this but requires pd access in order to work. This means we cannot use this approach as we would have to give everyone PD access which is annoying and costly.

One alternative is exporting the oncall schedule to Google calendar and querying it. However the native gcal app does not support this. I haven't yet found an easy way of doing so.

At the same time, I'm looking at this [app](https://ovvy.io/). Waiting for them to get back to me. 

There is also this long running [PD thread](https://community.pagerduty.com/forum/t/find-out-who-is-on-call-via-slack/228/75) where other users are asking the same questions. Looks like no good solutions from PD for now (makes sense since they want us to buy more seats). I'm leaving this here for posterity. There are some good ideas in there that I will dive more into.

As much as I detest having to write code ourselves, the Hubot solution looks like the most promising for now. I've going to give it a few days for the Ovvy guys to get back to me.

**Comment by davinchia** [comment]
Actually https://www.pagerduty.com/docs/guides/hubot-integration-guide/ makes it seem like it's mostly clicking buttons. The main downside is the easiest Hubot integration is with Heroku. @cgardens do we have a Heroku account? How would you feel if I create one for this?

**Comment by davinchia** [comment]
I'm going to start working on https://www.pagerduty.com/docs/guides/hubot-integration-guide/.
