### ISSUE TITLE
Redesign the registration/sign up page

### ISSUE THREAD

**Issue by timroes** [airbytehq/airbyte#11773]
We want to redesign the current Cloud registration page.

Figmas for the redesign:
- https://www.figma.com/file/qDwWxPe8NqUMJlvDMikXCr/01_04_SIGN_UP
- https://www.figma.com/file/5Bm1TPxow7b1kDbbJK3quu/01_05_SIGN_IN

This redesign also is expected to work with experimentation support. The change should include at least the ability to experiment with one of the elements described in the PRD:
https://www.figma.com/file/5Bm1TPxow7b1kDbbJK3quu/01_05_SIGN_IN?node-id=335%3A1852

┆Issue is synchronized with this [Monday item](https://airbyte-bunch.monday.com/boards/2536787439/pulses/2537099534) by [Unito](https://www.unito.io)

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by edmundito** [comment]
@nataliekwong  to do:
- Specify what areas needs to be experimented on
- Share design changes

**Comment by nataliekwong** [comment]
The latest mockup is here: https://www.figma.com/file/qDwWxPe8NqUMJlvDMikXCr/01_04_SIGN_UP

@edfarraye45 and I put this document together on our suggestion for experimentation on the landing page. 
https://docs.google.com/document/d/16aT4ibOviQYendfR1LtCp3uPfDqi2tSOz-sqIfqx3PA/edit?usp=sharing

**Comment by edmundito** [comment]
@nataliekwong @timroes I updated the description of this item but can you confirm that we still want to rotate the quotes in the latest iteration?

**Comment by timroes** [comment]
From the given designs I think we don't have a quote carousel in place anymore. @nataliekwong to confirm.

**Comment by nataliekwong** [comment]
The design does not rotate the quotes - it's just a static image of Micah with the quote over him. No carousel

**Comment by edmundito** [comment]
Ok! I removed the rotating carousel from the main description

**Comment by dizel852** [comment]
@nataliekwong @Upmitt  Just to clarify:
At the moment on sign-in/up pages we have a "Back" arrow button which leads us to [airbyte.com](https://airbyte.com/) 

<img width="612" alt="Screenshot at Jun 09 17-43-44" src="https://user-images.githubusercontent.com/20929344/172876104-5bbc7e1f-e46f-43a1-b98d-d39ce31cef8e.png">

But on mockups instead of a button, there is an Airbyte logo. @nataliekwong please confirm that we replace the button.

<img width="593" alt="Screenshot at Jun 09 17-43-16" src="https://user-images.githubusercontent.com/20929344/172876488-bec0f3ee-c54f-466f-86c1-1b38870e327a.png">

**Comment by nataliekwong** [comment]
We should remove the back arrow. We actually don't need to replace it with the Airbyte logo - we can just remove any outbound link in that upper-left space.
