### ISSUE TITLE
If Normalization fails retry only this operation

### ISSUE THREAD

**Issue by Tolsto** [airbytehq/airbyte#11933]
## Environment
- **Airbyte version**:  0.35.65-alpha
- **OS Version / Instance**: Ubuntu 20.04
- **Deployment**: Docker
- **Source Connector and version**: Postgres 0.4.9
- **Destination Connector and version**: Snowflake 0.4.24
- **Severity**: High
- **Step where error happened**: Sync Job

## Current Behavior
I started a sync for a new connection and the extract and load phase went fine. However, during the custom transformations one of the dbt models errored. As a result, Airbyte retries the entire sync, including the extract and load. In my case, the database is quite large and each full sync takes 20h+ and generates $600 in AWS Aurora IOPS fees.

## Expected Behavior
Airbyte should just retry the custom transformations.

## Steps to Reproduce
1. Create a custom transformation that will cause an error
2. Run the sync

**Comment by marcosmarxm** [comment]
I added the issue to team backlog @Tolsto

**Comment by grishick** [comment]
When normalization fails, it is most likely that it will fail on retry, because usually normalization failures are caused by one of:

1.  values are not as defined in schema (e.g. `float` in an `integer` field)
2. PK collisions
3. special values that are not supported by the destination (special characters, strings too large)
4. DBT bugs that cause SQL errors
5. Permissions
6. Platform crash/restart
7. Out of memory

Platform should be able to detect cases 6 and 7 and rerun just normalization in a subsequent attempt. In case of 5, platform should not run another attempt at and should warn the user about permission errors.

**Comment by cgardens** [comment]
We aren't going to pick this up. We want to stay away from orchestrating dbt. We recommend using Airflow or Dagster to do this orchestration. [Docs](https://docs.dagster.io/integrations/airbyte). In addition, we are moving away from Normalization and moving the typing and de-duping into connectors. That will obviate this issue!
