### ISSUE TITLE
Publish reference docs for config-based connectors

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#11951]
## Tell us about the problem you're trying to solve
We should publish reference docs for config-based connectors.

- [x] Publish cdk reference docs (including declarative module)
- [ ] Ensure all public methods for all classes in the declarative module have docstrings
  - [ ] `declarative.checks`
  - [ ] `declarative.datetime`
  - [ ] `declarative.decoders`
  - [ ] `declarative.extractors`
  - [ ] `declarative.interpolation`
  - [ ] `declarative.parsers`
  - [ ] `declarative.requesters`
  - [ ] `declarative.schema`
  - [ ] `declarative.states`
  - [ ] `declarative.stream_slicers`
  - [ ] `declarative`
 - [ ] Document the functions available in the jinja environment

**Comment by brianjlai** [comment]
Noting here:
There's a few different accepted options for how we can document declarative components since we're transitioning to dataclasses. Specifically with how we will document attributes now that the `__init__` will be inferred rather than explicitly defined. One way is to define it in a Google-esque way:
```
Attributes:
        response_filters (Optional[List[HttpResponseFilter]]): response filters to iterate on
        max_retries (Optional[int]): maximum retry attempts
        backoff_strategies (Optional[List[BackoffStrategy]]): list of backoff strategies to use to determine how long
        to wait before retrying
```

Reference doc and an example of what this will look like: https://stackoverflow.com/questions/51125415/how-do-i-document-a-constructor-for-a-class-using-python-dataclasses

To get this to look pretty, we'll need to tweak `airbyte-cdk/python/reference-docs/_source/conf.py` and add `'sphinx.ext.napoleon'` to the extensions. Just noting this as well, but I'll fold this into the work of transitioning everything to dataclasses
