### ISSUE TITLE
Put a GA label behind GA connectors

### ISSUE THREAD

**Issue by timroes** [airbytehq/airbyte#12034]
We want to show a `GA` label for all GA connectors in the selectbox (and other places we show the label).

We want the tooltip to say:

> A generally available release has been deemed ready for use in a production environment and is officially supported by Airbyte. Its documentation is considered sufficient to support widespread adoption.

But we don't want to show that as a warning box below the select box.

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by nataliekwong** [comment]
Hey @edmundito, we reviewed this issue in an onboarding review today and discussed a slight change to the implementation.  Rather than implementing a text labvel, it's preferred to use a checkbox, like this: https://www.figma.com/file/etaOkOsnXMoKwbfhCD71kw/WEB-APP?node-id=33635%3A177068

cc @Upmitt @misteryeo
