### ISSUE TITLE
Introduce more fine grained error boundaries

### ISSUE THREAD

**Issue by timroes** [airbytehq/airbyte#12172]
Currently we most often crash the whole app with an "Unknown error occured" in case a request fails (e.g. with a 500 internal server error). We should try to move error boundaries a bit lower, e.g. if the `connections/list` request fails, we should not error out the whole web app, but just the connection list, that it was needed for.

The sidebar should ideally always be possible and allow navigation.

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by edmundito** [comment]
While working on #10735, which at least provides an error when the user gets a 401, I tried to understand why the sidebar was not showing, and currently, it's a bit tricky. The error boundary components live outside of the bar, so if something errors badly, everything disappears.

What I recommend doing first is listing out understanding of what can be done and listing out which areas are the most valuable to update in this issue. Keep in mind for every area that is changed, testing is needed.

**Comment by krishnaglick** [comment]
I did a little investigation around this. I agree w/ Edmundo, due to the level in which we get certain resources it fails out the entire app. I think we could take some baby steps to move things like figuring out which workspace you're in lower in the render tree to get around it. But there's likely several places that we'll find this issue in.
