### ISSUE TITLE
SAT Testing confirms that a crash produces at least one `AirbyteTraceMessage`

### ISSUE THREAD

**Issue by pedroslopez** [airbytehq/airbyte#12473]
Full context in parent issue https://github.com/airbytehq/airbyte/issues/12322

The SAT should verify that an `AirbyteTraceMessage` is emitted when something goes wrong.

This may be done by using the `invalid_config.json` that most connectors have and running a sync with it.

**Comment by Phlair** [comment]
Open Q:
- Should we actually be testing for this is SAT if the implementation described [here](https://github.com/airbytehq/airbyte/issues/12471)/[here](https://github.com/airbytehq/airbyte/issues/12472) means that connectors will all be doing this automatically? In other words, this seems like a concern of the cdk implementation rather than the individual connector...
  - If we do want to have this test in SAT, then we should also create a similar issue for DAT.

**Comment by Phlair** [comment]
notes from backlog grooming:
- add this as a default test, opt-out possible for cases where cdk not being used.
  - document how to opt-out
- clarify stance on AirbyteTraceMessage in protocol
  - strict requirement? Highly recommend? Optional?
- create issue for DAT
