### ISSUE TITLE
Facebook Pages

### ISSUE THREAD

**Issue by awoehrl** [airbytehq/airbyte#1247]
## Tell us about the new integration you’d like to have
Which source and which destination? Which frequency?
Facebook Pages would be super. Most ETL tools only offer Facebook Ads integration unfortunately.

## Describe the context around this new integration
Which team in your company wants this integration, what for? This helps us understand the use case.
Performance data for our posts and videos is important for us but unfortunately right now it is only in the Fb silo...

## Describe the alternative you are considering or using
What are you considering doing if you don’t have this integration through Airbyte?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368133632077) by [Unito](https://www.unito.io)

**Comment by cgardens** [comment]
@awoehrl thanks! we will add it to our upcoming integrations. do you have a sense of which endpoints in the facebook pages API would be most helpful to extract data for?

**Comment by awoehrl** [comment]
@cgardens thanks! The api is very excessive in my view. The most important endpoints should be these:

For basic information and metadata around the page and posts:
https://developers.facebook.com/docs/graph-api/reference/page/
https://developers.facebook.com/docs/graph-api/reference/page-post/

For getting metrics around the page, posts, post-videos:
https://developers.facebook.com/docs/graph-api/reference/v9.0/insights


Hevo and Fivetran have connectors and also show ERD diagrams on their help pages. The Fivetran connector seems to have everything to satisfy my use case:

https://fivetran.com/docs/applications/facebook-pages
https://docs.hevodata.com/sources/marketing-&-email/facebook-pages/

**Comment by cgardens** [comment]
Thanks! This is a really helpful overview!

**Comment by dataluchs** [comment]
Really cool. I think it's great that there's finally hope for a proper open source data pipeline solution for facebook pages data.
Just as a sidenote, this problem exists for nearly all major social platforms.

**Comment by yevhenii-ldv** [comment]
## Integration Vetting

**Webhook-based? (no/partially/yes)**

No

**Available authentication modes (API key/Oauth/other)**

[Access token](https://developers.facebook.com/docs/graph-api/reference/page/) like we use with Instagram and FB Marketing connectors.

Needs permissions:

- [pages_read_engagement ](https://developers.facebook.com/docs/permissions/reference/pages_read_engagement)
- [pages_read_user_content](https://developers.facebook.com/docs/permissions/reference/pages_read_engagement)
- [read_insights](https://developers.facebook.com/docs/permissions/reference/read_insights)

**Creating an account**

Already exists

**How to populate the account with data?**

We have to create posts because all of our test pages have no posts.

I think we can create this through the [API](https://developers.facebook.com/docs/graph-api/reference/page-post/) or through the UI, but it might need some help.

**Available streams for sync**

- [Pages](https://developers.facebook.com/docs/graph-api/reference/page/)
- [Posts](https://developers.facebook.com/docs/graph-api/reference/page-post/)
- [Page Insights](https://developers.facebook.com/docs/graph-api/reference/v10.0/insights)
- [Post Insights](https://developers.facebook.com/docs/graph-api/reference/post/insights/)

**Integration supports incremental sync?**

For some Insights

**Other information/blockers**

No Page posts

**Comment by marcosmarxm** [comment]
@MohamadHaziq you are working on this right?

**Comment by MohamadHaziq** [comment]
@marcosmarxm yeah, at a slow pace at the moment due to prioritising something else, so if anyone wants to help/hijack more than welcome

**Comment by gaart** [comment]
@awoehrl

We just merged this connector into master and released a new version of the connector. 

The connector will be available in the next release of Airbyte (we usually release every Tuesday). If you can't wait and want to get started now trying it out in a running Airbyte instance, add the connector like described in https://docs.airbyte.io/integrations/custom-connectors#adding-your-connectors-in-the-ui . The information for the connector is: 

**Display Name**: Facebook Pages
**Docker repository name**: airbyte/source-facebook-pages
**Docker image tag**: 0.1.0
**Documentation URL**: hub.docker.com/r/airbyte/source-facebook-pages


Please let us know if you have any further questions. 

Enjoy!
