### ISSUE TITLE
Update loading state of the switch component

### ISSUE THREAD

**Issue by andyjih** [airbytehq/airbyte#12530]
1. Update the switch component to support the loading state
  a. Rename component from `Toggle` to `Switch`
  b. Migrate from styled components to sass
2. Identify areas where the loading state is supported
  a.  **Search in code for the Toggle component and figure out which ones need to have the loading state**
3. Update layout around toggle to include error messages when the request fails

Designs here: https://www.figma.com/proto/etaOkOsnXMoKwbfhCD71kw/WEB-APP?page-id=34030%3A187870&node-id=34051%3A188679&viewport=305%2C48%2C0.25&scaling=min-zoom&starting-point-node-id=34051%3A188679&show-proto-sidebar=1

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by krishnaglick** [comment]
The error functionality, based on the mocks, needs to exist outside the Switch component.
Adding in loading states is fine, and while I can include error messages if they're generated I feel it's slightly outside the apparent scope.
Error reporting should perhaps be part of a larger body of work as often our Error Boundaries just eat them since they're bubbled up through the render tree.
