### ISSUE TITLE
Get first simple acceptance test running in Cloud

### ISSUE THREAD

**Issue by pmossman** [airbytehq/airbyte#12539]
Goal is to establish the infra to run Cloud acceptance tests. A non-goal is having comprehensive tests for Cloud.

Explore if easy to use OSS tests first. Look at the OSS airbyte-tests module, [AcceptanceTests.java](https://github.com/airbytehq/airbyte/blob/master/airbyte-tests/src/acceptanceTests/java/io/airbyte/test/acceptance/AcceptanceTests.java). Potentially introducing a new dependency in build.gradle to use this code in Cloud.

 If not, then do a light test of Cloud-specific test like making sure that the API is running and you can call getUser() for example.

Includes establishing a github workflow to run Cloud acceptance tests. (Reference OSS workflows for assistance)

After you’ve finished this first test, scope out what the rest of the project might look like. (Create follow-up issues)

DoD:
test should included cases for:
Creating a source
Creating a destination
Creating a connection
Doing a full refresh

**Comment by davinchia** [comment]
Note, we already have some tests running [here](https://github.com/airbytehq/airbyte-cloud/tree/master/cloud-tests). However this is mostly around testing permissioning on certain routes and does not include a sync test. Ideally we buff up the tests to run a manual sync on cloud.

**Comment by terencecho** [comment]
An update for this ticket.

- dug into the acceptance test issues with our postgres container. After talking with Liren, seems like the postgres container we use for testing doesn’t allow for SSL, which we enforce in airbyte cloud. that discussion can be found [here](https://airbytehq-team.slack.com/archives/C03C4AVJWG4/p1660235999367159). 
  - the dbs/dws team has a ticket to allow SSL to be turned off in cloud [here](https://github.com/airbytehq/airbyte/issues/15265), but it’s not currently prioritized to be worked on. Seems like our options here are to ask dbs team to bump the priority of the ticket or to use a different source for our testing (i.e. not using the postgres containers), which is not ideal since we want to keep the acceptance tests as similar to the oss ones as possible.
  - the dbs team is merging the source-postgres and source-postgres-strinct-encrypt connectors soon, with that change we might be able to not enforce ssl in our cloud acceptance test, will follow up to double check when this is done

The PR for this ticket can be found here: https://github.com/airbytehq/airbyte-cloud/pull/1943

**Comment by pmossman** [comment]
@terencecho can you provide a quick update here?

**Comment by terencecho** [comment]
The PR linked above is ready to merge. Davin is going to do a final review later this afternoon, after which I'll merge the PR.

As things to note for the acceptance tests, they're working as expected when running locally and during builds (on github runners), but we have disabled some tests when running on a GKE environment. This is because there are some connection problems happening with the source/destination test postgres containers and the airbyte instance. Might be a good idea to follow up on the connectors org to see if they've seen such an issue before.

**Comment by terencecho** [comment]
The PR is now merged, but refer to the comment above regarding running integration tests on a GKE env

**Comment by terencecho** [comment]
The PR has been merged [here](https://github.com/airbytehq/airbyte-cloud/pull/1943).

Currently the tests the communicate with a source/destination postgres container are not working when running in a GKE env. It's having trouble connecting to those dbs, so those steps will be skipped for now if running an integration tests on a GKE env.
