### ISSUE TITLE
Frontend: Download button for logs in UI is not working

### ISSUE THREAD

**Issue by harshithmullapudi** [airbytehq/airbyte#12594]
See: https://discuss.airbyte.io/t/json-schema-validation-failed-redshift-snowflake/848/1

Validate if it can be reproduced and fix.

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by dizel852** [comment]
@harshithmullapudi is this issue still relevant?
Since I wasn't able to reproduce it, I was testing it on connection `Redshift => Local JSON` (don't have a Snowflake account), and seems like it works.
https://www.loom.com/share/77976f5f8cb04be7b362d03bbc067ff6

Thinking out loud 🤔 : is this case specific to the `Redshift => Snowflake` connection? I doubt.

**Comment by harshithmullapudi** [comment]
Hey @dizel852 we are not facing this issue now closing it
