### ISSUE TITLE
Main menu Hover State

### ISSUE THREAD

**Issue by Upmitt** [airbytehq/airbyte#12725]
Add hover state to the main menu's sections:

![image](https://user-images.githubusercontent.com/168664/167661420-deb64588-a030-4bfe-bc8a-a4ada9933e12.png)

https://www.figma.com/file/AxqFXuHo2BoTY0QY12hxm1/?node-id=5%3A335 - You can click on play to open the prototype and see the behavior

When a user hovers over the item on the main menu, it should hover

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by tealjulia** [comment]
@Upmitt I'm looking at the Figma and I could use some clarification on the expected outcome.

For states on the menu item I see
- `on`: Old "selected" state, do not want anymore
- `off`: Old "unselected" state, do not want anymore
- `on hover`: ?
- `off hover`: what a user sees if a non-selected item is hovered on
- `parent_selected`: an item is selected but user is not hovering on it
- `parent_selected hover`: an item is selected and a user is hovering

Can you help me understand how `on hover` should behave and let me know if I've interpreted the prototype and Figma design correctly otherwise?

**Comment by tealjulia** [comment]
@Upmitt I have a PR up with the changes we discussed yesterday.  The pieces I'm waiting on are:
1. How to handle the "flyout" menus (Support and Chat)
2. Settings doesn't have a top-level page (there is no `/settings`)... should that item act like "active" or "parent active"?
