### ISSUE TITLE
Release OTEL Metrics Implementation. Update Cloud.

### ISSUE THREAD

**Issue by davinchia** [airbytehq/airbyte#12909]
## Tell us about the problem you're trying to solve
Follow up to #12908 .  Make sure Cloud can correctly consume this.

## Describe the solution you’d like
- [x] Release Airbyte.
- [x] Modify Cloud so the correct env var is set and Datadog is used. 
- [x] verify you see a metric in datadog
- [x] make a doc if you did something interesting

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

**Comment by xiaohansong** [comment]
Nothing particular interesting but probably a mini post-mortem for metrics stopped emitting to datadog about half a day. Lesson here is I wrongfully had the impression that OSS is like a 'service' rather than a 'binary', so when I define the ENV_VAR there I didn't realize it could break the cloud - thought cloud was still using the old path (DogStatsDSingleton). But since the OSS is wrapped as airbyte-server in cloud, ENV_VAR needs to be correctly set in the cloud as well, but the correction PR comes later than the original PR, which eventually breaks the metric flow we had.
