### ISSUE TITLE
Creating a new python source tutorial

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#1319]
## Tell us about the documentation you'd like us to add or update
* A tutorial on how to create a new source and iterate on it.
* This tutorial should be have easy to consume steps (not massive walls of text like some of architecture docs). 
* We should link to relevant architecture docs.
* We should describe iterating using standard tests and a docker container.
* This should replace the checklist that is generated by the template.
* This should be the ONE place that a developer goes to get up and running. It can link to other stuff, but this this should be the checklist that they follow.

**Comment by ChristopheDuong** [comment]
I am not sure we need a dedicated tutorial document for writing sources...

Let's say my user story is:

1. I am thrilled to use airbyte but my specific source is missing from the list so I decide to write my own.
1. I start to read this page: https://docs.airbyte.io/contributing-to-airbyte/building-new-connector
1. I understand the pre-requisite to have a dev environment to build everything (seriously? Can I just worry about building my new connector only?)
1. I run the template: `npm run generate`
1. I select my preferred language from the list
1. I head to `NEW_SOURCE_CHECKLIST.md` which takes over to tell me what to do (that's my custom tutorial?)

Otherwise, we can make a video tutorial showing an example of going through that process

**Comment by michel-tricot** [comment]
What prevents us from just building the new integration actually?

**Comment by cgardens** [comment]
I'm going to let @sherifnada jump on this. It seems like he's maybe thought about it already as he's been trying to document incremental. Sounds like he has a good idea of what would be helpful.

The goal is to have _one_ place in the hosted docs that is a tutorial walkthrough on how to build your first python source. It will describe building an actual source. Will deprecate the checklist which is very hard to interact with now.

**Comment by cgardens** [comment]
done
