### ISSUE TITLE
Woocommerce connector not visible

### ISSUE THREAD

**Issue by deka** [airbytehq/airbyte#13268]
## Environment
- **Airbyte version**:  0.39.3-alpha
- **OS Version / Instance**:  Windows 10
- **Deployment**: Docker Desktop
- **Source Connector and version**: woocommerce v ? 
- **Destination Connector and version**: 
- **Severity**: Medium 
- **Step where error happened**:  /> docker-compose up

## Current Behavior
woocommerce connector is not in the source list

## Expected Behavior
See woocommerce connector

## Logs
N/A

## Steps to Reproduce
>git clone https://github.com/airbytehq/airbyte.git
>cd airbyte
>docker-compose up

## Are you willing to submit a PR?
N/A

**Comment by alafanechere** [comment]
Hey @deka , the Woocommerce connector is not available because we do not have a test account that will allow us to run our acceptance tests (https://github.com/airbytehq/airbyte/issues/13268)
You can build the woocommerce connector image yourself from [the repo](https://github.com/airbytehq/airbyte/tree/master/airbyte-integrations/connectors/source-woocommerce) and add it as a custom connector.
