### ISSUE TITLE
GCS destinaltion connection failed

### ISSUE THREAD

**Issue by harshithmullapudi** [airbytehq/airbyte#13590]
Is this your first time deploying Airbyte?: Yes
OS Version / Instance: Ubuntu
Memory / Disk: 8 GB
Deployment: Docker
Airbyte Version: What version are you using now?
Source name/version: snowflake
Destination name/version: GCS
Step: The issue is happening during creating a destination
Description: I have added the HMAC key but having this problem while the same credentials are working for other team member.
log file is attached

[logs-c3389aa3-6f93-4c82-be1c-a646006a1a4d.txt](https://github.com/airbytehq/airbyte/files/8858791/logs-c3389aa3-6f93-4c82-be1c-a646006a1a4d.txt)

https://discuss.airbyte.io/t/gcs-destinaltion-connection-failed/1196/1

**Comment by zbrak** [comment]
Hey @harshithmullapudi thought I'd hop in here because I hit the exact same error on my destination setup today.

In my case it was because the service account tied to the HMAC key did not have sufficient permissions to perform the load. 
Once I added the service account as the 'Storage Admin' role this cleared.

**Comment by Julianfried** [comment]
Thanks!!! It would be great if documentation is modify. It says:
![image](https://github.com/airbytehq/airbyte/assets/105244530/4d82cbe8-01da-472f-9a19-624bc43698d9)
The correct one is 'Storage Admin' role.

**Comment by Chaitanya674** [comment]
what are the permissions that we need to provide to the service account ?
