### ISSUE TITLE
How can I deploy Airbyte on Azure?

### ISSUE THREAD

**Issue by michel-tricot** [airbytehq/airbyte#1367]
I want a similar guide to deploy Airbyte on Azure as there are for GCP/AWS.

**Comment by qmnonic** [comment]
If i can deploy airbyte from a standard docker-compose, with images in docker hub, it might be possible to deploy as [Azure Container Instances](https://docs.microsoft.com/en-us/azure/container-instances/tutorial-docker-compose), which would be the simplest approach on azure.  No machine management, simply containers with volumes on azure storage.

**Comment by michel-tricot** [comment]
That's a great idea! I didn't know it supported docker-compose!

Did it work?

**Comment by qmnonic** [comment]
I can get all the components running, the hitch is it has to run on a public IP (not localhost), so i'm debugging your nginx config to get it off localhost and find a quick basicauth solution to provide minimal security.

I ran into an issue the the `seed` functionality (it didn't create the default workspace in my azure volumes for some reason, so i manually copied it for now), which suggests i may have missed other things too.

Once i get it running, i'll share how i did it.

**Comment by michel-tricot** [comment]
what problem do you have with the public ip? The webapp is trying to talk to a localhost api?

**Comment by qmnonic** [comment]
i need to debug further, but the webapp appears to only be listening to localhost:80 (i had to remove the docker-compose port mapping to 8000, which isn't supported in azure).  When I deploy to azure, the app assigns a public ip and dns name.  The webapp doesn't seem to hear requests from the public ip OR dns name.  I need to figure this out.

Next step would be to enable basicauth for your webapp.  At that point, it should just work.

I tried putting a caddy/nginx proxy infront of your webapp first, but in the Azure docker compose implementation, the webapp port (binds on 80 then remapped in compose) seems to conflict with the proxy (also trying listen on 80).  This appears to be an azure bug.

**Comment by qmnonic** [comment]
As an update here, docker-compose aci deployment won't work because airbyte needs access to docker engine via `docker.sock`, which isn't supported.  It's also complicated by postgres (azure storage won't run it because it doesn't support group permissions), and the current paths (i.e. /tmp) make mapping it to azurestorage non-trivial.


However, there is a path for deployment similar to AWS/GCP.  Here are the rough steps (with a few notes for improvement):

(1)  Install and configure azure-cli - https://docs.microsoft.com/en-us/cli/azure/

(2) Create a resource group to deploy a VM.
`az group create --name $RESOURCE_GROUP --location $LOCATION `

(3) Create a VM to run airbyte.
Azure's **Standard_F2s_v2** is roughly equivalent to an AWS t2.large 

`az deployment group create --resource-group $RESOURCE_GROUP --template-uri https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/docker-simple-on-ubuntu/azuredeploy.json --parameters adminUsername=$VM_USER dnsNameForPublicIP=$DNS_PREFIX vmSize=Standard_F2s_v2 location=$LOCATION authenticationType=sshPublicKey adminPasswordOrKey=@~/.ssh/id_rsa.pub
`
TODO: This created a VM named MyDockerVM in a similarly named subnet.  The docker-simple-on-ubuntu template should be extended to be a little more flexible.

(4) SSH into the new VM to install airbyte
```
ssh $VM_USER@$DNS_PREFIX.$LOCATION.cloudapp.azure.com
mkdir airbyte && cd airbyte
wget https://raw.githubusercontent.com/airbytehq/airbyte/master/{.env,docker-compose.yaml}

## update docker-compose binary, TODO: update docker-simple-on-ubuntu template
sudo curl -L "https://github.com/docker/compose/releases/download/1.28.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

# start airbyte
docker-compose up -d
```

(5)  Create tunnel
`ssh -L 8000:localhost:8000 -L 8001:localhost:8001 -N -f $VM_USER@$DNS_PREFIX.$LOCATION.cloudapp.azure.com`

(6)  Visit http://localhost:8000 and start moving some data.

**Comment by sherifnada** [comment]
@qmnonic Thanks for following up with the context. This is great! We'll add this to our standard documentation. 

Out of curiosity, what is your preferred mode of deployment in a production setting? Would you prefer something like Kubernetes support?

**Comment by qmnonic** [comment]
@sherifnada  Preferred mode of deployment - use a SaaS whenever possible to reduce the devops overhead.  I tried to get this working using Azure's ACI (azure container instances) to avoid managing a VM and the associated upgrades, user management, etc.  I prefer not to take on the overhead of managing a kubernetes cluster, unless it's simple to manage and cost effective.  

These guys have a good model (unrelated product) - https://streamnative.io/ - offering both a cloud option, and managed option.

**Comment by alexanderbanks** [comment]
@sherifnada I'm also very interested in an Azure deployment. I'm kind of curious about the deployment strategies for Airbyte. It seems like the two options are basically A.) Kubernetes, or B.) Create a whole VM instance and then on that instance, start `docker-compose`. I'm curious about the option of, instead of using Kubernetes, just having 5 (or however many containers there are in the compose file) containers running out of a Cloud-specific Container tool (AWS Fargate, Azure Container Instances, whatever GCP calls them)? I don't particularly want to take on Kubernetes just to deploy the handful of resources Airbyte uses, but I also don't super love a deployment strategy that involves SSHing and downloading software. Does that make sense? Is there a deployment strategy in the roadmap that involves linked, separate containers in the cloud? I couldn't find anything in the roadmap, but there's kind of a staggering amount of stuff in flight/defined (which is great! 😀)

**Comment by geekwhocodes** [comment]
> 
> 
> @qmnonic Thanks for following up with the context. This is great! We'll add this to our standard documentation.
> 
> Out of curiosity, what is your preferred mode of deployment in a production setting? Would you prefer something like Kubernetes support?

I agree with @qmnonic but given the restrictions on ACI, I would prefer AKS(Azure Kubernetes Service) in production setting. 

There might be some customers who would like to run it on virtual machine too.

**Comment by ulan-yisaev** [comment]
> Azure Container Instances

Hi Alex! 
I'm wondering if you were able to deploy Airbyte to Azure Container Instances?

Thanks in advance.

**Comment by Ritik45** [comment]
Hi , 
Can someone help me to move my local custom connectors onto AKS ?
