### ISSUE TITLE
Mark certain spec fields as cloud-only to support cloud-specific parameters

### ISSUE THREAD

**Issue by tuliren** [airbytehq/airbyte#13782]
## Tell us about the problem you're trying to solve
- The current solution for publishing connectors with different behaviors in OSS vs cloud is that a connector will behave differently based on the `DEPLOYMENT_MODE` environment variable, and we publish cloud-specific spec files.
- This is implemented in https://github.com/airbytehq/airbyte/pull/13522.
- To make the solution more flexible, an alternative solution for the spec file is to mark certain fields as cloud-only, and show those fields only on cloud deployment.
- This ticket requires a design spec to further evaluation.

## Additional context
- This is suggested by @evantahler in https://github.com/airbytehq/airbyte/pull/13522#discussion_r892533186.
- Relate to https://github.com/airbytehq/airbyte/issues/8634.

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by timroes** [comment]
To add some thoughts: The frontend should ideally not render a spec differently based on Cloud or OSS. If we need different parameter in Cloud, the spec returned should be differently on Cloud via OSS. That could happen via different connectors or some special mechanism that the connector knows about which environment it runs in. I just believe the spec returned should be ready for consumption by the FE and we should not build specific FE logic around, rendering fields conditionally based on the environment, since this will just add additional complexity to the FE, which is not needed in this case, since the BE anyway will need to handle it.

**Comment by evantahler** [comment]
Closing in favor of https://github.com/airbytehq/airbyte/issues/16676
