### ISSUE TITLE
Support all available entities in Source Freshdesk

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#1387]
## What 
Support the following streams in Freshdesk on a full refresh basis: 

* Agents (_exists_)
* Business Hours
* Canned Responses
* Companies (_exists_)
* Contacts (_exists_)
* Conversations
* Discussions
* Email Configs
* Email Mailboxes
* Field Service Management
* Groups (_exists_)
* Omnichannel Activities
* Products
* Roles (exists)
* SLA Policies
* Satisfaction Ratings
* Scenario Automations
* Settings
* Skills (_exists_)
* Solutions
* Surveys (_exists_)
* Ticket Fields
* Tickets (_exists_)
* Time Entries (_exists_)

Please make sure that:

1. In the standard tests for this source, every stream is tested (and that every stream outputs records) unless there is a rate limiting issue
1. you create fake data for every stream -- whoever is working on this issue, feel free to reach out to me if you need support

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368137570266) by [Unito](https://www.unito.io)

**Comment by lgomezm** [comment]
Some of these can't be mapped to streams:
* **Field Service Management:** Instead of being an HTTP resource, it's more like a configuration that can be enabled in the Freshdesk account. I could not find any endpoint providing any data regarding Field Service Management. See https://developers.freshdesk.com/api/#field-service-management.
* **Omnichannel Activities:** It's section in the API reference only defines an endpoint to publish activities: https://developers.freshdesk.com/api/#publish_omnichannel_activity.

Also, `Surveys` has not been implemented yet.

**Comment by lgomezm** [comment]
BTW, I'm claiming this issue 🙂
