### ISSUE TITLE
Source Jira: Issue Property Stream takes 48+ hours to complete sync

### ISSUE THREAD

**Issue by JCWahoo** [airbytehq/airbyte#13962]
## Environment
Airbyte version: All versions
OS Version / Instance: AWS EC2
Deployment: Docker
Source Connector and version: JIRA
Destination Connector and version: Redshift
Step where error happened: Sync Job

## Current Behavior
issue_properties stream takes over 48 hours to complete. All other streams complete in < 1 hour. 

## Expected Behavior
issue_properties stream has similar performance to other streams

## Steps to Reproduce
1. Create JIRA >Target connection
2. Execute sync
3. Observe timing to complete streams

**Comment by grubberr** [comment]
@JCWahoo 

In the old implementation, it could pretty slow stream because make a lot of HTTP requests.

  1. We call `project/search` to get all projects
  2. For every project we call `search` to get an issue for this project
  3. For every issue we call `issue/{issue_key}/properties` and get property_key
  4. For every property_key we call `issue/{issue_key}/properties/{property_key}` and finally get property values
   
  After this PR https://github.com/airbytehq/airbyte/pull/20128 it will become faster 
  because in this implementation [2] list of issues fetched faster not by projects
   
  But because of the nature of this stream being such nested, it still can be pretty slow

**Comment by grubberr** [comment]
This PR https://github.com/airbytehq/airbyte/pull/20128 has to improve this problem 
please re-open if problem still exists
