### ISSUE TITLE
"Query timed out after PT2S" exception appears in cassandra destination

### ISSUE THREAD

**Issue by liangfei** [airbytehq/airbyte#13960]
com.datastax.oss.driver.api.core.DriverTimeoutException: Query timed out after PT2S

**Comment by alafanechere** [comment]
Hey @liangfei I'm closing this issue because the description is too light at the moment to be processed by our team. 
I would suggest posting on our [forum](https://discuss.airbyte.io/) if you need assistance from our team. We'll try to troubleshoot with you to make sure this is a bug before opening an issue. 
We'd need to know:
* You Airbyte version
* Your cassandra connector version
* Your failing sync log
* You Airbyte deployment type: Docker / Kubernetes.
