### ISSUE TITLE
Fetching spec waits for too long in the UI when underlying jobs fails

### ISSUE THREAD

**Issue by michel-tricot** [airbytehq/airbyte#1406]
## Expected Behavior
As soon as the 3 attempts are finished, I want to see a failure on the ui

## Current Behavior
It seems to wait forever

## Steps to Reproduce
1. Try to pull spec from an image that doesn't exist

## Severity of the bug for you
Low because it only happens when building new connectors not when using airbyte

**Comment by cgardens** [comment]
I'm going to increase the priority on this one. It's pretty confusing. 

The issue is that the UI waits for all retries to complete before showing an error. This means we can wait 5 minutes for response (5 retries spaced a minute apart). While I think there's value in doing a 2-3 retries here, they should happen pretty much one right after another.

**Comment by cgardens** [comment]
fixed.
