### ISSUE TITLE
The server may still be starting up.

### ISSUE THREAD

**Issue by psalias2006** [airbytehq/airbyte#1409]
## Expected Behavior
running app
## Current Behavior
I follow the steps from the readme (just a docker-compose up) and the app is not running, Im getting the same msg on the app 
Cannot reach server. The server may still be starting up.
## Steps to Reproduce
1. clone
1. docker-compose up
1. localhost:8000

## Severity of the bug for you
Critical

## Additional context
*Environment, version, integration...*
I also just notice that I also have 2 dead containers with no logs

185c2f9ce0bc        airbyte/init:0.8.0-alpha         "/bin/sh -c './scrip…"   6 minutes ago        Exited (0) About a minute ago                                      init
cc19a87a2ba2        airbyte/seed:0.8.0-alpha         "/bin/sh"                6 minutes ago        Exited (0) About a minute ago                                      airbyte-data-seed

**Comment by psalias2006** [comment]
I just checkout v0.8.0-alpha is working!

**Comment by michel-tricot** [comment]
Thanks for reporting. Can we close it?

**Comment by ckaiser-graniterock** [comment]
Same issue when installing fresh using documentation here: https://docs.airbyte.io/deploying-airbyte/on-aws-ec2.

**Comment by cgardens** [comment]
@ckaiser-graniterock were you able to resolve your issue or are you still having problems? if so can you try again with 0.9.2-alpha?

**Comment by ckaiser-graniterock** [comment]
Yes. This was fixed by setting the api_url when performing docker-compose up -d. Similar to another user in the Slack channel posted earlier today.

**Comment by cgardens** [comment]
I believe this has been fixed by this PR: https://github.com/airbytehq/airbyte/pull/1524. Would we be good to close it?

**Comment by ckaiser-graniterock** [comment]
Yes. Thanks!

Cody Kaiser
Enterprise Data Warehouse Architect / Engineer
831-275-0575

**Comment by bbl-vidyut** [comment]
Hi there!
I periodically run into this error - "Cannot reach server. The server may be starting up."
![2291732c-6686-4c47-ba94-512cea140b88](https://user-images.githubusercontent.com/73094201/153031510-d1fe057c-3b74-4fad-941c-2db51ad57ccf.jpg)
 
 Could not see any errors in the logs for `airbyte-server`. 
 Neither could I see any particular errors in the logs for the `airbyte-scheduler`. Although, the Scheduler did keep logging `i.a.s.a.SchedulerApp(waitForServer):210 - Waiting for server to become available...`
![airbyte-scheduler logs screenshot](https://user-images.githubusercontent.com/73094201/153032221-179cfc86-aa76-47a2-99ab-a93bd870e065.png)

Despite shutting down and restarting docker, the front end (localhost:8000 over tunnel) showed the same error as indicated in the first image.
Intriguingly, some magic worked .... and about 10 minutes later, it worked. However, since I had to do `docker down`, I lost all my connections - which is obv not very ideal. So trying to understand what went wrong + how can I prevent this (non-ideal run-time concern) in the future.

As context, we are running v0.35.14-alpha

**Comment by dhananjayn0712** [comment]
Hi There:
I faced same issue saying "Server may still be starting up" and the reason was I had my VPN connected which eventually did not allow traffic from airbyte using docker. Disconnect the VPN and run below commands: 

cd airbyte/                                 -  Navigate to airbyte project folder.
1. docker-compose down -v     - This command will bring down all containers related to airbyte.
2. Disconnect VPN.
3. docker-compose up              - This command will start the container from fresh.
