### ISSUE TITLE
Add new streams to source-metabase connector

### ISSUE THREAD

**Issue by ChristopheDuong** [airbytehq/airbyte#14130]
## Tell us about the problem you're trying to solve
Following up on the initial implementation of source Metabase via #13131 
I would like to handle more streams to pull data from

## Describe the solution you’d like

For example, I would like to use the following query that should be an incremental stream to pull metadata on what users are looking at on the Metabase instance through the API:

```
curl -X POST \
  -H "Content-Type: application/json" \
  -H "X-Metabase-Session: <token>" \
--data-raw '{"limit":100,"type":"internal","fn":"metabase-enterprise.audit-app.pages.users/query-views","args":[],"offset":0,"parameters":[]}'   https://airbyte.metabaseapp.com/api/dataset
```
There might be more queries to pull data from and look at usage per card or dashboard

The activity stream should also probably be turned into an incremental stream btw.
It would be nice to have history changes / events on cards and dashboards.

**Comment by ChristopheDuong** [comment]
When adding new streams, we might need the `snippet` stream too!

**Comment by puru-khedre** [comment]
@justinbchau I want to work on it

**Comment by puru-khedre** [comment]
I open up a PR with `databases` & `native_query_snippets` streams are added. In my opinion the stream for the `/api/dataset` endpoint is not possible in Low-code language.

Because of two reasons:
1. It required body with `query` and `database` properties, value of query would be anything. And if we allow to add value of query in config, User can use only stream while the metabase have different many tables,
2. After getting response we don't already known the schema for the selected data
