### ISSUE TITLE
Custom Transformations: add ability to change order/position of transformers

### ISSUE THREAD

**Issue by philippeboyd** [airbytehq/airbyte#14185]
## Tell us about the problem you're trying to solve
Currently there's no way to reorder the custom DBT transformers.

![image](https://user-images.githubusercontent.com/3239656/175981341-9d2bfdab-64e7-4c7b-a045-424a9b103866.png)

Say I want to add a **custom DBT snapshot before my DBT run (`Create models`)**, I cannot add it. I need to delete my transformer `Create models`, add my new transformer, then re-add my previous one (to keep the order)

## Describe the solution you’d like
Be able to drag and drop (reordering) on the UI.

## Describe the alternative you’ve considered or used
Delete all custom transformers after the position that I want to add a new one and recreate them after I added my new one.

**Comment by sajarin** [comment]
Hey @philippeboyd thanks for the feature suggestion! The team will add it to the roadmap if we're able to implement it.

**Comment by nataliekwong** [comment]
Linking these related issues: https://github.com/airbytehq/airbyte/issues/23807

**Comment by chandlerprall** [comment]
question for @nora-airbyte : should the whole row be draggable, or only a handler at some location

**Comment by nora-airbyte** [comment]
A handler at the start of each row should do it
![drag_transformations](https://github.com/airbytehq/airbyte/assets/146028830/75e2efa0-d8a4-45f4-8011-983d8ba4e525)

**Comment by lmossman** [comment]
FYI we already have a place where we have draggable rows: in the User Inputs view of the connector builder:
<img width="1077" alt="Screenshot 2023-12-18 at 2 13 22 PM" src="https://github.com/airbytehq/airbyte/assets/22731524/7e5733e0-4ddf-49ec-bb98-2df372c7e466">

Here is the code that implements this: https://github.com/airbytehq/airbyte-platform-internal/blob/7f761e3b4973209b82d0ed96b3cde7917568225d/oss/airbyte-webapp/src/components/connectorBuilder/Builder/InputsView.tsx#L65-L71
And here is the PR that added it with details about the library used in the PR description: https://github.com/airbytehq/airbyte-platform-internal/pull/6969

Ideally, this code would be generified and reused for the feature described in this issue so that we don't have two separate drag-and-drop implementations.

**Comment by dizel852** [comment]
@lmossman Thanks for letting me know! 🙏 
Haven't noticed that we already have a dnd package 🤦‍♂️
