### ISSUE TITLE
Broken link to 'building new connectors' in docs

### ISSUE THREAD

**Issue by grishick** [airbytehq/airbyte#14320]
### Tell us about the documentation you'd like us to add or update.
On this page https://docs.airbyte.com/integrations/contributing-to-airbyte/ , this link  [building new connectors](https://docs.airbyte.com/integrations/contributing-to-airbyte/) is broken. Clicking it results in a 404 error.

### If applicable, add links to the relevant docs that should be updated
- [Link to relevant docs page](https://docs.airbyte.com/integrations/custom-connectors/)

**Comment by jromero** [comment]
FWIW, this seems related to this issue: https://github.com/facebook/docusaurus/issues/2654#issuecomment-621700521

If you navigate through the menu to `https://docs.airbyte.com/integrations/custom-connectors` you end up with no trailing space and "[contributing guide on building connectors](https://docs.airbyte.com/contributing-to-airbyte/)".

If you navigate to the same page via URL (ie type it into browser), a trailing slash is automatically added: `https://docs.airbyte.com/integrations/custom-connectors/` and the same link is now broken "[contributing guide on building connectors](https://docs.airbyte.com/integrations/contributing-to-airbyte/)" because "../contributing-to-airbyte" is now using a different relative directory.

**Comment by jromero** [comment]
I spent a little more time on this out of curiosity and I have to say, there doesn't seem to be a quick satisfactory fix for this due to my understanding that the docs use GitHub Pages. GitHub Pages is what creates the redirect for directories from  `custom-connectors` -> `custom-connectors/` (see behavior documented [here](https://github.com/slorber/trailing-slash-guide#summary)).

Adding [`trailingSlashes: true`](https://github.com/facebook/docusaurus/blob/main/website/versioned_docs/version-2.0.0-beta.21/deployment.mdx#trailing-slash-configuration-trailing-slashes) option to docusaurus does resolve the issue in that the behavior is predictable between navigation and browser input _but_ the links within markdown because awkwardly misleading. For example, in markdown, `[contributing guide on building connectors](../contributing-to-airbyte/)` would actually need to be `[contributing guide on building connectors](../../contributing-to-airbyte/)` which isn't accurate in the local filesystem given:

```
docs
│
├── contributing-to-airbyte
│   ├── README.md
│   └── ...
├── integrations
│   ├── README.md
│   ├── custom-connectors.md # <-- LINK HERE
│   └── ...
└── ...
```

There may be other options I haven't found or considered. I'd be interested to hear what the maintainers think would be the best possible path forward given the constraints.
