### ISSUE TITLE
Add config-based connector option to connector template

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#14361]
## Problem
Config-based connectors require slightly different boilerplate from our standard CDK connectors. 
I've been manually updating the files whenever I worked with a config-based connectors, but we should enable the code genrators to produce the right boilerplate so developers don't need to modify the files by hand.

## Suggested solution
The generator should produce the same file as it does for CDK connectors with the following differences:
- the source.py file should look like [this file] (https://github.com/airbytehq/airbyte/blob/bf910ccf25e566d8137b7883ddcb5003d42bd006/airbyte-integrations/connectors/source-sendgrid/source_sendgrid/source.py), where the class name and path to yaml are templated based off the connector name (see https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/source-python-http-api/source_%7B%7BsnakeCase%20name%7D%7D/source.py.hbs for a template example)
- generate a connector_definition.yaml file similar to [this file](https://github.com/airbytehq/airbyte/blob/bf910ccf25e566d8137b7883ddcb5003d42bd006/airbyte-integrations/connectors/source-sendgrid/source_sendgrid/sendgrid.yaml), containing
  - a single stream definition
  - the default schema_loader
  - a requester with no pagination
  - no pagination 
  - no stream slicer
  - mocked out authentication, url_base, primary_key, path, and record selector

**Comment by girarda** [comment]
grooming notes:
* need to ensure we're not leading devs in the wrong path with stream slicer examples

**Comment by pedroslopez** [comment]
Regarding the stream slicer examples, I would suggest keeping the generated content to basic components that are needed to build most connectors with just enough to get you started, and using docs to communicate the additional or more complex features that may not be required. It can be confusing when theres a lot of generated code with things that aren't going to be used, and could make things seem more complicated than it is.

So more concretely for slicers, if it's something that you're going to have to implement most times then I think it's fine to have on the generator. Otherwise, docs is probably more appropriate.
