### ISSUE TITLE
Source Google Ads: not able to use custom queries GAQL don’t allow segments.date parameter

### ISSUE THREAD

**Issue by serhio7** [airbytehq/airbyte#14446]
## Environment
- **Airbyte version**:  is 0.39.1-alpha
- **OS Version / Instance**: macOS,
- **Deployment**: Docker
- **Source Connector and version**: Google AdsBETA 0.1.38
- **Step where error happened**: Sync job

## Current Behavior
*Got error when run sync job on custom GAQL .*

## Expected Behavior
*Completed sync job.*

## Logs
Cannot select or filter on the following segments: \'segments.date\'(could not support requested resources: \'GEO_TARGET_CONSTANT\'), since segment is incompatible with the resource in the FROM clause or other selected segmenting resources." )

## Steps to Reproduce
1.Add custom GAQL to Google Ads  SELECT geo_target_constant.country_code, geo_target_constant.id FROM geo_target_constant
2. Run sync job

**Comment by marcosmarxm** [comment]
Thanks @serhio7 I added the issue in connector team backlog.

**Comment by midavadim** [comment]
Problem description: custom query is converted to the one which can be fixed for incremental sync. 

Source modify custom query by adding:
1. 'segments.date' columns 
2. additional WHERE conditions: "segments.date BETWEEN '{start_date}' AND '{end_date}"

Example from customer:

CUSTOM QUERY:
SELECT geo_target_constant.country_code, geo_target_constant.id FROM geo_target_constant

FINAL QUERY (after modifications):
SELECT geo_target_constant.country_code, geo_target_constant.id, segments.date FROM geo_target_constant WHERE segments.date BETWEEN '{start_date}' AND '{end_date}

And the problem is that "geo_target_constant" API resource does not have such a column as 'segments.date'

Solutions:
- add additional limitations/requirements for custom queries
or
- somehow identify API 'resources' which does not support 'segments.date' columns and perform full_refresh syncs for such custom queries.

**Comment by MaxKrog** [comment]
Same issue here, trying to query the source/table **conversion_action**

Does anyone here with more experience of the Google Ads connector have the possibility to point me at interesting lines of code for solving this issue? Would be happy to contribute

**Comment by grubberr** [comment]
I have added support for custom full-refresh streams
right now I have added only 2 google ads tables:

https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-google-ads/source_google_ads/source.py#L40

in future, it would be possible pretty easily add new tables which can only work in full_refresh mode

**Comment by jpmmcneill** [comment]
@grubberr why not make this configurable on the custom query level to allow faster feedback?
