### ISSUE TITLE
Google Sheets Destination does not emit state when records are persisted. 

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#14748]
## Problems

Consider the following section of the Google Sheets destination code:  https://github.com/airbytehq/airbyte/blob/71ab5ff21653f4e8e4341f5d5b044eb1424adc5a/airbyte-integrations/connectors/destination-google-sheets/destination_google_sheets/destination.py#L63-L73

Every time the destination receives a record, it adds it to a queue to send later.  The queue is sent only once we have 1000 records to sent to the stream (sheet).  We also immediately echo any state messages we receive. This is not what is expected for a few reasons:

1. A destination emitting a state message indicates to the platform that any preceding records for that stream have been persisted in the destination.  Since the records have only been added to a queue to be sent later, this is incorrectly signaling that those records are stored in the sheet.  This means if the sync were to crash, we won't retry those records.
2. Because the queues storing records to upload are only flushed once the queue's length is 1000, this can lead to memory issues.  If rows are particularly wide or there are many streams with sparse data, these queues won't be sent and cleared until the end of the sync (`writer.write_whats_left()`).  This ever-increasing memory usage makes an OOM crash more likely.  

Combining both issue 1 and 2 leads to an unstable destination 

## Solutions

1. State messages need to be stored and echoed only once the records that preceded those message have truly been committed to the destination.
2. We need to more regularly clear the queues to reduce the memory load of the connector

Proposal:  Every time a state message is received, we flush all the pending queues.  

```py
 for message in input_messages: 
     if message.type == Type.RECORD: 
         record = message.record 
         # process messages for available streams only 
         if record.stream in configured_stream_names: 
             writer.add_to_buffer(record.stream, record.data) 
             writer.queue_write_operation(record.stream) 
     elif message.type == Type.STATE: 
         writer.write_whats_left() # <-- Change
         yield message 
     else: 
         continue 
```

This small change will work with the legacy state messages and the new per-stream state messages.  We will be writing more, which leads to a more stable sync, but likely slower performance.

**Comment by bazarnov** [comment]
@evantahler 
Good point. Thanks for the issue and suggestions, If we need only to clean the buffers, I'll check whether we can use some other methods for this, after the STATE message is received, because `writer.write_whats_left()` was designed to do other things. 
I'll create the PR starting next week to cover this issues.

**Comment by bazarnov** [comment]
Couple of moments from the code:
1) `writer.queue_write_operation(record.stream)` cleans the `records_buffer` once the `flush_interval` is hit, so another buffer clean command will not have any effect on memory usage, I believe.
2) If we add additional cleaning of the buffer, let's reuse the method called: `clear_buffer()`, I've suggested the correction in the latest commit. Also, I've decreased the `flush_interval` to be `500` instead of `1000`, this will bring state messages more frequently and buffer clean as well. But in any way this should be properly handled by what @sherifnada suggested here: https://github.com/airbytehq/oncall/issues/338#issuecomment-1185670288, I completely agree.
