### ISSUE TITLE
Dev database out of sync with logs

### ISSUE THREAD

**Issue by alovew** [airbytehq/airbyte#14760]
This is the issue that occurred: https://github.com/airbytehq/airbyte/issues/10575

This ticket is not to fix the underlying issue and prevent this from happening, but rather to get dev back into a usable state. The dev jobs db appears to have been deleted, and since the job ids in the db are used to point to that job's logs stored in google cloud, the logs are out of sync which the jobs. In order to fix this, I think the jobs db will have to be reset, and the logs deleted, as well as the dev state storage (which also uses the job id):  https://console.cloud.google.com/storage/browser/dev-ab-state-storage/%2Fstate/jobs?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&project=dev-ab-cloud-proj&prefix=&forceOnObjectsSortingFiltering=false

This is blocking testing for a feature that uses Datadog. Dev is the only cluster that has datadog enabled, so using this one specifically is required for testing this feature.

**Comment by supertopher** [comment]
I have deleted the buckets for state storage and for app logs.  (allow up to 10 minutes for the app logs to finish deleting)
I need to log into the dev database to clear those records.  I think you may be able to do your work now anyway though. 

can you see how your environment looks?  If I understand the error correctly, your logs are criss-crossed because all logs run append operations.  I believe you will see an environment with missing logs for old jobs, but correct logs for new jobs

documented my actions here, though without admin permissions I'm not sure how self service this can be https://github.com/airbytehq/airbyte-cloud/pull/2080

**Comment by alovew** [comment]
It looks like someone is using dev right now, so we might want to make sure nobody is using it when we delete everything so nothing gets out of sync.

**Comment by alovew** [comment]
I think you're right that we might not need to clear out the jobs db - I can't test right now since someone else is using dev though.

**Comment by supertopher** [comment]
We found a previously unknown retention policy that blocked the work from completing on Friday.  The guide that I linked has been updated with a workaround for the policy so we can actually delete logs.  Deletion is ongoing... again because it takes forever to actually run

**Comment by alovew** [comment]
Hi Topher! Is this complete?

**Comment by supertopher** [comment]
all the logs were deleted, however Xiohan was using the cluster so I'm not quite sure how that fits into your needs

**Comment by alovew** [comment]
@supertopher I'm still seeing this issue on dev and I'm not sure why. Here's a link to the job: https://dev-cloud.airbyte.io/workspaces/d7510f1c-9bf8-454d-a802-b707cecf3961/connections/0d0a2453-36eb-4d87-b7fc-1c44ba2c8b97/status

It's for the pokeapi, but it's showing 10k records synced, so it's definitely logs for the wrong job.

**Comment by cpdeethree** [comment]
Closing, will revisit with ephemeral environments
