### ISSUE TITLE
Update Button component to match current design

### ISSUE THREAD

**Issue by edmundito** [airbytehq/airbyte#14847]
The current Button component does not match the current design:
https://www.figma.com/file/gMNRYVJav25pdsoxAyW7Qp/00_01_WEB-APP-LIBRARIES?node-id=2%3A395

* Review the design and finalize with our designer, and implement the new button changes.
* Update component to use SCSS over styled components.
* Update component to support icon and icon side properties instead of being set by the `children` by each button implementation
* Add loading state and deprecate `LoadingButton` component
* Adjust all pages to make sure updated buttons look good
* Break down changes into separate PRs where possible

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by timroes** [comment]
As part of this I'd suggest we could also cleanup the button component for two things:

* Merge LoadingButton into Button and just have it a property of the component.
* Give a simple property option to add an icon onto the button (currently e.g,. we just use `+` as a character in the string instead of an icon).
