### ISSUE TITLE
CDK: Run MyPy as part of CI

### ISSUE THREAD

**Issue by pedroslopez** [airbytehq/airbyte#14907]
MyPy checks are currently failing on the CDK:

```
$ mypy airbyte_cdk unit_tests
[...]
Found 66 errors in 31 files (checked 218 source files)
```

Searching for existing issues, this is something that has happened a few times #9500 #9926 #9037

Mypy is important to run because it: 
1. Prevents us from leaving a million "nit: please type hint" comments in PRs
2. Catches mis-uses of types which could cause bugs

To ensure this doesn't keep happening, we should add running mypy as part of our CI.

## Acceptance criteria
- Fix mypy issues on airbyte_cdk and its unit tests
- mypy runs as part of our CI checks for the CDK (add to the build)

**Comment by pedroslopez** [comment]
grooming notes:
- after fixing current issues, enforce type hints via mypy option
- should we do this for all python projects
- cdk might be a good start to enable and check the issues that comes up, and then we can add this to all the other python modules
- also do it for SAT
- could we show a warning on connectors that are failing and give it a time frame to comply

- opt in flag for airbytePython plugin (?) 
- we should use the same mypy config for everything

**Comment by sherifnada** [comment]
Some additional context: 
* `./type_check_and_test.sh` in the CDK directory can be used to run mypy locally
* As part of this ticket we should take the time to fix the mypy failures happening in the CDK

**Comment by girarda** [comment]
I did a spike in [this PR](https://github.com/airbytehq/airbyte/pull/27790).

- It is possible to check changed files (`mypy ${{ steps.changed-py-files.outputs.all_changed_files }}`) (https://github.com/airbytehq/airbyte/pull/27790/files#diff-0d634959c8276ae976e39ba475e63d0b9ec27824470c79f1971f58fe37c46325R205)
- ^This will require using follow_imports = silent to ignore files that are imported, but not modified  

Proposal is to turn on mypy and to fix the failures as we modify the codebase instead of trying to fix them all at once.
We should fix one module (I suggest file based) as a demo.

- To investigate: the spike ignores "attr-defined" because I wasn't able to import the types from the airbyte-protocol. Alternative is to keep ignoring these errors for the time being since running most checks now is better than running all checks later

## Acceptance criteria
- CDK build runs mypy on modified changes
- CDK documentation is updated with instructions on how to run mypy locally
- mypy failures in the file based module are fixed

**Comment by sherifnada** [comment]
great find @girarda

**Comment by girarda** [comment]
grooming notes:
- Option: we can scope this to only checking source code (not unit tests) if checking the unit tests is too much effort
- additional acceptance criteria: document escape hatch to allow us to push in hotfixes (#noqa, approve-bot, remove step from the pipeline)
