### ISSUE TITLE
Postgres CDC stops syncing new rows

### ISSUE THREAD

**Issue by ameyabhope** [airbytehq/airbyte#14932]
## Environment
- **Airbyte version**:  0.39.2-alpha
- **OS Version / Instance**: GCP n2. 
- **Deployment**: Docker
- **Source Connector and version**: 0.4.30 
- **Destination Connector and version**: BigQuery 1.1.11 
- **Step where error happened**: Sync job

## Current Behavior
*Tell us what happens.*
Logical replication stops syncing new rows and yet shows a `Succeeded` sync with no records. This seems to happen without any kind of change to either the version or the source dataset.
Posting 3 log files below - 
484689 - Last successful sync job (Log1)
484702 - Successive job which doesn't sync any new rows yet says Succeeded. (Log2)
485136 - Successive job to Log2, again doesn't sync any new rows yet says Succeeded (Log3)

Checking the source tables, there is data that should have shown up in Log2 as well as Log3.

<img width="348" alt="Screen Shot 2022-07-21 at 8 27 30 AM" src="https://user-images.githubusercontent.com/21052763/180252791-d6dbefa6-99ef-4ac6-8972-3dc111202d29.png">

Looking at the logs, Log1's `closing debezium state` (line 21561) matches Log2's `Initialized CDC state`(line132) i.e. same `lsn_proc`, `lsn_commit` and `lsn`.

But, Log2's `closing debezium state`(line 875) is exactly same as it's `Initialized CDC state` (line132) i.e. no change in lsn numbers even though there are new rows to be sync.

Similarly, Log3's `Initialized CDC state` (line 131) is exactly same as Log2's closing and initializing states with it's closing state as same.

## Expected Behavior
*Tell us what should happen.*
Logical replication should sync new rows as expected. The only remedy to problem is to do full resets (which for us with about 107GB data take about 4 hrs to complete), which isn't ideal. After a full reset, a few sync jobs run without any issues; but again this same problem reappears.

## Logs

[Log1 484689.txt](https://github.com/airbytehq/airbyte/files/9160820/Log1.484689.txt)
[Log2 484702.txt](https://github.com/airbytehq/airbyte/files/9160822/Log2.484702.txt)
[Log3 485136.txt](https://github.com/airbytehq/airbyte/files/9160823/Log3.485136.txt)

## Steps to Reproduce
1. Start logical replication sync (pgoutput plugin)
2. See `succeeded` sync message but no new rows are synced

## Are you willing to submit a PR?

Yes, if pointed in the right direction.

**Comment by harshithmullapudi** [comment]
Hey @ameyabhope have triaged the issue so to that it reaches the team

**Comment by dhk** [comment]
What's the next step with this ?

**Comment by grishick** [comment]
@dhk this should be fixed now. Have you tried Postgres Source connector version 1.0.0 or greater?

**Comment by ameyabhope** [comment]
@grishick Tried to resync with 
- Airbyte version: 0.40.3
- Source Connector and version: Postgres 1.0.7

After the initial sync (post-reset), new rows were replicated for a few cycles. After which intermittently it started syncing all the rows instead of just the new rows.

Here's the log of the last successful run - 
[logs-558829.txt](https://github.com/airbytehq/airbyte/files/9559303/logs-558829.txt)

and the following 2 are logs where it started to sync from scratch - 

[logs-558850.txt](https://github.com/airbytehq/airbyte/files/9559307/logs-558850.txt)
[logs-558888.txt](https://github.com/airbytehq/airbyte/files/9559308/logs-558888.txt)

These 2 were cancelled after 45mins, since we have an auto-cancellation for long running jobs.

Pls lemme know if any other info is needed.

**Comment by grishick** [comment]
@ameyabhope this is why it is syncing from scratch:
```
Saved offset is before Replication slot's confirmed_flush_lsn, Airbyte will trigger sync from scratch
```
I suspect that your Postgres DB is purging WAL in between Airbyte jobs (perhaps to prevent filling up the disk). Could you try running airbyte sync jobs more often and extend the auto-cancellation timeout?

**Comment by ameyabhope** [comment]
@grishick The DB isn't purging WALs in between jobs - earlier when the new rows stopped syncing the WAL size kept increasing, since nothing was consuming it. So no purging would be happening now.

Checking the source db, only a few rows were added between the runs so it shouldn't take longer than 45 mins to sync. 
Our sync jobs run every 15 mins.

**Comment by grishick** [comment]
@ameyabhope one more question - is Airbyte reading from a leader or a follower replica?

**Comment by ameyabhope** [comment]
@ameyabhope It's reading from the main (leader) instance of the Postgres DB.

**Comment by shrodingers** [comment]
@grishick @ameyabhope, I have the exact same issue with syncs triggered from scratch, and I noticed that was tied with this message on the prev sync (causing the lsn not to be correctly stored on the state of connection, thus triggering a full refresh on next sync)

```
2022-09-19 07:37:38 INFO i.a.w.g.DefaultReplicationWorker(run):268 - Source did not output any state messages
WARN i.a.w.g.DefaultReplicationWorker(run):276 - State capture: No new state, falling back on input state: {input state}
```
Except there was some update that shall be persisted to the state since lsn cursor has been moved. This happens for me on two connection with kinda huge data volumes, and around once every two days

**Comment by gianniskod** [comment]
Hello, I believe that we have faced the same issue with the Postgres Connector. I have created a discourse thread describing thoroughly our use case, which matches a lot with the one [ameyabhope](https://github.com/ameyabhope) has shared.

Airbyte Discourse Thread: https://discuss.airbyte.io/t/stack-syncs-and-automated-full-resyncs-on-cdc/2675

**Comment by sh4sh** [comment]
Hi folks, if you're still experiencing this issue can you try the latest Postgres source connector version v1.0.14 and let us know if it helped? There was a Debezium upgrade in v1.0.13 that may improve this behaviour @ameyabhope

**Comment by subodh1810** [comment]
Alright so I see 2 different issues being discussed here. 
1. CDC not syncing new data -> I went through the logs and you will see the message `2022-07-20 22:53:24 [44msource[0m > 2022-07-20 22:53:24 [32mINFO[m i.a.i.d.i.DebeziumRecordIterator(computeNext):78 - Closing cause next is returned as null
` We have a timeout for receiving records from debezium. If debezium doesnt return a record within that time period, Airbyte assumes there are no records in the source to be returned and shuts down. This can happen when your WAL logs contain records from tables that you are not syncing. In this case, debezium will just iterate through these WAL records but will not return anything back to Airbyte. By default the waiting time is 300 seconds but it can be increased. I advice you to increase it. Also we acknowledge that this is not ideal behaviour and is a but hacky and thats why we have an [issue](https://github.com/airbytehq/airbyte/issues/15040) to improve this. Debezium provides a feature called heartbeat which we think can be used to solve this problem and the user wont have to worry about setting the right value for the waiting duration. But until we implement it, a work around as mentioned is to increase the duration from 300 seconds.

2. error in processing a message at a certain lsn that causes a full refresh on next sync => maybe related to previous case, since it is also a case when state message is missing -> So as debezium reads through WAL logs, it also acknowledges it on the source database which allows postgres to clear WAL logs. Now imagine we were not able to load data into the destination successfully (cause destination failed or some error occurred), we wont be able to save the state. In the next sync, we will try to start from the WAL log which has already been deleted and as a result we dont have any option but to sync everything from scratch. We have an [issue](https://github.com/airbytehq/airbyte/issues/15214) to provide users the ability to decide when would they want Airbyte to acknowledge the LSN. 

I am going to close this issue and request you to track the above mentioned issue.
