### ISSUE TITLE
Add toggle for advanced mode for connection state

### ISSUE THREAD

**Issue by timroes** [airbytehq/airbyte#15145]
Since we see users regularily stumble across that, we should add a "Advanced Mode" in the setting that when turned on will give access to more advanced features, that are hidden by default. We should make the Connection state one of those features.

Ideally that setting would be on the user object in the database, but we could for now also make it a localstorage setting instead, for the ease of the implementation.

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by ambirdsall** [comment]
This be an account- and workspace-specific setting, right? In that case, it makes sense to put it in "workspace settings" for cloud (with the account implicitly available from the user's login) and "account settings" for OSS (where the workspace is implicitly available since there's effectively a singleton workspace for the OSS version). That all seem reasonable?

**Comment by edmundito** [comment]
Discussed in planning - @lmossman  will take over to merge and close this issue while @ambirdsall is on PTO
