### ISSUE TITLE
Source File: support oauth

### ISSUE THREAD

**Issue by HALLOWe3n** [airbytehq/airbyte#15230]
## Tell us about the problem you're trying to solve
With the release of Airbyte Cloud, we need to start supporting Oauth for this connector, since it's the recommended way of authenticating users into a SaaS application.

If this connector doesn't support oauth already (i.e: doesn't accept a client_id and client_secret) then we need to update its spec to accept those parameters. There are two ways to do this:

If the connector already supports some auth mechanism like api_key, I suggest that this be a oneof nested inside a top-level field called "authentication":

{ authentication: { type: object oneOf: [ // api key, // oauth ] } }

If the connector only supports webflow oauth, then no changes are needed to the properties format and we will only need to add annotations.

See the connector spec reference in the docs for reference on how a oneof can be implemented.

This should be done in a backwards compatible manner i.e: users currently supplying authentication info in the config's top-level should not be impacted by this change.

## Acceptance criteria
The connector supports oauth webflow authentication with client_id/client_secret in a backwards compatible manner
Oauth properties are annotated properly. See this PR for an example

**Comment by midavadim** [comment]
Hi all,

I have checked specs for source-file and it appears that 3 of 7 "Storage Provider" could support Oauth2: GCS, S3, AzBlob.

The problem is with limitation in spec.json file which does not allow to set 'multiple' ouath2 credentials, example of spec file if I enable oauth for GCS only, but there will be no way to enable oauth2 for other storage providers:

"authSpecification": {
    "auth_type": "oauth2.0",
    "oauth2Specification": {
      "rootObject": ["provider", 1, "credentials", 0],      **<--- path to GCS (index=1) only**
      "oauthFlowInitParameters": [["client_id"], ["client_secret"]],
      "oauthFlowOutputParameters": [["refresh_token"]]
    }
}


Solutions:

Solution_1:
Re-build the completely spec file with the idea to change nesting levels:

from: StorageProviderType(Http,local.gcs...) -> CredentialType(apikey, oauth2, etc)
    to: CredentialType(apikey, oauth2, etc)    -> StorageProviderType(Http,local.gcs...), for example:

Authentication:
 - "No authentication (Https, localfile)"
 - "SSH creds (sftp, scp, ftp)"
 - "Access token (GCS, S3, AzBlob)":
    Provider: GCS
    Provider: S3
    Provider: AzBlob
 - "Oauth2.0 (GCS, S3, AzBlob)":
    Provider: GCS
    Provider: S3
    Provider: AzBlob

This approach allows to specify simple path to oauth2 cred like:

"authSpecification": {
    "auth_type": "oauth2.0",
    "oauth2Specification": {
      "rootObject": ["Authentication", 3],
      "oauthFlowInitParameters": [["client_id"], ["client_secret"]],
      "oauthFlowOutputParameters": [["refresh_token"]]
    }
}

but UX is not the best.


Solution_2:
Implement Oauth2 for 1 storage provider only - new "Box" provider, which actually does not have other good authentication methods.


Solution_3:
Update CDK to support multiple ouath2 creds in one connector

Solution_4:
create separate 'source-file-oauth2.0' connector which supports only oauth2.0 authentication.

**Comment by midavadim** [comment]
The task is put on hold, because of oauth limitation in spec file

**Comment by midavadim** [comment]
https://airbytehq.slack.com/archives/C02U9R3AF37/p1660162097867779?thread_ts=1660146198.763629&cid=C02U9R3AF37

**Comment by midavadim** [comment]
Issue is closed according to the conversation in slack:

https://airbytehq.slack.com/archives/C02U9R3AF37/p1660162097867779?thread_ts=1660146198.763629&cid=C02U9R3AF37
