### ISSUE TITLE
Helm Chart: external minio with S3 object storage

### ISSUE THREAD

**Issue by subhranil05** [airbytehq/airbyte#15254]
Hi Team,

I'm trying to implement external minio with S3 object storage and also with external postgres in airbyte helm charts but minio internal minio is getting deployed everytime ignoring the 'enable: false' option and temporal pod is not coming up searching for the external postgres but I checked all parameters releted to external postgres is ok. 

Please guide me on this. thanks much on advance !!!!

**Comment by natalyjazzviolin** [comment]
Hello @subhranil05, could you please edit your comment with the template below? This will give me enough details to better help you and triage this. Thanks!

## Environment
- **Airbyte version**:  
- **OS Version / Instance**:
- **Deployment**:
- **Source Connector and version**: 
- **Destination Connector and version**:
- **Severity**: 
- **Step where error happened**:

## Current Behavior

## Expected Behavior

## Logs

## Steps to Reproduce
1.
2.
3.

## Are you willing to submit a PR?

**Comment by subhranil05** [comment]
hey ,I have tested airbyte by setting external postgres and minio , logs are successfully sent to external minio buckets for S3 and GCP, but wondering why azure blob option not given , can you help me please?

**Comment by natalyjazzviolin** [comment]
@subhranil05 just to confirm - your issue is now resolved?

**Comment by marcosmarxm** [comment]
Closed due inactivity.
