### ISSUE TITLE
Allow users to turn off SSL on cloud

### ISSUE THREAD

**Issue by tuliren** [airbytehq/airbyte#15265]
## Tell us about the problem you're trying to solve
The strict encrypt connectors implicitly enforce SSL connection. These connectors are used in cloud. The purpose of this behavior is to ensure all traffic is encrypted when the data is transmitted through the open internet.

However, this configuration has a few downsides:
- When SSH tunneling is enabled, the data is double encrypted. It is unnecessary, and slows down the sync.
- If the database is running in a container, SSL cannot be used.

## Describe the solution you’d like
Expose this option on cloud, and let users choose what to do.

## Describe the alternative you’ve considered or used
- Do not enforce SSL when SSH is enabled.
- Detect whether SSL is supported by the environment the database is running in, and do not enforce SSL when it is not possible.

## Additional context
Slack [thread](https://airbytehq-team.slack.com/archives/C02UF50V9HA/p1659373561932189) for airbyters only.

**Comment by grishick** [comment]
one way to do this is to allow selecting "allow" or "prefer" SSL modes, but ideally that would be possible only if SSH tunnel is enabled

**Comment by terencecho** [comment]
Commenting to share that the cloud platform team is interested in this ticket!

Most of the acceptance tests for running syncs only run in OSS right now, and the cloud team is trying to port over some of them to run on the cloud repo (along with testing other things like credits/auth permissioning). The initial attempt was to do an almost 1:1 copy of the OSS basic acceptance tests regarding testing incremental sync with changes to use postgres-strict-enforce configs.

Technically this is not a hard blocker since we can use a different source for our acceptance tests, although I would like it to be similar to our OSS acceptance tests. Adding more acceptance tests for cloud is one of the cloud platform team’s goals for the quarter.

**Comment by tuliren** [comment]
This is no longer a high-priority issue. Platform can add an `is_test` flag to the config and bypass the SSL modification.

**Comment by grishick** [comment]
We have a policy of not allowing unencrypted traffic in/out of Airbyte Cloud to/from customer resources, so we should only allow turning off SSL to customers when they have enabled SSH tunneling. Currently, that's not possible due to UI limitations.
