### ISSUE TITLE
[webapp] Connection sync log link does not land on log component

### ISSUE THREAD

**Issue by edmundito** [airbytehq/airbyte#15320]
## Environment
- **Airbyte version**:  v0.39.41-alpha
- **Step where error happened**: Connection Status Page

## Current Behavior
When opening the connection log link, the page does not scroll down to the log nor expands it

## Expected Behavior
When opening the connection log link, the page scrolls down to the log and expands it

## Steps to Reproduce
1. Open the airbyte webapp
2. Navigate to a connection with multiple syncs completed
3. Scroll to the last sync job, expand and click the copy link button
4. On a new browser tab or window, paste the link and go

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by timroes** [comment]
The problem for this is in https://github.com/airbytehq/airbyte/blob/master/airbyte-webapp/src/components/JobItem/JobItem.tsx#L56 (and likely one more file with similar code). There is a missmatch in types, since some IDs are `string` and some `number` and we always get a `string` from the URLs, but try to `===` match that with a numeric ID (the TS types are not showing that right now, the `getJobId` method casts types, and thus actually breaks the correct TS typing), i.e. to fix that we should make sure to fix the `getJobId` method to not use casting, and at that point will see the type missmatch and address that.
