### ISSUE TITLE
Cron string: make supported timezones available to frontend

### ISSUE THREAD

**Issue by mfsiega-airbyte** [airbytehq/airbyte#15593]
See conversation in https://github.com/airbytehq/airbyte/issues/11431 for context.

**Comment by pmossman** [comment]
Refining notes:
- Core question is: how do we keep Frontend and backend in sync when it comes to supported timezones?
- Java packages supported timezones, and stuff can change without us necessarily knowing about it
- Can add a test that compares the Java source of truth to the list used by the front-end
- Might not actually be worth doing anything, since builds should fail pretty loudly if timezones change
- Could have the file live in the server, and during build, place it in the front-end location at build time?
- Best effort to value tradeoff is probably to write the test, don't worry about moving things to a common module, have an error message explaining what to do if it fails.
