### ISSUE TITLE
Understanding the behavior of "Incremental Dedup History" sync

### ISSUE THREAD

**Issue by skt7** [airbytehq/airbyte#15661]
Hi,

We are trying to understand how exactly the syncs occur for the "Incremental Dedup History" sync mode. Sharing our analysis and some of the queries. It would be great if someone could validate the understanding and clarify the questions.

## Setup
Source: Postgres
Destination: Postgres
Base Data: about 3.5 million rows 

## Sync Runs
Run 1: Initial data transfer (3510433 rows transferred), time taken: 22m 30s, rows committed: 3510433, rows emitted: 3510433  
Run 2: Single row updated, time taken: 54m 43s, rows committed: 3510434, rows emitted: 3510434
Run 3: 235 rows updated, time taken: 13m 21s, rows committed: 235, rows emitted: 235  
Run 4: Single row updated, time taken: 5m 11s, rows committed: 1, rows emitted: 1  
Run 5: 15000 rows updated, time taken: 5m 45s, rows committed: 30000, rows emitted: 30000   
Run 6: 100000 rows updated, time taken: 9m 5s, rows committed: 200000, rows emitted: 200000   

Attaching image for reference (run order is: oldest bottom, latest top) - 
![airbyte](https://user-images.githubusercontent.com/26714108/184654785-bbfc0933-8f53-4dee-8165-c67672fef32b.png)

## Queries
Run 1: NA

Run 2: Only a single row was updated, but it took 54m 43s to complete the sync.
Our Understanding: As it was the very first sync after the base data transfer, there were certain one-time processes that were required to run - Can you please validate if the understanding is correct, and would be great if you can share info on what exact processes occur during this?

Run 3: NA

Run 4: NA

Run 5 & Run 6: Rows emitted & Rows committed show double the number.
Our Understanding: NA - Can you please explain why it shows double the number i.e. in Run 5 only 15000 rows were updated whereas it shows 30000 as emitted and committed?

**Comment by harshithmullapudi** [comment]
Hey could you share the logs for these syncs?

**Comment by yash-ghelani-dsw** [comment]
> Hey could you share the logs for these syncs?

Hi @harshithmullapudi , I am colleague of @skt7 , please find the logs below:
Run - 1:
[logs-123.txt](https://github.com/airbytehq/airbyte/files/9399370/logs-123.txt)
Run - 2:
[logs-124.txt](https://github.com/airbytehq/airbyte/files/9399373/logs-124.txt)
Run  - 3:
[logs-125.txt](https://github.com/airbytehq/airbyte/files/9399376/logs-125.txt)
Run - 4:
[logs-126.txt](https://github.com/airbytehq/airbyte/files/9399377/logs-126.txt)
Run - 5:
[logs-127.txt](https://github.com/airbytehq/airbyte/files/9399381/logs-127.txt)
Run - 6:
[logs-128.txt](https://github.com/airbytehq/airbyte/files/9399385/logs-128.txt)

**Comment by harshithmullapudi** [comment]
Hey have requested to team to look into this.

**Comment by subodh1810** [comment]
Alright let me see if I am able to explain it precisely or not :
1. Run 1 : This is the first sync that runs for the connector. We pull in all the existing data from the source database and move it to the destination. This takes around 22 minutes. As you can imagine, most of the time is spent in pulling data from the source. The normalization takes just around 4 minutes. (Ref logs-123.txt file)
2. Run 2 : This is where we switch to WAL logs processing, and read WAL logs and pull data from it. If you take a look at the start and finish log from the source, we spent around 19 minutes for pulling data from the WAL logs.

START LOG:
```
2022-08-13 06:50:28 [32mINFO[m i.a.w.i.DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-08-13 06:50:28 [32mINFO[m i.a.i.b.a.AdaptiveSourceRunner$Runner(run):85 - Starting source: io.airbyte.integrations.base.ssh.SshWrappedSource
```
FINISH LOG: 
```
2022-08-13 07:09:25 [44msource[0m > 2022-08-13 07:09:25 [32mINFO[m i.a.i.b.a.AdaptiveSourceRunner$Runner(run):87 - Completed source: io.airbyte.integrations.base.ssh.SshWrappedSource
```
So its evident that the majority time was not spent in pulling data from the source, the majority time was spent in Normalization.
```
2022-08-13 07:45:08 [32mINFO[m i.a.w.g.DefaultNormalizationWorker(run):73 - Normalization executed in 32 minutes 51 seconds.
```
Now regarding the question why do we see so many records when according to the user only 1 record was updated, it seems these records were already present in the WAL logs. From the time a replication slot is created, any change happening to a table will be put in WAL logs and will not be cleared until the replication slot consumer has acknowledged it. It seems like the user first created the replication slot then made tons of writes to the table and then triggered a sync. Now all those writes were also sent to the WAL log and stayed there for the consumer of the replication slot. In the first sync we took the snapshot of the table. In the second sync we switched to the WAL log processing and asked the replication slot to provide with WAL logs and since this is the first time we consume the WAL logs, all those previously held records also pop up.  The user is assuming that between two syncs he only made 1 change so only 1 change should be propogated but since this is the first time we are processing the WAL logs from the replication slot, so everything that the replication slot has is being sent to the connector by the source. (Ref logs-124.txt file)

3. Sync ran as usual, nothing weird
4. Sync ran as usual,  nothing weird
5. and 6. Am not sure I see anything weird. We dont do any extra processing on our end. We just connect to the WAL log and whatever the source WAL logs provide Airbyte source connector, its sent downstream and it seems like the source sent those many WAL logs. I dont see any weird behaviour in the logs.
