### ISSUE TITLE
adopt connector best practices in google ads source

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#1568]
## Tell us about the problem you're trying to solve
We'd like to follow [the published connector development best practices ](https://docs.airbyte.io/contributing-to-airbyte/building-new-connector/best-practices-for-connector-development) on this connector. 

Since this connector is Singer based, for each of the below items please verify whether:
- the singer tap already implements it
- the singer tap does not implement it and would require forking the tap to implement
- it's something we can implement easily on top of the Singer tap without forking it

**If implementing any of the below items would require forking the Singer tap, please notify @sherifnada and move on to the next issue.** 

## Checklist
- [ ] Check connection verifies permissions upfront
- [ ] Check connection failure emits actionable error messages. This will probably require you to think about the failure modes that can occur (e.g: timeout, permission not granted, token does not exist, etc.. -- make sure that you add custom integration tests to verify each of these failure modes, or unit tests if you can mock the HTTP requests involved)
- [ ] If API connector: integration tests validate that every stream outputs data (you may need to seed the underlying API with fake data). This will establish a baseline confidence that the connector works correctly on every data stream. If this is not possible, please reach out to @sherifnada with the reason to discuss how to move forward. 
- [ ] If API connector: backs off on hitting rate limits (instead of just failing/exiting)
- [ ] If API connector: implements incremental sync (where possible -- not all streams will allow this)

**Comment by vitaliizazmic** [comment]
The estimate time to complete this task is 7h

## Checklist
- [ ] Check connection verifies permissions upfront - 1h
- [ ] Check connection failure emits actionable error messages. -1h
- [ ] If API connector: integration tests validate that every stream outputs data (you may need to seed the underlying API with fake data). - 2h
- [ ] If API connector: backs off on hitting rate limits (instead of just failing/exiting) - 1h
- [ ] If API connector: implements incremental sync (where possible -- not all streams will allow this) - 2h
