### ISSUE TITLE
Update Collecting metrics page

### ISSUE THREAD

**Issue by Amruta-Ranade** [airbytehq/airbyte#15772]
**Note:** If you'd like to work on this issue, please read the [Docs Contributor guide](https://docs.airbyte.com/contributing-to-airbyte/updating-documentation) and comment on the issue to confirm it is still up for grabs.

From Slack:

This [page](https://docs.airbyte.com/operator-guides/collecting-metrics/) clearly calls out two ways of collecting metrics, but when you go down to the second method it says TBD. Maybe we revise the language until the second method is no longer TBD?

**Comment by Jagrutiti** [comment]
Hi @Amruta-Ranade 

I went through the page in the link. I see it is the datadog way of collecting metrics that says TBD.

I would like the first line to be refactored as:

> Airbyte supports two ways to collect metrics - using open telemetry and datadog(to be determined at a later stage)

And remove DataDog header from the end of the page.

I do not know if this is the best solution or maybe you want to retain datadog header at the end.

Let me know what you think.

**Comment by Amruta-Ranade** [comment]
Hey Jagruti! Turns out, we have new guidance re: Datadog setup. I'm meeting with the engineer this week -- will keep you posted :)

**Comment by davinchia** [comment]
The set up for Datadog is pretty straightforward. There are two env vars that must be set:
1) `METRIC_CLIENT` set to `datadog`.
2) `PUBLISH_METRICS` set to `true`.

There are two additional env vars to configure where the DD endpoint:
1) `DD_AGENT_HOST` - set this to the ip the DD agent is running at.
2) `DD_DOGSTATSD_PORT` - set this to the port the DD agent is using.

Not sure if we want to set up an entire tutorial just like we do with OTEL since DD has pretty good docs (better than OTEL) on how to set this up. I'm thinking we can point folks to https://docs.datadoghq.com/agent/ to start.

**Comment by davinchia** [comment]
I threw up https://github.com/airbytehq/airbyte/pull/15861 to make clear the monitoring related variables we support. We previously didn't add these as support was much more spotty.

**Comment by Amruta-Ranade** [comment]
Thanks, @davinchia 🙌🏽 
@Jagrutiti I think you have all the info you'd need to work on the issue. Let us know if you need help!

**Comment by Jagrutiti** [comment]
Hey @Amruta-Ranade ,

I am going to fill the details in the `datadog` section with as per [the comment above](https://github.com/airbytehq/airbyte/issues/15772#issuecomment-1223090442)? 

Have I got it right? Or I have to do something else?

**Comment by Amruta-Ranade** [comment]
Yep! Try following the [Google style guide](https://developers.google.com/style/highlights) when you draft the section. Or open a PR and I can help you with the style guide :)

**Comment by jhajajaas** [comment]
Went through good first issue label and look like we can close this one?
