### ISSUE TITLE
Cleanup Card components in webapp

### ISSUE THREAD

**Issue by edmundito** [airbytehq/airbyte#15790]
Update `Card`, `ContentCard`, `ConnectorCard` components:

* Migrate to SCSS
* Add storybooks if missing
* Add unit tests where necessary (for testing behavior, not how it looks)

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by timroes** [comment]
As our offline discussion earlier here some more details:

* We should exclude `ConnectorCard` for now from this list. This component is very different from `Card` and `ContentCard` and should likely just be named differently (but not as part of this change).
* We should merge `ContentCard` and `Card` into one `Card` component, that just takes a title optionally as a property and applies the `ContentCard` styling only in case a title is present.
* We should remove the `onClick` property of `ContentCard` (since this is a `div` which should not be clickable). The only place this is currently needed is the `WorkspaceItem` component (the button on the workspace overview page). We instead want to make this a simple `button` for now with some custom styles applied and reconsider that in a later step to move using another component (a `Button` maybe after it's cleanup, but there are some styling differences, why this isn't necessarily the best option). While the style duplication isn't ideal, we found it in discussion better than not being able to really cleanup the `Card` component fully and need to carry around an `onClick` that we want to remove later on.
