### ISSUE TITLE
Broken link in public docs (custom connector section)

### ISSUE THREAD

**Issue by grishick** [airbytehq/airbyte#15897]
### Tell us about the documentation you'd like us to add or update.
On this page: https://docs.airbyte.com/integrations/custom-connectors/
the link in "We invite you to check our [contributing guide on building connectors](https://docs.airbyte.com/integrations/contributing-to-airbyte/)" is broken, because https://docs.airbyte.com/integrations/contributing-to-airbyte/ returns 404

**Comment by Upendra-Singh-Karmiyal** [comment]
Hi @Amruta-Ranade, I think this issue is resolved. I opened the  page: https://docs.airbyte.com/integrations/custom-connectors/
and checked the link in line "We invite you to check our [contributing guide on building connectors](https://docs.airbyte.com/contributing-to-airbyte/).", It was redirecting properly without giving 404 error.
