### ISSUE TITLE
Source Zendesk Support: `ticket_audit` stream freezes after second incremental sync

### ISSUE THREAD

**Issue by Wolff-Lucas** [airbytehq/airbyte#16162]
## Environment
- **Airbyte version**: 0.40.2
- **OS Version / Instance**: debian 11 bullseye / GCP e2
- **Deployment**: Docker
- **Source Connector and version**: Zendesk Support 0.2.15
- **Destination Connector and version**: BigQuery 1.1.15
- **Step where error happened**: Sync job

## Current Behavior
I want to sync all the zendesk support tables with incremental + dedup when it's available and full refresh overwrite when it's not.
The first sync is working well.
But during the second one, ticket_audit start to sync but after reading few records it's hang forever.
## Expected Behavior
Second sync should succeed

## Logs

[logs-134.txt](https://github.com/airbytehq/airbyte/files/9459645/logs-134.txt)

## Steps to Reproduce
1. Select all tables with incremental + dedup when it's available
2. Do a first sync
3. Launch a second sync

**Comment by RobertoBonnet** [comment]
Hello. It is occurring because the connector does not stop making requests. Your data is synced on the first sync. Airbyte detects that it doesn't need to process any more records, but the connector continues to paging the data in the api. In practice, every sync all data is processed from the api, even if you only need some of it to keep up to date. I don't know if I explained it well. I solved this checking the response, but I don't know if is the best approach to everyone. For those who have a lot of data in Zendesk, it's a problem

![image](https://user-images.githubusercontent.com/19189101/189346118-6b501f7e-bb22-4e6d-b95c-2c8ca400b05e.png)

![image](https://user-images.githubusercontent.com/19189101/189346404-09075119-a334-4a92-b12f-673b1942e705.png)

**Comment by natalyjazzviolin** [comment]
Thank you for your input, @RobertoBonnet!

**Comment by BenoitHugonnard** [comment]
It is indeed misleading. The connector seems to be freezing but actually it is making the requests in the background because the endpoint doesn't directly support the incremental search so Airbyte does it behind the scene if I understood it correctly.

**Comment by artem1205** [comment]
closing as outdated
