### ISSUE TITLE
Update high vulnerability dependencies

### ISSUE THREAD

**Issue by edmundito** [airbytehq/airbyte#16218]
Merge PRs related to high security vulnerabilities found by dependabot and snyk:

- [x] #14875
- [x] #13821
- [x] #13688
- [x] #15048
- [x] #16100

For specific dependencies that are difficult or time-consuming to upgrade, create a new issue for each in the product backlog describing the challenges you encountered.

Related: #10573

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by krishnaglick** [comment]
That page 404's for me.

**Comment by timroes** [comment]
The page works fine for me.

**Comment by krishnaglick** [comment]
Could I be missing some permissions?

**Comment by timroes** [comment]
Adding a note here: we often saw a lot of vulnerable dependencies coming from Storybook being really slow in updating their dependencies. Since storybook is not part of our product, it's fine just adding the vulnerable dependencies ,that are only pulled in for storybook to https://github.com/airbytehq/airbyte/issues/10573 and close of the relevant dependabot alert as "Risk is tolerable to this project"

**Comment by edmundito** [comment]
Updated the description with the list of PRs currently open instead of the list that some of us can see.

**Comment by krishnaglick** [comment]
Is the goal to branch off of master and make these changes ourselves so CI runs?

**Comment by tealjulia** [comment]
Skipped 1/added to the Storybook Issue linked at the top.  All others done ✅
