### ISSUE TITLE
Install Chameleon in Segment & Google Tag Manager

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#16221]
We are trialing a product called Chameleon (chameleon.io) for in-app product surveys and product tours. This should replace Intercom product tours (not renewing the product for next year) and replace the in-app onboarding survey that was built in-house. It could also replace Delighted, our NPS survey tool.

This will be a tool that:
- Ingests Segment track and identify calls
- Collects survey input from the user
- Potentially integrates downstream to customer.io (emails), Intercom (chats) and Slack (through Zapier). 

We should install this as a destination for Segment UI Cloud so that it can receive user events to trigger the surveys. It should also be implemented in Google Tag Manager so that the widgets display. My understanding is that it does not interface with the form data in-app, but it would be great to check and verify. 

@letiescanciano invited you to the platform to see the installation guide. Feel free to invite anyone else you feel is relevant.

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by timroes** [comment]
I've checked the tool quickly and there are no security concerns from the frontend side. It's also SOC2 compliant and doesn't collect data it shouldn't as far as a research of their features, past news about security incidents or my investigation of their UI can tell.

Small note: we don't need to enable it via GTM, since enabling it via segment, will cause segment to load the required Chameleon FE code.

**Comment by timroes** [comment]
This is enabled now via Segment, thus closing this issue.
