### ISSUE TITLE
Add ability to enforce SSL in Databricks Destination connector

### ISSUE THREAD

**Issue by ryankfu** [airbytehq/airbyte#16308]
## Tell us about the problem you're trying to solve
Databricks does not _always_ enforce SSL 

## Describe the solution you’d like
Implement configuration for adding `ssl` parameter for Databricks destination

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

## Additional context
[Building the connection URL](https://docs.databricks.com/integrations/bi/jdbc-odbc-bi.html#building-the-connection-url-for-the-legacy-spark-driver)

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by grishick** [comment]
Notes on scope:
 - figure out if DataBricks allows unencrypted connections (if it doesn't, this is a no-op 🎉 ). Otherwise:
    - add SSL on/off switch to spec
    - enforce SSL in Airbyte cloud unless SSH tunnel is on
    - add tests that verify the above behaviors

**Comment by grishick** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Database-and-Warehouse-Connectors-6258a559d235e00013bec81c/issues/airbytehq/airbyte/16308?planning-poker) with Zenhub @edgao @rodireich @ryankfu @subodh1810 @tuliren

**Comment by grishick** [comment]
## Investigation
I plaid around with our databricks sandbox account and found the following:

- Databricks clusters always require SSL to be enabled in JDBC connections. I tried disabling it and was not able to connect
- If JDBC connection URL does not explicitly enable SSL, SSL is still enabled by default
- If JDBC connection URL explicitly disables SSL, Databricks cluster refuses the connection

Here are some references: 

- [DBeaver (or any other DB browser) integration](https://docs.databricks.com/dev-tools/dbeaver.html)
- [JDBC configuration guide](https://docs.databricks.com/integrations/bi/jdbc-odbc-bi.html)

## Remaining scope for this issue
I also found that our JDBC connection string for Databricks currently does not conform to the [JDBC connection guide](https://docs.databricks.com/integrations/bi/jdbc-odbc-bi.html) and is missing `ssl=1` parameter. Although this parameter is implied, we should still add it as recommended in Databricks [documentation](https://docs.databricks.com/integrations/bi/jdbc-odbc-bi.html). My understanding is the only thing we need to do is to add `ssl=1` JDBC URL parameter hardcoded in Databricks connector. The reason it has to be hardcoded is because, Databricks does not allow any value for this parameter.

**Comment by grishick** [comment]
Moving to Blocked until @tuliren finishes current Databricks changes
