### ISSUE TITLE
Add ability to enforce SSL in S3 Destination connector

### ISSUE THREAD

**Issue by ryankfu** [airbytehq/airbyte#16301]
## Tell us about the problem you're trying to solve
S3 does not _always_ enforce SSL 

## Describe the solution you’d like
Implement configuration for adding `ssl` parameter for S3 destination

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

## Additional context
[S3 bucket policy ssl-requests-only](https://aws.amazon.com/premiumsupport/knowledge-center/s3-bucket-policy-for-config-rule/)

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by grishick** [comment]
Note from backlog grooming: rather than creating a new strict-encrypt connector for S3 destination, we can use the environment variable (see `PostgresSourceStrictEncrypt` for the example.

Scope of this ticket (definition of done):

- update the documentation to recommend that users set bucket policies that enforce TLS (see AWS [docs](https://docs.aws.amazon.com/AmazonS3/latest/userguide/security-best-practices.html#transit))
- configure S3 client to always use TLS

**Comment by grishick** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Database-and-Warehouse-Connectors-6258a559d235e00013bec81c/issues/airbytehq/airbyte/16301?planning-poker) with Zenhub @edgao @rodireich @ryankfu @subodh1810 @tuliren

**Comment by grishick** [comment]
Relevant note about NodeJS library: https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/enforcing-tls.html

**Comment by grishick** [comment]
Based on this doc, all access to S3 on AWS is with TLS: https://docs.aws.amazon.com/AmazonS3/latest/userguide/network-isolation.html

**Comment by grishick** [comment]
Reading the [JavaDoc](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/ClientConfiguration.html#withProtocol-com.amazonaws.Protocol-) for S3 client it appears it is configured to use HTTPS by default already
