### ISSUE TITLE
Lever Hiring connector basic authentication

### ISSUE THREAD

**Issue by GLaDOS9000** [airbytehq/airbyte#16358]
I’m trying to set up an integration pipeline from Lever Hiring to snowflake for recruitment processes reporting.
Alas, the airbyte connector from Lever Hiring only allows OAuth authentification which is part of Lever partner integration program reserved for apps and I cannot pretend to such partnership.
I’would like be able to perform basic authentication with the connector using a simple API key.

**Comment by sajarin** [comment]
@GLaDOS9000 thanks for the feature suggestion. Are you willing to submit a PR for the basic auth version of the connector?

**Comment by akashkmr27089** [comment]
Hi @sajarin, can i take up this task.

**Comment by sajarin** [comment]
@akashkmr27089 by all means please! We'll help review the PR.

**Comment by akashkmr27089** [comment]
Hi @sajarin, do you have any api key which i can use to test my features? I have refered airbyte api documentation, google analytics connector and Lever hiring api documentation to raising this PR

**Comment by sajarin** [comment]
Hi @akashkmr27089, we don't have any api keys that we can share especially since this PR introduces basic auth and we only have credentials for oauth at the moment. To test locally, you'll have to follow the instructions on the Lever developer documentation to create your own api keys/credentials for testing. 

More info here if you haven't already found it: https://hire.lever.co/developer/documentation#:~:text=Authentication-,Basic%20Auth,-API%20Keys%20are

**Comment by akashkmr27089** [comment]
Hi @sajarin I have already checked the documentation and have not found anything contributing to how to get Api token. Everything requires us to create Lever account for which i need organization email address. 
Since i couldn't create, i cannot procced with the steps mentioned in the api documentation.

**Comment by sajarin** [comment]
I'll try to see if we can get credentials on our end created for basic auth but it will be a bit difficult for us to help with your PR if you're unable to run the tests locally yourself. But given that you're not adding any new streams, we just have to verify that our tests pass. I'll keep you posted @akashkmr27089
