### ISSUE TITLE
PayPal Transaction Search API

### ISSUE THREAD

**Issue by zmandell** [airbytehq/airbyte#1640]
## Tell us about the new integration you’d like to have
Which source and which destination? Which frequency?
Payment related data is a large and important dataset for many companies. PayPal is often used to complement popular PSP'd like Stripe, Braintree and Adyen. It is valuable to get all of this data into a single source, so that payments KPI's (e.g., cost of acceptance, authorization rates) can be tracked and accounting departments can reconcile costs.

https://developer.paypal.com/docs/api/transaction-search/v1

## Describe the context around this new integration
Which team in your company wants this integration, what for? This helps us understand the use case.
I'd like to use this integration as a payments consultant to help build out data pipelines for clients.

## Describe the alternative you are considering or using
What are you considering doing if you don’t have this integration through Airbyte?
SFTP is an alternative way to integrate

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368206678857) by [Unito](https://www.unito.io)

**Comment by michel-tricot** [comment]
Thank you @zmandell for submitting the issue! We will take a look at it.

**Comment by Zirochkaa** [comment]
**Webhook-based? (no/partially/yes)**
no

**Available authentication modes (API key/Oauth/other)**

**Creating an account**
Login [here](https://www.paypal.com/signin) using login/password from LastPass.
There you will see `airbyte-integration-test` app with needed credentials. [Here](https://developer.paypal.com/docs/api/overview/#get-credentials) is more info about getting credentials.

**How to populate the account with data?**
_Can it be done entirely through the API?_
Yes, [here](https://developer.paypal.com/docs/integration/direct/payments/paypal-payments/#create-paypal-payment) is the guide on how to create transactions.

**Available streams for sync**
[Transactions](https://developer.paypal.com/docs/api/transaction-search/v1/#transactions)
[Balances](https://developer.paypal.com/docs/api/transaction-search/v1/#balances)
 
**Integration supports incremental sync?**
[Transactions](https://developer.paypal.com/docs/api/transaction-search/v1/#transactions) API doesn't have parameters like `updated_after` or `since` or similar so no incremental sync.
[Balances](https://developer.paypal.com/docs/api/transaction-search/v1/#balances) stream has an `as_of_time` request parameter which could be used for incremental sync but it has to be tested whether it's true or not.

**Other information/blockers**
[Here](https://developer.paypal.com/docs/integration/direct/transaction-search/) is more docs regarding Transaction Search API.

**Comment by sherifnada** [comment]
brilliant, thank you @Zirochkaa
