### ISSUE TITLE
Appsflyer Connector - Add Crendetials to Github Secrets

### ISSUE THREAD

**Issue by Muriloo** [airbytehq/airbyte#1650]
Hi Airbyte team!

I created this issue #1649 for an Appsflyer integration that I'm finishing developing.
I would like your help to create Airbyte own credentials to connect to Appsflyer API, so it's possible to run integration tests.

It'll be necessary 2 parameters, here is an explanation of how to find them:

* app_id (it's different for iOS and Android, you can find it in the home page)
* [api_token](https://support.appsflyer.com/hc/en-us/articles/360004562377-Managing-API-tokens)

Any questions please let me know.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368082758846) by [Unito](https://www.unito.io)

**Comment by cgardens** [comment]
@sherifnada the Appsflyer Connector has been merged but it has _not_ been run against standard tests yet (because the contributor doesn't have access to an appsflyer account anymore). It looks like already have credentials for Appflyer, we just need need to connect our test account to the standard tests (and work out any kinks we might find). Can we scheduler this with zazmic?

For now the Appsflyer Connector is merged and available on our docker hub but it is not, by default, visible in the ui.

**Comment by sherifnada** [comment]
This is going to be a difficult one because it requires having an actual iphone app with the appsflyer SDK baked into it. I think we should make this available in the Ui by default once we can display certification badges a la #2588, but prepping this sandbox feels like the wrong place to spend time right now. LMK if you feel differently.
