### ISSUE TITLE
Add check to prevent users from using http url with Tplcentral

### ISSUE THREAD

**Issue by YowanR** [airbytehq/airbyte#16521]
Tell us about the problem you're trying to solve
Currently, it is possible to use unsecured URL (http) in the Tplcentral config.

Describe the solution you’d like
We should fail the CHECK if a user enters a non-https URL for Tplcentral.

**Comment by YowanR** [comment]
@lazebnyi @YuliiaNahoha This needs to be prioritized.

**Comment by YowanR** [comment]
This has been deprioritized and will be moved to Q4 instead.

**Comment by arsenlosenko** [comment]
@YowanR the security check itself is complete, the functionality to prevent users for using HTTP URLs is complete in https://github.com/airbytehq/airbyte/pull/18763 (also covered by unit tests), but because this connector is not yet published, it does not have a test account that could be used in integration tests, thus we couldn't test this connector in full extent. The unit tests are running fine, and covering the basic functionality (most of them were written during initial development of the source).
Considering that credentials and sandbox setup is out of scope of this task, could we close this ticket (as well as PR attached to it), only based on results of unit tests that we have?

**Comment by YowanR** [comment]
Thanks, @arsenlosenko ! Let's close this issue as completed and can you create a new ticket where we will track both creating the test account and then testing it thoroughly before it gets released on Cloud.
cc @igrankova @ycherniaiev -- Would you have the bandwidth to look at this?
