### ISSUE TITLE
Create a strict-encrypt version of AlloyDB Source connector

### ISSUE THREAD

**Issue by grishick** [airbytehq/airbyte#16613]
We need a strict encrypt version of AlloyDB source connector, which wraps AlloyDB (or source-postgres-strict-encrypt) similar to how source-postgres-strict-encryp wraps source-postgres connector to enforce encryption in transit.

Also, source-alloydb as well as source-alloydb-strict-encrypt should be marked GA and versions should be bumped to 1.0.0

**Comment by yurii-bidiuk** [comment]
Hi @grishick 
AlloyDB is a cloud service and all connections should always use SSL. There is no reason to have non-SSL connections because there will be rejected by AlloyDB service.
We decided to not create a strict-encrypt version for AlloyDb connector, but to change source-alloyDb to make it use an SSL connection. We just need to wrap `PostgresSourceStrictEncrypt` instead of `PostgresSource` inside `AlloyDbSource.java`

CC: @alexandr-shegeda @etsybaev

**Comment by grishick** [comment]
> Hi @grishick AlloyDB is a cloud service and all connections should always use SSL. There is no reason to have non-SSL connections because there will be rejected by AlloyDB service. We decided to not create a strict-encrypt version for AlloyDb connector, but to change source-alloyDb to make it use an SSL connection. We just need to wrap `PostgresSourceStrictEncrypt` instead of `PostgresSource` inside `AlloyDbSource.java`
> 
> CC: @alexandr-shegeda @etsybaev

The keyword here is "should". AlloyDB is deployed inside a VPC and in order to connect to it from outside the VPC, admins will have to configure a proxy (see docs [here](https://cloud.google.com/alloydb/docs/connect-external)). Admins will be able to configure the proxy with or without SSL and in fact, when testing our Postgres connector with AlloyDB we have confirmed that we were able to connect through pgbouncer w/o SSL
