### ISSUE TITLE
Shopify normalization fails on Postgres

### ISSUE THREAD

**Issue by ns-admetrics** [airbytehq/airbyte#1692]
## Expected Behavior
After synchronizing Shopify data, normalization should work.

## Current Behavior
The normalization step fails for transactions, see attached log file.
The issue is that the column name `authorization` is a reserved word but unquoted in `airbyte_utils/models/generated/transactions.sql`. Quoting it as in the attached SQL script fixes the issue.

I couldn't find where the model is generated, however using something like https://github.com/fishtown-analytics/dbt-utils#surrogate_key-source could be an easy way to generate this `_transactions_hashid` instead.

## Severity of the bug for you
High/Critical, trying to setup a proof of concept for a client project which needs the Shopify connector.

## Additional context
Running via current docker-compose.yml in `master` branch, from Shopify into a GCP CloudSQL Postgres 13 instance.

[shopify-normalization-failure.txt](https://github.com/airbytehq/airbyte/files/5830797/shopify-normalization-failure.txt)

[transactions.sql.txt](https://github.com/airbytehq/airbyte/files/5830869/transactions.sql.txt)

**Comment by sherifnada** [comment]
@ns-admetrics Thanks for reporting this issue. Will take a look and report back.

**Comment by ChristopheDuong** [comment]
>  couldn't find where the model is generated, however, using something like https://github.com/fishtown-analytics/dbt-utils#surrogate_key-source could be an easy way to generate this _transactions_hashid instead.

We are indeed using that dbt-utils surrogate_key macro for that!

There is actually a snippet of generated DBT models in this tutorial at the end:
https://docs.airbyte.io/tutorials/airbyte-config-persistence#export-and-customize-normalization-step-with-dbt

**Comment by ns-admetrics** [comment]
Yes, I did eventually see that. In this specific case, I think the step just before https://github.com/airbytehq/airbyte/blob/3670545995a6cbc6579104ac9726f82315b1003d/airbyte-integrations/bases/base-normalization/normalization/transform_catalog/transform.py#L384 fails to quote. In general, all columns with names supplied by external parties need to be quoted.

**Comment by ChristopheDuong** [comment]
Yes! 

This is indeed the part of the code that is responsible for the bug you are reporting.

In Postgres, there is a differentiation between delimited identifiers and unquoted identifiers and we are trying to create as many unquoted identifiers as possible. Otherwise, the user would have to use quotes and be aware of case sensitive names on all table/columns all the time.

see https://docs.airbyte.io/integrations/destinations/postgres#notes-about-postgres-naming-conventions

It seems we are missing the cases of "reserved keywords" in the code you are linking that should be detected as quoted identifiers in order to solve your issue!
