### ISSUE TITLE
Source Amazon S3: new compression type .tar, or .zip

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#17021]
## Tell us about the problem you're trying to solve
[API Reference](https://arrow.apache.org/docs/python/api.html)
Implement .tar, or .zip compression type for Amazon S3

## Describe the solution you’d like
Research pros and cons for implementing this compression type.

**Comment by tolik0** [comment]
Tar files cannot be directly supported due to their structural limitation. Unlike zip files, which have a central directory, tar files do not allow for quick inspection of their contents. To inspect or access specific content within a tar file, one would need to read the entire file sequentially, making it inefficient for certain operations or applications. For reference, support for zip files was added in this PR: https://github.com/airbytehq/airbyte/pull/31340.
