### ISSUE TITLE
Upgrade Temporal: security dependency bump

### ISSUE THREAD

**Issue by vr** [airbytehq/airbyte#17075]
## Environment
- **Airbyte version**:  0.40.8
- **OS Version / Instance**: GKE
- **Deployment**: Kube

## Current Behavior

there is currently an issue in one of linked dependency, temporal (because Alpine 3.11 is End Of Support since a while)

## Expected Behavior

Upstream has been [updated](https://github.com/temporalio/temporal/releases), so i expect you will upgrade temporal to v1.18.0

**Comment by marcosmarxm** [comment]
Right now there are two PR trying to upgrade temporal version:
* https://github.com/airbytehq/airbyte-platform/pull/240
* https://github.com/airbytehq/airbyte-platform/pull/212

These come from the Vulnerability report Artifacthub shows to users:
https://artifacthub.io/packages/helm/airbyte/airbyte?modal=security-report
![image](https://github.com/airbytehq/airbyte/assets/5154322/3461acd4-c573-4684-a5c9-1f2e0c6ee5b8)
5 of 8 Critical vulnerabilities are from the old version of Temporal Airbyte uses today.
![image](https://github.com/airbytehq/airbyte/assets/5154322/3f6f7ba9-83c2-451d-88be-3d6acf687054)

@pmossman can you give some information about you're attempt to upgrade Temporal?

**Comment by pmossman** [comment]
@marcosmarxm sorry I missed your question earlier. At one point I tried building a branch with an updated Temporal version just to see what would happen, and quite a few tests were failing. I didn't dig in much further, I think we'll need to investigate what breaking changes exist between our current version and the latest version in order to make this happen.
