### ISSUE TITLE
Consider default values for oneOf fields in connector specs

### ISSUE THREAD

**Issue by lmossman** [airbytehq/airbyte#17352]
## What

See original [slack thread](https://airbytehq-team.slack.com/archives/C03088BTMFC/p1664320332231419) for context.

Currently our frontend code does not consider the `default` field if it is set on a oneOf property in the connector specification. We should update our code to use these default values if they are set when a user first creates a connector, and set the dropdowns to those default values automatically in that case.

## How

This would likely require changes in several places. Here is a draft PR with some progress started on these changes, though this still likely requires more testing and iteration: https://github.com/airbytehq/airbyte/pull/17351/files 

One open question: In the case of oneOfs of objects, does the `default` need to contain default values for every sub-field as well? Or is there some way in the json schema that we can just say `default: X` where X is one choice in the oneOf, without needing to also provide defaults for all of its children?

**Comment by octavia-squidington-iv** [comment]
cc @airbytehq/frontend

**Comment by sw-yx** [comment]
more broadly i wonder if we can use a jsonschema interpreter library that will at least ensure we are "up to spec" whatever that means

**Comment by timroes** [comment]
We are using types for jsonschema in Typescript via a library (there's not much to parse since JSON schema is already plain JSON itself). This though won't solve the problem that we need to generate our UI and forms from that spec, which a library won't help us with.

**Comment by flash1293** [comment]
In the context of https://github.com/airbytehq/airbyte/issues/14250 I would like to close this one because a connector developer can always achieve the same by reordering their oneOfs to put the first one on top.

This is a preferable solution because it makes the UI more consistent - if there is a oneOf, the default selection will always be the top one. Preselecting another one that's not the default could be slightly unexpected/confusing for a user.

Instead I would like to enforce no `default` values on `oneOf`properties via SAT (already added it to this issue: https://github.com/airbytehq/airbyte/issues/20063)

What do you think @lmossman ?

**Comment by flash1293** [comment]
Discussed with @rodireich and we concluded that there are good use cases for this functionality. I checked through our existing specs and it turns out a bunch of them are already implementing `default` values. All of them specify the value of the shared const field, so I'm going to implement this behavior.

**Comment by rodireich** [comment]
Thanks @flash1293 
This was in the context of #16664 from a few months back.
Once a `default` is implemented I can go back and improve they way our config UI behaves.

**Comment by flash1293** [comment]
Approved, waiting for the code freeze

**Comment by flash1293** [comment]
@rodireich This should work now
