### ISSUE TITLE
differentiate between expected and unexpected errors in tracking

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#1744]
## Tell us about the problem you're trying to solve
We want to be able to differentiate between user errors (e.g wrong password) and airbyte/server errors (e.g sync worker unexpectedly failed) in our tracking code so we can have a better gauge of how well our connectors are doing. 

## Describe the solution you’d like
In our segment/amplitude analytics, add a tag for any emitted exception that indicates whether it was user error or server error

**Comment by davinchia** [comment]
After discussion with @sherifnada, this issue is focused on the `CheckConnection` step. Although the Airbyte protocol does require better error propagation facilities, this is a bigger architectural change and doesn't have immediate benefit yet.

Slack discussion: https://airbytehq.slack.com/archives/C019WEENQRM/p1615559804147400

**Comment by davinchia** [comment]
I observed some strange temporal exception handling behaviour - I've documented this in a follow up ticket.

**Comment by cgardens** [comment]
this was closed when this PR: https://github.com/airbytehq/airbyte/pull/2385 was merged.
