### ISSUE TITLE
Persist connector dependency versions for tracking upon /publish

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#17532]
## Tell us about the problem you're trying to solve
Most of our connectors dependencies are not pinned to a specific version:
e.g. in `set-up.py`

```
MAIN_REQUIREMENTS = [
    "airbyte-cdk,
    "cached_property~=1.5",
    "facebook_business~=11.0",
    "pendulum>=2,<3",
    "backoff",
]
```
It makes auditing of the connectors more difficult when we ask ourselves "*Which version of this package is this connector using?*".
With the example above it's impossible to know which version of the CDK this connector is using. 

## Describe the solution you’d like
For python connectors I'd like the `pip freeze` output to be stored on our repo and/or be archived on each connector update.
This data will not have a technical use in the connector folder itself so it can be stored elsewhere:
- in the `sources_spec.yaml` file? 
- in a file on an S3/GCS bucket? 
- in BigQuery?

I'd also like this data to be in our data-warehouse for fast and easy dependency scanning.

## Describe the alternative you’ve considered or used
Adhoc local script:
* loop on connectors declared in `source_defintions`
* Pull their docker image
* Run `pip freeze` on the image
* Capture the output

This is ineffective as the dependency version can be stored on image build.

## Additional context
I faced this problem when we migrated python sources to per-stream state: per-stream state was enable in a specific CDK version but I did not know which connectors were already migrated because their `setup.py` file is not pinning CDK versions.

**Comment by evantahler** [comment]
A few alternatives to consider:
1. as part of `/publish` we cat the output of `pip freeze` to a file in the connector directory and check that into git. 
2. Perhaps `cdk_version` belongs in [source_definitions.yaml](https://github.com/airbytehq/airbyte/blob/master/airbyte-config/init/src/main/resources/seed/source_definitions.yaml)

**Comment by evantahler** [comment]
Grooming:

Goals:
* The goal is to get the output of `pip freeze` into the data warehouse
* nit: the pip install process inside the container might not be the same as your host os - the pip freeze should be generated from within the container
* this should be done as part of the publish command

Get the data into bigquery using the BQ CLI.

**Comment by ChristopheDuong** [comment]
I mentioned `source-airbyte` in the past to:
- grep log files during sync to expose as a data stream. 
- call airbyte APIs to surface data from the platform

In this use case, it seems better to add steps to the /publish command instead to:
- create an extra file on a GCS bucket
- create an external table in BigQuery to expose that data to be queryable by metabase dashboards/queries

For example, here are some telemetry on some CI workflows from github: `ab-analytics-308500.airbyte_ci_visibility.raw_workflow_tests`

You can also choose to git version in the repository if that's good for your use too.

**Comment by erohmensing** [comment]
I would love to see when things were published as well, so that I could sort by publish date (e.g. to determine potential blast radius of changes in a dependency that was merged in on x date). Other helpful columns could be the current version of the connector in cloud, and the connector type (java, python, other)

From my notes for [P0 - CDK 0.13](https://docs.google.com/document/d/1ixej4VVcU-c5UtCHSrIn8aokFiA2cLnHwGAz5DtMWws/edit#): 
[It would be great to have a] Metabase query containing data of which versions of which connectors were published when (e.g. sourced from dockerhub API), with which versions of dependencies. This could cover steps 1-4 of the steps followed to assess potential blast radius.

Those steps were: 
1. Get list of connectors updated since 12/12 
2. Remove java connectors
4. Check connectors docker images and verify their CDK version >=0.13
3. Check cloud masks to verify if the affected versions are in cloud

**Comment by bnchrch** [comment]
Closing in favor of this solution https://github.com/airbytehq/airbyte/issues/31263
