### ISSUE TITLE
Track permission errors on streams

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#17616]
In order to know we made things better, we need a way to track/count the types of errors users are seeing related to not having access to a particular stream.

This can be manual, in metabase, in sentry, etc.

**Comment by evantahler** [comment]
Grooming Notes:
* This is usually a 403 exception.  Can we count them in sentry?  Maybe Sentry doesn't let us grep/aggregate issues - we should check.
   * But metabase does, and has the same errors! 
   * Sentry can group things by tags, but we might need a bigger plan?  What does that cost?
* Many connectors are manually already skipping streams w/o access in the should_retry method
* Right now, connectors can't emit metrics.

Scope: Just for APIs for now

TODO: How do we want to measure this?  

Goal - pick the tool, make the chart. 

Suggestion - start with metabase if we can.

**Comment by pedroslopez** [comment]
Played around with sentry's Discover feature a bit. Searching for "403 Client Error" we can get all the events that have happened with that error in a given time period.

Example, in the past month we've seen 73 events due to this:

![image.png](https://images.zenhubusercontent.com/62585178f8599f85447ea63f/43fd6adc-46e0-44de-addd-c41b1a651b24)

https://sentry.io/organizations/airbytehq/discover/results/?display=default&field=title&field=event.type&field=project&field=user.display&field=timestamp&interval=1d&name=All+Events&project=6527718&query=403+Client+Error&sort=-timestamp&statsPeriod=30d&yAxis=count%28%29

We should determine if it's just these 403s that we want to track, and whether it's worth having something more "permanent" in metabase.

**Comment by evantahler** [comment]
That's pretty neat! you can chunk them by week/period as well -https://sentry.io/organizations/airbytehq/discover/results/?display=previous&field=title&field=event.type&field=project&field=user.display&field=timestamp&interval=7d&name=All+Events&project=6527718&query=403+Client+Error&sort=-timestamp&statsPeriod=90d&yAxis=count%28%29

Just restating that this method:
* only works for API sources
* assumes that API sources to the right HTTP error thing and respond with 403 and not some [other code 🫖](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/418)

As an alternative, here's Metabase - https://airbyte.metabaseapp.com/question/1005-403-errors-by-week

**Comment by pedroslopez** [comment]
> As an alternative, here's Metabase - https://airbyte.metabaseapp.com/question/1005-403-errors-by-week

@evantahler I seem to be getting a 403 on the 403 question :D 

![image.png](https://images.zenhubusercontent.com/62585178f8599f85447ea63f/080051c2-67a0-45a5-a5ea-b604347b6362)

**Comment by evantahler** [comment]
Try now!

**Comment by pedroslopez** [comment]
Did a bit of tweaking on the metabase query, mainly changing the main failure origin to be `contains` instead of `is` and only using attempt count = 3 to represent a final attempt failure. I think metabase is better than sentry because it's more flexible in how we want to group or display the data. 

However, I'm not sure how we want to use this as a goal - does it make sense to just track the events per quarter and say we want to get to 0?

It's not exactly feasible to get to 0 since the work isn't in yet and won't be completed until all sources are updated

(see we've already had 14 failures this Q)

<img width="224" alt="image" src="https://user-images.githubusercontent.com/4368928/196872460-8953d3b7-ad79-42c7-a6dc-1c821a90cfe2.png">

  https://airbyte.metabaseapp.com/question/1094-permission-failures-by-quarter 

Should the goal be expressed more as a % reduction in errors?

(cc @evantahler )

**Comment by evantahler** [comment]
I'll delete my report so we don't get confused

**Comment by pedroslopez** [comment]
We can also break these down by connector by quarter https://airbyte.metabaseapp.com/question/1130-permission-failures-by-connector-by-quarter

@evantahler Given the goal:

> Goal - pick the tool, make the chart.

Is this done? I'm not sure what the definition of done here looks like. Do we update the OKR sheet?

**Comment by evantahler** [comment]
Great question - yes, if you update the ORK sheet with this link (and update the epic with the choosen dashboard), this is done!

**Comment by pedroslopez** [comment]
@evantahler Updated the OKR sheet with:

KR | Q3 result | Q4 goal 
-- | -- | --
Enable 80% fewer failed syncs due to partial stream permissions  | 324 failed syncs | < 65 failed syncs
