### ISSUE TITLE
Show users IP addresses during connector setup

### ISSUE THREAD

**Issue by timroes** [airbytehq/airbyte#17680]
We'd like to show users the IP address our cloud connects from during the setup of the connector so they can allow list them already in their tool before testing the connection.

The list of IP addresses should also be linked up to LaunchDarkly, so we can quicker adjust it in case they change, before we adjust it in code.

**Comment by octavia-squidington-iv** [comment]
cc @airbytehq/frontend

**Comment by timroes** [comment]
@andyjih or @misteryeo Do you know if there is a reasonable way to detect from the connector spec somehow if it makes sense to show that information for that connector? I.e. if that connector needs to communicate to another system of the user, since I'd say it makes no sense showing this on the API connectors.

**Comment by misteryeo** [comment]
I don't believe so but I think @alafanechere @girarda might be able to confirm?

**Comment by girarda** [comment]
@timroes, [you can use the sourceType, which is specified in the source definition](https://github.com/airbytehq/airbyte/blob/master/airbyte-config/init/src/main/resources/seed/source_definitions.yaml#L7), if all you care about is whether the source is an API or a database

**Comment by pmossman** [comment]
Refining notes:
- Currently, our IP addresses are in docs, and it sounds like we just want to bring those closer to the configuration UI. 
- We don't think this requires any back-end change, ideally can be handled entirely on the front-end and LaunchDarkly
- @timroes does the front-end already have access to the `sourceType` so that the IP addresses can be shown/hidden conditionally? Just trying to make sure there's no hidden back-end work necessary here

**Comment by timroes** [comment]
@pmossman yes we already have access to the `sourceType` via the `api/v1/source_definitions/list` and `api/v1/source_definitions/list_latest` APIs.

**Comment by mfsiega-airbyte** [comment]
Refining notes:
- Unclear how high-priority this is
- Unclear precisely how this would look
- For now, will icebox unless more demand arises

**Comment by nataliekwong** [comment]
As an additional data point for how it would help the Support team, today we get about 17 inbound chats a month (5% of the intercom chats) asking about the IP whitelist requirements. Data source: https://airbyte.metabaseapp.com/question/2021-intercom-conversations-about-ip-whitelist

**Comment by nataliekwong** [comment]
Thank you, I hadn't looked as closely at the content! If it's really just 1% of the Intercom chats it won't have much impact on deflecting those chats.

The only other data point I can think of it more upstream - the errors from the source/destination checks themselves. We haven't done any reporting on those yet as we just started getting them recorded in Segment calls, so I don't have data on how often a check error shows up related to a lack of IP whitelisting (or which errors from each destination necessarily relate to IP whitelisting). 

Can leave this in the nice to have bucket unless we can pull data that says otherwise.

**Comment by josephkmh** [comment]
@lmossman removing this from the compose backlog as it seems like a more extensibility related issue!

**Comment by lmossman** [comment]
We are currently running an experiment with the Postgres connector to show a message about allowlisting Airbyte IP addresses. See relevant slack thread [here](https://airbytehq-team.slack.com/archives/C04QVJR9E78/p1685569612436149)
