### ISSUE TITLE
Generate python connector builder API server code

### ISSUE THREAD

**Issue by lmossman** [airbytehq/airbyte#17813]
## Tell us about the problem you're trying to solve
As described in the [Tech Spec](https://docs.google.com/document/d/11HrieUnA7oa6YsDhOVZpAVkOoZt2RWQQWJLPf7xQodY/edit#heading=h.i0wxd065dtfh), the connector builder server API that will back the UI is defined in an OpenAPI specification, so that server and client code can be auto-generated from the API spec.

## Describe the solution you’d like
This ticket involves configuring the connector-builder-server module to auto-generate python server code from the connector-builder-server OpenAPI spec on build, so that the server always has the most up-to-date classes to use in implementation of the server.

This should be done with the [OpenAPI Generator](https://github.com/OpenAPITools/openapi-generator), which has support for generating either FastAPI or Flask python code from an API spec.

## Acceptance Criteria
- Python server code for the connector builder API is auto-generated on build of the connector-builder-server module
- Generated code is not committed to github

**Comment by lmossman** [comment]
The generated code should NOT be committed to github, similar to the airbyte webapp: https://github.com/airbytehq/airbyte/blob/ec5496840df4b0af93afa341d820268d0212c7e9/airbyte-webapp/.gitignore#L32-L33

**Comment by sherifnada** [comment]
update after some investigation: it’s unclear how the FastAPI OpenAPI Generator is supposed to be used because there is no separation between the Python code declaring the API Contract (e.g: an abstract class with abstract methods each corresponding to an API endpoint) and the Python code implementing the contract. This means that every time you re-generate the server, the implementation will get overwritten. 

[this thread seems to confirm this problem](https://github.com/tiangolo/fastapi/issues/2942#issuecomment-1257273775) 

Some alternatives I'm looking into: 

* seeing how big of a lift it would be to restructure the OpenAPI generator/submit a PR
* Looking into other frameworks' python generators

**Comment by sherifnada** [comment]
Flask's generator also seems to have the same problem

**Comment by sherifnada** [comment]
I posted a thread in the OpenAPI repo with suggestions for a solution. [see here](https://github.com/OpenAPITools/openapi-generator/issues/13863)

I think we can use custom templates to generate this without necessarily being blocked on upstreaming the solution I described. 

Taking a step back, our options for the moment are probably: 
* create a PR against the upstream repo. This will likely take the most amount of time. 
* create our own templates and use them in our repo without upstreaming
* manually keep a FastAPI (or Flask, it still has the same issue) in sync with our OpenAPI implementation (maybe borrowing the models generated by the openAPI generator, as they are still usable

As far as I can tell there is no out-of-the-box Python OpenAPI generator that enables the development workflow described above. This being said I haven't tried codegen for Django, and I haven't looked outside of the OpenAPI repo for external generators.

**Comment by sherifnada** [comment]
Update from Monday October 31st.

My goal for today was to see if we can avoid manually keeping our FastAPI implementation in sync with our openAPI implementation.

### High level
There is nothing in the OpenAPI OSS Python ecosystem that supports the development experience we're targeting. Our options are therefore: 
- manually keep the codebase in sync with the openapi spec
- use OpenAPI custom templates to make things work
- Use a paid vendor 
  - one vendor would handle the autogeneration for us, the catch is they use their own custom DSL (which can be converted to OpenAPI via a converter they provide)
  - one vendor plugs into API requests and just alerts us if a new endpoint or signature is detected (but doesn't autogen anything)

### Trying out OpenAPI custom templates
I'm currently seeing if I can make OpenAPI templates work. The basic structure I listed in https://github.com/OpenAPITools/openapi-generator/issues/13863 is proving harder than expected to make work because FastAPI has some typing magic that needs to happen. I'm iterating on [this repo](https://github.com/sherifnada/openapi-python-test).

**Comment by dannysheridan** [comment]
Howdy, @sherifnada @lmossman --

>   * one vendor would handle the autogeneration for us, the catch is they use their own custom DSL (which can be converted to OpenAPI via a converter they provide)

My team at **Fern**  can handle autogenerating the FastAPI server interfaces for you. I understand (and agree!) that a downside of using our custom DSL is that devs have to learn another spec. We’ve gotten similar feedback, and are working on two features to mitigate this:

1. **OpenAPI → Fern converter** 
There are certain features of OpenAPI that preclude high-quality code generation (e.g. types without names, `anyOf`). If you don’t use those features, transforming your OpenAPI into Fern is trivial, as the two specs are pretty similar.

2. **User interface**
Nobody likes writing YAML. We’re working on an API builder UI that abstracts away our custom DSL. It outputs an OpenAPI spec that lives in your repo.

We have a Fern → OpenAPI convertor, so you’re never locked in. We actively maintain this convertor because we have customers who use it to integrate with their API docs provider. Additionally, our spec & the [corresponding typescript types](https://github.com/fern-api/fern/blob/e69eff1337b4b0b881bd9cea39a382979dfadf87/packages/cli/yaml/yaml-schema/src/schemas/file-schemas/ServiceFileSchema.ts#L6-L11) are open source, so you can always implement your own converter.
