### ISSUE TITLE
Octavia CLI: allow disabling stream reset when applying changes

### ISSUE THREAD

**Issue by henriblancke** [airbytehq/airbyte#17968]
## Tell us about the problem you're trying to solve
More information in [this slack thread](https://airbytehq.slack.com/archives/C02RRUG9CP5/p1665669390703719)

TL;DR: when you apply a change to a stream using Octavia CLI (for example enabling a previously disabled stream), Airbyte will apply a reset for either all or affected streams. The UI allows you to bypass resetting streams. It'd be great if Octavia CLI allows you to do the same.

## Describe the solution you’d like
A configuration key or CLI arg to disable automatically resetting all or affected streams.

**Comment by marcosmarxm** [comment]
Thanks @henriblancke I added the issue to team backlog.

**Comment by marcosmarxm** [comment]
This week Airbyte repo merging code is blocked because of holidays.
I'll prioritize the PR next week.

**Comment by terencecho** [comment]
Slight oversight on my end. (Comment copied from the PR): I think because this field is set to required, it is failing some of the other integration tests. I can put up a fix for this (either making the field optional or updating the integration tests).  In the meantime I will revert this PR so the builds are able to pass.

I will update this PR and the corresponding issues with my progress.

**Comment by terencecho** [comment]
Fix for the failing integration tests: https://github.com/airbytehq/airbyte/pull/20093. hoping this get this merged today

**Comment by terencecho** [comment]
the fix has been merged
