### ISSUE TITLE
Remove supportsDbt and supportsNormalization from DestinationDefinitionSpecificationRead

### ISSUE THREAD

**Issue by andriikorotkov** [airbytehq/airbyte#18239]

**Comment by alafanechere** [comment]
@airbytehq/connector-operations the front-end needs to access the `supportsDbt` field for the [`ConnectionTransformationTab`](https://github.com/airbytehq/airbyte/blob/master/airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/ConnectionTransformationTab.tsx#L102). It's currently reading this information from the `DestinationDefinitionSpecificationRead` model. This story should evolve to be: 
- Remove `supportsDbt` + `supportNormalization` from `DestinationDefinitionSpecificationRead` model
- Expose `supportsDbt` + `normalization`  in `DestinationDefinitionRead` model so that FE can read these field from the API
- Change `DestinationDefinitionsHandler` to build `DestinationDefinitionRead` with these new fields
- Change the logic in `ConnectionTransformationTab` to use the definition model and not the spec model.
