### ISSUE TITLE
dbt Default Normalization - dbt parse takes a long time

### ISSUE THREAD

**Issue by jkleinkauff** [airbytehq/airbyte#18317]
## Environment
- **Airbyte version**:  0.40.15
- **Deployment**: Kubernetes
- **Source Connector and version**: Postgres 1.0.18 
- **Destination Connector and version**: Redshift 0.3.50 
- **Step where error happened**: dbt default normalization

## Current Behavior

I'm ingesting a postgres table to Redshift using a default normalization (dbt).
The problem is dbt is taking so long to start the model execution that most of the integration time is waiting for this step to start - **_the gap between the first "Concurrency: 4 threads" log and the log for the first model being executed_**.

18:31 - 18:39 - 8 minutes to start the first model
18:02 - 18:11 - 9 minutes
18:31 - 18:39 - 8 minutes

![image](https://user-images.githubusercontent.com/58440667/197271934-022ce940-e6e9-48e8-b006-2198e5eaa644.png)
![image](https://user-images.githubusercontent.com/58440667/197272065-5bfc0033-f1a5-47cd-a121-c190f9e98a2a.png)
![image](https://user-images.githubusercontent.com/58440667/197272278-b87b4ca9-f7f4-4285-a450-3ee54f6e0fcc.png)

There are some cases where dbt will start executing the model instantly, right after the first "Concurrency: 4 threads" message. It seems that this delay happens with Redshift only.

From Postgres to Postgres

![image](https://user-images.githubusercontent.com/58440667/197277537-6a4f660d-5118-4728-9f01-ae765159c5bd.png)

## Expected Behavior

I think this is happening because dbt is doing a full-parse of the project. A partial parse could drastically improve the performance of this step.

https://docs.getdbt.com/reference/parsing

I believe dbt relies on a file called manifest.json, not sure how we are handling this tho.

## Are you willing to submit a PR?

Yes.

**Comment by jkleinkauff** [comment]
I've written about what I think it may be the problem https://github.com/jkleinkauff/airbyte_dbt.
Let me know if it makes sense.

**Comment by edgao** [comment]
notes from slack: slowdown is probably `dbt compile`, because redshift needs to get the column type once per column. See https://github.com/airbytehq/airbyte/blob/4b93a9b436ead9657c5fa56cdef76c974151ea85/airbyte-integrations/bases/base-normalization/dbt-project-template/macros/cross_db_utils/json_operations.sql#L210 and https://github.com/airbytehq/airbyte/blob/4b93a9b436ead9657c5fa56cdef76c974151ea85/airbyte-integrations/bases/base-normalization/dbt-project-template/macros/configuration.sql

iirc this is backwards-compatibility code from https://github.com/airbytehq/airbyte/pull/12064. Potential options:
* release a breaking change to just cut the backwards-compat code, under the assumption that it's been long enough for users to have upgraded destination-redshift to a post-SUPER version (the SUPER switch happened in April, so it's been about half a year)
* maybe find some way to cache the result of the query per table, since it won't change
* other ideas?

**Comment by jkleinkauff** [comment]
I have built my worker and normalization images removing the super_type validation. To be more precisely, on the [configuration.sql](https://github.com/jkleinkauff/airbyte_dbt/blob/main/airbyte_dbt/macros/configuration.sql) I'm just returning **True**. If we go forward with this change we can certainly remove all of the calls to the macro and wiped out the file.

That said, now my Redshift jobs are executing much much faster. As i said to @edgao I really think users of the actual version are being deeply affected.

**Comment by cgardens** [comment]
We aren't going to pick this up. We want to stay away from orchestrating dbt. We recommend using Airflow or Dagster to do this orchestration. [Docs](https://docs.dagster.io/integrations/airbyte).
