### ISSUE TITLE
Display stack trace in UX after a check() or discover() emits a config-error via AirbyteTraceMessage

### ISSUE THREAD

**Issue by akashkulk** [airbytehq/airbyte#18407]
When check fails (by throwing an exception), there currently an area in the UX which allows the user to view the stack trace: 
https://www.loom.com/i/9d85acd501b8430ab6aa83456a79b526

However, if the check() returns with an ``AirbyteConnectionStatus == failed``, we don’t have the ability to see the stack trace. 
e.g. https://www.awesomescreenshot.com/image/33719281?init_open=true

Ideally, both the stack trace and a custom error message would be shown to the user if the connector emitted a trace message via ``AirbyteTraceMessageUtility.emitConfigErrorTrace``. This is similar to the sync page, where the stack trace is always shown if the check() fails. The benefits here would be that : 

-  A more granular error message would be displayed to the user. (e.g. Double check your SSL configuration)
-  Stack trace would also be available to support teams, oncall engineers, etc in case more visibility is needed into the issue. 

Brainstorming with @pedroslopez, the ask here is to show the stack trace for config errors when a config error trace is emitted in check().

**Comment by octavia-squidington-iv** [comment]
cc @airbytehq/frontend

**Comment by timroes** [comment]
To add some context: the log message under a check is not shown in case the job itself doesn't fail, because in this case the error should be returned as part of the actual response (and not just be burried in the log), why showing the logs usually was not helpful for users (especially since the actual job would succeed and we'd show a "error in your configuration", but right below a "succeeded check job", which was very confusing).

If we already have a stacktrace emitted from the connector and it's part of the actual response of the `api/v1/sources/check_connection` API, this is purely a FE issue to add the stacktrace into the UI. If it's not returned from that API, we'll first need to make sure it's passed through there.

**Comment by pedroslopez** [comment]
The stack trace / FailureReason is not currently part of the API response. I created an issue in #18514 for adding this to the responses. This would enable FE to use this information to properly display them to users.

**Comment by evantahler** [comment]
Title updated to reflect that we need to show better errors for both CHECK and DISCOVER failures

**Comment by evantahler** [comment]
Is this closed by https://github.com/airbytehq/airbyte/issues/23302?

**Comment by erohmensing** [comment]
Should be, yes! Trace messages get shown in the UI as failureReasons when we capture them
