### ISSUE TITLE
Sendgrid source tests failing

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#1840]
## Expected Behavior
CI for the sendgrid source connector should succeed

## Current Behavior
https://github.com/airbytehq/airbyte/runs/1766740232?check_suite_focus=true it is currently failing

## Acceptance criteria
1. identify root cause
2. implement fix

**Comment by eugene-kulak** [comment]
probably account related

**Comment by yevhenii-ldv** [comment]
@sherifnada, I checked the access, this account exists and it is possible to reach it, but by streams:
```
lists
campaigns
contacts
```
I get a `403` status code.
Because of this, we do not receive a single record, and the tests crash.
I think the solution to this bug is changing the access rights to read the above streams for `apikey`, since using my own account and `apikey` launched the tests and they passed.
