### ISSUE TITLE
Sandbox Credentials for Workable

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#18439]
## Tell us about the problem you're trying to solve
PR https://github.com/airbytehq/airbyte/pull/18033/files adds new source Workable. Need credential to run proper tests.

## Describe the solution you’d like
A clear and concise description of what you want to see happen, or the change you would like to see

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by igrankova** [comment]
Support answer: Since we don't have any dedicated sandbox accounts, what we usually recommend is creating a trial account. Once the trial period ends, you can email us asking for an extension mentioning that you are using the trial as a sandbox.
We can apply for a [partner program](https://developers.workable.com/partner-program/apply) to have more permanent account.

**Comment by igrankova** [comment]
@marcosmarxm, the trial period of the account is almost finished. If you need to prolong it, please let me know, I can contact support and ask them.
