### ISSUE TITLE
Integration tests for import/migration of config/database

### ISSUE THREAD

**Issue by ChristopheDuong** [airbytehq/airbyte#1862]
## Tell us about the problem you're trying to solve
If we modify configuration files or table schemas from databases, we need to make sure we also provided the adequate migration class to convert an old archive file from a previous version to the version of airbyte with the new changes.

## Describe the solution you’d like
- Should we put a "standard" test archive in the git repo 
- apply all migration classes on top of it as part of integration tests in CI
- try to import the migrated archive as part of integration tests in CI to a fresh airbyte installation and check that it worked? 
- this could be part of end-to-end acceptance tests or just integration tests?

**Comment by ChristopheDuong** [comment]
it might need to check that we don't forget to  migrate of #1787 too

**Comment by ChristopheDuong** [comment]
> it might need to check that we don't forget to migrate of #1787 too (which change all the time)

We don't need such check anymore since core and connectors release cycles are now decoupled with https://github.com/airbytehq/airbyte/issues/1983

**Comment by davinchia** [comment]
Initial discussions
1) Everytime we release a new version, a tarball for that version is uploaded to Cloud Storage (S3)
2) Everytime there is a new major/minor version is released, a test suite should run checking:
&nbsp; - for every tarball in S3, all subsequent migration versions should be able to successfully run against it.
&nbsp; - the produced migrated tarball should be able to be imported.
&nbsp; - the end workspace should have the sane configurations e.g. set up connections, using the same images etc.

**Comment by cgardens** [comment]
> If we modify configuration files or table schemas from databases, we need to make sure we also provided the adequate migration class to convert an old archive file from a previous version to the version of airbyte with the new changes.

can we dig a little deeper into the problem a little bit? some of the solutions being described a pretty involved and i want to make sure we are staying laser focused on the real problem.

e.g. we are forgetting to write migrations
e.g. the migrations we write are wrong

etc... is there some pattern to the problem we are having?

**Comment by davinchia** [comment]
followup discussions with @cgardens :

our current issues seem to be:
* we sometimes forget to write a migration (there is nothing to remind us)
* our migrations run into bugs due to edge cases (e.g. forgetting to update the `schema.yaml` etc.) 

By testing that every migration, when run on the previous version, produces the correct output, we can simplify the approach in the [comment above](https://github.com/airbytehq/airbyte/issues/1862#issuecomment-810275174). Since the migrations are applied in order, if we know every migration is correct, upgrading from any version to any subsequent version will be correct.

Tentatively, work can be broken down into:
1) As part of the build, Gradle should runs the most recent migration (it should match the most recent released version) and checks the migration outputs the correct schema. This solves point 1 (build will fail if there a migration does not exists) and partially solves 2 (build will fail if the migration is written wrongly and does not output the right yaml). 
2) Implement a generative testing migration helper to make writing migration tests more comprehensive and easy. The generative tool should, for some number of combinations of optional/required field, for a schema, check the migration succeeds.

we think this breakdown makes sense for now since each task is reasonably scoped + delivers values in itself.

how does this sound @ChristopheDuong ?

**Comment by ChristopheDuong** [comment]
It seems like it worked as detected here: https://github.com/airbytehq/airbyte/pull/3414/

So it's great!!
