### ISSUE TITLE
Unable to authenticate Azure blob with Databricks Lakehouse connector

### ISSUE THREAD

**Issue by anshul-cached** [airbytehq/airbyte#19011]
## Environment
- **Airbyte version**:  0.40.18
- **OS Version / Instance**: Windows 7/10
- **Deployment**: Docker
- **Destination Connector and version**:  DatalakeHouse 
- **Step where error happened**: Setup new connection

## Current Behavior
* I am trying to use Databricks Lakehouse connector as my destination, for which I generated the SAS token for Azure blob (for lake house connector configuration, also I am using Azure Databricks). However the connector errors out saying 'Signature doesn't match', which is a little weird as I am able to access the SAS URL on my browser and is working fine as expected*

## Expected Behavior
*The connector should be able to connect to the service as both the databricks details and Azure blob SAS token are correct and working fine out of the airbyte environment*

## Logs
<img width="537" alt="image" src="https://user-images.githubusercontent.com/16463997/200247080-07f45cac-2df1-480a-94f1-54bc7867e248.png">

**Comment by jtv8** [comment]
Experiencing the same issue - Databricks Lakehouse connector 0.3.1. The SAS is valid and has every possible permission on the container (Read, Add, Create, Write, Delete, List, Immutable Storage). I'm at a loss here - it's unclear what else I could try.

**Comment by jtv8** [comment]
OK, I got this to work. This is a documentation issue. It needs to be an _account level_ SAS rather than a _container level_ SAS. That's misleading given that it asks you for the container name right before!

It would also be helpful to have a list of the specific permissions the SAS should have so we don't have to guess (or violate the least privilege principle by assigning it everything!)

**Comment by evantahler** [comment]
Closing - this destination has been updated significantly since this issue was posted.
