### ISSUE TITLE
tracking New Connection - Action event does not accurately track source definition

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#1910]
## Expected Behavior
I expect the [New Connection - Action ](https://analytics.amplitude.com/org/85488/chart/gw1d38g/edit/9k3ifc8) events in in Amplitude to have their `connector_source_definition` property set to the name of the source definition e.g: `Postgres` or `Google Analytics`

## Current Behavior
They are set to the name of the source, not the source definition. This means that whatever someone calls their source is what ends up getting counted. 

## Steps to Reproduce
See amplitude link above. 

## Severity of the bug for you
High -- important to know connector popularity as it helps with prioritization

**Comment by cgardens** [comment]
Good catch. Looks like we just need to fix the inputs here: https://github.com/airbytehq/airbyte/blob/master/airbyte-webapp/src/components/CreateConnectionContent/CreateConnectionContent.tsx#L74-L77 and hit is use the respective source and destination definition names instead of source and destination names.
