### ISSUE TITLE
Python CDK: Support filtering columns inside connectors

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#19238]
## Tell us about the problem you're trying to solve
Currently the Python CDK does not pass the input configured catalog to any of its stream objects. This was fine since the Airbyte product didn't really have column selection. However, this means that once we do support column selection at the product level, the Stream object won't have access to the column selection configuration (encoded in the configured catalog). This means that for APIs like Facebook marketing or Greenhouse which support column selection natively, the connector can't make use of that filtering functionality at the API level. It must pull down all columns then filter locally. This is not always feasible e.g: the user might not have permission to access all columns or for security reasons they may never want Airbyte infrastructure to even see PII or secret data. 

## Describe the solution you’d like
I would like Stream objects to be aware of selected column sets so connectors can choose to make use of those selections.

**Comment by mikebaldry-acu** [comment]
Has this changed at all in the Python CDK since column selection was added to Airbyte? I'm working on a custom Python connector (based closely on top of the existing SFTP connector), and am having problems with getting the connector to exclude columns that I've de-selected in the UI from the _airbyte_raw tables. 

Other connectors we use (ex: MSSQL) seemingly use the column selection to build up their SELECT statements, so this issue doesn't exist for them.

**Comment by girarda** [comment]
this is now possible using the stream's configured catalog
