### ISSUE TITLE
Zendesk Support Missing Cursors

### ISSUE THREAD

**Issue by ryjabe** [airbytehq/airbyte#19266]
## Expected Behavior
As a GA connector, Zendesk Support should have a cursor enabled for all possible streams.  From some cursory scoping it appears a few streams are missing cursors.  Below is that list for Zendesk Support (stream_name:cursor_name)

Streams with possible Cursors:
**custom_roles**: updated_at
**schedules**: updated_at
**sla_policies**: updated_at
**tickets**: updated_at
**users**: updated_at

The request here is if possible to add cursors for the above streams. 
@YowanR FYI

**Comment by emilmar** [comment]
I'd like to bump this issue!

Today I found out that **ticket_metrics** is using time based offset. We have about 150k ticket_metric records, and the sync ended up taking 3 hours the first time. Since ticket_metrics is archived after 120 days, I don't expect that many users to have this many records, but who doesn't like scaling? ;) 

`Response Code: 429, Response Text: Pagination limit reached for offset model` 

[Ticket Metrics supports cursor based pagination](https://developer.zendesk.com/api-reference/ticketing/tickets/ticket_metrics/)

**Comment by btkcodedev** [comment]
I would like to work on this issue

**Comment by btkcodedev** [comment]
@artem1205, Already I raised the PR https://github.com/airbytehq/airbyte/pull/26329 and @sh4sh was reviewing it for solving the issue,
Please check twice on further issues to reduce duplicate efforts :)
Closing https://github.com/airbytehq/airbyte/pull/26329 as Issue is solved 
CC: @sh4sh 
Thanks
