### ISSUE TITLE
Lowcode CDK: Allow authenticators to inject secrets into query parameters

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#19334]
## Tell us about the problem you're trying to solve
The [docs for authenticators](https://docs.airbyte.com/connector-development/config-based/understanding-the-yaml-file/authentication) seem to imply that you can't inject an API key anywhere other than headers. 

## Describe the solution you’d like
I would like to be able to inject API keys in query parameters.

**Comment by girarda** [comment]
Some thoughts on the interface change required for this:

### Option A: replace `ApiKeyAuthenticator`'s `api_token` field with a `RequestOption`
- This is somewhat high effort because this is a breaking change
- Better option long-term because it is consistent with other components that inject values in the request

### Option B:
- Add `inject_into` field to the `ApiKeyAuthenticator`, which will be an enum

### Option C:
- Deprecate the `api_token` field, but keep it around so we don't have to update all existing connectors (there are 26 connectors using ApiKeyAuthenticator according to `git grep --files-with-matches ApiKeyAuthenticator | grep yaml | wc -l`)

**Comment by girarda** [comment]
closing because this can be done with the api key authenticator and with the session token
