### ISSUE TITLE
Adopt connector best practices for Twilio Source

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#1946]
## Tell us about the problem you're trying to solve
We'd like to follow [the published connector development best practices ](https://docs.airbyte.io/contributing-to-airbyte/building-new-connector/best-practices-for-connector-development) on this connector. 

Since this connector is Singer based, for each of the below items please verify whether:

* the singer tap already implements it
* the singer tap does not implement it and would require forking the tap to implement
* it's something we can implement easily on top of the Singer tap without forking it

**If implementing any of the below items would require forking the Singer tap, please notify sherifnada and move on to the next issue.**

## Checklist
* [x] Check connection verifies permissions upfront
* [x] Check connection failure emits actionable error messages. This will probably require you to think about the failure modes that can occur (e.g: timeout, permission not granted, token does not exist, etc.. -- make sure that you add custom integration tests to verify each of these failure modes, or unit tests if you can mock the HTTP requests involved)
* [x] If API connector: integration tests validate that every stream outputs data (you may need to seed the underlying API with fake data). This will establish a baseline confidence that the connector works correctly on every data stream. If this is not possible, please reach out to sherifnada with the reason to discuss how to move forward. 
* [x] If API connector: backs off on hitting rate limits (instead of just failing/exiting)
* [x] If API connector: implements incremental sync (where possible -- not all streams will allow this)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368211373991) by [Unito](https://www.unito.io)

**Comment by vitaliizazmic** [comment]
1. Singer based source.
2. Tap handle API calling errors
3. It is required credentials for Twilio account for checking and populating API data.
4. Tap uses backoff.
5. Incremental sync is implemented

**Comment by sherifnada** [comment]
Subtasks: 
* populate data in the Twilio account
* add all streams to integration test configured catalog

@vitaliizazmic will update the issue with a more granular estimate

**Comment by davydov-d** [comment]
- Twilio does not require any extra permissions beside having the `auth_token`
- Check connection failure emits actionable error messages. - yes, it does. Unit tests added in this [PR](https://github.com/airbytehq/airbyte/pull/14000)
 - If API connector: integration tests validate that every stream outputs data - expected records added in the same [PR](https://github.com/airbytehq/airbyte/pull/14000)
 - If API connector: backs off on hitting rate limits (instead of just failing/exiting) - yes, due to being implemented using CDK
 - If API connector: implements incremental sync (where possible -- not all streams will allow this) - yes, where the API allows (7 out of 22 streams)
