### ISSUE TITLE
support limiting number of pages / records retrieved from connector builder server

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#19500]
## Tell us about the problem you're trying to solve
As a connector builder UI developer, if my stream contains a large number of records and I press the test read button, I might have to wait a very long time for all the records to be retrieved. 

## Describe the solution you’d like
I want a way to limit the number of records retrieved from the connector builder. 

## Acceptance Criteria
- [ ] #19937
- [ ] The API read endpoints exposes a `record_limit:` parameter which limits the number of records returned
- [ ] Wire up the two points above

**Comment by lmossman** [comment]
@sherifnada I think the second acceptance criteria may have not been fully written

I think my main open question here is: should this allow users to limit the number of pages or number of records, or both? Some thoughts here:
- Limiting the number of pages only makes sense if pagination is configured, so if it is not configured we would either need to only allow users to limit records, or not let them limit anything
- My guess is that most of the turnaround time for a `read` operation is taken up by submitting an HTTP request to the source and waiting for the result (but correct me if I'm wrong here). Therefore, limiting pages may make more sense than limiting records, because one HTTP request is submitted per page

**Comment by sherifnada** [comment]
@lmossman woops, brain timed out while writing the issue. Your reasoning makes a lot of sense. Changed to talk about pages.

**Comment by girarda** [comment]
grooming notes:
* we only want to limit the number of records so we don't need to modify the CDK
