### ISSUE TITLE
Prepare 4 backend issues for new hires

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#19520]

**Comment by brianjlai** [comment]
The following tickets are groomed and ordered by best ones to tackle first which our new backend engineers can tackle. I'll manage distributing the tickets out once they're up and running:

- [cdk] [19733](https://github.com/airbytehq/airbyte/issues/19733) - Good straightforward refactor.
- [cdk] [18946](https://github.com/airbytehq/airbyte/issues/18946) - Good for intro to basics of the CDK and builds on top of the 19733 and good intro to releasing airbyte-cdk
- [low-code cdk] [15628](https://github.com/airbytehq/airbyte/issues/15628) - Good first ticket to fix a limitation of the low-code. Non-breaking, but unlocks some value right away since developers have mentioned it.
- [low-code cdk] [19735](https://github.com/airbytehq/airbyte/issues/19735) - Small contained ticket that makes a small change and can practice an airbyte-cdk deploy
- [low-code cdk] [19622](https://app.zenhub.com/workspaces/connector-extensibility-6257455decf3920012f4e872/issues/airbytehq/airbyte/19622) - Excellent ticket for covering a lot of aspects of how the CDK interacts with the connector builder. Builds off of #19735 but this is from the connector builder side
