### ISSUE TITLE
Cancellation should not be red

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#19630]
## Tell us about the problem you're trying to solve
![Screen Shot 2022-11-18 at 4 18 12 PM](https://user-images.githubusercontent.com/9092207/202823643-b160d58e-6214-4877-bcbd-c7a4b4f49d52.png)
* When an attempt is cancelled, the UI shows a red X and a failure reason. This implies that the sync is broken in some way. This is misleading.

## Describe the solution you’d like
* When an attempt is cancelled the symbol should be gray with a more neutral symbol (perhaps a dash), and we should not show the failure reason line. There should be no red.

@timroes is the workflows team the right place to send this?

**Comment by octavia-squidington-iv** [comment]
cc @airbytehq/frontend

**Comment by timroes** [comment]
> @timroes is the workflows team the right place to send this?

:+1: Yes it is!

**Comment by edmundito** [comment]
cc @Upmitt

**Comment by andyjih** [comment]
Ideas here:
- "Failure Origin" makes it read like a failure. How does this message get populated? Is there a way for us to change the wording so it doesn't show "Failure Origin"? 
- Separately, if we can use a different color or icon instead of a red X. Maybe we can borrow from Github Action's pattern of a minus or slash with a circle around it: 

![Image](https://user-images.githubusercontent.com/633226/204654506-b63ae8d4-39db-4d17-82d3-420dbc4fd607.png)

**Comment by edmundito** [comment]
I will take another pass at removing some of the text mentioned here:
https://github.com/airbytehq/airbyte/pull/20774#issuecomment-1370212640
