### ISSUE TITLE
Use column filter for CDC sources in Debezium

### ISSUE THREAD

**Issue by subodh1810** [airbytehq/airbyte#19701]
We should use the [column.include.list](https://debezium.io/documentation/reference/stable/connectors/postgresql.html#postgresql-property-column-include-list) filter for CDC implementation in Debezium so that we only query for the columns that are present in the catalog.

**Comment by bleonard** [comment]
Slack [thread](https://airbytehq-team.slack.com/archives/C046V1Z2YJH/p1669078989934329) about this.

Let's pipe the list from the protocol to debezium. Verify the behavior in CDC or for example, if a column changes that is not in the list, we don't output it (and vice versa).
If might be worth checking what happens with a column name with a `.` because the docs say they are regular expressions.
If there is anything else they are adding (maybe `*`?), then make a new issue for that.

**Comment by rodireich** [comment]
Debzium uses regexp for matching of included tables/columns lists, so `.` or other special characters should go escaped.
Verifying with those as well

**Comment by rodireich** [comment]
After making sure all characters are escaped correctly for both table and column include lists,
The backslash(`\`) character is not working as expected.
I filed [DBZ-5917](https://issues.redhat.com/browse/DBZ-5917) for what I think is a bug in how debezium is doing its regex name matching.

**Comment by rodireich** [comment]
Debezium put a PR for DBZ-5917: https://github.com/debezium/debezium/pull/4206.
(Fix is going to go on 2.2.0. We're still using 1.9.6)
