### ISSUE TITLE
Source Twilio: new stream Usage Records

### ISSUE THREAD

**Issue by ycherniaiev** [airbytehq/airbyte#19745]
## Tell us about the problem you're trying to solve
The UsageRecords resource provides a simple API to retrieve actions made by your Twilio account during any time period and by any usage category. This makes it easy to build reporting and analytics tools for your application.

UsageRecords used in combination with [Subaccounts](https://www.twilio.com/docs/iam/api/subaccounts) created for each of your end-users make it possible to build recurring usage-based billing systems on top of Twilio’s API with just a few simple API calls. If rectifying UsageRecords with billing, [see our dedicated article](https://www.twilio.com/docs/voice/resolve-call-log-usage-discrepancies).

You can also set up [usage triggers](https://www.twilio.com/docs/usage/api/usage-triggers) to notify your application when a particular category of usage reaches a threshold on a daily, monthly, yearly, or all-time basis. Triggers can help determine if your users have reached a cap on usage or if your application has runaway requests.
GET https://api.twilio.com/2010-04-01/Accounts/{AccountSid}/Usage/Records.json
## Describe the solution you’d like
 Research pros and cons for implementing this stream

**Comment by grubberr** [comment]
I have implemented `usage_records` stream in this PR https://github.com/airbytehq/airbyte/pull/21446

**Comment by grubberr** [comment]
This stream was implemented in a low-code version of `source-twillio` https://github.com/airbytehq/airbyte/pull/21446
but unfortunately, this low-code implementation is put on hold because low-code CDK does not allow us to finish the job.

If we need this stream: "Usage Records" in `source-twillio` probably we need to implement it now in AirbyteCDK
until problems with low code will be resolved.

I have unassigned from myself and moved to the backlog 

tag: @lazebnyi
