### ISSUE TITLE
Source freshdesk: investigate whether to use HTTP requests vs python SDK

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#1974]
## Tell us about the problem you're trying to solve
The python sdk for freshdesk seems not to contain all entities in the API. Implementer of this ticket should verify if this is the case and if so, devise the best way to support the missing entities (main impoirtant one right now is satisfaction_ratings).

**Comment by eugene-kulak** [comment]
Currently, we use only the minimal functionality of the Python Client (because public API returns instances of model, not JSON).
The parts that the client missing are: 
- conversations
- satisfaction ratings

Conversations can be retrieved as:
-  an embedded field of a ticket (up to 10)
-  a substream of a ticket (`/api/v2/tickets/<id>/conversions`)

Satisfaction ratings can be retrieved as:
- a stream `/api/v2/surveys/satisfaction_ratings`
- a substream of a ticket (`/api/v2/tickets/[ticket_id]/satisfaction_ratings`)
 
Taking into account that embedding might consume call credit and doesn't provide all data, we will need a highly customized version of the Python Client to support backoff (#1972 and #1962 ).

Also, #1388 will need additional filters for incremental updates.

Nevertheless, we still can use Python Client as part of integrations tests in #1388 to create, update and delete records.
