### ISSUE TITLE
Write the 1st draft of tech spec for Destination checkpointing

### ISSUE THREAD

**Issue by grishick** [airbytehq/airbyte#19764]
Write up a summary of the destination checkpointing:
* the how come this change is desired
* what the complications of the current iteration has
* the benefits of the changes
* the tradeoffs made

Follow through on this work is to answer any questions generated from the knowledge sharing session and questions within the tech spec document

[Tech Spec](https://docs.google.com/document/d/1A-HNz4EIpgajClkX-yp9MI6hl9dI3JhbO-k6w7QnyC0/edit#)

**Comment by ryankfu** [comment]
Follow up here, tech spec has been reviewed by various members of the Airbyte organization. There are still some open questions the are not *hard* blockers but will be areas that should be addressed

Notable questions include:
* What impact will this have on _FULL_REFRESH_ mode since this change is no longer the _all or none_ case where destinations will only commit when the full read has been completed
* Will this overall increase costs for the user (belief is that this change will actually overall reduce costs since it removes the overhead of _airbyte_temp_ tables and there's no process executed periodically to reap these lingering _temp_ tables
* Is the usage of a jobs/audit table valuable for first pass? The reason being that jobs table will allow users to be able to identify when a sync has started executing and when a sync job has completed. It will be useful in the case with _FULL_REFRESH_ mode where partial data is not completely known otherwise
