### ISSUE TITLE
Snowflake source encodes integers as floats

### ISSUE THREAD

**Issue by grishick** [airbytehq/airbyte#19776]
(this issue came up in OC and I reproduced it with test data)

I have a table in Snowflake created as follows:

```
create or replace TABLE INTEGRATION_TEST_DESTINATION.GREGS_SCHEMA.MY_TEST_TABLE (
	ID VARCHAR(16777216),
	IMPRESSIONS NUMBER(38,0)
);
```
Attached is the sample data that I inserted into this table

[oc-966.csv](https://github.com/airbytehq/airbyte/files/10079367/oc-966.csv)

when I run a sync from this table to BigQuery, the records in raw table show up as following (in column `_airbyte_data_`):
```
{"ID":"19c9e8f81c9b9d44c17148ab45a4eb25","IMPRESSIONS":1790.0}
```

values like `1790.0` break normalization SQL, because the schema reported by Snowflake source says that `IMPRESSIONS` is an `Integer`.

**Comment by bleonard** [comment]
either parsing wrong or `discover` is saying it's a float.

**Comment by rodireich** [comment]
Curiously I don't see the problem on the following table:
```
create or replace TABLE INTEGRATION_TEST_SOURCE.JDBC_INTEGRATION_TEST1_ZLRYQ.ID_AND_NAME (
	ID NUMBER(38,0) NOT NULL,
	NAME VARCHAR(200) NOT NULL,
	UPDATED_AT DATE NOT NULL,
	primary key (ID)
);
```
But I do see it on a table is similar to what @grishick has created above:
```
create or replace TABLE INTEGRATION_TEST_SOURCE.RODI_TEST.MY_TEST_TABLE (
	ID VARCHAR(16777216),
	IMPRESSIONS NUMBER(38,0)
);
```
Sync failure with 
```2022-12-10 00:09:39 - Additional Failure Information: invalid input syntax for type bigint: "1790.0"```

**Comment by grishick** [comment]
@rodireich from looking at the code I cannot tell why the behavior is different for your table. I think this has something to do with your table using the integer column as PK, but that's just a guess.

**Comment by rodireich** [comment]
yes. checking exactly that

**Comment by rodireich** [comment]
I see where the problem is: 
In snowflake an Integer or BigInteger, TinyInt etc. is a [`NUMBER`](https://docs.snowflake.com/en/sql-reference/data-types-numeric.html#examples-of-fixed-point-data-types-in-a-table) with a scale of 0 (e.g `NUMBER(38,0)`.

When read by the JDBC driver and converted to a `JsonNode`, for both `NUMBER(38,0) - e.g 1970` and `NUMBER(38,1) - e.g 1970.2` a [DecimalNode](https://fasterxml.github.io/jackson-databind/javadoc/2.4/com/fasterxml/jackson/databind/node/DecimalNode.html) is generated by the Jackson library.

By default a decimal node (back by java's BigDecimal) will output a string using a scientific notation (e.g `197E+3`).

Jackson's behavior it to always [deserialize scientific notation values as floats with a trailing `.0`](https://github.com/FasterXML/jackson-databind/issues/2908), which is the reason we see this bug.  **<<<<<<< This is the problem**.

What can be done:
BigDecimal has a [`.toPlainString()`](https://docs.oracle.com/javase/8/docs/api/java/math/BigDecimal.html#toPlainString--) which outputs a simple number (`1970` rather than `197E+3`).
We can use the [`Feature.WRITE_BIGDECIMAL_AS_PLAIN`](https://fasterxml.github.io/jackson-core/javadoc/2.7/com/fasterxml/jackson/core/JsonGenerator.Feature.html#WRITE_BIGDECIMAL_AS_PLAIN) in our json object mapper to force this.
The question I need to figure out is whether there's a case in which depend on the scientific notation.
If not we can add this feature flag in out default json [ObjectMapper](https://github.com/airbytehq/airbyte/blob/master/airbyte-commons/src/main/java/io/airbyte/commons/jackson/MoreMappers.java#L20)
Which is fixing this issue.

**Comment by rodireich** [comment]
The reason we don't see this issue in other source connectors such as postgres is that a NUMBER(38,0) in postgres source will translate to a Double column in destination, while in Snowflake a NUMBER(38,0)  will translate to a destination Integer.
