### ISSUE TITLE
Create "Out of date definitions" endpoint

### ISSUE THREAD

**Issue by krishnaglick** [airbytehq/airbyte#19853]
The frontend currently makes a request to source_definitions, destination_definitions, as well as their "latest" endpoint counterparts solely to determine if any definitions are out of date.

This is done on _every_ initial page load.

By creating an endpoint that handles all that logic on the backend will save us an immense amount of transfered bytes.

Frontend code triggering this lives [here](https://github.com/airbytehq/airbyte/blob/09d1c06cff2c5b385eef597d664a8a49db73200f/airbyte-webapp/src/views/layout/SideBar/NotificationIndicator.tsx#L15)

**Comment by gosusnp** [comment]
Since we are calling this on every page, what are we using this data for? If it is only used for the dot on the settings, I believe we could do something even more specific. We could just have an API that returns if there are connectors to upgrade.
On the backend, we could be more efficient in this case because I don't think we currently store the "latest" for all connectors. Which means we'd have to look this up every time if we were to map it to each connector. However, we have a step that is checking if there is upgradable connectors, this could be a simpler result that would be easier for us to cache.

**Comment by krishnaglick** [comment]
![Screenshot 2022-11-30 at 11 55 10 AM](https://user-images.githubusercontent.com/4967694/204859770-dde3f7ec-3a36-4be3-bbf7-d68a5bfc55e2.png)
This dot is the only place it's used. However you think it's best, the only real piece of data the FE needs is if any definitions are out of date.

**Comment by gosusnp** [comment]
Provide an endpoint that returns if there is connectors that could be updated.

**Comment by gosusnp** [comment]
New endpoint `/v1/web_backend/check_updates`
