### ISSUE TITLE
Automate version bump and package publishing for `airbyte-cdk`

### ISSUE THREAD

**Issue by clnoll** [airbytehq/airbyte#19981]
## Tell us about the problem you're trying to solve
There are two issues when publishing the CDK: 
1. Many people could be working on the CDK in parallel, which results in version conflicts between in-flight PRs for the `airbyte-cdk` package
2. Publishing the CDK is done from a branch, which can lead to nasty race conditions, not to mention being tedious/manual 

## Describe the solution you’d like
We could solve the two problems at once, or we could solve just one or the other. 
To solve 1 we need to add a GitHub Action to bump the version and publish the package on merge to `master`. If we do this, we'll want a way to indicate whether it's a major/minor version change. One possible solution could be to use the commit message, or possibly the PR description since the template indicates whether there are breaking changes.

To solve 2 we need a Github action that checks whether the `airbyte-cdk` directory was changed on merge to master, and runs the publish workflow if so. We will also need a clear path for error recovery if the publishing fails for any reason. 

The implementer of this issue is free to think about whether to solve both issues vs. just one, and the sequencing of a solution. 

## Describe the alternative you’ve considered or used
We could queue up the PRs that would require a version bump and merge them once a day. We might end up wanting to do this eventually anyway, with or without automatically bumping the version, so it's somewhat orthogonal.

**Comment by maxi297** [comment]
## Current situation
<img width="852" alt="image" src="https://user-images.githubusercontent.com/3360483/211082493-83b084a7-cb46-415f-aebf-c6cf38ca29ad.png">

## Challenges with proposed solution
There were a couple challenges making the release automatic on merge:
* What happens if the version in the setup.py has been updated as part of the PR? Do we generate an error and block the merge? Do we release on that version even though it would allow race conditions as stated in the issue?
* Input needs to be provided by the dev. However, it is not very intuitive when this input should be provided when merging the PR. We could check the last comment with a specific format but what happens if the dev forgets before merging?
* What happens if the pipeline on master fails? Should we still publish the new version?

## New Proposed Solution
Let's decouple two problems: 
* Race condition generated by releasing in the feature branches
* Having to manually do something to release

Given that releasing needs user input, let's ignore the second problem for now. This enables us to create this flow:
<img width="598" alt="image" src="https://user-images.githubusercontent.com/3360483/211082571-535427a2-6b54-4ee3-ba7e-aab9477dff65.png">

This gives more flexibility to the dev:
* We can release from anywhere. This could be useful for hotfixes eventually for example (before doing this, we will need to define the versioning in case of hotfixes)
* This allows us to release outside of the context of PR (and therefore, enables the release of master)
* For now, this removes the race condition assuming devs will release from master

## What About Automatically Releasing on Merge in Master?
If we define how the dev will provide the information regarding the major|minor|patch and the changelog message, we can easily add this on top of the current solution.
