### ISSUE TITLE
Redshift reports successful sync after ignoring some of the records

### ISSUE THREAD

**Issue by dave-tomkinson** [airbytehq/airbyte#19990]
## Environment
- **Airbyte version**:  0.40.18
- **OS Version / Instance**: ubuntu EC2
- **Deployment**: docker on a single instance but with RDS datastore
- **Source Connector and version**: airbyte/source-postgres 1.0.22
- **Destination Connector and version**: airbyte/destination-redshift 0.3.51
- **Step where error happened**: Sync job

## Current Behavior
I run a sync and when it completes I get the message
`Sync Succeeded 10,000,000 emitted records | 10,000,000 committed records`
However when I check the database I only have 9,986,326 rows.
When I check the log there's a message 
`A total of 13674 record(s) of data from stream AirbyteStreamNameNamespacePair{name='events_196', namespace='analytics_raw'} were invalid and were ignored.`

## Expected Behavior
I would expect the UI to tell me it was only a partial success! 
The UI should tell me how many rows were actually inserted to the destination (and ideally a way to retrieve the id's of the failures)

## Logs
The logs are attached in the [slack thread about this issue](https://airbytehq.slack.com/archives/C021JANJ6TY/p1668518421758359)

## Steps to Reproduce
1. create a postgres (or any?) source that contains a jsonb column that has more than 65535 characters stored in it
2. Run a sync (mine was raw not normalised)

## Root Cause
I did some digging and the root cause of the issue is that the SUPER column in Redshift can only store 65535 characters of data, so it overflows (more pronounced as the json from the source gets escaped which further increases its character count and all columns are combined into the _airbyte_data column).
The root cause (in this case) looks like it'll be fixed by a Redshift update [https://aws.amazon.com/about-aws/whats-new/2022/11/amazon-redshift-sql-capabilities-speed-data-warehouse-migrations-preview/](https://aws.amazon.com/about-aws/whats-new/2022/11/amazon-redshift-sql-capabilities-speed-data-warehouse-migrations-preview/) 

I'm still raising the issue as it's the UI reporting of what happened that's the actual issue.

## Are you willing to submit a PR?
erm... I've never looked at the Airbyte source, it says Java and Python... If it's in a Python bit I _might_ be able to have a go if someone can point me in the right direction... but it might take a long while.

**Comment by marcosmarxm** [comment]
Thanks for reporting this @dave-tomkinson definitely something need more thoughts about how to output to users.

**Comment by grishick** [comment]
We have a method in all destinations that validates data before writing it. Redshift is the only destination that actually implements that method (all other destinations just return true and don’t do any validation). The only validation Redshift does is checking the size of the value according to Redshift documentation, which says “[The MAX setting defines the width of the column as 4096 bytes for CHAR or 65535 bytes for VARCHAR.” ](https://docs.aws.amazon.com/redshift/latest/dg/r_Character_types.html#r_Character_types-varchar-or-character-varying) and ["Amazon Redshift doesn't support the following query functionality on tables with SUPER type columns that hold any SUPER object larger than 1 MB."](https://docs.aws.amazon.com/redshift/latest/dg/limitations-super.html). I think the connector is doing what it is supposed to do, because it is better to do partially succeed than fail the entire job because of one record. Other connectors should probably do the same unless that dramatically decreases the throughput. 

However, I think there is a bug in Redshift destination where it reports state messages as success even if it failed to commit all records, which is incorrect per Airbyte protocol, which says `Outputting a state message indicates that all records which came before it have been successfully written to the destination.`

**Comment by marcosmarxm** [comment]
@grishick should be this renamed to only be applied to Redshift so?

**Comment by marcosmarxm** [comment]
@HishamAssi go for it!

**Comment by tianchen98** [comment]
@HishamAssi just curious how was your shot? Really appreciate any update since I'm encountering a similar problem now. TYSM.

**Comment by evantahler** [comment]
Take a look here https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/destination-redshift/src/main/java/io/airbyte/integrations/destination/redshift/operations/RedshiftSqlOperations.java#L65C1-L86.  This override should probably be removed
