### ISSUE TITLE
after successfully updating schema the button isn't available until refreshing or revisiting

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#2035]
1. Configure a sync
2. Go to settings for the sync and update schema
3. After it succeeds the button isn't available unless you refresh the page or navigate away (to status for example) and come back.

Ideally after the update has finished and the connection settings are re-rendered the update schema button would be available again.

**Comment by Jamakase** [comment]
The button is disabled until you make new changes and that's the expected behaviour. If you change schema 1 more time - it's available for the update again.

Do you think we need to fix it? @cgardens @jrhizor

**Comment by cgardens** [comment]
I will defer to @jrhizor as the reporter. I'm not too tuned into what the issue is here.

**Comment by jrhizor** [comment]
This isn't referring to the "Save changes" button, it's referring to "Update Schema", which doesn't get disabled -- it just goes missing

![Screen Cast 2021-02-23 at 2 54 40 PM](https://user-images.githubusercontent.com/120362/108919049-36aaf200-75e7-11eb-9b5a-c228ff47554f.gif)

**Comment by Jamakase** [comment]
> This isn't referring to the "Save changes" button, it's referring to "Update Schema", which doesn't get disabled -- it just goes missing
> 
> ![Screen Cast 2021-02-23 at 2 54 40 PM](https://user-images.githubusercontent.com/120362/108919049-36aaf200-75e7-11eb-9b5a-c228ff47554f.gif)

Ok, got it. Thank you for the clarification

**Comment by Jamakase** [comment]
@jrhizor I checked 1 more time - and that's the expected behavior and implemented according the initial specs. So when you press update schema - you enter edit mode. So you have not updated the schema yet. 

So you should either update schema and save or cancel the edit mode. 

Probably we should make it more clear on UI side that we are in edit mode?

**Comment by jrhizor** [comment]
Oh you're 100% right, this is on spec. You do have to save afterwards to make the changes... 

It's really confusing as is. The dialog we added makes the change seem final. And in this case, the update results in the same schema but you can't save to reset because nothing is modified... 

Let me get back to you on this.

**Comment by cgardens** [comment]
thanks @jrhizor . @Jamakase  and i discussed this today and came to a similar conclusion. the current behavior is by design but is still confusing. if we can map out a clearer interaction then we should go for it? feel free to pull in @johnlafleur if you think he might be able to give some insight on how we might improve the interaction.

**Comment by johnlafleur** [comment]
Here are suggestions for the UI:
https://www.figma.com/file/AODY4oi15iI5l0fbxHvobt/Daxtarity?node-id=21380%3A1340

There are 2 suggestions, because specs are changing in terms of UI in the Connection Settings page. So I've made one with the current UI, and one with the future one.

The suggestion changes the behavior with the modale. I believe displaying the modale after clicking on "Update schema" is very confusing, as it makes the user expect that by confirming in the popup whatever is displayed next is the new schema, while it's not true. The popup should be displayed as a confirmation after clicking on "Save changes". 

Let me know what you think.

**Comment by cgardens** [comment]
@Jamakase john put together a new mock up to try to improve this. let me know if it doesn't address all of your concerns.
