### ISSUE TITLE
🐛 Source SalesForce: `test_parallel_discovery` fails on CI continuously 

### ISSUE THREAD

**Issue by bazarnov** [airbytehq/airbyte#20432]
Based on this and familiar SAT test for `source-salesforce`:  https://github.com/airbytehq/airbyte/actions/runs/3679281776

The `test_parallel_discovery` fails all the time on CI. This should be investigated properly and fixed.
Meanwhile, this test is commented out to avoid failing SAT: https://github.com/airbytehq/airbyte/pull/20237/files#diff-57d94ba5414b4e8360871482e5f06ddd4e9d163d2b977daaff2e5ebda8d4d461R133

**Comment by davydov-d** [comment]
@YowanR @YuliiaNahoha please pay attention to this issue

**Comment by YowanR** [comment]
Is this more of a backlog item?

**Comment by davydov-d** [comment]
@YowanR yes

**Comment by grubberr** [comment]
## The problem happens because CI runs on Ubuntu 22.04 with OpenSSL 3

For some reason, in multithreaded environment, all code that uses OpenSSL3 under the cover starts to work slower
You can see people complain about this problem:
https://stackoverflow.com/questions/74574427/python-https-requests-slow-with-openssl-3
https://github.com/openssl/openssl/issues/17064

Test python script:
```python
#!/usr/bin/env python3

import time
import requests
import concurrent.futures

STAT = []

def get_page(page):
    start_time = time.time()
    response = requests.get("https://google.com")
    STAT.append(time.time() - start_time)

for max_workers in [1, 2, 5, 10, 20]:
    STAT.clear()
    with concurrent.futures.ThreadPoolExecutor(max_workers=max_workers) as executor:
        list(executor.map(get_page, range(100)))
    print("max_workers", max_workers, "average round trip time: ", sum(STAT)/len(STAT))
```

Ubuntu 22, openssl3
--------------------------------------------------------
max_workers 1, average round trip time:  0.3215585064888
max_workers 2, average round trip time:  0.4377863764762878
max_workers 5, average round trip time:  0.8989488029479981
max_workers 10, average round trip time:  2.403364851474762
max_workers 20, average round trip time:  4.985973258018493

Ubuntu 20, openssl1
-------------------------------------------------------------
max_workers 1 average round trip time:  0.22932467460632325
max_workers 2 average round trip time:  0.23023553371429442
max_workers 5 average round trip time:  0.23826370000839234
max_workers 10 average round trip time:  0.271535370349884
max_workers 20 average round trip time:  0.37978396415710447

On **Ubuntu 22**, you can see RTT degradation when we increase the number of threads.
