### ISSUE TITLE
[Epic] Track schema validation errors 

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#20554]

**Comment by erohmensing** [comment]
:white_check_mark: What's been completed:
- Migrating `acceptance-test-config.yml` files for the beta + GA sources that fail the unexpected fields test has been completed 
- Issues for those sources are created and added to an epic
- Code used to do this process, refactoring `strictness_level_migration` to accommodate performing different migrations on different sets of connectors, is up for review
- Updates to source breaker came as a result of needing easy testing of schema validation errors locally 

:construction: What got in the way:
- It was hard to decide where to stop with regards to the initial modularity of the config migration code, as I wanted both pieces of migration code to be easily runnable, which required abstracting a fair amount of stuff already (but there's plenty more to improve in the next epic!)
- The current way that we collect and log validation errors is pretty convoluted and has a history of many small updates to patch issues with it. I honestly think a decent amount of it could be scrapped in favor of just counting and reporting the actual json schema validation messages instead of building our own. This also addresses us losing the expected type in the process. 

:seedling: What's next:
- Merge the refactored config migration code
- Improve/simplify the way we log schema validation errors, revisit all the restrictions we have put on it 
- Add datadog metrics for the missing desired fields of schema validation errors

:question: Learning / Questions / Changes:
- Nothing in particular

:no_entry: Blockers:
- None at the moment.

**Comment by erohmensing** [comment]
✅ What's been completed:

- [Add Metrics to Record Validation Errors so that we will know the stream of the failing property](https://github.com/airbytehq/airbyte/issues/24710) - we now have expected and actual types for each type mismatch error and extra info like the docker image tag. See [this post]() for an into to using the updated dashboard
- [Schema validation refactor](https://github.com/airbytehq/airbyte/issues/24853) accomplished 2 main things: one, it cleaned up a lot of unnecessary code and extra calls to the validator/recreations of the validator. It also removed the limit of validating up to 10 records with errors per stream. This removal is currently behind a feature flag. 

🚧 What got in the way:
- Not much - @evantahler made local development to Datadog pretty breezy, so thank you for that!
- I backburnered getting in the config migration PR due to lots of OC Tzar work, so I still need to get that in. 

🌱 What's next:
1. Monitor the feature flag roll out, remove the feature flag code if it looks successful
2. Merge the refactored config migration code

❓ Learning / Questions / Changes:
- All sorts of learnings about datadog:
  - Application keys != API keys
  - Datadog doesn't like commas in its metrics!
  - [How datadog bills on custom metrics](https://docs.datadoghq.com/account_management/billing/custom_metrics/?tab=countrate#counting-custom-metrics)

⛔ Blockers:

None at the moment - https://github.com/airbytehq/airbyte-platform-internal/pull/5756 is still waiting on Cole, but it hasn't been up for very long and I expect it to go in without issues

**Comment by evantahler** [comment]
Can we close this epic?
