### ISSUE TITLE
oauth: better handling of "user configuration" error

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#20705]
## Tell us about the problem you're trying to solve
500 status responses are sent by the `/complete_oauth` route when a user perform and incomplete OAuth flow:
E.g:
* click the oauth button and then "cancel" on the popup. 
* do not tick the required permissions  in the popup.

The following error is sent with the 500 response: 

```
java.io.IOException: Undefined 'code' from consent redirected url.
```

Our alerting system on Datadog captures these errors but they do not characterize broken connectors, they characterize bad user input. 
Incomplete OAuth flow will lead to "Authentication required" message when users try to save their configuration.

## Describe the solution you’d like
I would like this kind of error to be better handled by connectors implementing errors: 
- return a `400` response with a more meaningful error message.

Filter out these responses from our Datadog alerting system - ignore 400 errors from the alert.

## Describe the alternative you’ve considered or used
Explicitely filter out traces with this error from our alerting system.

## Additional context
All the error traces can be found [here](https://app.datadoghq.com/apm/traces?saved-view-id=1370140) on Datadog

**Comment by evantahler** [comment]
Grooming:

These errors happen when within the oAuth flow the user hits cancel.  This is the right thing to do with a canceled oAuth callback, but our platform code doesn't handle this case

**Comment by erohmensing** [comment]
I'm not sure if this parameter is widespread or specific to coming from the Google Sheets connector, but if I cancel the google sheets oauth, the `/complete_oauth` request is sent with a query param `error=access_denied`. Maybe there is something we can do to check if something specific indicating that we aren't given access (or enough permissions) on the Oauth side, instead of checking what is missing? Or even checking for `error` :thinking:

![image.png](https://images.zenhubusercontent.com/5c9df18c8ddfda53adf61cc8/7b7eac3d-17a3-43de-bd76-4fbe9d9e7dee)

**Comment by evantahler** [comment]
I think ideally the frontend doesn't try to hit `/complete_oauth` if the user didn't complete the flow.  That would solve a lot of problems...

**Comment by erohmensing** [comment]
That was my first thought as well! But then I was wondering if it did make sense or not for the frontend to have an opinion on it :thinking: if the popup still sent the user to the callback url (this im not sure of) then I could see it happily sending things on for the Oauth handler to determine if everything required was given. (This makes more sense in the case of less than adequate permissions given. E.g. if we coded that into the frontend, and then something changed where our connector didn't need all of those permissions, that's something I'd expect to be changing in the oauth handler rather than in the frontend)
