### ISSUE TITLE
MSSQL Connector for Azure Managed Instance fails to connect when using CDC

### ISSUE THREAD

**Issue by nrcowan** [airbytehq/airbyte#20770]
Hi,

While trying to configure a new source connection to an Azure Managed Instance, with CDC enabled, I get the following error:

`airbyte-worker                      | 2022-12-21 19:29:25 INFO i.a.w.i.DefaultAirbyteStreamFactory(internalLog):120 - Checking that the SQL Server Agent is running using the query: 'SELECT status_desc FROM sys.dm_server_services WHERE [servicename] LIKE 'SQL Server Agent%' OR [servicename] LIKE 'SQL Server 代理%' '
airbyte-worker                      | 2022-12-21 19:29:25 INFO i.a.w.i.DefaultAirbyteStreamFactory(internalLog):120 - Set initial fetch size: 10 rows
airbyte-worker                      | 2022-12-21 19:29:25 INFO i.a.w.i.DefaultAirbyteStreamFactory(internalLog):120 - Exception while checking connection:
airbyte-worker                      | Stack Trace: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
airbyte-worker                      |   at java.base/java.util.ImmutableCollections$ListN.get(ImmutableCollections.java:680)
airbyte-worker                      |   at io.airbyte.integrations.source.mssql.MssqlSource.assertSqlServerAgentRunning(MssqlSource.java:317)
airbyte-worker                      |   at io.airbyte.integrations.source.mssql.MssqlSource.lambda$getCheckOperations$4(MssqlSource.java:248)
airbyte-worker                      |   at io.airbyte.integrations.source.relationaldb.AbstractDbSource.check(AbstractDbSource.java:85)
airbyte-worker                      |   at io.airbyte.integrations.base.ssh.SshTunnel.sshWrap(SshTunnel.java:266)
airbyte-worker                      |   at io.airbyte.integrations.base.ssh.SshWrappedSource.check(SshWrappedSource.java:43)
airbyte-worker                      |   at io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:123)
airbyte-worker                      |   at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:98)
airbyte-worker                      |   at io.airbyte.integrations.source.mssql.MssqlSource.main(MssqlSource.java:470)`

In the source code for the mssql connector, you can see a comment that references this potential issue here:
https://github.com/airbytehq/airbyte/blob/e34963c07e8c179fcc605a2246909f4d0c84f113/airbyte-integrations/connectors/source-mssql/src/main/java/io/airbyte/integrations/source/mssql/MssqlSource.java#L306

In an Azure MI, running the query `SELECT status_desc FROM sys.dm_server_services WHERE [servicename] LIKE 'SQL Server Agent%' OR [servicename] LIKE 'SQL Server 代理%'` does not return anything, even if the sql server agent is running. It always returns an empty list, hence the index 0 out of bounds exception.

**Comment by natalyjazzviolin** [comment]
Hi @nrcowan , please reformat your initial comment using our bug report template that I'm repasting below. If this issue is not reproducible, please start a thread in Slack or the forum. Closing for now.

 

## Environment
- **Airbyte version**:  example is 0.22.0-alpha
- **OS Version / Instance**: example macOS, Windows 7/10, Ubuntu 18.04, GCP n2. , AWS EC2
- **Deployment**: example are Docker or Kubernetes deploy env
- **Source Connector and version**: (if applicable example Salesforce 0.2.3) 
- **Destination Connector and version**: (if applicable example Postgres 0.3.3) 
- **Step where error happened**: Deploy / Sync job / Setup new connection / Update connector / Upgrade Airbyte

## Current Behavior
*Tell us what happens.*

## Expected Behavior
*Tell us what should happen.*

## Logs


## Steps to Reproduce
1.
2.
3.

## Are you willing to submit a PR?

Remove this with your answer.

**Comment by nrcowan** [comment]
Recreated the issue with the right formatting here: https://github.com/airbytehq/airbyte/issues/20847
