### ISSUE TITLE
Tech Spec "Track schema validation errors and create OC issues"

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#20987]
1. Log messages today in the platform about Records not matching Schema become Sentry or Data Dog Errors
2. These errors probably become OC issues.  Who is notified and what is the priority?  Keep in mind that maybe there is no user impact as Normalization might swallow the error

Questions:
* Should we use Sentry?
* Is this the same sentry project?
* What priority are the OC issues?
* Do we need new Github tags for workflows?
* Is there nuance between missing properties vs additional properties?  Are they equally bad?

**Comment by evantahler** [comment]
Update:

This work might be getting done already as part of column selection

https://airbytehq-team.slack.com/archives/C046V1Z2YJH/p1674682714717139

**Comment by evantahler** [comment]
https://github.com/airbytehq/airbyte/pull/15668 could be the PR that made the change

**Comment by erohmensing** [comment]
As it turns out, we already do track schema validation errors in datadog! https://github.com/airbytehq/airbyte/pull/13393 - Will look into talking to someone who knows how best to consume this info in datadog

@evantahler looking into the link there, it looks similar but ultimately not the same - you can see where we currently track validation errors, vs where we want to track unexpected field names [here](https://github.com/airbytehq/airbyte-platform/blob/876139deba3d60dacc6d5e5511eb7637918f0e5e/airbyte-commons-worker/src/main/java/io/airbyte/workers/general/DefaultReplicationWorker.java#L398-L409). IMO they could be handled similarly (though they might have different priorities, as it seems like maybe the latter was causing some major issues?). I think it makes sense to add this to the scope?

**Comment by evantahler** [comment]
> @evantahler looking into the link t[here](https://github.com/airbytehq/airbyte-platform/blob/876139deba3d60dacc6d5e5511eb7637918f0e5e/airbyte-commons-worker/src/main/java/io/airbyte/workers/general/DefaultReplicationWorker.java#L398-L409), it looks similar but ultimately not the same - you can see where we currently track validation errors, vs where we want to track unexpected field names here. IMO they could be handled similarly (though they might have different priorities, as it seems like maybe the latter was causing some major issues?). I think it makes sense to add this to the scope?

I think that does make sense!  I _think_ we would want to treat both "a required property is missing" and "a property that wasn't in the spec has appeared" in the same way - This record didn't match the spec, therefore this is a connector bug.
