### ISSUE TITLE
Google Directory API

### ISSUE THREAD

**Issue by sfc-gh-afedorov** [airbytehq/airbyte#2110]
## Tell us about the new integration you’d like to have
From the Google Directory API, we'd like a daily inventory of [users](https://developers.google.com/admin-sdk/directory/v1/guides/manage-users#get_all_users), [groups](https://developers.google.com/admin-sdk/directory/v1/guides/manage-groups#get_all_domain_groups), and [memberships](https://developers.google.com/admin-sdk/directory/v1/guides/manage-group-members#get_all_members).

## Describe the context around this new integration
Security and Compliance.

## Describe the alternative you are considering or using
We have third party solutions as well as a [Python script for login logs](https://github.com/snowflakedb/SnowAlert/blob/master/src/connectors/gsuite_logs.py) that we might extend.

**Comment by sfc-gh-afedorov** [comment]
some (working) sample code in case anyone finds it useful —

```import json
import os

from googleapiclient.discovery import build
from google.oauth2 import service_account

service_account_info = json.loads(os.environ['SVS_USER_CREDS'])

subject = 'security-monitor@sandbox.snowflakecomputing.com'
domain = 'sandbox.snowflakecomputing.com'

SCOPES = [
    'https://www.googleapis.com/auth/admin.directory.user.readonly',
]

creds = service_account.Credentials.from_service_account_info(service_account_info)
creds = creds.with_subject(subject).with_scopes(SCOPES)

service = build('admin', version='directory_v1', credentials=creds)
service.users().list(domain='sandbox.snowflakecomputing.com').execute()```

**Comment by sherifnada** [comment]
Spoke with @sfc-gh-afedorov  offline today to clarify requirements of the connector. Some notes: 
* The use case is to have a snapshot of the state of the entire Google Directory API every time a sync is performed in order to be able to say that on a given day, a user had certain permissions. 
* The sync cadence is expected to be once a day.

**Comment by sherifnada** [comment]
Breakdown of work for implementing this connector at the moment: 

- [ ] implement a connector which supports full refresh sync on the [User](https://developers.google.com/admin-sdk/directory/v1/guides/manage-users#get_all_users), [groups](https://developers.google.com/admin-sdk/directory/v1/guides/manage-groups#get_all_domain_groups), and [memberships entities](https://developers.google.com/admin-sdk/directory/v1/guides/manage-group-members#get_all_members) entities. 
- [ ] Ensure there is data populated in the account. Initially we'll be using Airbyte's Gsuite. This is probably not ideal from a sandboxing standpoint but should be a fine starting point. 
- [ ] Follow connector best practices on the connector (rate limiting, test all streams, etc..) 
- [ ] ensure documentation is added

**Comment by sherifnada** [comment]
the Gdirectory API only works with OAuth. This leaves our users with two options at the moment: 
1. Either they create the Oauth credentials by running a script like [this one](https://developers.google.com/admin-sdk/directory/v1/quickstart/python)
2. we don't release this connector until we have "proper" oauth support. It will require some small changes to the connector to add Airbyte's oauth implementation to it, but it shouldn't be too large. 

cc @cgardens -- do we have a timeline for oauth implementation?

**Comment by sherifnada** [comment]
@sfc-gh-afedorov we did some scoping after our conversation on Friday. Your initial description of the use case was that you'd like a separate table to be written everytime a sync is done. What if instead, we wrote the full dataset to the same table, but associated a `sync_id` to each record that was replicated in the same sync job, and associate a date with that sync_id? this would still allow you to find the full state of the directory on any given day, but the data would instead live in one table.

**Comment by sfc-gh-afedorov** [comment]
Sorry for the misunderstanding, def no need for separate tables -- a single table for all of the responses makes the most sense for our use-cases, e.g. finding the last time a user existed or was in a group in a domain and making sure they do not anymore.

Three separate tables for users, groups, and memberships make sense if you'd prefer them, or a single table that records the API name, request details (service, resource, method name, params), and response or error columns. If the responses from Google's API's contain any dates or metadata about when they recorded this state, that could be helpful, as well.

**Comment by sherifnada** [comment]
@sfc-gh-afedorov 

We just added this connector and merged it into master. 

The connector will be available in the next release of Airbyte (we usually release every Tuesday). If you can't wait and want to get started now trying it out in a running Airbyte instance, add the connector like described in https://docs.airbyte.io/integrations/custom-connectors#adding-your-connectors-in-the-ui . The information for the connector is: 

**Display Name**: <human_readable_connector_name e.g: Postgres>
**Docker repository name**: airbyte/<connector_name e.g: source-mongodb or source-googleanalytics-singer>
**Docker image tag**: 0.1.0
**Documentation URL**: hub.docker.com/r/airbyte/<connector_name>

For the record, the feature to append full refresh syncs into the same table (instead of overwriting the data in the table) is currently WIP and can be tracked here #2372. 

Let us know if you have any questions or comments on the implementation of the connector. We'd love to hear your feedback!
