### ISSUE TITLE
Source Sendgrid: support more entities

### ISSUE THREAD

**Issue by Manutd34** [airbytehq/airbyte#2117]
I am using sendgrid 0.1.2 and not listing out all tables as expected. Added to that in snowflake I see 2 tables one as transient and other as normal table.

Please look at slack conversation for more details and let me know if you need anything from my end.

https://app.slack.com/client/T01AB4DDR2N/C01A4CAP81L/thread/C01A4CAP81L-1613580745.241500

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368149100548) by [Unito](https://www.unito.io)

**Comment by sherifnada** [comment]
This issue is asking to support more of the entities available in the Sendgrid API. @Manutd34 is potentially interested in contributing this to the connector. Some pointers on getting started: 

### Prerequisites
1. Make sure you have python 3.7
2. clone the Airbyte repo
3. navigate to `airbyte-integrations/connectors/source-sendgrid` then run `python -m venv .venv` follwed by `source .venv/bin/activate` to activate the virtual environment for developing this connector

### Make the change 
4. Adding the schema of the entities being pulled from the sendgrid pi into `airbyte-integrations/connectors/source-sendgrid/source_sendgrid/schemas` 
5. make the changes to https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-sendgrid/source_sendgrid/client.py to add the new streams. each stream can be added by adding a method `stream__<stream_name>`. 
6. adjusting `integration_tests/confgiured_catalog.json` to contain the new entities

### Create a PR
7. create a PR that gives maintainers right to edit (so we can make some small adjustments to the code related to releasing the new connector version)

At any time if you have any questions or would like any assistance, please reach out to us on Slack or create a Draft PR with your questions. We strive to answer any questions or PRs quickly.

**Comment by cgardens** [comment]
closing as stale
