### ISSUE TITLE
Add icons to existing connectors

### ISSUE THREAD

**Issue by michel-tricot** [airbytehq/airbyte#2122]
## Tell us about the problem you're trying to solve
Right now we never show pretty icons for connectors. @gordalina collected all of them, we should add them to the connectors.

## Describe the solution you’d like
UPDATED 2021/04/09
* ~~the connector spec should expose a new field: `svgIcon` which contains a base64 string of the file.~~
* Store the icons in in airbyte-config/init/src/main/resources/icons/
* Serve them via the api for sources and destinations respectively the following endpoints: 
```
/v1/source_definitions/list
/v1/source_definitions/get
/v1/destination_definitions/list
/v1/destination_definitions/get
```
* Frontend should then be able to display the image. (When the API work is done, we will ask our FE contractor to consume the icons from the endpoints).

We should document best practices for images:
- square aspect ratio
- transparent background
- anything more?

[svg.zip](https://github.com/airbytehq/airbyte/files/6006894/svg.zip)

**Comment by cgardens** [comment]
should this be in the connector as opposed to just a switch statement in the API / UI?

**Comment by michel-tricot** [comment]
Yes. it should be in the connector. 

I mentioned the spec as it is where we expose the metadata of the connector. Agreed that it will be noisy but if we don't do it this way then we need to expose another communication channel between the connector and the outside of the connector.

**Comment by cgardens** [comment]
> if we don't do it this way then we need to expose another communication channel between the connector and the outside of the connector

I'm suggesting that it could be put in the API or UI, so what you describe here would _not_ be necessary. In general, I am having trouble understanding where you draw the line between what does and does not belong in the protocol. Square, base64 encoded svgs do not obviously belong in our protocol. I want to make sure at least have considered the alternative.

**Comment by michel-tricot** [comment]
interesting. I guess we need to draw the line on what belongs to the connector metadata and what doesn't.

I see a few things that could belong to it (or not):
- a uniq uuid for the connector
- a name
- a link to the documentation
- a link to the original vendor
- a list of authors
- a list of labels
- a status (mvp, alpha, beta, certified)
- a vendor image
- ...

what do you think?

**Comment by cgardens** [comment]
@jrhizor @sherifnada i think had some opinions on this as well.

there are 2 paths i see:
* spec contains every piece of metadata about that version of the connector. includes UI info... includes info that we can't enforce rules on (e.g. if we include unique uuid, there is no guarantee that people creating connectors will indeed create unique ids. if we have status, there is no guarantee that people create a bad connector and mark it as certified).
* spec is the bare minimum (least friction) for someone needs to use a connector programmatically. it does not include any information that we can't enforce (e.g. id uniqueness, status (mvp, alpha, etc)).

also regarding the implementation... keep in mind that in order to show the icons in the case where the icons are in the spec, it means you need to call get spec (which includes pulling the image and running the method) on every connector for which you want to get an icon. so if we want to include icons in the drop down list in create source / destination, first we need to do get spec on every single connector. for the lists of sources / destinations we need to do get spec on all connectors that are being used just to render those pages. i think this is probably a no go on that basis. putting this in the UI or API we can, without having to worry about performance issues, use the icons wherever we want.

**Comment by jrhizor** [comment]
I think there is a third path which is every piece of metadata that we don't care about controlling: vendor image, name, etc. Basically everything but unique IDs and airbyte certification.

**Comment by sherifnada** [comment]
IMO this should be outside the connector: i shouldn't need to download the whole connector to display its image, this will not scale. 

I lean slightly towards putting it in the config API where other metadata about a connector would live, but am fine if we decide the UI is a better home. Less opinionated on this point.

**Comment by jrhizor** [comment]
We could have a pre-poulated cache for images maybe. If someone is using their own custom connector internally I don't think we would want to prevent them from having an icon though?

**Comment by cgardens** [comment]
@michel-tricot wdyt?

**Comment by michel-tricot** [comment]
You convinced me! the piece about downloading the image to show icons is a deal breaker.

In that case we could have a metadata API about each existing connector (or simply part of the SourceDefinition/DestinationDefinition endpoint)? 

Could this metadata live in airbyte-config/init/src/main/resources/seed/*.yaml?

**Comment by cgardens** [comment]
agred

**Comment by gordalina** [comment]
MongoDB SVG: https://gist.github.com/gordalina/212f97160451bf78883e61633d67693c

**Comment by masonwheeler** [comment]
Are there SVGs available for the following connectors?

- Google Directory
- Instagram
- Gitlab
- Google Workspace Admin Reports
- Tempo
- Oracle
- Local JSON
- Local CSV
- BigQuery
- Snowflake
- MeiliSearch

**Comment by cgardens** [comment]
Not that we've collected yet! Let's move forward without them. Once you've figured out how to serve the existing ones, it should be pretty easy to add the ones you mentioned once they are collected.

**Comment by gordalina** [comment]
I could not find good icons for google workspace / directory so I used google instead.
These are only for sources, not destinations.
[svg-new.zip](https://github.com/airbytehq/airbyte/files/6348155/svg-new.zip)

**Comment by cgardens** [comment]
cool. going to close this issue because the initial work we set out to do is done. created this issue to add additional svgs.
