### ISSUE TITLE
SAT: stricter schema validation (artificially set additionalProperties to false on record schema validation)

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#21258]
## Tell us about the problem you're trying to solve
If we have a stream schema like this one:
```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "additionalProperties": true,
  "properties": {
      "id": "string",
      "foo": ["null", "string"],
      "bar": ["null", "string"],
   }
 }
```

And a record like this one:
```json
{"id": "1", "Foo": "xxx", "Bar": "xxx"} # note the capital letters
```

SAT record schema validation will pass 🟢  because the schema declaration error related to field casing will remain unnoticed. 
Because:
* The schema declares the `foo` and `bar` field as nullable. As these two fields are absent during the validation no error is raised because considered null.
* The schema has `additionalProperties` set to `true` (by default for backward compatibility) so fields not declared in the schema `Foo` and `Bar` are tolerated.
* The record shares at least one field with the schema (`id`), there's a field intersection so the structure is considered valid (`test_record_structure`).

## Describe the solution you’d like
I would like to artificially set `additionalProperties` to `false` on stream schema while running SAT schema validation.
This will allow us to catch the errors related to field naming inconsistencies.

## Additional context
This kind of problem  happened in [this P0](https://github.com/airbytehq/oncall/issues/1293) and led to broken normalization.

**Comment by evantahler** [comment]
This test makes sense.  Can you share more about how you could end up with a spec like this where all the 'data' properties could be null?  Is this anticipating a stream that produces records like this (optional properties toggling on and off):

```
{"id": 1, "foo": "a"}
{"id": 2, "bar": "b"}
```

**Comment by alafanechere** [comment]
@evantahler I'm not sure I totally get your question.
We have [this check](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py#L491) that performs a field intersection computation. So if a record does not share any field with the stream schema, and all the fields declared in the stream schema are nullable, it will fail. 

The docstring of this test is quite helpful: 
```
        Check object structure similar to one expected by schema. Sometimes
        just running schema validation is not enough case schema could have
        additionalProperties parameter set to true and no required fields
        therefore any arbitrary object would pass schema validation.
        This method is here to catch those cases by extracting all the paths
        from the object and compare it to paths expected from jsonschema. If
        there no common pathes then raise an alert.
```

**Comment by evantahler** [comment]
I was thinking about a source could have all properties nullable (like airtable) except for a primary key. I guess that makes sense if there's a row in the table with no content.

**Comment by evantahler** [comment]
Goals

```
{"id": 0} -> Valid
{"id": 1, "foo": "a"} -> Valid
{"id": 2, "bar": "b"} -> Valid
{"id": "3", "Foo": "xxx", "Bar": "xxx"} -> Invalid
{"id": "4", "aaa": "xxx", "bbb": "xxx"} -> Invalid
{"id": "5", "Foo": "xxx", "Bar": "xxx", "foo": "xxx", "bar": "xxx"} -> Invalid
```

**Comment by evantahler** [comment]
Moving to the backlog as this becoming important for Column Selection (cc @mfsiega-airbyte)

**Comment by evantahler** [comment]
In [#column-selection](https://airbytehq-team.slack.com/archives/C046V1Z2YJH) they noticed that there are probably a lot of connectors are suddenly going to fail CAT once we complete this issue.  If there really are going to be a lot of connectors to change, we shouldn't merge in this change to CAT without thinking about how the rollout should go.

I think there are 2 competing goals here:
* CAT approximates what a real sync does, so if we find that a connector is failing, especially a GA connector, a failing test should mean that it jumps to the top of the relevant team's priority to fix
* Teams are CEOs of their own projects and if they suddenly have to change what they are doing to fix CAT tests, at the expense of their OKRs/goals, that's not a good experience

So, a rollout plan could look like this:
1. Make the changes to CAT in a PR
2. run the new CAT against all connectors locally and get a list of those which are going to fail the new test (because they have properties in records that are not in the connector schemas)
3. In the same PR, add a `bypass_reason` for the new test for all those connectors which fail the new test
    * Tag the PR with a new label like `record-schema-mismatch` so we can track this
    * Add the relevant `community` label to get help from our OSS community to make the change
    * Add a guide in the issue how to fix the issue (likely adding the missing record property to the catalog) and removing the bypass reason
    * We've got a tool (TODO) from previous work to help make a back of issues
4. Share the list of issues created with @andyjih and @mfsiega-airbyte so they can monitor their completion and decide how that effects the rollout of column selection

Technical notes:
* Connectors can still choose to bypass any test, including this new one we are about to add
* We still want to ensure that connector catalogs have [`allowAddtionalProperties=true`](https://github.com/airbytehq/airbyte/blob/ea776ef19aa8ec9f2928a77e765f990e0354d61f/airbyte-integrations/bases/connector-acceptance-test/connector_acceptance_test/tests/test_core.py#L460) to help with version upgrades, even though it philosophically is at odds with the new record<->catalog check we are going to add
