### ISSUE TITLE
New source: Harvest

### ISSUE THREAD

**Issue by bludrop** [airbytehq/airbyte#2134]
## Tell us about the new integration you’d like to have
Which source and which destination? Which frequency?
Harvest (time tracking and billing software) to BigQuery, daily frequency

## Describe the context around this new integration
Which team in your company wants this integration, what for? This helps us understand the use case.
The People team uses this information to track consultant productivity and billed amounts.

## Describe the alternative you are considering or using
What are you considering doing if you don’t have this integration through Airbyte?
A singer tap already exists for this (tap-harvest). Currently using Stitch to transfer this data.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368149331631) by [Unito](https://www.unito.io)

**Comment by michel-tricot** [comment]
Thank you @bludrop! 

How good the is the singer tap? Have you used it?

**Comment by bludrop** [comment]
I have not used it "on its own", but I think Stitch is using it to extract our data from Harvest everyday, which seems to work pretty well.

**Comment by Zirochkaa** [comment]
## Integration Vetting


**Webhook-based? (no/partially/yes)**
No.

**Available authentication modes (API key/Oauth/other)**
They support [Personal Access Token](https://help.getharvest.com/api-v2/authentication-api/authentication/authentication/#personal-access-tokens) and [OAuth2 Authentication](https://help.getharvest.com/api-v2/authentication-api/authentication/authentication/#oauth2-application). We could use `Personal Access Tokens` since they are easy to obtain (it takes like 30 seconds to generate one) and they have full access to all available streams.
In order to generate one:
1. Do to [Account Settings](https://airbyte.harvestapp.com/company/account) page (login/password are in LastPass);
1. Under Integrations section press `Authorized OAuth2 API Clients` button;
1. New page will be opened on thich you need to click on `Create New Personal Access Token` button and follow instructions.

The same flow (3 steps) can do Airbyte users in order to get their `Personal Access Tokens`.

**Creating an account**
I created an account and put login/password into LastPass.
We have 30 days of free trial (which started today) and after 30 days it'll cost us $12 per user (in terms of team). Currently there is only one actual user (Airbyte Developer) and I think one will be enough.

**How to populate the account with data?**
_Can it be done entirely through the API?_
Yes. Look at postman collection. Also when I created an account I chose an option about filling some test data so there are some test data already available but I'm not sure whether it's for all streams or for some of them.

_Will it require some work through the UI? If so, what is required?_
You can also fill the data using UI.

**Available streams for sync**
Clients
Client Contacts
Company
Invoice Messages
Invoice Payments
Invoices
Invoice Item Categories
Estimate Messages
Estimates
Estimate Item Categories
Expenses
Expense Categories
Tasks
Time Entries
Project User Assignments
Project Task Assignments
Projects
Roles
User Billable Rates
User Cost Rates
User Project Assignments
Users
Expense Reports
Uninvoiced Report
Time Reports
Project Budget Report
 
**Integration supports incremental sync?**
Yes, depending on stream.
Streams support `updated_since` parameter in request.
Few streams can be run only in full sync mode: Company, Roles, User Billable Rates, User Cost Rates and all Reports streams (there are 4 of them).

**Other information/blockers**
Link to the `Harvest docs` is [here](https://help.getharvest.com/api-v2/).
Link to the `stitch` page for Harvest is [here](https://www.stitchdata.com/docs/integrations/saas/harvest).
Link to the `tap-harvest` is [here](https://github.com/singer-io/tap-harvest).
Also Harvest provides [Postman Collection](https://help.getharvest.com/api-v2/introduction/overview/postman-collection/) with almost all streams available for using.

**Comment by htrueman** [comment]
Found that [Estimates API](https://help.getharvest.com/api-v2/estimates-api/estimates/estimates/) returns a 403 error when I try to make a requests. Looking for the reason and possible solutions.
