### ISSUE TITLE
The connector builder UI should display the valid jinja macros

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#21370]
## Tell us about the problem you're trying to solve

Connector developers can use pre-defined jinja macros as part of InterpolatedString, but it is difficult for them to know what they are and how to use them without reading through the code or the documentation.

The connector builder UI should know what jinja macros are available so they can be conveyed to the connector developer.

[Existing macros with their corresponding docstring](https://github.com/airbytehq/airbyte/blob/master/airbyte-cdk/python/airbyte_cdk/sources/declarative/interpolation/macros.py):
- now_local(): Current local date and time
- now_utc(): Current local date and time in UTC timezone
- today_utc(): Current date in UTC timezone
- timestamp(datetime): Converts a number or a string to a timestamp
- max(*args): Returns biggest object of an iterable, or two or more arguments
- day_delta(num_days): Returns datetime of now() + num_days
- format_datetime(datetime, format): Converts datetime to another format

[Additional contextual values to show](https://docs.google.com/document/d/1f9EQAvUHQ5x0VJKUoQCN6z9uCdnZ5B4ZLOHwRhIbIRY/edit#heading=h.w280snr40tja)

## Solution
Add an enum to the connector manifest describing the enum values

## Alternatives
- Hardcode the in the UI
- Add an endpoint to the connector builder returning the enum values
- Link to a documentation page

**Comment by flash1293** [comment]
Going one step further with this we could also show available variables in the same way (see https://github.com/airbytehq/airbyte/issues/21013) - e.g. if stream slicing is enabled it suggests `stream_slice`

**Comment by Upmitt** [comment]
https://www.loom.com/share/97ace0cc6a6d47c79c79be45c444f127 - proto: https://www.figma.com/proto/F1ljvrJerLoVbNvtejBWid/LOW-CODE-CONNECTOR-BUILDER?page-id=3875%3A130182&node-id=3875%3A130183&viewport=3385%2C1073%2C1&scaling=contain&starting-point-node-id=3875%3A130183 - ("cmd + space" doesn't work in Figma, so to simulate it just press "space")

**Comment by Upmitt** [comment]
Figma updated: https://www.figma.com/proto/F1ljvrJerLoVbNvtejBWid/LOW-CODE-CONNECTOR-BUILDER?page-id=4040%3A130874&node-id=4040%3A130875&viewport=3202%2C841%2C1&scaling=min-zoom&starting-point-node-id=4040%3A130875

**Comment by girarda** [comment]
@Upmitt [here's the list of additional contextual values that can be available](https://docs.google.com/document/d/1f9EQAvUHQ5x0VJKUoQCN6z9uCdnZ5B4ZLOHwRhIbIRY/edit#heading=h.w280snr40tja)

**Comment by lmossman** [comment]
@Upmitt I've moved this issue back to In progress, because I think it needs some more iteration on a couple of things:
1. The doc that @girarda  linked above: https://docs.google.com/document/d/1f9EQAvUHQ5x0VJKUoQCN6z9uCdnZ5B4ZLOHwRhIbIRY/edit#heading=h.w280snr40tja
This doc enumerates the different contextual values that are available in the different components of the UI. Since these are neither user inputs, nor jinja macros, we may need a new section/icon for these values to display in the menu
2. As in [this design](https://www.figma.com/proto/F1ljvrJerLoVbNvtejBWid/LOW-CODE-CONNECTOR-BUILDER?page-id=4145%3A141716&node-id=4202-140612&viewport=695%2C224%2C0.14&scaling=min-zoom&starting-point-node-id=4158%3A134196&show-proto-sidebar=1), where you added a nice looking "pill" box for the user input (replacing the complex `{{config['field']}}` string), we probably also want to display something similar for the jinja macros and contextual values:
<img width="486" alt="Screen Shot 2023-03-17 at 3 28 43 PM" src="https://user-images.githubusercontent.com/22731524/226063767-121fc41f-27ce-4609-824e-33969f06f336.png">

If you could iterate on those points, that would be great!

**Comment by lmossman** [comment]
These were added to the tooltips in https://github.com/airbytehq/airbyte-platform-internal/pull/6053
