### ISSUE TITLE
Stripe connector don't allow restricted API tokens.

### ISSUE THREAD

**Issue by ttr-tf** [airbytehq/airbyte#21394]
Stripe allows you to create "restricted api tokens" to interact with only of a subset of API endpoits.
In my case i have a token that has only permissions on "disputes".

The problem is that on the source screen while creating the Stripe source, if you use a restricted token the "save and test" will always fail because the stripe connector validate ALL the permissions required for a full synchronization of Stripe account.

If we enforce the token value ( with octavia by example) the synchro of the dispute table will work. 
This is only related to UI problem. 

## Logs
PermissionError(message="The provided key 'rk_live_*********************************************************************************************Twm3u3' does not have the required permissions for this endpoint on account 'acct_1****'. Having the 'rak_connected_account_read' permission would allow this request to continue.", http_status=403, request_id='req_****')

## Steps to Reproduce
1. go to source > new source > Stripe
2. Fill the form with all the credential and put the restricted api token in "secret key" field
3. click on "save and test"

## Are you willing to submit a PR?
No

**Comment by natalyjazzviolin** [comment]
@ttr-tf please update the initial comment according to the template, then I will reopen the issue:
## Environment
- **Airbyte version**:  example is 0.22.0-alpha
- **OS Version / Instance**: example macOS, Windows 7/10, Ubuntu 18.04, GCP n2. , AWS EC2
- **Deployment**: example are Docker or Kubernetes deploy env
- **Source Connector and version**: (if applicable example Salesforce 0.2.3) 
- **Destination Connector and version**: (if applicable example Postgres 0.3.3) 
- **Step where error happened**: Deploy / Sync job / Setup new connection / Update connector / Upgrade Airbyte

## Current Behavior
*Tell us what happens.*

## Expected Behavior
*Tell us what should happen.*
