### ISSUE TITLE
SQL Sources can skip records if the cursor field is being modified during a sync

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#21500]
More details about this problem can be found here: https://www.grouparoo.com/blog/building-a-sync-engine

---

Consider the same dataset as https://github.com/airbytehq/airbyte/issues/14732 with an incremental sync using `updated_at` as the cursor:

| id | email             | name  | created_at          | updated_at          |
|----|-------------------|-------|---------------------|---------------------|
| 1  | evan@example.com  | Evan  | 2022-01-01 00:00:00 | 2022-01-01 00:00:00 |
| 2  | brian@example.com | Brian | 2022-01-02 00:00:00 | 2022-01-02 00:00:00 |
| 3  | andy@example.com  | Andy  | 2022-01-03 00:00:00 | 2022-01-03 00:00:00 |
| 4  | greg@example.com  | Greg  | 2022-01-04 00:00:00 | 2022-01-04 00:00:00 |

Today, we `select * from users order by updated_at LIMIT 1 OFFSET 1` and then adjust the offset until we are done:

```SQL
select * from users ORDER BY updated_at LIMIT 1 OFFSET 0 -- 1 record, Evan
select * from users ORDER BY updated_at LIMIT 1 OFFSET 1 -- 1 record, Brian
select * from users ORDER BY updated_at LIMIT 1 OFFSET 2 -- 1 record, Andy
select * from users ORDER BY updated_at LIMIT 1 OFFSET 3 -- 1 record, Greg
select * from users ORDER BY updated_at LIMIT 1 OFFSET 4 -- 0 records, we are done!
```

However, if records are being updated while the sync is running, it is likely that we will end up skipping some records.  If, while we are syncing, user 2 updates and becomes sorted after Greg.  This means that it would be possible to skip a record

| id | email             | name  | created_at          | updated_at          |
|----|-------------------|-------|---------------------|---------------------|
| 2  | brian@example.com | Brian | 2022-01-02 00:00:00 | **2022-01-10 00:00:00** |

## The problem today:
```SQL
select * from users ORDER BY updated_at LIMIT 1 OFFSET 0 -- 1 record, Evan
select * from users ORDER BY updated_at LIMIT 1 OFFSET 1 -- 1 record, Brian
-- Brian updates NOW
select * from users ORDER BY updated_at LIMIT 1 OFFSET 2 -- 1 record, Greg
select * from users ORDER BY updated_at LIMIT 1 OFFSET 3 -- 1 record, Brian again
select * from users ORDER BY updated_at LIMIT 1 OFFSET 4 -- 0 records, we are done!
-- ... we never saw user 2, Andy.
```

The right way to solve this problem is that **our queries should never use an offset without locking the cursor value**.  The query should be modified to use the last seen cursor and step though each cursor-defined-chunk.  Once we know the number of records in each cursor-defined-chunk, _then_ we can use offset to step though the number of records in each cursor-defined-chunk.

## The suggested solution:
```SQL
select * from users ORDER BY updated_at LIMIT 1 -- 1 record, Evan
-- The current cursor position extracted from the latest record is `2022-01-01 00:00:00`
select * from users WHERE updated_at = "2022-01-01 00:00:00" ORDER BY updated_at LIMIT 1 OFFSET 1 
-- there are no more records in this cursor-defined-chunk, we can move on.

select * from users WHERE updated_at > "2022-01-01 00:00:00" ORDER BY by updated_at LIMIT 1 -- 1 record, Brian
-- The current cursor position extracted from the latest record is `2022-01-02 00:00:00`
select * from users WHERE updated_at = "2022-01-02 00:00:00" ORDER BY updated_at LIMIT 1 OFFSET 1 
-- there are no more records in this cursor-defined-chunk, we can move on.

-- Brian updates NOW

select * from users WHERE updated_at > "2022-01-02 00:00:00" ORDER BY by updated_at LIMIT 1 -- 1 record, Andy
-- The current cursor position extracted from the latest record is `2022-01-03 00:00:00`
select * from users WHERE updated_at = "2022-01-03 00:00:00" ORDER BY updated_at LIMIT 1 OFFSET 1 
-- there are no more records in this cursor-defined-chunk, we can move on.

select * from users WHERE updated_at > "2022-01-03 00:00:00" ORDER BY by updated_at LIMIT 1 -- 1 record, Greg
-- The current cursor position extracted from the latest record is `2022-01-04 00:00:00`
select * from users WHERE updated_at = "2022-01-04 00:00:00" ORDER BY updated_at LIMIT 1 OFFSET 1 
-- there are no more records in this cursor-defined-chunk, we can move on.

select * from users WHERE updated_at > "2022-01-04 00:00:00" ORDER BY by updated_at LIMIT 1 -- 1 record, Brian (again)
-- The current cursor position extracted from the latest record is `2022-01-10 00:00:00`
select * from users WHERE updated_at = "2022-01-010 00:00:00" ORDER BY updated_at LIMIT 1 OFFSET 1 
-- there are no more records in this cursor-defined-chunk, we can move on.

select * from users WHERE updated_at > "2022-01-10 00:00:00" ORDER BY by updated_at LIMIT 1 -- No records, we are done
```

... and now we've seen all the records, and we are sure that we haven't skipped any!

**Comment by edgao** [comment]
I ask myself that exact question every time I think about cursors >.>

agree that the problem exists; the proposed solution maybe still has issues with low-granularity cursors but is strictly better than what we have today :shrug: The case I'm thinking of is if updated_at is a date, rather than a timestamp - then I _think_ if users are deleting+inserting records with `updated_at = today()` while a sync is running, we might still skip records?

**Comment by evantahler** [comment]
@edgao I think Airbyte's "at least once delivery" saves us here!  In the case where we have a corse date cursor and we are on "today", we'll get _some_ of the records this sync and then end.  The next time we sync, tomorrow, we will resume with the same cursor value we had previously (now yesterday) and get everyone in that bucket, including the people we missed and the people we already saw.

**Comment by rodireich** [comment]
If we take the approach of using offset from the last read cursor (as opposed to the initial sync cursor).
That would bring us to eventual consistency - that is a subsequent sync will pick up any records that updated mid-flight.
That should be sufficient I think.

**Comment by akashkulk** [comment]
This is definitely an issue on the source side where we are constructing one query 

e.g. : 
`SELECT * FROM "table_name" WHERE "id" > 5 ORDER BY "id"`

at `AbstractJdbcSource.queryTableIncremental()` [https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-jdbc/src/main/java/io/airbyte/integrations/source/jdbc/AbstractJdbcSource.java#L334]

We'd have to change the architecture of how we query the table to support the "cursor defined checks". Couldn't come up with a better word for it either :(

**Comment by subodh1810** [comment]
We might have customers getting impacted cause of this https://github.com/airbytehq/airbyte/issues/21500

**Comment by akashkulk** [comment]
I tried to reproduce this on Postgres, MySQL, Mssql and was unable to. 

Setup: 
-  Changing batch size = 1. This ensures that we have to fetch a new result from the source database. Verified this by inspecting the `ResultSet` and seeing that only one row is fetched at a time. In addition, disconnecting the connector from the database paused the connector from processing results, meaning that the connector was indeed fetching results from the database.
- Setting a breakpoint while processing results in an incremental sync
- Update the cursor associated with a previously processed row.

The expectation was that the next non-processed value would be clobbered based on the explanation above. However, what I actually saw was that the results are read in a single transaction and a snapshot of the database at that point in time of the initial query is locked in. This is verified by querying the `pg_stat_activity` table in Postgres to see the list of active queries : https://www.loom.com/i/ed4da0e890464ca3b671b35d56abb53b. As you can see, the based `select * from table where cursor_field > cursor_valie ORDER BY cursor_field INCR` is running without breaking it into limits and offsets. Any changes to the source database after the sync had begun were not picked up by the connector.

**Comment by akashkulk** [comment]
Data loss can occur when there are live modifications to the underlying source. This is a known problem, however for full-refresh mode this is fine as the next sync will pick up the changes, as no state is saved between syncs. 

For incremental mode, there are some more nuances. If these records are added to the table while the incremental sync is happening, then we can be in a situation where these records are missed. Since the cursor is normally chosen in a way that it keeps incrementing beyond the latest value in the database, this is normally not a problem. If the user is choosing a cursor in  a way such that this invariant is not respected, this can be treated as a user error. 

However, there can be a situation where we end up missing a record altogether. Consider a case where we are performing an incremental append. Data snapshot while performing a read : 
| id | email             | name  | created_at          | updated_at          |
|----|-------------------|-------|---------------------|---------------------|
| 1  | evan@example.com  | Evan  | 2022-01-01 00:00:00 | 2022-01-01 00:00:00 |
| 2  | brian@example.com | Brian | 2022-01-02 00:00:00 | 2022-01-02 00:00:00 |
| 3  | andy@example.com  | Andy  | 2022-01-03 00:00:00 | 2022-01-03 00:00:00 |
| 4  | greg@example.com  | Greg  | 2022-01-04 00:00:00 | 2022-01-04 00:00:01|

The state Airbyte saves corresponds to the high watermark of the last `updated_at` timestamp it saw. In this case, it is `2022-01-04 00:00:01`. During the read, this entry 3 was already being updated, but the read replica was stale and didn't get reflect the changes in the DB. The new state of the table looks like: 

| id | email             | name  | created_at          | updated_at          |
|----|-------------------|-------|---------------------|---------------------|
| 1  | evan@example.com  | Evan  | 2022-01-01 00:00:00 | 2022-01-01 00:00:00 |
| 2  | brian@example.com | Brian | 2022-01-02 00:00:00 | 2022-01-02 00:00:00 |
| 3  | andy@example.com  | Andy  | 2022-01-03 00:00:00 | 2022-01-04 00:00:00 |
| 4  | greg@example.com  | Greg  | 2022-01-04 00:00:00 | 2022-01-04 00:00:01 |

However, on the next incremental sync, we will miss the updated record 3 since it is before Airbyte's calculated high watermark. This will result in a discrepancy between the source DB and the destination DB. CDC is the only way to actually get round this case. 

From the customer's point of view this could be a valid case. Consider the sequence of events : 
1. User 3 (Andy) is created on the application side
| id | email             | name  | created_at          | updated_at          |
|----|-------------------|-------|---------------------|---------------------|
| 3  | andy@example.com  | Andy  | 2022-01-03 00:00:00 | 2022-01-04 00:00:00 |
3. User 4 (Greg) is created on the application side
| id | email             | name  | created_at          | updated_at          |
|----|-------------------|-------|---------------------|---------------------|
| 4  | greg@example.com  | Greg  | 2022-01-03 00:00:00 | 2022-01-04 00:00:01 |
4. Both entries are written into the database by the customer's application. However, the transaction for User 4 is committed first. 
5. Airbyte starts a sync
6. User 3 is committed into the database
7. Data loss as User 3 is never synced. 

To me, this seems like a plausible sequence of events from the application developer's point of view as they may not necessarily be concerned about which entry is committed to the database first (as long as the timestamps are accurate). It may not even be performant for them to do so.

**Comment by akashkulk** [comment]
Some additional options: 

**_Option 4_** : Provide documentation and best practices for how to increment a cursor value. Users are largely aware that cursors should be monotonically increasing. However, creating a monotonically increasing cursor value on (say) the application backend doesn't correspond to the values being monotonically increasing in Postgres. A good way to do so is to define a Postgres trigger : https://x-team.com/blog/automatic-timestamps-with-postgresql/
This can be included in the documentation of how to choose a good cursor value

**_Option 5_** Implement Xmin syncs similar to what Fivetran does. They actually doesn't have an option for cursor-defined incremental syncs. A previous investigation into this : https://github.com/airbytehq/airbyte/issues/5022)
-

**Comment by akashkulk** [comment]
Decision : Currently, we will be updating documentation based on best practices to update the cursor field. The other solutions are put on hold as this data loss is not as egregious as we initially thought

Tech Spec : https://docs.google.com/document/d/14-27V39nxP43AUIVdUya0ywpr5ZQeYWBxjxbkIgHa6U/edit#heading=h.fa72b39y2m99
