### ISSUE TITLE
Helm Chart for stable version

### ISSUE THREAD

**Issue by Imploxion** [airbytehq/airbyte#21518]
Hello.
As I see 0.40.28 is the latest stable version, but I can't find a Helm Chart of this version.
There is another version I can get in helm or find this chart in other place.
Thank you.

**Comment by TheEverlastingBish** [comment]
Hello, 

Just to add to this. When I source the Helm Chart `"0.43.13"` it only upgrades Airbyte to the earliest version when that chart was bumped with ~ `0.40.26` instead of say `0.40.28`.

Are you thinking of updating the chart versions for each `app_version` upgrade?

Otherwise, how do I get to the latest `app_version` using just the helm chart version?

**Comment by marcosmarxm** [comment]
Here you can find the app_version:
https://github.com/airbytehq/airbyte/blob/5ceb14a91ef4c75b72cc46cf91267db6d54fdb68/charts/airbyte/Chart.yaml#L24
 
Isabel the version is different because the Chart receives changes different from the platform, as new variables or resources control for Kubernetes. Today Helm deployment it is Beta and will improve in the future. Version try to follow Airbyte App but sometimes can have problems.
