### ISSUE TITLE
show when the UI is disconnected from the API server

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#2152]
## Tell us about the problem you're trying to solve
If you have an airbyte webapp window open and turn off the server, the behavior isn't handled well in a few places. Selecting a source in onboarding just silently fails for example. 

Instead of solving each of these cases (which I imagine is very time consuming) we could just have an indicator at the top of the page when we are unable to poll the server after a few seconds.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368214661251) by [Unito](https://www.unito.io)

**Comment by johnlafleur** [comment]
Design suggestion: https://www.figma.com/file/AODY4oi15iI5l0fbxHvobt/Daxtarity?node-id=21380%3A1307

**Comment by cgardens** [comment]
In a vacuum, this seems great. before we move forward with this i remember we have: https://github.com/airbytehq/airbyte/issues/1495. Do you think that we would want to display this error in the same way we display generic errors?

I bring it up because for the can't connect error, i think it is fine that it is really annoying and in the middle of the screen. for other generic errors we probably wouldn't want that. so either we can have generic errors just look different from the can't connect to api error or we can make them the same but less intrusive.

**Comment by johnlafleur** [comment]
I think there could be 2 different levels of error messages: critical, and non-critical. 
The API disconnect one is a critical. So I would suggest this design for the critical message. But I'll work on #1495 so we have a good understanding of that part.

**Comment by cgardens** [comment]
ok. sounds good.

**Comment by michel-tricot** [comment]
Not super fan of having two places where errors could show. We could keep a generic display as #1495. The only diff would be that these critical errors need a manual action to stop showing or smth like that.
