### ISSUE TITLE
Source Google Spreadsheets: silent failure when discovering a sheet with duplicate headers

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#2153]
## Expected Behavior
If my spreadsheet has duplicate header and I try to replicate it with the google sheets connector, I expect two things to happen: 

1. The UI should display a warning message saying "We can't replicate column X because its header is duplicated. Please resolve the duplicity and try again". 
2. The connector should allow me to replicate every other non-duplicate column.

## Current Behavior
The connector fails to discover the schema entirely, instead returning an empty schema. 

## Steps to Reproduce
1. Create a spreadsheet with duplicate headers
1. run `discover`
1. no schema is returned

## Severity of the bug for you
Medium -- an edge case but blocking when it happens

## Airbyte Version
spreadsheets 0.1.7 (latest) -- Airbyte version irrelevant

## Acceptance Criteria
1. If there are duplicate columns, the connector logs warning messages and continues with schema discovery as normal. 
2. If there are no non-duplicate columns in a sheet, raise an exception and fail discovery.

**Comment by makalaaneesh** [comment]
Hi, can I pick this up?! 
I went through the code and was able to see that the google-sheets source just throws an exception in the discover step if it encounters duplicate headers.

@sherifnada Couple of questions though: 
>If there are duplicate columns, the connector logs warning messages and continues with schema discovery as normal

So, the connector should not include the duplicated column in the stream? (i.e. inline with your expected behavior)

>The UI should display a warning message saying "We can't replicate column X because its header is duplicated. Please resolve the duplicity and try again".

Is this automatically setup? I.e. if the connector logs warnings, will they automatically show up on the UI?

**Comment by sherifnada** [comment]
@makalaaneesh of course, feel free to take this on! 

> So, the connector should not include the duplicated column in the stream? (i.e. inline with your expected behavior)
Correct, the connector should just drop both columns (or keep one of them e.g: the one that appears first since that at least gives the user some way to replicate data). 

> Is this automatically setup? I.e. if the connector logs warnings, will they automatically show up on the UI?
Nope, but this is a great idea. It would be very nice to have the UI show warnings. but since that requires changes to the UI it's probably going to be separate from this issue/PR. Alternatively, we could change the `check` method (in addition to the change in this PR) to fail if there are duplicate columns. This way any messages returned in the `message` field of the connection check message will be displayed on the UI automatically. You're welcome to also implement that in addition to the change described in this issue!

**Comment by makalaaneesh** [comment]
Thanks!
>the connector should just drop both columns (or keep one of them e.g: the one that appears first since that at least gives the user some way to replicate data)

Going with dropping both the columns as I think it's the simpler/cleaner solution for now. The alternative of keeping one of them can be confusing to the user since it isn't obvious which one of the duplicates the connector would pick. Also, currently, there would be no way to identify which one was picked from the connection settings UI. Once we have the UI change to show warnings, we could revisit this if needed. Let me know if you think otherwise!

>Alternatively, we could change the check method (in addition to the change in this PR) to fail if there are duplicate columns.

Hmm, that's interesting! Although from [docs](https://github.com/airbytehq/airbyte/blob/master/docs/architecture/airbyte-specification.md#check), it seems like the `check` command is only to "verify that the provided credentials are usable". Doesn't seem like it should be concerned with checking for duplicate columns. Thoughts?

**Comment by sherifnada** [comment]
@makalaaneesh very generally speaking the `check` command tries to surface any potential issues that may disrupt using the connector ahead of time. The most obvious form of this is checking credentials but it is not limited to that. So I'd say in this case doing it in the check command is totally fine as long as we provide a readable error message for the user.

**Comment by makalaaneesh** [comment]
@sherifnada raised a PR https://github.com/airbytehq/airbyte/pull/2905
