### ISSUE TITLE
Solve the requirement for docker-in-docker

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#2157]
## Tell us about the problem you're trying to solve
Running docker containers from within docker containers has become a big friction point. It limits what tools we can use to deploy Airbyte (e.g. most "one-click" docker deploys are out of bounds, K8s), and it is hampering us as we figure out how to add new functionality to Airbyte in a modular fashion (e.g. custom DBT, post hooks, normalization, transformations, etc)

## Describe the solution you’d like
We need to figure out how we are going to deal with this going forward. It may no be necessary to implement the vision immediately (depending on what it is), but we need to be able to design new features with the constraints of that vision in mind.

## Checklist
* [x] - technical brainstorm on how to move forward
* [ ] - technical proposal on how to implement the option described in these [notes](https://docs.google.com/document/d/1QWq-PJOU4sPQW5TrID9M1b-nWnj1cSvbU6fdvd92sO0/edit)
* [ ] - tbd...

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368214476553) by [Unito](https://www.unito.io)

**Comment by cgardens** [comment]
Scheduler brainstorm for how to get started here.

**Comment by cgardens** [comment]
The brainstorm happened and the checklist above has been updated with next steps (and notes from the meeting). Un-assigning myself as for now as we have hit the desired deliverable for the moment. This issue will be come active again when we begin work on the next item on the checklist.

**Comment by Tranquility** [comment]
How are you planning to solve this? Are you planning to change the Airbyte Specification significantly?

**Comment by jrhizor** [comment]
@Tranquility We're addressing this as part of https://github.com/airbytehq/airbyte/issues/3839

For each platform we launch on (like Kubernetes), we're implementing a java `Process`-like model that functions without the "docker-in-docker" dependencies. In the Kuberentes case, we can do something where we have a `Process` that interacts with the Kube API and uses servers to transmit data between the source and the sync worker and the sync worker and the destination.

This happens without modifying the Airbyte specification at all.

I'm going to close this issue since we have an approach that we're already implementing for Kube.

We should create separate issues for other non-Kube platforms we want to support. 

The one caveat is that some platforms do not have the flexibility to support these requirements (or can't do it in a way with reasonable latency). For now we're deprioritizing those cases.
