### ISSUE TITLE
Evaluate Databricks Destination and scope path to beta

### ISSUE THREAD

**Issue by grishick** [airbytehq/airbyte#21815]
We need to answer the following questions about our databricks destination connector:
 - does it work as expected (as defined in the documentation)?
 - what limitations it has currently, how critical each of the limitations are, and how hard it is to remove each limitation?
 - how does the user experience of our databricks destination compare to other connectors ([Stich](https://docs.databricks.com/partners/ingestion/stitch.html), [Fivetran](https://docs.google.com/document/d/1GUjTHp_54b3vMG21qTkF-h0wbczqn14RsIpWwLR3bx4/edit)) and what are the UX gaps?
 - how important each UX gap is and how hard it will be to close?

When filing issues that come out of this research, please link them to [this epic](https://github.com/airbytehq/airbyte/issues/21813)

**Comment by grishick** [comment]
timeboxing to 13 points

**Comment by suhomud** [comment]
## Opened issues
- Currently, this connector requires 30+MB of memory for each stream https://github.com/airbytehq/airbyte/issues/11424. **Notes**: I see it as a most have before the Beta
- Destination Databricks - currently uses int type when long needed (cast to 'null')  https://github.com/airbytehq/airbyte/issues/21943.
- Destination Databricks - Destination process message delivery failed https://github.com/airbytehq/airbyte/issues/21860
- Is Airbyte really only able to transfer less than 2MB/s? https://github.com/airbytehq/airbyte/issues/21318. **Notes**:  Would be solved with file based buffering? Could it be not related to the buffering? 
- Destination Databricks: Support Google Cloud/GCS for Delta staging tables  https://github.com/airbytehq/airbyte/issues/21292. **Notes**: Related to Question number 3. Currently we supports only S3 and Azure data sources.
- Destination Databricks: Datatypes missing in SQL CREATE-statement https://github.com/airbytehq/airbyte/issues/21193. Notes: there is an PR from community contributor https://github.com/airbytehq/airbyte/pull/21238
- Destination Databricks: Replicate data into new catalog instead of metastore  https://github.com/airbytehq/airbyte/issues/20953
- Unable to authenticate Azure blob with Databricks Lakehouse connector https://github.com/airbytehq/airbyte/issues/19011. **Notes**: From the comment section I see ` This is a documentation issue. It needs to be an account level SAS rather than a container level SAS.`. So most-likely we need to check and modify the documentation which describe permissions setup.
- Destination Databricks - Does not escape commas in JSON Fields https://github.com/airbytehq/airbyte/issues/18926. **Notes**: Could be related to https://github.com/airbytehq/airbyte/issues/21193
- Update destination-databricks to handle the new data types protocol https://github.com/airbytehq/airbyte/issues/18548
- Destination S3: Credentials not being accepted, but are valid and working on CLI  https://github.com/airbytehq/airbyte/issues/18277. **Notes**: Another ticket about credentials not being accepted so the docs should be revisit and possibly the check method required revisiting
-  Enable integration test for Databricks with Azure storage https://github.com/airbytehq/airbyte/issues/18026. Notes: checked this one and it's still relevant the Azure tests are marked with @Disabled
- Destination S3: Correctly generate int64 values https://github.com/airbytehq/airbyte/issues/17564. **Notes**: from the comment section this issue affects databricks also 
## Opened PRs
- Allow Incremental Deduped sync https://github.com/airbytehq/airbyte/pull/14445. The downside of this Pr is that it supports only csv staging and no Parquet. Also it’s conflicting with File-base buffer and if we want to support it the PR needs to be almost re-written. 
## Questions
1. Databricks connector use in-memory buffer. Should we migrate to File-based buffer?
2. Databricks service has Delta table modes: 
   - Managed storage (no source data is needed)
   - External storage (like S3, Azure)
   
   Currently we are supporting External storage only so should we implement Managed storage in a scope of moving to Beta? 
   
3. Current implementation supports S3 and Azure external storages. Should we extend it before moving to Beta? The full list of supported sources can be found [here](https://docs.databricks.com/external-data/index.html)

**Comment by grishick** [comment]
Still TBD: manually test the connector

**Comment by grishick** [comment]
> 1. Databricks connector use in-memory buffer. Should we migrate to File-based buffer?
Yes

> Currently we are supporting External storage only so should we implement Managed storage in a scope of moving to Beta?
Yes

> Current implementation supports S3 and Azure external storages. Should we extend it before moving to Beta? The full list of supported sources can be found [here](https://docs.databricks.com/external-data/index.html)

No. S3 and Azure are OK for Beta.
