### ISSUE TITLE
Missing version tags in GitHub

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#2201]
## Expected Behavior
For each version (major, minor, patch), there should be an associated tag in GitHub.

## Current Behavior
We are missing tags for all of the path version for 0.14.X. Possibly others, but those are the ones I noticed.

## Steps to Reproduce
1. Go to https://github.com/airbytehq/airbyte/tags

**Comment by jrhizor** [comment]
Added tags for:
0.14.4 a661883b9d6f72cca3ce5b680908de8daefd3b43
0.14.3 739f941b4fdfe57692bd0fc33b5c1c5bd4e74e42
0.14.2 6ea2d2db4c5035d44c6712b455b7a173b3187b0a
0.14.1 0b9718687596f6a79a395f46f370f1a0b9737f89

0.12.1 65cec6700c56929076ec7c952d72667af25aed08
0.12.0 eacae3f8e8097bc191357ef6113cb2c32f3b94ac

There are some cases I did not fix but that are "broken":
1. 0.12.2 exists on docker hub but has commit because we decided to switch to v13 https://github.com/airbytehq/airbyte/pull/1778
2. Some of the early tags are missing docker images but I don't think we want to bother to do anything about that now.

I didn't create releases for any of these because I didn't want to send out emails to watchers.
