### ISSUE TITLE
On the /connections page, Ctrl + click or cmd + click should open connections in a new tab

### ISSUE THREAD

**Issue by andyjih** [airbytehq/airbyte#22054]
This is not high priority, but a small quality of life request :slightly_smiling_face:

Is it possible to allow users to `ctrl+click` on the connections in the <https://cloud.airbyte.io/workspaces/bed3b473-1518-4461-a37f-730ea3d3a848/connections|connection page> to open them in a new tab? I find myself trying to do this often to compare settings between connections.

**Comment by josephkmh** [comment]
I'd like to add a related thought here, but maybe it's more appropriate as a separate ticket.

Currently we have some "nested interactions" that I find both error-prone and not very clear for the user:

![nested actions](https://user-images.githubusercontent.com/7550957/216335734-f966da42-866d-48a7-9cdc-e7555595158a.png)

I think this is a consequence of making the whole row clickable. I think we should move away from making rows of our tables clickable, since they generally include more than one interactive element. I would be in favor of something more like this:

![Screenshot 2023-02-02 at 2 07 54 PM](https://user-images.githubusercontent.com/7550957/216334282-e6f3b43e-a537-4924-bc7a-f48673765d0d.png)

This would be a usability improvement (IMO), but definitely an [accessibility win](https://dequeuniversity.com/rules/axe/4.3/nested-interactive) and it would also make the requested behavior in this issue much easier to implement!

**Comment by josephkmh** [comment]
Moving to the icebox for now because it's not a clear priority
