### ISSUE TITLE
Template for writing custom destinations

### ISSUE THREAD

**Issue by varunbpatil** [airbytehq/airbyte#2207]
In https://github.com/airbytehq/airbyte/pull/1405, I see the following comment.
> An outside contributor can't reasonably write a destination at this point.

Does this mean that writing custom destinations are not going to be supported? If not, it would be really helpful if the documentation can include a simple tutorial to write a custom destination including (most importantly) how to handle state messages(for incremental sync).

On a side note, the [incremental sync documentation](https://docs.airbyte.io/architecture/incremental#overview:~:text=A%20copy%20of%20each%20new%20or,same%20record%20in%20the%20destination%20warehouse.) mentions that the destination can only append data. Is there a reason why **upsert** (update or insert) cannot be done by Airbyte for destinations that support it?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368150177928) by [Unito](https://www.unito.io)

**Comment by ChristopheDuong** [comment]
For the moment, destinations are indeed incremental in append-only mode but we will be working on making them support other modes of incremental, etc.

Customs destinations are not forbidden, it's just as you say, we haven't made it easy or documented yet. On top of that, we have only Java destinations and no destination written in other languages yet because we are still figuring out a nicer abstraction around destinations and tweaking the protocol.

For example, in order to do upsert (updates, or insert) we would have to define primary keys, which is not the case today so it is supported yet.

**Comment by varunbpatil** [comment]
That makes sense, thank you.

**Comment by sherifnada** [comment]
@varunbpatil this is now available
