### ISSUE TITLE
Add normalization setting updated timestamp to UI

### ISSUE THREAD

**Issue by maximevaillancourt** [airbytehq/airbyte#22110]
## Tell us about the problem you're trying to solve
It's currently difficult to know when the normalization setting was last updated. A colleague accidentally turned off tabular data normalization, and a few hours later, upon realizing replication was broken and logging into the Airbyte UI, seeing a "Last updated 3 hours ago" would have been super useful to identify this as the culprit.

![image](https://user-images.githubusercontent.com/8457808/215611482-718bef14-ba14-44b1-9062-375c3c47a036.png)

## Describe the solution you’d like
A small `Last updated on <timestamp>` label close to the radio buttons selection (or next to the "Normalization" section header) would be super helpful.

## Describe the alternative you’ve considered or used
There is currently no built-in solution for this (other than keeping track of setting changes in an external system).

## Are you willing to submit a PR?
Yes, but being new to the Airbyte codebase, I'd appreciate pointers to identify files we'd touch to persist the `updated_at` timestamp and how to retrieve it alongside the normalization setting shown on the page.

**Comment by nataliekwong** [comment]
Now that we've migrated to using Typing & Deduping in destinations rather than using basic normalization through dbt, I will go ahead and close this issue.

In the future, any change to connection settings will be logged as a part of the new connection Timeline feature, so the general use case of getting recorded timestamps will be supported.
