### ISSUE TITLE
`SUB_BUILD=CONNECTORS_BASE` is very slow for CDK development

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#22128]
## Tell us about the problem you're trying to solve
![image](https://user-images.githubusercontent.com/6246757/215671310-ff842f25-cd2d-4e63-994e-0b19665ea723.png)

As a CDK developer, running the CDK unit tests locally typically takes no more than 30 seconds. Yet, I must wait [15 minutes](https://github.com/airbytehq/airbyte/actions/runs/4050031231/jobs/6967044347) for the build to run in CI. I get that there's formatting and other stuff that runs. But 15 minutes seems excessive.

## But why is the world so?
We can get a lot of insights by inspecting the build scan of a `SUB_BUILD=CONNECTORS_BASE ./gradlew build` command [such as this one](https://scans.gradle.com/s/xo22uzd3nudrs/performance/execution). 
<img width="713" alt="Screen Shot 2023-01-30 at 9 15 51 PM" src="https://user-images.githubusercontent.com/6246757/215671903-534047b2-c854-48f8-9800-118154ae4b98.png">

There's a few things that stand out: 
1. We're building a TON of unrelated things. Many build tasks which have nothing to do with the CDK i.e: they are not downstream of the CDK. A big example is a number of java connectors which run. You can see exactly how they impact the build [here](https://scans.gradle.com/s/xo22uzd3nudrs/timeline). Why are these running at all in a PR which changes? Should we introduce another `SUB_BUILD=PYTHON_CONNECTORS_BASE` or something to separate the build trees entirely? 
2. `:airbyte-integrations:bases:source-acceptance-test:_unitTestCoverage` takes 6-7 minutes to run. I don't know why, but 6-7 minutes for unit tests + computing coverage seems excessive. 

The actual CDK build takes 1m40s. Which is a positive sign that big gains lay in waiting!

My guess is that by solving the two concerns above we gain a significant speed-up. 

## Acceptance Criteria
1. At least a 50% improvement in CI build time (Connectors Base) for a CDK developer.

**Comment by evantahler** [comment]
From now-closed but related issue:

Say you are [publishing a python connector](https://github.com/airbytehq/airbyte/actions/runs/4051035949/jobs/6969001007).  The `/publish` task takes over 10 minutes, and most of that time is spent on sub-tasks that are not relevant to the connector.  There are some strange dependencies in our grade tasks. 

For example, running the SAT test for a connector (e.g. `./gradlew :airbyte-integrations:connectors:source-faker:integrationTest`) tests normalization (`:airbyte-integrations:bases:base-normalization:checkPython`), and builds and tests all of SAT locally, including SAT's own test suite (`:airbyte-integrations:bases:source-acceptance-test:_unitTestCoverage`).  

This issue is to think about our gradel DAG and look for improvements:
* Why is normalization involved at all?  I'll bet we build the normalization imagage in-case the connector is a destination needs normalization.  Can we be smarter and only build normalization for destinations?
* If there are no changes to the local SAT directory, can we use the `#latest` docker tag, or at the very least, skip SATs own internal tests?
* Should the publish command's `manage.sh` script use `gradle --scan` so we can better track/time these things?
