### ISSUE TITLE
Allow free connector syncs even if the workspace is delinquint

### ISSUE THREAD

**Issue by mfsiega-airbyte** [airbytehq/airbyte#22159]

**Comment by mfsiega-airbyte** [comment]
Notes:
- Customers have tried to enroll in the free connector program and run free syncs; but we don't allow syncs if the workspace is delinquent.
- We're proposing that these workspaces should be allowed to run free syncs.
- Q: are customers allowed to create/configure connections today in delinquent workspaces?
- Need to update the cron to leave free connections alone (when appropriate)

Next steps: nail down and document the specifics are the precise behaviour we want @pmossman

**Comment by josephkmh** [comment]
I clicked through my [delinquent workspace](https://cloud.airbyte.io/workspaces/f7ebd351-dacd-4b23-8a5f-53516c99b2d9/credits) and noticed two places where we will want to make frontend changes:

1. The UI prevents users from enabling a connection when their workspace has <=0 credits. This is hard-coded here and will need to be changed: https://github.com/airbytehq/airbyte/blob/master/airbyte-webapp/src/packages/cloud/cloudRoutes.tsx#L54

![image](https://user-images.githubusercontent.com/7550957/215863313-106c7bf1-cb88-485f-bf1a-947879713832.png)
![image](https://user-images.githubusercontent.com/7550957/215863333-4ad606db-377e-4c95-bdac-374507a61a6b.png)


2. We check `cloudWorkspace.remainingCredits <= 0` when showing the warning below. This is misleading, so we should consider rewording this banner. Maybe `Some of your syncs have been stopped because your credit balance is 0. Add more credits to enable all your syncs again.` Then again, maybe this workspace _only_ has free AB connectors. Should we even show anything in that case?

![image](https://user-images.githubusercontent.com/7550957/215863280-4274022f-fadf-4e0c-b6ff-27f9fd2d25d1.png)

**Comment by pmossman** [comment]
I wonder if it would be worth tweaking the wording to say "All of your *paid* syncs have been stopped" if they're enrolled in the program?

Also  @josephkmh the backend changes are all merged and deployed to prod now, so the front-end changes here should be unblocked!
