### ISSUE TITLE
Fix the build status icon in build summary

### ISSUE THREAD

**Issue by bnchrch** [airbytehq/airbyte#22163]
## Problem
The build status icon in the summary is broken

![image.png](https://images.zenhubusercontent.com/63d02817d1857451994bd656/7d4fc84c-4cdf-48da-b2b8-c6479f8b60eb)

https://airbyte-connector-build-status.s3.us-east-2.amazonaws.com/tests/summary/connectors/source-pokeapi/index.html

Where as its working in the builds.md file

https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/builds.md

![image.png]

(https://images.zenhubusercontent.com/63d02817d1857451994bd656/105229cd-12d7-4fe0-93e7-1ca8738d67e4)

**Comment by NikitaChernykh** [comment]
It looks like there should be a different URL for the badge. Instead of `https://img.shields.io/endpoint?url=https%3A%2F%2Fairbyte-connector-build-status.s3-website.us-east-2.amazonaws.com%2Ftests%2Fsummary%2Fconnectors/source-pokeapi%2Fbadge.json` it should be `https://img.shields.io/endpoint?url=https%3A%2F%2Fdnsgjos7lj2fu.cloudfront.net%2Ftests%2Fsummary%2Fsource-pokeapi%2Fbadge.json` When I tried the second URL in the open tab I see the badge. Hope this helps 🙌
