### ISSUE TITLE
[Octavia CLI] Add X-Airbyte-Analytic-Source header to all API requests

### ISSUE THREAD

**Issue by timroes** [airbytehq/airbyte#22215]
We're want to improve tracking of sources that called APIs. Octavia CLI should attach the following header to all the requests it's doing against the Airbyte server's APIs:

```
X-Airbyte-Analytic-Source: octavia-cli
```

**Comment by JonsSpaghetti** [comment]
Should be very quick and straightforward.

airbyte/octavia-cli/octavia_cli/api_http_headers.py:61 has the function we use for setting the generated APi client's default headers. We can just append a header to that of X-Airbyte-Analytic-Source at that point and it should propagate to all called endpoints. There might need to be updates to a test or two but otherwise should be good to go.

**Comment by rileybrook** [comment]
@JonsSpaghetti @terencecho @bgroff There is a business incentive for this work to be done. It will unblock us on the path towards getting insights into usage across our various OSS Airbyte interfaces (UI, API, CLI). Related [slack discussion here](https://airbytehq-team.slack.com/archives/C02UJ11D3S6/p1677746983363219?thread_ts=1677715868.897349&cid=C02UJ11D3S6).
