### ISSUE TITLE
Source Zendesk Support: `ticket_audit` is very slow / performance

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#22611]
This Github issue is synchronized with Zendesk:

**Ticket ID:** [#5752](https://airbyte7538.zendesk.com/agent/tickets/5752)
**Priority:** high
**Group:** Community Assistance Engineer
**Assignee:** Marcos Marx

**Original ticket description:**

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">Hello. Our Zendesk Support jobs take around 1 hour to complete even though I configured the streams as incremental and the size of our data is relatively small (around 3 million tickets). I wonder if anyone else has the same problem.
<br> [via Slack] Open original slack thread in #public-airbyte-help channel: <a href="https://airbytehq-team.slack.com/archives/C021JANJ6TY/p1675697516204149" target="_blank" rel="nofollow noreferrer">https://airbytehq-team.slack.com/archives/C021JANJ6TY/p1675697516204149</a></p></div></blockquote>

**Comment by marcosmarxm** [comment]
Some users are reporting problems with `ticket_audit` performance.

From Murat:
```
2023-02-07 16:41:56 [44msource[0m > SourceZendeskSupport runtimes:
Syncing stream groups 0:00:00.926138
Syncing stream organizations 0:00:01.216432
Syncing stream ticket_audits 1:09:22.084443
Syncing stream ticket_comments 0:00:20.628914
Syncing stream ticket_fields 0:00:00.495242
Syncing stream tickets 0:00:11.601779
Syncing stream users 0:00:08.868781
````

From Carolina.
https://files.slack.com/files-pri/T01AB4DDR2N-F04NQ3HBT98/screenshot_2023-02-08_at_1.44.57_pm.png

**Comment by marcosmarxm** [comment]
I didn't see any note in the connector docs or code about performance consideration.

**Comment by murat-cetinkaya** [comment]
Any news on this issue @marcosmarxm ?

**Comment by noah-abramson** [comment]
We are experiencing the same issue - very slow replication.

**Comment by marcosmarxm** [comment]
Hello @noah-abramson and @murat-cetinkaya I escalated the issue to our oncall team. I'll ask them if it is possible to have any ETA for this issue.

**Comment by sh4sh** [comment]
This stream will have slower incremental syncs because the endpoint it pulls data from doesn't have a `start_date` parameter. Airbyte receives all available data and filters out old records on the client side. There's a note about it in the docs: https://docs.airbyte.com/integrations/sources/zendesk-support#supported-streams

The [api docs](https://developer.zendesk.com/api-reference/ticketing/tickets/ticket_audits/#list-all-ticket-audits) say that`ticket_audit` data can be pulled incrementally using the [Incremental Exports API](https://developer.zendesk.com/api-reference/ticketing/ticket-management/incremental_exports/#incremental-ticket-event-export). Maybe it's possible to migrate the stream to this endpoint? I asked about it in https://github.com/airbytehq/airbyte/issues/16858#issuecomment-1620612678

**Comment by artem1205** [comment]
As it was mentioned by @sh4sh , `ticket_audit` stream supports Client side incremental only.
I could not find any mentions about incremental support for audits.

P.S. `api/v2/incremental/ticket_audits?start_time=123` returns `"error": "InvalidEndpoint"`
