### ISSUE TITLE
Add LaunchDarkly flag for minimum credit purchase

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#22688]
The Growth team would like to understand the impact of the conversion rate of Stripe checkout when the minimum purchase amount is lowered. Currently, the minimum number of credits is set to 100. We'd like to see how moving this to as low as 1 credit would change the conversion rate to purchase.

Today, the minimum/maximum values are configured via code when we create the Stripe checkout session. We can use LaunchDarkly to link the minimum & maximum values to a LaunchDarkly flag.

cc @andyjih

**Comment by nataliekwong** [comment]
Is platform-compose the correct team for this @andyjih ?

**Comment by mfsiega-airbyte** [comment]
Refining notes:
- Scope here is to support a flaggable control for minimum credit purchase (eg for experimenting)
- We'd like to be able to serve a specific value rather than a boolean included/excluded; this will probably involve a small change in the backend feature-flag implementation
- Question for @nataliekwong  - are we also maybe interested in experimenting with the default? 
- Note: this is an entirely backend change. Difficult component will be testing here.
- We'd like to get to this soon, but not pressing urgency.

**Comment by nataliekwong** [comment]
@mfsiega-airbyte Yep, I do have interest in experimenting with the default as well (would be handy in the future as we can then try setting a default based on indications like their usage or company size). If it makes sense to include that in this work, I'd appreciate it!

**Comment by nataliekwong** [comment]
Hey @mfsiega-airbyte ! Haven't seen any movement on this one, do you know if it will be scheduled for a future sprint?

**Comment by malikdiarra** [comment]
Hi @nataliekwong, It has not been scheduled yet. Now. that we are in a better spot about reliability and the release process, we might be able to pick that one up. I'll discuss it with the team tomorrow.

**Comment by mfsiega-airbyte** [comment]
Plan to discuss on Thursday, March 23.

**Comment by mfsiega-airbyte** [comment]
Refining notes: considering as a good ramp-up project for @flutra-osmani.
