### ISSUE TITLE
Prevent creating connection without any selected stream

### ISSUE THREAD

**Issue by timroes** [airbytehq/airbyte#22944]
We currently allow creating a connection even if no stream is selected. I think we should treat this as an error, because I don't see any reason why we'd ever want a connection to be created with all streams disabled, since it won't sync any data and just cause some overhead.

**Comment by edmundito** [comment]
cc @andyjih 

Putting on the customer's shoes, they may want to set up a connection first and then enable it once they are ready. Another way to frame it is that sync jobs should even run when the connection has no streams selected.

**Comment by timroes** [comment]
I agree that they might want to setup the connection without having it run (which they can via setting it to manual). I'm not fully seeing the use-case why a user would want to create a connection without selecting a single stream, but have it run.

> Another way to frame it is that sync jobs should even run when the connection has no streams selected.

Could you clarify what's the use-case for this, and what the user would hope to get from this? They'll wait 5 minutes for a sync job, but we know that nothing will happen during that?

I think if we want to allow the creation of sync jobs without a stream (and I still am more on the side of, that users might be negatively surprised after the creation of the connection that nothing happened, because they just missed enabling streams), we should make sure that at least the sync jobs are not able to run?

**Comment by nataliekwong** [comment]
I haven't come across a use case for saving a connection with no streams enabled.

In case it helps, here's a recent user who was setting up Salesforce and accidentally synced with 0 streams: https://fsty.io/v/cwy76ptb They returned back to the connection settings in order to select tables after their sync succeeded in sending 0 rows.

**Comment by andyjih** [comment]
My preferred approach here would be to make it clearer that 0 streams have been enabled on a Connection and preventing syncs from running when 0 streams have been enabled. Especially since the product will be moving to a more stream-centric world, I think adding this validation at the moment isn't necessary. 

My sense is that this isn't affecting many users, but let me know if I'm mistaken!

**Comment by nataliekwong** [comment]
Hey @andyjih, today, since the default is set to all streams selected, it is true we don't encounter this often since we've done the pre-selection for them.  We're moving forward with this experiment (https://github.com/airbytehq/airbyte/issues/22851) to see how users are affected by either selecting 1 stream by default or no streams. One of the learnings we want to understand is the effect of changing the default behavior to deselect all. In setting that default, it means that we'll have more users who will be affected by this.

**Comment by nataliekwong** [comment]
Was curious on the [metrics](https://airbyte.metabaseapp.com/question/1928-onboarding-first-connection-stream-count-selection) so I pulled the data for how many users hit this today while setting up their first connection:
- 4% select no streams
- 10% select only 1 stream
- 18% select some streams (somewhere between 2 and all streams)
- 68% select all (the default)
Hope that helps frame the question around how many users are affected.

**Comment by andyjih** [comment]
Oh got it, I missed the context of that current experiment. In that case, I think adding validation makes sense especially if we're going to be defaulting to no streams selected.

**Comment by edmundito** [comment]
Based on this discussion, Should the solution be that validation prevents creating/saving the connection if all the streams have been deselected?

**Comment by nataliekwong** [comment]
Yes, that seems to be the simplest solution.

**Comment by andyjih** [comment]
@edmundito @timroes Are y'all thinking of this validation as being purely frontend?
