### ISSUE TITLE
MaskedDataInterceptor is set at build time, should be updated at runtime - Research 

### ISSUE THREAD

**Issue by bnchrch** [airbytehq/airbyte#23254]
## Problem
The [MaskedDataInterceptor](https://github.com/airbytehq/airbyte-platform/blob/main/airbyte-commons/src/main/java/io/airbyte/commons/logging/MaskedDataInterceptor.java) (responsible for masking secrets) is built off a static list of secret field names in `specs_secrets_mask.yml`.

This file `specs_secrets_mask.yml` is generated at build time from the downloaded catalog. (Recently it was generated at build time from the downloaded spec files).

This is a problem if you consider the cloud_catalog is updated at runtime.

This means that any new specs in the cloud catalog will not be referenced by the specs_secrets_mask file. Which means those files wont be marked as secret.  (this is to be done in a later story)

### Context to be aware of
1. `MaskedDataInterceptor` has to be static as its a log4j plugin. I dont know if we can update secret data in the class on the fly?
2. `MaskedDataInterceptor` lives higher in the import order than our DefinitionsProvider Tasks.

### Possible solution
Run a job after each cloud catalog download that regenerates the mask

**Comment by evantahler** [comment]
Grooming:
1. Split the story
  * One story to remove the dependency on the YAML
  * When new workers/orchestrators boot up, if they can use the new secret definitions, is this a problem?
2. Connectors themselves should handle secret masking this is a SAFTEY NET, not the first line of defense.  we also shouldn't be logging configs anywhere. 

This is a new-ish problem because we decoupled platform deploys from connector deploys.

**Comment by evantahler** [comment]
re-tagging this into the metadata epic
