### ISSUE TITLE
Source Zoom: JWT auth methods will be deprecated soon

### ISSUE THREAD

**Issue by nauxliu** [airbytehq/airbyte#23268]
## Tell us about the problem you're trying to solve

According to the document, the Zoom JWT auth methods will be deprecated on June 1, 2023.  The Zoom source connector only supports JWT and will stop working at that time. 

https://marketplace.zoom.us/docs/guides/build/jwt-app/jwt-faq/

> The JWT app type will be deprecated June 1, 2023. We recommend that you create [Server-to-Server OAuth](https://marketplace.zoom.us/docs/guides/build/server-to-server-oauth-app) or an [OAuth](https://marketplace.zoom.us/docs/guides/build/oauth-app) apps to replace the functionality of a JWT app in your account. See below for frequently asked questions about this change.

## Describe the solution you’d like
Update the Auth method

**Comment by marcosmarxm** [comment]
Thanks @nauxliu I added the issue to connector team backlog!

**Comment by igrankova** [comment]
@YowanR, we have an account on the LastPass: zoom.us, I can't access the account because Okta login is needed (see my screenshot)
![image](https://user-images.githubusercontent.com/87977540/226875574-94081651-f18b-43c1-ad5c-04b876fe3734.png)
@ycherniaiev worked on the OAuth App: https://marketplace.zoom.us/develop/apps/5jc1kW8pSY2RdZAH3hZeKg/publish
It is in Draft status now, can't access account to find out details.
Due to the JWT auth method deprecation, we tried to investigate how to complete OAuth method, but are blocked.
If there's a need to proceed with Zoom, please help to unblock login.
cc @grubberr 
Obtain public developer application for the Zoom source connector #6191
