### ISSUE TITLE
Non-breaking schema changes detected as false positive

### ISSUE THREAD

**Issue by gosusnp** [airbytehq/airbyte#23349]
## What

The notification for non-breaking schema changes stays up, however, when going through the schema change review process, no changes are detected.

Related issues: https://github.com/airbytehq/oncall/issues/1515

**Comment by benmoriceau** [comment]
@edmundito Let me know when you get a chance to look at why the 2 discovery schema are triggered by the UI.

**Comment by gmyrianthous** [comment]
Same here - Any workarounds for this? The issue persists even after upgrading Airbyte

**Comment by defujihara** [comment]
> Same here - Any workarounds for this? The issue persists even after upgrading Airbyte

**Comment by flutra-osmani** [comment]
I digged into related oncall discussions and tickets. They seem to be related to the same catalog producing two different hash values. That issue has been addressed some time ago so I am assuming this is no longer an issue. @nataliekwong do we have any existing cases where this issue occurs?

**Comment by nataliekwong** [comment]
@flutra-osmani 
I just observed this in our internal workspace for this connection: https://cloud.airbyte.com/workspaces/bed3b473-1518-4461-a37f-730ea3d3a848/connections/fd0a463a-ad13-44b3-987f-78169e2cbc34/replication

1) I see the "non-breaking schema changes detected" banner
2) I click "Review changes"
3) Page refreshes - no modal appears. I get a toast message that says "no changes were detected in the source schema".

**Comment by nataliekwong** [comment]
Here's another connection: https://cloud.airbyte.com/workspaces/d61c4719-d1a7-4e33-a3df-49d8d16951c3/connections/d49cd5c1-325e-455c-9c51-c12f79c85b21/replication

cc @tealjulia

**Comment by nataliekwong** [comment]
Here's another one I found, where there is no version difference: https://cloud.airbyte.com/workspaces/56812376-bba8-4eb6-a6a1-df64ea889a5d/connections/9dac07ce-1e05-40ab-91b9-ecc5aacd5890/replication

I see the banner, but when the schema is refreshed, no schema changes are detected. Additionally, my connection has always been set to propagate all field changes. 

Could it be that it has detected schema changes for a stream I have not enabled?

**Comment by tealjulia** [comment]
@flutra-osmani I wonder if this is in part related to the protocol change I made?  That there is a schema change, but it isn't one that we'd track in the diff?  I haven't looked in the catalogs table to confirm this.

**Comment by flutra-osmani** [comment]
> @flutra-osmani I wonder if this is in part related to the protocol change I made? (not reporting the "false positives" for field changes in a stream, such as a primary key changing) That it something still being considered non-breaking schema change, but it isn't one that we'd track in the diff? I haven't looked in the catalogs table to confirm this.

Not related. I already have a fix but been unable to fix some of the acceptance tests so far. Work in progress.

**Comment by nataliekwong** [comment]
Issue raised in Cloud Support this week (Workspace URL: https://cloud.airbyte.com/workspaces/79dcb011-3622-4fe3-b5d1-2d974225cc66):

> I got a notification that there was a non-breaking schema change detected in my NetSuite connection. Upon checking the changes, I get a popup that says "No changes were detected in the source schema" (see screenshot). This is a false positive. How can I fix this?

<img width="1280" alt="Screenshot 2024-01-19 at 11 27 22 AM" src="https://github.com/airbytehq/airbyte/assets/38087517/d8ef119e-ed21-4c9f-b162-856255b9e78d">

**Comment by mfsiega-airbyte** [comment]
I believe https://github.com/airbytehq/airbyte-platform-internal/pull/10719 _should_ resolve this.

**Comment by nataliekwong** [comment]
Great! I'll check again once that is merged.

**Comment by nataliekwong** [comment]
@mfsiega-airbyte Just checked these three connections again that were called out previously in the comments:

https://cloud.airbyte.com/workspaces/79dcb011-3622-4fe3-b5d1-2d974225cc66/connections/398f2493-9b4e-40c3-a0a3-1d614e6b7a75/status
https://cloud.airbyte.com/workspaces/d61c4719-d1a7-4e33-a3df-49d8d16951c3/connections/d49cd5c1-325e-455c-9c51-c12f79c85b21/replication
https://cloud.airbyte.com/workspaces/56812376-bba8-4eb6-a6a1-df64ea889a5d/connections/9dac07ce-1e05-40ab-91b9-ecc5aacd5890/replication

They still show the "No schema change detected" banner after refreshing the schema. They all have the informational banner that says that non-breaking schema changes were detected.

**Comment by mfsiega-airbyte** [comment]
Sorry, should have clarified the "solution" a bit. It relies on the schema auto-refresh that runs during a sync. Basically if we run auto-refresh and detect that there's a newer schema but no diff, we will just bump the catalog id to say `we acknowledge the new catalog, there are no other pending changes`. In other words we ALWAYS auto-propagate an empty diff, to prevent the banner from showing up.

For https://cloud.airbyte.com/workspaces/d61c4719-d1a7-4e33-a3df-49d8d16951c3/connections/d49cd5c1-325e-455c-9c51-c12f79c85b21/job-history I see that a sync ran, but schema refresh didn't happen: https://cloud.temporal.io/namespaces/prod.ebc2e/workflows/sync_7948713/d588e717-ea28-442c-aa65-4538665601d3/history. I'm guessing this was because of the 24-hour limit - when you went in to check if it was fixed by refreshing the schema, you actually reset the limit so auto-refresh was skipped. Does that sound plausible? If so, we should just be able to wait until tomorrow when the sync runs again, and let auto-refresh resolve it.

In terms of fixing this problem so that it doesn't rely on auto-refresh, I see two options:
1. Add some logic to the frontend ([right here](https://github.com/airbytehq/airbyte-platform-internal/blob/66811a67642218cc948b7ba0dafd9f7c47bf493c/oss/airbyte-webapp/src/hooks/services/ConnectionEdit/ConnectionEditService.tsx#L63)) to do: `if we got an empty diff, but it's marked non-breaking changes, just automatically send a connection update with the latest source catalog id and don't display the banner`. We probably need a small backend change for this too. This _should_ be super simple (like, within a day) but I can't say for sure because all the React stuff on the frontend is too complicated for me to follow. @tealjulia any thoughts?
2. Alternatively, fix the fundamental way we decide whether a connection has non-breaking changes or not. This seems best because our current approach is super confusing -- thus bugs like this one -- but it's more work. Probably it would only make sense to do in the context of a broader cleanup of all the crazy stuff around schema refresh which we should definitely do but would probably take a demi-quarter.

**Comment by josephkmh** [comment]
@nataliekwong I was just chatting with Mike about this, and option 1. is something we could solve with a small amount of frontend work (~1 day). I wrote up an issue [here](https://github.com/airbytehq/airbyte-platform-internal/issues/11000), and we can discuss it on Monday in refinement if you want.

Just FYI! I'll leave the prioritization up to you.

**Comment by Ishankoradia** [comment]
@josephkmh @mfsiega-airbyte which way did we decide to go , 1) is it ? 

Also what does `that there's a new schema but no diff` mean ? What case would this be ?

**Comment by josephkmh** [comment]
@Ishankoradia we solved this with 1) described above. If there is a new schema but no diff, the frontend will automatically update the connection and you should see a toast success message:
![image](https://github.com/user-attachments/assets/9105e138-c698-4240-8087-7538d9a734c1)

> Also what does that there's a new schema but no diff mean ? What case would this be ?
It's possible that certain parts of the schema object change (e.g. adding or altering the `description` of a field) which Airbyte considers a "new schema" even though there is not any substantive change to the schema's data structure (e.g. a completely new field, a deleted field, or a field with a changed data type).

**Comment by josephkmh** [comment]
Yes the connection is updated, but only with the new source catalog id. The `diff` is only ever used to display to the user so they can decide whether to accept the new schema.

**Comment by Ishankoradia** [comment]
Gotcha !! 
Which api would do this ? Just an update to the connection, right (using this maybe `api/v1/web_backend/connections/update`) ?
