### ISSUE TITLE
Show valid cursor granularity and step values

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#23357]
## What
It should be possible for the users to know what are the valid cursor granularity and step values.

The cursor granularity represents the smallest cursor increment. This is usually one second.
The step represents how time size of the slice. Usually measured in days or months.

Both these fields follow the [ISO 8601 duration format](https://en.wikipedia.org/wiki/ISO_8601).

## Potential ideas
- Link to ISO 8601 documentation with examples
- Use two fields: one is a scalar (eg 1), the other is the time unit (eg day or month). The application can take care of converting to ISO 8601

**Comment by Upmitt** [comment]
loom video: https://www.loom.com/share/50642ca136f449bda17d9a1983859fc8
prototype: https://www.figma.com/proto/F1ljvrJerLoVbNvtejBWid/LOW-CODE-CONNECTOR-BUILDER?page-id=4145%3A141716&node-id=4174%3A135251&viewport=695%2C224%2C0.14&scaling=min-zoom&starting-point-node-id=4174%3A135251&show-proto-sidebar=1

**Comment by girarda** [comment]
Looks great @Upmitt !

I don't think there's a lot of value in allowing connector developers to use more specific steps like 2 weeks so a dropdown is a good solution.

**Comment by lmossman** [comment]
@Upmitt @girarda  one small note here: If we are rendering this as a dropdown, then we won't be able to render the `{{👤}}` button in the field, because that is only useful in text input fields. 

I think this should be fine, since it looks like no one is ever making these values user-controllable in existing low-code yamls (and I don't think it would be very useful to do that in general).

And since we are enumerating the values in the UI, this means we will also won't be able to convert imported YAMLs into the UI if they are using a value other than those listed in the dropdowns. 

Again, I think these aren't blocking issues - I just wanted to call them out and make sure that sounded okay to you

**Comment by lmossman** [comment]
FE issue: https://github.com/airbytehq/airbyte/issues/24119

**Comment by girarda** [comment]
Good callout @lmossman. IMO it's ok for the connector builder to be more opinionated and disallow these values.

> And since we are enumerating the values in the UI, this means we will also won't be able to convert imported YAMLs into the UI if they are using a value other than those listed in the dropdowns.

Again, probably fine, but it might cause problem at some point (maybe for another similar decision we'll make in the future). I wonder if there's a way we could use a dropdown to populate the textbox, but still allow freeform text?

**Comment by Upmitt** [comment]
If there is a way to still allow freeform text it would be perfect. I see this field as an input with suggested values more than like a dropdown. Can we think about it like an autocomplete, displayed when you click in the input and don't type anything?
