### ISSUE TITLE
Source OneSignal: Certify to Beta

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#23546]
## Tell us about the problem you're trying to solve
Certify to Beta OneSignal source connector.
LastPass: onesignal.com

**Comment by andnig** [comment]
Just for your info, the following issue might be relevant for beta certification. As at the moment, the connector basically does not work due to a OneSignal API auth change #23535 
Happy to help out if required, but there is a question in the issue which would need an answer before I can attempt a fix.
