### ISSUE TITLE
Source GitHub cannot pull data

### ISSUE THREAD

**Issue by yeedster** [airbytehq/airbyte#2361]
## Expected Behavior
Adding GitHub as a source with my user token should allow AirByte to pull in my repo information into my postgres instance as raw table data.

## Current Behavior
During the sync process the tables are generated but the data is unable to sync. 
Error from logs:

```
ERROR (/tmp/workspace/99/0) DefaultSyncWorker(run):104 - Sync worker failed.
io.airbyte.workers.WorkerException: Tap process wasn't successful
```

## Steps to Reproduce
1.  Link GitHub as Source
1.  Link postgres as Destination
1.  Sync GitHub Data

## Severity of the bug for you
High

## Airbyte Version
0.16.1-alpha

## Connector Version (if applicable)
0.1.9

## Additional context
MacOS Catalina, Docker 20.10.2

**Comment by sherifnada** [comment]
@yeedster could you post the full error log? you can download it from the sync overview page in the UI (there should be a button on the top right of the window where logs are displayed).

**Comment by yeedster** [comment]
Thanks @sherifnada uploaded the log file.
[logs-99-0.txt](https://github.com/airbytehq/airbyte/files/6104139/logs-99-0.txt)

**Comment by yeedster** [comment]
Added correction.  github connector is version 0.1.9

**Comment by sherifnada** [comment]
@yeedster the issue is that to sync the `teams` stream, the repository you are trying to sync must be in a Github Org of which you are a maintainer. Looks like you are trying to sync your fork of Airbyte, but because that's on your personal account not a github org, the teams concept doesn't exist and the sync fails. See the following error in the logs: 

```
2021-03-08 20:22:16 ERROR (/tmp/workspace/99/0) DefaultAirbyteStreamFactory(internalLog):108 - yeedster/airbyte {"message":"Not Found","documentation_url":"https://docs.github.com/rest/reference/teams#list-teams"}
```

This is definitely an unintuitive experience (we should tell you upfront based on the repo you selected whether you will be able to select the teams stream) but for now the workaround will be to deselect the `teams` table from your sync schema. See the bottom of the [Github Setup Guide](https://docs.airbyte.io/integrations/sources/github) for more details. I created an issue here: https://github.com/airbytehq/airbyte/issues/2364 to track a longer term fix.

**Comment by sherifnada** [comment]
Can you update us here about whether deselecting the teams stream helped fix the issue?

**Comment by michel-tricot** [comment]
@sherifnada it seems to be a recurring issue. Do we have a way to detect if the `team` stream is available during the discovery phase?

**Comment by sherifnada** [comment]
It's possible if we limit selections to a single git repository. Otherwise, you can select something like `airbytehq/airbyte` and `sherifnada/airbyte` and one would have it and the other would not. 

Alternatively we can always say the teams resources is available but if it's not an organization then we output no records (instead of failing the whole sync). 

I think the latter is more robust (the connector shouldn't fail because of this problem) given that we document in the docs.

**Comment by michel-tricot** [comment]
I like the latter. The only cons would be that it silently fails but for this particular use case it seems to make sense

**Comment by yeedster** [comment]
@sherifnada that seems to have fixed the issue!  Thanks for the help.  I'll close the issue for now since you have the long term tracking number for it.

**Comment by sherifnada** [comment]
created issue to implement: https://github.com/airbytehq/airbyte/issues/2365
