### ISSUE TITLE
Add CTA to Talk to Sales for sub-1 hour jobs

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#23737]
We see users in Fullstory trying to set up connections that have a frequency of less than 1 hour. In Cloud, we prevent these users from setting up these syncs because we are being careful of the load on the infrastructure.

On the Sales / Sales Engineering side, the team already enables sub-1 hour syncs for the right use case and fit with the existing feature flag.  We also should talk to these users instead of rejecting their attempt, so that we can better understand why they are looking for a sub-1 hour sync. It may be that down the line we decide to price this functionality differently from a standard self-serve customer (like Fivetran, Hightouch or Rivery)  as a part of our Enterprise or a separate add-on offering.  Encouraging a conversation with sales enables the team to have the knowledge of why a customer values this feature and helps us decide down the line if it should be a part of our pricing model or a feature we allow all users to utilize.

**Acceptance criteria:**

Instead of showing an error message that says "syncs under 1 hour are not allowed", we should show:
> Interested in syncing more frequently than once an hour? [Chat with us](https://airbyte.com/talk-to-sales) to unlock this feature.

<img width="998" alt="image" src="https://user-images.githubusercontent.com/7550957/235525055-48064621-ae03-4fdf-b0a5-4afad93a75aa.png">

**Comment by nataliekwong** [comment]
@letiescanciano this is an interesting one too (ie. where should it live?)

- It directly impacts the GTM motion (generating sales meetings)
- Purely frontend
- Small in effort (potentially even done through i8n string adjustment that Tim set up)
- Note it's not an experiment to put behind a feature flag, but we would maybe want to change the wording flexibly later on if sales gives us feedback on it

**Comment by nataliekwong** [comment]
Discussed with Tim and Leti; for minor text changes like these route will be to post in #dev-frontend for anyone to pick up.

**Comment by nataliekwong** [comment]
Refining since I created the issue: Support now handled these requests, so the CTA should say "Chat with us" and open the Intercom chat in the bottom right to initiate an inbound chat.

**Comment by josephkmh** [comment]
@dizel852 could you pick up this issue? I think I've added enough context in the issue description, but let us know if it's not clear!

**Comment by dizel852** [comment]
@josephkmh sure, will take it 👌

**Comment by dizel852** [comment]
I've just created a draft [PR](https://github.com/airbytehq/airbyte-platform-internal/pull/6335), before I make it available for review a few things need to be addressed:

**Question 1:**
@nataliekwong  do we need to change the message color for the case when a user tries to set a cron expression under one hour? In other cases, it remains red. IMO "technically" it's not an error it's just a restriction 😅 I've changed the text color to default `darkBlue`. 
Please, tell me if I need to revert back to the `red` color, here is what it looks like:

<img width="1111" alt="Screenshot at May 03 00-45-44" src="https://user-images.githubusercontent.com/20929344/235793232-2740df52-f236-447e-8e55-9a7415803e48.png">

Before:
<img width="1102" alt="Screenshot at May 03 00-46-40" src="https://user-images.githubusercontent.com/20929344/235793325-7bf52c57-7dc2-4f34-8907-0b2c35262312.png">

**Question 2:**
> CTA should say "Chat with us" and open the Intercom chat in the bottom right to initiate an inbound chat.

@josephkmh could you please give me a hint, do we have such a functionality(open intercom chat)? 
Since I have not found it. 

Also, I noticed that we already have `Talk to sales` button which opens the same link as in the description:
<img width="284" alt="image" src="https://user-images.githubusercontent.com/20929344/235794621-ce1d58c3-ac13-4a4e-a350-d70e9f46f3f9.png">

> Interested in syncing more frequently than once an hour? [Chat with us](https://airbyte.com/talk-to-sales) to unlock this feature.

Should I leave an external link? 🤔

**Comment by josephkmh** [comment]
@dizel852 I think if you check out the `useIntercom()` hook you can do that. We use it e.g. in the [CloudSupportDropdown.tsx file](https://github.com/airbytehq/airbyte-platform-internal/blob/master/oss/airbyte-webapp/src/packages/cloud/views/layout/CloudMainView/CloudSupportDropdown.tsx#L14) to trigger the chat to open here:

<img width="298" alt="image" src="https://user-images.githubusercontent.com/7550957/235801689-4903a07b-de54-43af-9264-a42cce5a7b27.png">

@nataliekwong just double-checking here: do we want to open the Intercom chat here? Is TCS able to act on there requests?

**Comment by josephkmh** [comment]
As for the color of the validation message - I think it should remain red. It's basically still an error that is preventing the user from submitting the form, so IMO it would be consistent to color it red.

**Comment by dizel852** [comment]
> We use it e.g. in the [CloudSupportDropdown.tsx file](https://github.com/airbytehq/airbyte-platform-internal/blob/master/oss/airbyte-webapp/src/packages/cloud/views/layout/CloudMainView/CloudSupportDropdown.tsx#L14) to trigger the chat to open here:

Awesome! Thanks for pointing this out! That's what I was looking for 👍 

> As for the color of the validation message - I think it should remain red. It's basically still an error that is preventing the user from submitting the form, so IMO it would be consistent to color it red.
> 

Gotcha! 👌 
> But could we maybe underline the `Chat with us` text and make it red too? It looks a little weird with red + blue text in the same sentence!
Sure, will update the PR 🙆‍♂️
