### ISSUE TITLE
Add Connection metadata (eg. "Connection Name") to webhook notifications

### ISSUE THREAD

**Issue by mangelons** [airbytehq/airbyte#23748]
Please, could it be included the name of the connection inside the message of the webhook? It would be good to know wich connection has failed rather than the source and the destination of it.

**Comment by imrehg** [comment]
Definitely agree, that the message should be clearer.

Schema changes notifications should also include that too (not just the source ID), as this is currently not very informative:

```json
{"text":"Your source schema has changed for connection ID: 8d7e1312-f5c0-4c50-8afd-a8df3ac9c9f0\n\nVisit your connection page here: http://localhost:8000/workspaces/206f1e5d-8efb-4420-97ec-62e399909945/connections/8d7e1312-f5c0-4c50-8afd-a8df3ac9c9f0\n\nRefresh your source schema in order to update this connection.\n"}
```

**Comment by nataliekwong** [comment]
Hey @mangelons  and @imrehg , thank you for your feedback! I've assigned this to the correct team for triage / development. 

As far as schema change notifications - we are actively exploring adding the schema change diff to the content of the notification. Thanks for your patience as we work on this enhancement!

**Comment by nataliekwong** [comment]
Refining notes:

- The additional metadata should be passed as individual attributes in a JSON payload so that it follows traditional webhook structure, like so:
{
  blocks: { ... slacks block configuration .. } 
  data: {
    connectionId: "...",
    modifiedStreams: [ ... ],
    ...
  }
}

- Listed out all relevant metadata for each notification type in this [doc](https://docs.google.com/document/d/1eNyEk5EqEZ5B-5uE4iIP-YHKm2t--JxRW0004Q7zfmk/edit#heading=h.fng0rduxx5wc)

- As an example, for a Failed Sync, we would include the following:

Workspace ID
Workspace Name
Connection Name
Connection ID
Source Name
Source ID
Destination Name
Destination ID
Job ID
Duration
Started At
Finished At
Job Error
Bytes Emitted
Rows Emitted
Bytes Committed
Rows Committed

**Comment by webserviceXXL** [comment]
@nataliekwong This would be awesome. Always was wondering why some of the information I see in the "Job history" are part of the webhook but others not. And a object like in your post is also much more attractive then the current big string in "text".

**Comment by timroes** [comment]
@malikdiarra Is the connection name available in the webhook text now since your latest improvements on webhook notifications?

**Comment by malikdiarra** [comment]
Once https://github.com/airbytehq/airbyte-platform-internal/pull/11566 and its follow up are merged, we can close that
