### ISSUE TITLE
The next step after setting up the base url and the authentication is not obvious to the user

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#23998]
## What
When a user is done setting up the global configs (base url and authentication), the next step is not obvious.

We should make it clear that the users should create a new stream

## Ideas
- Lean on the onboarding flow
- [Explanation in the stream panel]([https://www.figma.com/file/F1ljvrJerLoVbNvtejBWid/LOW-CODE-CONNECTOR-BUILDER?node-id=4145%3A184554&t=6ORd5p6ynpr68vib-4](https://www.google.com/url?q=https://www.figma.com/file/F1ljvrJerLoVbNvtejBWid/LOW-CODE-CONNECTOR-BUILDER?node-id%3D4145%253A184554%26t%3D6ORd5p6ynpr68vib-4&sa=D&source=docs&ust=1678734398359924&usg=AOvVaw0aShwAIBcD7Cc_1FnjFCW6))
- Highlight the + sign to create a new stream

**Comment by Upmitt** [comment]
We already have a onboarding flow for that, but don't know if we plan to integrate it soon or not. For the moment, without onboarding flow, I suggest this little animation + update of the stream panel:

loom video: https://www.loom.com/share/f5ac3e718af241db91b2414d850ca1b3
prototype: https://www.figma.com/proto/F1ljvrJerLoVbNvtejBWid/LOW-CODE-CONNECTOR-BUILDER?page-id=4145%3A141716&node-id=4145%3A184554&viewport=695%2C224%2C0.14&scaling=min-zoom&starting-point-node-id=4145%3A184554&show-proto-sidebar=1

**Comment by girarda** [comment]
I like it!

@lmossman can you confirm this is something we can implement? I'd also like to get your pulse on the effort since this is meant as a way to unblock users since we don't have the onboarding flow

**Comment by lmossman** [comment]
Yeah this should be doable. To confirm: we would like animate the button like this once the user has filled out the API URL field, right? Since they may not need to set up authentication, so we shouldn't wait for that to show it? Is it possibly distracting to animate the button like this while they still need to set up authentication?

@flash1293 any thoughts here?

**Comment by flash1293** [comment]
Good question. I think in practice most APIs will require authentication, maybe we can just assume that and only prompt the user once they have auth set up (especially since this is an interim solution)? I agree that we shouldn't have an animation while we expect the user to interact with another part of the UI.
