### ISSUE TITLE
See what e2e tests break when stream first ux is enabled

### ISSUE THREAD

**Issue by krishnaglick** [airbytehq/airbyte#24072]

**Comment by dizel852** [comment]
Checked all e2e tests with `"connection.streamCentricUI.v1": true` feature enabled on master - all tests have passed.

Also, since Centric UI partially uses the new stream table(open details), I took the latest master and merged it locally with https://github.com/airbytehq/airbyte-platform-internal/pull/5328  - there the new table is enabled and some tests were updated.

Result - all tests have passed 🟢 
Closing this issue since no more actions are required.
