### ISSUE TITLE
Source: AWS CloudTrail

### ISSUE THREAD

**Issue by arhip11** [airbytehq/airbyte#2418]
## Tell us about the new integration you’d like to have
* Which source and which destination?
* Do you need a specific version of the underlying data source e.g: you specifically need support for an older version of the API or DB? 

## Describe the context around this new integration
* Which team in your company wants this integration, what for? This helps us understand the use case.
* How often do you want to run syncs?
* If this is an API source connector, which entities/endpoints do you need supported?

## Describe the alternative you are considering or using
What are you considering doing if you don’t have this integration through Airbyte?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368153461930) by [Unito](https://www.unito.io)

**Comment by sherifnada** [comment]
Quick braindump: 
* Docs starting point: https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-user-guide.html
* CT records actions taken in an AWS account. There are 3 types of actions
    * **data**: S3 object-level activity (put/get/delete), S3 Lambda executions, blockchain service executions
    * **management**: control-plane level operations on resources. Logins, role attachments, resource creation, etc.
    * **insights**: unusual activity in an AWS account e.g: an account that logs no more than 5 bucket creates per month suddenly creates 500 in an hour
* Cloudtrail by default retains events for up to 90 days, and they can be browsed from the UI/API/CLI
* A "trail" is a configuration that allows delivering CT events to S3 buckets and Cloudwatch where it can be retained for as long as needed. It also allows filtering for specific types of actions. 
* For airbyte to support CT trails are not strictly needed but are likely a useful filtering mechanism since they can also be used for region/event type filtering
* Without trails, getting events is very simple: we just hit the [LookupEvents](https://docs.aws.amazon.com/awscloudtrail/latest/APIReference/API_LookupEvents.html) endpoint
* With trails, the access pattern is more complicated because logs are stored in an S3 bucket. We have two choices: read the S3 bucket and stream events into the destination (inefficient but perfectly compatible with the current airbyte protocol). To be efficient we need to implement some sort of "batch update" mechanism that triggers commands like `COPY INTO` e.g: on snowflake, which just point to the S3 bucket directly.

**Comment by sherifnada** [comment]
For an MVP I think it makes the most sense to read from the event history API and not use any trails. In the future we can support trails.

**Comment by sherifnada** [comment]
## Integration Vetting

**Webhook-based? (no/partially/yes)**
No

**Available authentication modes (API key/Oauth/other)**
API key

**Creating an account**
Airbyte has an AWS account (will need to provide @arhip11 with access)

**How to populate the account with data?**
Already populated with data

**Available streams for sync**
Like mentioned above, since we are focusing on non-trail data i.e: data from the EventHistory, we just need to support the LookupEvents endpoint.
 
**Integration supports incremental sync?**
Yes

**Comment by arhip11** [comment]
Hey @sherifnada.
Can you share the credentials to AWS?
Besides having credentials, is anything else required?

**Comment by sherifnada** [comment]
@arhip11 I created credentials for the AWS account and you should have access. Please let me know if there is anything else needed from me to be able to hit the API (i believe you should be able to generate credentials yourself)
