### ISSUE TITLE
[Roadmap] [Epic] Automatic Management of Connector Breaking Change Releases

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#24445]
When connectors have a new version released which is a breaking change, Airbyte Cloud users will be presented with a deprecation window by which they will need to upgrade.  This will be accompanied by various notifications.  This replaces today's manual process and surprise release of breaking changes.

**Comment by erohmensing** [comment]
Weekly project update for Automatic Management of Connector Breaking Change Releases
:white_check_mark: What's been accomplished:
The PRD is ratified! 

🛫 What's next
This week's focus is on finalizing the tech spec.
Share the tech spec with non-team stakeholders and get their :ballot_box_with_check:. Hoping that on the tech side, the earliest steps won't require much external approval (e.g. get metadata from connector devs to platform db) and we can get off the ground quickly.

**Comment by erohmensing** [comment]
Connector Breaking Changes update: Time to hit the ground running :sonic:

:white_check_mark: What's been accomplished:
Tech spec was split into phases in order to help us get the earlier pieces that we're more sure of out the door so we can work on them.
Tech spec for phase 0 is ready and awaiting review!
Issues have been created for the metadata portion. 2 issues (update connector model, update metadata jsonschema) need to be done before 2 others (validate metadata, validate relevant docs)

:rocket: In Progress:
Continuing to flesh out the phases doc to make sure it reflects all of the tasks we want to accomplish correctly.

:warning: What got in the way:
Edge cases, galore - so many to consider while designing
The brain dump was helpful, but trying to design the specifics of everything at once was too slow before focusing on splitting into phases
We realized there is an issue with how we consume version-specific versus global metadata - we spent a lot of time digging into it and will need to solve it at some point.

:construction: Blockers:
We will wait for reviews from external peeps (platform compose mostly) before going forward with the platform side of things

:crystal_ball: What's next:
Solidify phases doc
Work on tech spec for phase 1
Start picking up metadata issues
Get phase 0 tech spec ratified :i_voted:
