### ISSUE TITLE
Source Pinterest: error pulling revenue?

### ISSUE THREAD

**Issue by lluisgassovillarejo** [airbytehq/airbyte#24452]
## Environment
- **Airbyte version**: 0.40.10
- **OS Version / Instance**: Debian 11
- **Deployment**: Open Source On GCP as per the documentation. The machine has 2 CPUs and 16 Gb
- **Source Connector and version**: 0.1.7
- **Destination Connector and version**: BigQuery (denormalized typed struct) 1.2.4
- **Step where the error happened**: Initial Sync job

## Current Behavior
We extract spend from ad_group_analytics using SPEND_IN_MICRO_DOLLAR. However, we don't get the correct amount when pulling revenue with TOTAL_CHECKOUT_VALUE_IN_MICRO_DOLLAR (lower than it should). Would you know if this is due to a calculation or Airbyte's data extraction error?

## Expected Behavior
Get the correct revenue amount using TOTAL_CHECKOUT_VALUE_IN_MICRO_DOLLAR.

**Comment by lluisgassovillarejo** [comment]
Any update here?

**Comment by lazebnyi** [comment]
The `SPEND_IN_MICRO_DOLLAR` metric corresponds to the amount spent by the Advertiser, measured in micro currency units (one millionth of a currency unit). On the other hand, `TOTAL_CHECKOUT_VALUE_IN_MICRO_DOLLAR` represents the total value of view-through conversions specifically related to the "checkout" type.

The discrepancy between the spend extracted from ad_group_analytics using `SPEND_IN_MICRO_DOLLAR` and the revenue obtained from `TOTAL_CHECKOUT_VALUE_IN_MICRO_DOLLAR` being lower than expected is likely due to a calculation. 

More details - https://developers.pinterest.com/docs/redoc/adsreporting/#section/Metrics
