### ISSUE TITLE
Source Shopify: Support additional visits data using Shopifyql

### ISSUE THREAD

**Issue by YowanR** [airbytehq/airbyte#24538]
## Tell us about the problem you're trying to solve
Shopify provides details on session information and unique visits.  This allows someone to look into conversion percentage, how many unique visits in a day result in a sale , etc. Having this information is important to understand the customer traffic of a storefront.

## Describe the solution you’d like
This information is available from :https://shopify.dev/docs/api/shopifyql

**Comment by misteryeo** [comment]
**Issue was linked to Harvestr Discovery:**  [Source Shopify: Support Visits Collection](https://app.harvestr.io/components/0/list/RPlkJ4EzG)

**Comment by bazarnov** [comment]
Some findings why we cannot have this info at this moment:
1)  https://community.shopify.com/c/shopify-apis-and-sdks/rest-api-querying-visited-products/td-p/442256 - It was available for Shopify Plus customers
2) The Analytics API, which provided the `Visits` (session/sales) data is deprecated and no longer available: https://community.shopify.com/c/shopify-apis-and-sdks/how-to-get-total-sales-and-visitors-of-store/td-p/561932

 We might probably need to purchase the  Shopify Plus plan in order to identify the possibility to fetch such data. Currently closed. It actually could be a great contribution, BTW.
