### ISSUE TITLE
Add Metrics to Record Validation Errors so that we will know the stream of the failing property

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#24710]
Main collection of info we want to have according to [schema validaton pain points](https://docs.google.com/document/d/1OB1g8tvz0uiELFiKg394zcVDNouO6kbEmUsPJ3IxzJA/edit#):
* Source
* Source version
* Stream
* Full dpath to attribute that doesn't meet the schema
* In case of type mismatch, expected and actual type 
* Do we want to check for extra fields in nested objects? -> not at the moment, this happens separately from general schema validation and was something that was added specifically for column selection restrictions

Possible bonus:
* In case of missing fields, add the type of the value that came through (helps with adding to the schema)

To implement, look in [WorkerMetricReporter](https://github.com/airbytehq/airbyte-platform-internal/blob/master/oss/airbyte-commons-worker/src/main/java/io/airbyte/workers/WorkerMetricReporter.java)!

**Comment by erohmensing** [comment]
This was blocked by #24853... After fully filling out the issue, I think there is a way I could add the actual type of the attribute to the log and then parse the log in order to add the attributes to the metrics. This could get it in speedier than the refactor, especially if the refactor needs input from any other teams. Will make this decision while grooming the other!
