### ISSUE TITLE
[Epic] Move normalization into destinations

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#24791]

**Comment by edgao** [comment]
for continuity: previous related updates can be found here https://github.com/airbytehq/airbyte/issues/24787#issuecomment-1540582015

**Comment by edgao** [comment]
:white_check_mark: *What’s been completed:*
* POC officially completed
* Joe updated the DATs to use in-connector normalization! https://github.com/airbytehq/airbyte/issues/24880

:books: *Learnings and hurdles:*
* Installing dbt-snowflake is nontrivial (compared to dbt-bigquery, which was completely plug-and-play)
* Joe and Edward spent most of the week working on an interrupt
* Bigquery rollout was blocked due to some unrelated prod instability

:no_entry_sign: *Blockers:*
* none

:seedling: *Looking ahead:*
* Joe investigating how to run existing normalization integration tests as part of each destination's integrationTests task
* Cynthia continuing with implementing in-connector normalization for destination-snowflake
* Edward to start production bigquery rollout
* Joe + Edward working on 1s1t tech spec

**Comment by edgao** [comment]
:white_check_mark: *What’s been completed:*
* bigquery rollout at 30%
* joe put together some thoughts on 1s1t / destinations v2
* edward has a pr mostly ready to go for redshift https://github.com/airbytehq/airbyte/pull/26165
* cynthia working on getting snowflake ready https://github.com/airbytehq/airbyte/pull/25782
* cynthia also working on refactoring platform + our feature flags to support more than just bigquery

:books: *Learnings and hurdles:*
* our launchdarkly project supports rules based on connector definition id! This will simplify the platform piece and remove the need to manage multiple feature flags.

:no_entry_sign: *Blockers:*
* none

:seedling: *Looking ahead:*
* Cynthia continuing with implementing in-connector normalization for destination-snowflake
* Cynthia continuing with platform/LD refactor
* Evan starting work on destination-clickhouse
* Edward doublechecking the difference between normalization images https://github.com/airbytehq/airbyte/pull/25782#discussion_r1191604090
* Edward finishing up redshift
* Edward starting concrete work on 1s1t tech spec

**Comment by edgao** [comment]
:white_check_mark: *What’s been completed:*
* bigquery rollout at 100%
* cynthia working on refactoring platform + our feature flags to support more than just bigquery
* evan working on normalization in mysql https://github.com/airbytehq/airbyte/pull/26376
* edward starting work on 1s1t spec https://docs.google.com/document/d/12iQv2G7rQMdNWPik973l8B5U3aGLnnlK4u4zi1Xcji0/edit

:books: *Learnings and hurdles:*
* Some destinations have some longstanding broken integration tests. It seems likely that we'll continue running into this as we move normalization into the other destinations.

:no_entry_sign: *Blockers:*
* destination-mysql integration tests are broken and need to be fixed
* Setting up a connection to our Snowflake dev account is failing due to an OOM in `check`, so we can't e2e test dest-snowflake

:seedling: *Looking ahead:*
* Cynthia looking into snowflake connection setup
  * if this works - we can deploy the platform changes + roll out destinations snowflake+redshift
* Evan continuing to work on dest-mysql tests
* Edward+Joe continuing on 1s1t tech spec

**Comment by evantahler** [comment]
Closing, as related work will be done as part of each 1s1t effort for the remaining destinations
