### ISSUE TITLE
[Epic] Isolate Snowflake dependencies from other destination connectors

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#24809]
## What
Destination Connectors have a tight dependency where the usage of commands/lambdas cause Factories and other `Consumer` components to be difficult to break apart while also creating larger blast radiuses. Specifically, if we need to update or change base classes in a more impactful or risky way, we want to be able to limit the number of destinations impacted. 

For instance, a change in `BufferedStreamConsumer` will result in nearly all `ConsumerFactory` methods needing to update their lambdas. The goal of this EPIC is to break apart the destination connectors in such a way that unblocks connector development from being a lock step. 

_Some destinations may reach a point of stability and only require updates yearly for library versions, maintenance, etc. while others might need more new feature work. Long term goal is more "API" thinking around connector development._

## How
Options to consider are:
- Create versioned libraries. That way, new library versions of base classes can be applied one at a time to connectors. 
    - Further evaluation will be taken in the upcoming quarter Q2b
- Copy pasting Factories with targeted classes to avoid issues with tight dependencies on other destination connectors ✅ 

## Definition of Done
Ability to work on Destination Snowflake without affecting Destination BigQuery/BigQuery Denormalized connector

**Comment by ryankfu** [comment]
*:white_check_mark: What's been completed:*
- One Java One Publish [Tech Spec [DRAFT]](https://docs.google.com/document/d/1m0T_q_uZDaFRZpKh0vrD0xt2bssuYulVQqlH_2RKT3A/edit#)
- Hoisted destination-jdbc into bases folder [PR merged](https://github.com/airbytehq/airbyte/pull/25120) 

*:books: Learnings and hurdles:*
- Gradle executes dependencies in lexicographical order, which causes difficulty in reasoning why builds fail, a [ticket](https://github.com/airbytehq/airbyte/issues/25251) to track for untangling

*:no_entry_sign: Blockers:*
- [destination-snowflake](https://dnsgjos7lj2fu.cloudfront.net/tests/summary/connectors/destination-snowflake/) integration tests are failing, currently working on fixing this to ensure the split for base-java and bases-destination-jdbc don't break snowflake and bigquery

*:seedling: Looking ahead:*
- Expect to be able to get a fix for the SnowflakeAzureBlobCopyDestinationAcceptanceTest, still work needed on testSyncWriteSameTableNameDifferentNamespace
- Have a draft PR with [split bases-destination-jdbc and base-java](https://github.com/airbytehq/airbyte/issues/25225) in the coming days
- Work for this EPIC will be tabled after the split to focus on Snowflake async writing/reading with Jeff

**Comment by ryankfu** [comment]
**One Java One Publish Project Update:  Let the new age of async writing begin**

:white_check_mark: What's been accomplished:
* Draft changes to split base-java and bases-destination-jdbc are completed and tested in this [PR](https://github.com/airbytehq/airbyte/pull/25347)

:books: Learnings and hurdles:
* Our `./gradlew format` pulls in dependencies from an external service mavenCentral if we fail to pull in the dependencies from our [airbyte.myclcoudrepo.io](http://airbyte.myclcoudrepo.io/) ([Slack thread with context](https://airbytehq-team.slack.com/archives/C05349NNNDU/p1682027019206009?thread_ts=1682026494.064529&cid=C05349NNNDU)) which can lead to flakey builds
* Currently, Snowflake and Redshift tests seem to be flakey (4-hour runs instead of the usual 45 min even after the fixes) which blocks [the refactor base changes](https://github.com/airbytehq/airbyte/pull/25346) from Jeff which is currently blocking the split since the renaming would be useful to happen once

:no_entry_sign: Blockers:
* Identify how come tests are failing on [destination-snowflake](https://dnsgjos7lj2fu.cloudfront.net/tests/summary/connectors/destination-snowflake/) and [destination-redshift](https://dnsgjos7lj2fu.cloudfront.net/tests/summary/connectors/destination-redshift/) (the latter needs to sync with Cynthia)

:seedling: Looking ahead:
* The next steps are all focused on unblocking Jeff's PR and rebasing his changes into the bases split
    * Mostly have been syncing with Jeff on async writing work since there was a strong belief that integration tests shouldn't be this flakey (yet they are :cry: )

**Comment by ryankfu** [comment]
One Java One Publish Project Update: Let the new age of async writing begin

✅ What's been accomplished:

* Bases split for `destination-snowflake` dependencies have been merged, unblocking Snowflake async writing work from affecting other destination connectors https://github.com/airbytehq/airbyte/pull/25649

📚 Learnings and hurdles:

* AzureBlobStorage was a unused loading method for Snowflake with not enough team know-how to fix so removal was the fastest approach to unblocking Q2a projects: https://github.com/airbytehq/airbyte/pull/25739
* Our dependencies can break due to not pinning package libraries (not really a huge issue but still annoying)

🚫 Blockers:
* N/A

🌱 Looking ahead:
* Definition of done has been completed, the next forward goal is to have the Java split revisited when our team evaluates if dependency versioning is the path for isolating connector changes
