### ISSUE TITLE
Skip running normalization container for whatever feature flag

### ISSUE THREAD

**Issue by edgao** [airbytehq/airbyte#24882]
use the same feature flag as https://github.com/airbytehq/airbyte/issues/24876 to control this rollout. Once that issue AND this issue are done, we can start turning on the flag for specific workspaces.

This needs to happen in SyncWorkflowImpl, `if (!flagEnabled) { normalizationActivity.normalize(...) }` - this also is a nice stepping stone to just deleting the `.normalize` call entirely, once we completely kill of the base-normalization image

or maybe we run a noop normalization container... inject env var into normalization container to trigger noop? (meh)

---

This should also do some sort of version check on destination-bigquery - if it's a version older than https://github.com/airbytehq/airbyte/issues/24878 then we need to still run the normalization container.

open question:
* when can we remove that check? can we just wait X months and assume that anyone running platform `now + X months` has also upgraded to the latest destination-bigquery?

**Comment by jbfbell** [comment]
Since adding feature flags is inexpensive and more granularity allows us to roll out individual destinations on their own timeline - we are opting to use individual feature flags rather than re-using the same one. For bigquery the key is `connectors.normalizationInDestination.bigquery` and is setup in [Launch Darkly](https://app.launchdarkly.com/default/production/features/connectors.normalizationInDestination.bigquery/targeting) and other Destinations will follow a similar pattern of appending the destination specific name.

**Comment by edgao** [comment]
closing this issue as completed + submitted https://github.com/airbytehq/airbyte/issues/25964 to track feature flag rollouts
