### ISSUE TITLE
Update ActorDefinitionVersionHelper to retrieve default version from the database

### ISSUE THREAD

**Issue by pedroslopez** [airbytehq/airbyte#25061]
## What

In #25059 we introduced actor_definition_version table into the database and added default version foreign keys to the actor_definition table.

We should update the ActorDefinitionVersionHelper to retrieve the default version from this new db table rather than pulling the fields from the StandardDestinationDefinition/StandardSourceDefinition.

To make sure this goes smoothly, we should put this behind a feature flag. The old behavior of getting these fields from the standard definitions should stick around until this is validated.

#### Notes

- While the db will be empty until #25060 is completed, this ticket can be worked on assuming that the database has the right data.
- If a default version is not found, we should raise an exception and fail. A default version not being present indicates an inconsistency problem, meaning something went wrong or a version was wrongly deleted.

**Comment by erohmensing** [comment]
Decision: we should hard fail if the `default_version_id` is null because of `onDeleteSetNull` in the constraint. (I.e. if the default version goes missing from the actor_definition_version table). That issue should be resolved when the cron comes around and seeds the table again. See comment https://github.com/airbytehq/airbyte-platform-internal/pull/5845#discussion_r1166218570
