### ISSUE TITLE
Update Connector Health Reports to use new Dagger test statuses

### ISSUE THREAD

**Issue by bnchrch** [airbytehq/airbyte#25435]
## Overview
We want to update our slack connector health reports  generated currently from [report.sh](https://github.com/airbytehq/airbyte/blob/master/tools/status/report.sh#L106) to use the new dagger test reports.

This may or may not involve updating the system to use the new orchestrator to monitor for test report changes

**Comment by alafanechere** [comment]
The wishlist on this issue is the following:
* It'd be great to have a daily report generated from the aggregation of connectors nightly test results (currently stored here for Dagger pipelines, but the path can change: `s3://airbyte-connector-build-status/python-poc/tests/history/source-twilio/master/2.0.28/3e49e509906298e60aa28e6bc50a4e5a8c97d858.json`)
* It'd be great that this report could be
  - uploaded as an HTML files to a public location
  - sent out as a slack message to #connectors-health 
  - Committed as a markdown file every day 🤔 ? (not sure this is useful, but it's cool for archiving and checking the history of build results)
  - written to a machine readable format we can upload to a GCS bucket for ingestion in our datalake
