### ISSUE TITLE
find workflow execution from temporal metadata

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#2564]
depends on https://github.com/airbytehq/airbyte/issues/2387

Use the temporal metadata to find the workflow execution for cancellation instead of writing to a file.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368220450589) by [Unito](https://www.unito.io)

**Comment by cgardens** [comment]
@jrhizor I think this is done? This code is querying temporal to figure out the workflow id instead of using the file. 
issue: https://github.com/airbytehq/airbyte/pull/5850 
code: https://github.com/airbytehq/airbyte/blob/master/airbyte-server/src/main/java/io/airbyte/server/handlers/SchedulerHandler.java#L380-L396
