### ISSUE TITLE
Feedback on the Docs list of Connectors

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#25678]
In https://github.com/airbytehq/airbyte/pull/25650, we replaced the list of connectors on https://docs.airbyte.com/integrations/ with the registry list generated by the metadata pipeline.  That was a first pass.

Now, we should make a view of this data specifically for the docs site. This issue is to collect feedback on what that page should have:
* Ideally, we don't use an iFrame, and we load the remote data at build time from the metadata manifest
* We don't need actor ids
* The links should be easier to find
* It should work better in dark mode
* ...

Add additional ideas below as comments on this issue

**Comment by bnchrch** [comment]
From @alex-gron 
- Make Connector Name a clickable link that takes you to docs

**Comment by evantahler** [comment]
From @ryjabe 

Some feedback on it:
Can we move definition ID to the last column?  I imagine the majority of our Cloud users don't care about it. Not sure if OSS does. 
Can we make Icon the first column? I'm not a UI/UX guy, but it feels like it should be logo, then name. 
Why do we have a source column when the table is already defined as sources?  Feels redundant, and like we could remove it.
Release stage should be above the fold.  That's probably the single most important thing Followed by OSS/Cloud status.  Those need to be above the fold too. 
Can the name of the source link to the Docs instead of having a separate column?

**Comment by amaliaroye** [comment]
Just bit more feedback from me as well (mostly UX/UI):
- It would be helpful to have a tooltip or something that explains that the ✅ and ❌ in the "OSS" and "Cloud" columns means they're available/unavailable. Maybe even having the header as "Available on OSS" and "Available on Cloud"
- The connector type column seems somewhat unnecessary since the sources and destinations are in separate tables
- For connectors that are not created by Airbyte, the build status badge is broken
![Screen Shot 2023-04-28 at 4 12 03 PM](https://user-images.githubusercontent.com/80241026/235244761-bb260ff6-3f93-43d6-b660-e986ae0b9c54.png)
- May just be on my browser, but there is no visible horizontal scroll bar and is tricky to scroll through.
- The header for Connector Name scrolls away while the column itself is fixed. The border scrolls away as well so you can see the columns behind poking through
![Screen Shot 2023-04-28 at 4 21 03 PM](https://user-images.githubusercontent.com/80241026/235245957-85332f40-b49b-433a-9373-a3f6701cde89.png)
- On mobile, because the Connector Name column is fixed, the table is unreadable
![Screenshot_20230428-161908](https://user-images.githubusercontent.com/80241026/235245770-5c057f06-adb2-494d-b6b1-a4864cd50f74.jpeg)
- Are the connectors sorted alphabetically? It seems to be a bit out of order towards the end
![Screen Shot 2023-04-28 at 4 24 30 PM](https://user-images.githubusercontent.com/80241026/235247185-1996f516-9994-41b6-baa0-00cb54954723.png)
- This is more of a wishlist item, but it would be great if you were able to sort by the release stage or if the connector is available on Cloud
- Because the docker images are also searchable when using Ctrl+F, there's 3x the number of results when searching for a connector

Thanks Evan!
