### ISSUE TITLE
Connector Issue: Amazon Seller Central 

### ISSUE THREAD

**Issue by robertlansing** [airbytehq/airbyte#25830]
### Connector Name

airbyte/source-amazon-seller-partner

### Connector Version

1.1.0

### What step the error happened?

None

### Revelant information

When trying to setup the Amazon Seller Central API (with a Vendor Central account) I am receiving the error output below. Using the API directly I am able to authenticate, create, and pull the GET_VENDOR_SALES_REPORT, so the credentials are working.

During setup, I did receive errors from the Amazon API, until I set the following reportOptions:

{"GET_VENDOR_SALES_REPORT": {"reportPeriod": "WEEK", "distributorView": "SOURCING", "sellingProgram": "RETAIL"}}

Those options appear to be required now.

### Relevant log output

```shell
Configuration check failed
AttributeError("'NoneType' object has no attribute 'get'")

Docker log:
2023-05-05 05:59:02 ERROR i.a.w.i.VersionedAirbyteStreamFactory(internalLog):313 - Check failed
```

### Contribute

- [x] Yes, I want to contribute

**Comment by robertlansing** [comment]
More details, here is the stack trace:
```
Traceback (most recent call last):
  File "/airbyte/integration_code/source_amazon_seller_partner/source.py", line 139, in check_connection
    next(orders_stream.read_records(sync_mode=SyncMode.full_refresh))
  File "/airbyte/integration_code/source_amazon_seller_partner/streams.py", line 870, in parse_response
    if stream_slice.get("dataEndTime"):
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by sherifnada** [comment]
Looked into this issue with @robertlansing, here are some thoughts on what's going wrong: 
* to validate the input user configuration, we pull 1 record from the [`VendorSalesReports` stream](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/source.py#L136). The `read_records` call does not pass in the optional `stream_slice` parameter. Therefore, inside the `read_records` method and [`parse_response`](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/streams.py#L844) method, the `stream_slice` variable is `None`
* However, the `parse_response` method [always assumes the stream slice will be set](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/streams.py#L858)

I think there's a couple of things we need to improve here: 
1. to solve the specific problem reported in this issue we need to change [this line](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/streams.py#L858) to be `if stream_slice and ...`
2. all streams should be impervious to `stream_slice` being null
3. It generally seems odd that we're pulling a `VendorSales` report just to do a connection check. Is there not a lighter weight endpoint that we can look at rather than an async report to verify user credentials? Do all users have `VendorSales` data? etc... It would be more reliable to call a simple synchronous endpoint to verify credentials. 

In any case, to solve the problem reported here, we can very tactically make the change in point 1 above. @robertlansing would you be interested in submitting that as a contribution?

**Comment by robertlansing** [comment]
#26057

**Comment by askarpets** [comment]
This issue has been fixed at CDK level. For this specific stream, since stream slices are defined, `parse_response` function will never get `stream_slice` as `None`. Closing the ticket.
