### ISSUE TITLE
Investigate micronaut server builder lag

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#26277]
After experimenting with the performance of the connector builder, we want to allocate some time to scope what might be the issue.

**Comment by maxi297** [comment]
Creating a sidecar project and adding datadog to this project allowed us to have more visibility on the Python process. This allowed us to emit the following hypotheses (filtered because some were not relevant):

Hypothesis | Setup | Proven? | Why
-- | -- | -- | --
We are bounded by the number of threads | executors:    io:      type: fixed      n-threads: 300 | Not proven | The performance wasn’t better
Java is bounded by the CPU/memory | Increase k8s resources | Proven for atelierNot proven for sidecar | Atelier: Performance hit a new plateau
Sleeping the equivalent of the span Datadog mentions for the Python HTTP request would reproduce the issue | Change Controller implementation to sleep | Disproven | Latency is always ~300 ms (the sleep time)
Datadog metrics for Python/FastAPI are not representative | Running Python server locally (without k8s and docker) | Probably | k6 sees response time of ~1s while Datadog only reports ~100 ms

So in the end, we think that:
* Current prod solution is CPU/memory bound (for 10 VUs, removing 1 CPU and 1 Gb lead to average from 8.4s to 2.42s)
* Sidecar with 2/3 of the actual CPU/memory is also bounded by resources (for 10 VUs, removing 0.666 CPU and 0.666 Gb lead to average from 2.43s to 1.29s)
* Passed that, we're not exactly sure what is the bottleneck but Python seem to be involved for both cases
* Datadog and k6 see different latencies for Python/FastAPI which is really annoying... This is important because it invalidates our understanding that the FastAPI responded in ~300ms

Next steps:
This is unclear to me. With the current solution, if we are dissatisfied with the performances in production, we should increase the resources if we can. If we want to switch to the sidecar solution, we would need to ensure that Datadog reports the correct metrics

**Comment by maxi297** [comment]
Other actions taken:
* Create Datadog metrics dashboard
* Increase memory from 1Gi to 2Gi
* Only read the CDK version from file once and cache the response on health checks
* Enable access logging
