### ISSUE TITLE
Display connector/actor version number in the UI

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#26686]
With Launch Darkly overrides, slow roll-outs of breaking changes, or general development hacks... it's possible to be running a version of a connector that's not the default version.  When this happens, we should show this to folks in the UI.
(connector pages, connection pages)

Only when viewing the 'overview' or 'settings' page of a connector, show the version.  Use the `dockerImageTag` value.

![Screenshot 2023-05-30 at 10.44.50 AM.png](https://images.zenhubusercontent.com/625848c232857a5abeb89721/ef03ba77-1e7a-4e5f-87cd-1769ec6337ad)

Modify the response of `https://cloud.airbyte.com/api/v1/source_definition_specifications/get_for_source` to return the dockerImageTag as well.

**Comment by pedroslopez** [comment]
A way to do this could be:
1. add a new `isDefaultVersion` bool to the API response for [SourceDefinitionSpecificationRead](https://github.com/airbytehq/airbyte-platform-internal/blob/7a3dfbc911cb02404e020fd88ab8a0c9faaeba0d/oss/airbyte-api/src/main/openapi/config.yaml#L3389) and [DestinationDefinitionSpecificationRead](https://github.com/airbytehq/airbyte-platform-internal/blob/7a3dfbc911cb02404e020fd88ab8a0c9faaeba0d/oss/airbyte-api/src/main/openapi/config.yaml#L3778)
2. Populate the above when building the read (here for [destinations](https://github.com/airbytehq/airbyte-platform-internal/blob/7a3dfbc911cb02404e020fd88ab8a0c9faaeba0d/oss/airbyte-commons-server/src/main/java/io/airbyte/commons/server/handlers/SchedulerHandler.java#L483-L506), there's an equivalent for sources)
    - This can be done by checking if destination.getDefaultVersionId() == destinationVersion.getVersionId(). If they're different, it means there was some kind of override applied.
    - 
3. When `isDefaultVersion: true`, on the frontend side show a banner on the source/destination page.

**Comment by evantahler** [comment]
As part of this, change the heading "current version" to "default version" for Cloud

![Screenshot 2023-05-30 at 10.50.33 AM.png](https://images.zenhubusercontent.com/625848c232857a5abeb89721/ad3db827-3d16-4554-b3a7-1337643165e4)

**Comment by erohmensing** [comment]
I think we want to specifically know if the version was overriden via a feature flag. 

* For this UI change, we want to show the version if it comes from LD (honestly, probably even if it is the same as the default - this is our way of knowing not only what version an overriden one is on, but whether a version has been overriden)
* For the breaking changes, we want to hide the breaking change banner if the version comes from LD. If a user is pinned on a deprecated/unsupported version its probably for a specific reason, since we're the ones that configure those overrides. I.e. we probably still calculate the breaking changes off of the ADV, but if it came from a LD override, we don't show the impending updates

**Comment by erohmensing** [comment]
We'll show this always!
