### ISSUE TITLE
Octavia CLI: Change on stream schema not reflected on Airbyte UI/re-imported config after successful application

### ISSUE THREAD

**Issue by JcMeeopp** [airbytehq/airbyte#26895]
### Octavia CLI Version

0.44.4

### Revelant information

**Airbyte Version: 044.2**

### Connection
Mongodb -> PostgresSQL

### My Usecase

Airbyte schema refresh refuses to pickup some fields from my mongodb collection  (possibly due to sampling not seeing the field). So I resorted to Octavia CLI to edit the connection configuration and add the column to the schema.

What I did was
1.  run `octavia import all` which dump my airbyte config. 
2. Edit the file `configuration.yaml` in the target connection folder.
3. run `octavia apply` to apply the change. 
    - Note that I had to manually remove `geograph` and `breaking_changes_preference` (as per mentioned in this [issue](https://github.com/airbytehq/airbyte/issues/19768#issuecomment-1477669273))
 
While I know afterward my schema change was successful because after I perform a sync, I do see my new column being created in my destination table in postgres DB, It was really baffling that:
1. When I go to airbyte UI, `connections`->`replication` and the stream that was changed DO NOT have the additional column I added in.
2. When I run `octavia import all` or `octavia get connection <connecton_id>` and inspect the updated config from my airbyte instance, I also DO NOT see the column I added and applied. 

I am unable to use this to sync my config to version control because I cannot retrieve the most updated config without overwriting my modified config which contains the column that I wanted.

**Comment by JcMeeopp** [comment]
hello team is there any response on this issue?
i.e. do we know if it's my problem that that's not supposed to be the case ? Or it's actually a known problem that others have reported?

**Comment by zachloertscher** [comment]
I'm running into a similar issue, but with data type changes.

I have a sql-server connection that I am creating with the octavia cli using `octavia apply --force`.  When I try to sync this connection, however, I get the following error messages in the log:
```
2023-07-20 14:09:18 source > WARN i.a.i.s.r.DbSourceDiscoverUtil(logSourceSchemaChange):82 Source schema changed for table Treatment.PpoInsurancePolicy! Potential mismatches: [FeeScheduleId, CoinsurancePercentage, TreatmentInsurancePolicyId]. Actual schema: {"type":"object","properties":{"DeductibleDentalRemaining":{"type":"number"},"DeductibleOrthoLifetimeRemaining":{"type":"number"},"DeductibleOrthoAnnualRemaining":{"type":"number"},"FeeScheduleId":{"type":"number","airbyte_type":"integer"},"TreatmentInsurancePolicyId":{"type":"number","airbyte_type":"integer"},"CoinsurancePercentage":{"type":"number","airbyte_type":"integer"}}}. Catalog schema: {"type":"object","properties":{"DeductibleDentalRemaining":{"type":"number"},"DeductibleOrthoLifetimeRemaining":{"type":"number"},"DeductibleOrthoAnnualRemaining":{"type":"number"},"FeeScheduleId":{"type":"integer"},"CoinsurancePercentage":{"type":"integer"},"TreatmentInsurancePolicyId":{"type":"integer"}}}
```

and then 

`2023-07-20 14:09:18 source > ERROR i.a.i.b.s.SshWrappedSource(read):76 Exception occurred while getting the delegate read iterator, closing SSH tunnel java.lang.IllegalArgumentException: No enum constant io.airbyte.protocol.models.JsonSchemaPrimitiveUtil.JsonSchemaPrimitive.INTEGER`

HOWEVER, when I...
- click the Replication>Refresh Source Schema button
- save the connection 

The connection works, no problem...

This really limits me to still using the UI because creating these connections with the Octavia CLI doesn't allow me to refresh the source schema & capture new changes.

Have there been any updates on this?

**Comment by marcosmarxm** [comment]
Octavia was removed from the main repo and won't receive updates anymore.
