### ISSUE TITLE
Make user type in name of item they're deleting as part of confirmation

### ISSUE THREAD

**Issue by chandlerprall** [airbytehq/airbyte#27038]
### What area the feature impact?

None

### Revelant Information

Proposal: introducing a type the name of the thing to confirm deletion action into connection & workspace deletions.

I've accidentally deleted the wrong connection a couple times. I think this makes sense to add for workspaces, connections, sources, and destinations.

Thinking something similar to AWS's S3 bucket deletion flow:

![Screen Shot 2023-05-31 at 1 27 23 PM](https://github.com/airbytehq/airbyte/assets/313125/691b3222-3609-4cce-ba63-32d9ffccf0e2)

**Comment by tealjulia** [comment]
Popping this one back in "Incoming" to revive the discussion.

This idea was brought up again by @rileybrook as well https://airbytehq-team.slack.com/archives/C05J0J1TXCK/p1693323233560419

**Comment by josephkmh** [comment]
Refining notes:
- This should be added in a modal
- User should be required to type full name of the resource they are deleting
- GitHub & AWS are good examples of how this can work
- Worth checking whether we can make this consistent with the component introduced here: https://github.com/airbytehq/airbyte-platform-internal/pull/8645

**Comment by ambirdsall** [comment]
@tealjulia yep. The deletion modal exists and works in my branch for cloud; then I spent some time trying to make it a generic "type value to confirm" utility, but ended up having to throw out two separate drafts—I couldn't find a clean way to factor out all the delete-workspace-specific logic, especially since it ended up interleaved with the modal lifecycle. Once a utility goes past a certain number of arguments, it's more confusing to reuse and maintain than a copy/paste rewrite of the existing modal would be, and I kept running into that line last week 🤦

**Comment by josephkmh** [comment]
@ambirdsall any update here?

**Comment by ambirdsall** [comment]
The code was done a couple weeks ago—I checked back here because I was starting to wonder why the review was stalled in limbo and.... I hadn't actually pushed it up to a PR 🤦. Well, that's embarrassing! It's also no longer true, at least: https://github.com/airbytehq/airbyte-platform-internal/pull/9697
