### ISSUE TITLE
Update docs to enable unlisted (sidebar) migration guide docs

### ISSUE THREAD

**Issue by bnchrch** [airbytehq/airbyte#27086]

**Comment by erohmensing** [comment]
Grooming: 
* Update sidebar logic [here](https://github.com/airbytehq/airbyte/blob/87f277f41b01afdc908c6e228e84db790cf6d60f/docusaurus/sidebars.js#L8-L17) which finds the files
* .inapp.md files should go in the new folders too -> this probably requires some platform finagling

**Comment by erohmensing** [comment]
Old description:

## Overview
We want to support connector specific migration guides

This requires us to place a file at
`docs/integrations/sources/aircall/migration_guide.md`

However connector docs are currently served at
`docs/integrations/sources/aircall.md`

What we need to do is

- [ ] Migrate all connector docs to this format `docs/integrations/sources/aircall/readme.md
- [ ] Ensure that inapp docs still work
- [ ] Ensure that https://docs.airbyte.com/integrations/sources/aircall still serves the same info

**Comment by erohmensing** [comment]
We decided not to move the old docs until the big metadata move. Now we want to enable the migration guide docs another way. Either: 
- putting migrations in their own folder (containing them for all sources/all destinations instead of the opposite nesting), or
- list them alongside the existing docs, like the .inapp docs
