### ISSUE TITLE
Add tooltips for connection status icons

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#2715]
## Tell us about the problem you're trying to solve
I setup a new connection with "manual" cadence and I'm seeing a yellow icon to the left of it. The connection has never synced data before. This yellow icon is concerning because it feels like there is a warning here somewhere, but I don't know what it means. I would like to be able to understand what the problem is by hovering on the icon. 

<img width="489" alt="Screen Shot 2021-04-01 at 10 41 56 PM" src="https://user-images.githubusercontent.com/6246757/113384735-8ba2fc00-933b-11eb-86a3-1826218c5530.png">

## Describe the solution you’d like
Tooltip describing what the icon means

Separately, yellow feels like the wrong color here? it typically means "warning" but I'm not sure there is anything to warn about for a manual connection that hasn't run yet.

**Comment by jrhizor** [comment]
For something that never synced, maybe something like ⭕   would be good (but green). Then it doesn't imply it isn't healthy. 

I like the tooltip idea though, we should have that too

**Comment by Jamakase** [comment]
The idea of using yellow here is next: when a user sets up the connection with manual sync and it was never run he may be confused why he has a connection but may not have any data in his destination. That's why I think green is also not a great colour here - some could be confused that their sync is set up correctly and is running, however, it was never run.

@jrhizor @sherifnada @cgardens
