### ISSUE TITLE
Appstore connect not able to synk Subscriber, Subscriber Events and Subscription reports

### ISSUE THREAD

**Issue by winbergj** [airbytehq/airbyte#27235]
### Connector Name

appstore-singer

### Connector Version

0.2.6

### What step the error happened?

Configuring a new connector

### Revelant information

I have an issue with the Appstore connector not able to synk our Subscriber, Subscriber Events and Subscription reports. Just the Sales reports. Anyone else experiencing this issue and knows how to solve it?
Have setup the access with "Finance" role, which should be enough?

### Contribute

- [ ] Yes, I want to contribute

**Comment by deepapt** [comment]
I am also experiencing this issue in AppStore connect- cloud (Enabled by Airbye).  subscription-related data has not synced since 2023-03-01. The log history says **`There were no sales for the date specified for 2023-03-02`**. But I can able to retrieve the report via [API](https://developer.apple.com/documentation/appstoreconnectapi/download_sales_and_trends_reports). But Airbyte doesn't pull data.

**Comment by marcosmarxm** [comment]
The App Store connector has been [archived](https://docs.airbyte.com/integrations/sources/appstore#deprecation-notice) and won't get updates in the future. We're closing this issue to focus on features and connectors in our roadmap. Thanks for understanding! 🚀
