### ISSUE TITLE
[MySQL] CDC replication mode to specify source defined cursor

### ISSUE THREAD

**Issue by prateekmukhedkar** [airbytehq/airbyte#27340]

**Comment by prateekmukhedkar** [comment]
In MySQL the file name and position can be repeated, so we can't use LSN analogy from Postgres.
This will be generated by source-mysql : some kind of a composite key that can be ordered and sortable.

Catalog currently does not contain _ab_cdc_lsn.

**Comment by nguyenaiden** [comment]
@subodh1810 Per the conversation we had during sprint planning, Log Pos and Log file can't be used as a cursor individually since we know that they aren't guaranteed to be unique.
 I'm thinking something along the lines of creating a composite cursor value like `[updated_at]-[bin_log_file]-[bin_log_pos]`. But even then, in the case of when the customer DB source doesn't have a PK and string-type fields can technically be monotonic, we can't really guarantee the correct order, correct?

**Comment by nguyenaiden** [comment]
Looking at the different columns that we can use for a default cursor, GTID looks like a very good options as it is guaranteed to be unique _and_ monotonically increasing. [Documentation](https://dev.mysql.com/doc/refman/8.0/en/replication-gtids-concepts.html#:~:text=Client%20transactions%20are%20guaranteed%20to,on%20the%20server%20of%20origin.)
But I did see in the MySQL doc that enabling GTID mode is optional for CDC syncs. 
 
@subodh1810, is it worth it for us to identify all of MySQL CDC customers and ask them if they have `gtid_mode=off` and have them turn it on? Since the GTID value has the characteristics that we need for a default cursor field and is less troublesome to generate compared to the composite key solution mentioned above, I think it is the right cursor field to choose.
