### ISSUE TITLE
Airbyte CDK: Change Error message if stream is not found

### ISSUE THREAD

**Issue by artem1205** [airbytehq/airbyte#27393]
### What area the feature impact?

Connectors

### Revelant Information

In case of changing/renaming streams in connector we have error:
Stream not found

| Current message | New Message |
|--------|--------|
| The requested stream {`stream_name`} was not found in the source. Available streams:... | The stream {`stream_name`} no longer exists in the configuration. Refresh the schema in replication settings and remove this stream from future sync attempts. |

**Comment by sherifnada** [comment]
I think we should also make it so that the connector can choose whether a missing stream should be an error i.e: provide a `raise_exception_on_missing_stream` option in `AbstractSource` so that this isn't even a failure. The option should default to true, but connectors such as Facebook or Google Ads can override it to be False. I recommend we do this because this should not impact whether we sync the user's remaining data.

**Comment by keu** [comment]
Intriguing, it would be great to know all possible reasons for a stream not to be found. Also, @sherifnada do you think it should be configured on Source or Stream level?
