### ISSUE TITLE
Make source grid filterable by release stage

### ISSUE THREAD

**Issue by josephkmh** [airbytehq/airbyte#27456]
The source selection grid is currently sorted alphabetically with an option to search, but no further filters.

Acceptance criteria:
- A filter is added under the search bar that lets users sort connectors by any combination of Alpha, Beta or GA
- By default Alpha sources should not be selected (as these clutter the page)

**Comment by cgardens** [comment]
@nataliekwong @josephkmh would it make sense to take @bmcgilli 's [suggestion](https://airbytehq-team.slack.com/archives/C02U6CXJQFN/p1686932023885359) to sort based on release stage as well?

**Comment by nataliekwong** [comment]
We are defaulting to only show the GA/beta connectors on page load so that the Alpha sources are removed from the view, which is the original issue that was raised. I think that will solve the core issue of a cluttered view.

I think we should allow sorting by Name or Release Stage as well (not in the original issue but would be an addition to scope), but I prefer the default be by Name given we'd be hiding by default the Alpha connectors, so we would be sorting and filtering by the same attribute.

**Comment by josephkmh** [comment]
Refining notes:
- If we're hiding several hundred connectors, it would be useful to show some subtle text about how many items are hidden (e.g. `95 connectors hidden`)
- Design ideas: https://www.figma.com/file/8aM4gBoW95whyshI5kwVct/01_06_SOURCES?type=design&node-id=1927-84771&mode=design&t=4IZELiTN1kA9FmzQ-0
