### ISSUE TITLE
migration: add actor_definition_breaking_change table to platform 

### ISSUE THREAD

**Issue by erohmensing** [airbytehq/airbyte#27507]
We want to add a new table to the platform to keep track of `breakingChanges` that come in through metadata.

Tasks: 
1. Write a migration to add the new table (empty)

fields:
- Actor_definition_id: UUID FK actor_definition.id
- version: string
- migration_documentation_url: string
- upgrade_deadline: date
- message: string
- created_at: datetime
- updated_at: datetime

primary key:
- composite key of (actor_definition_id, version)

2. New jsonSchema2pojo class, ActorDefinitionBreakingChange

fields: 
- actorDefinitionID (string, format: uuid) 
- version (string, format: regex: (semver regex))
- migrationDocumentationUrl (string)
- upgradeDeadline (string, format: date-time)
- message (string)

3. ConfigRepository methods for reading/writing 
- writeActorDefinitionBreakingChange stores an ActorDefinitionBreakingChange object in the db
- getActorDefinitionBreakingChanges (actorDefinitionID) gets a (potentially empty) list of ActorDefinitionBreakingChanges for a specific actorDefinitionID.

These methods should be enough for read/write testing. In future issues some of the ConfigRepository methods might change: 
- the write method will become an upsert, since breakingChanges data is global and therefore can change at any time 
- the read method we will likely allow passing in a version in order to be able to filter the list to only get breaking changes >= a specific version. (I think?) this should be more efficient than retrieving all breaking changes for a given version and then filtering them on the object side.

**Comment by erohmensing** [comment]
Grooming topics: 
- nullable vs non-nullable: how enforcing are we with the data that comes in from metadata? 
- any chance at being able to use the Version java class in ActorDefinitionBreakingChange?

**Comment by pedroslopez** [comment]
Note: we should probably use micronaut data for the reading/writing portion, since platform is moving to it generally and started to use it.

Note here on what it would take https://airbytehq-team.slack.com/archives/C04TK6HA0CQ/p1687990360789069

Namely, there are some things currently that prevent adding the repository class to the existing config-persistence module. We should be able to create a new module for shared usages though, maiking sure that the cron and bootloader apps properly unwrap the datasources/contexts.
