### ISSUE TITLE
E2E tests for PK Incremental

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#2756]
## Tell us about the problem you're trying to solve
What are you trying to do, and why is it hard? A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

## Describe the solution you’d like
A clear and concise description of what you want to see happen, or the change you would like to see

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

**Comment by ChristopheDuong** [comment]
Acceptance tests include a method called `testIncrementalDedupSync` that creates a table and insert/replicates data incrementally while deduping rows following primary key definition.

This was also causing tests to take longer to run so I had to increase the acceptance tests timeout so normalization had more time to run through the syncs too (in order to deduplicate)

**Comment by cgardens** [comment]
Cool. I guess we can close this then. Maybe in the future our E2E tests should include a python source as well, but that is definitely out of scope for what this issue was getting at.

**Comment by cgardens** [comment]
@michel-tricot, @ChristopheDuong 's response answers your question from the weekly planning meeting yesterday about having a test for PK incremental in the E2E tests.
