### ISSUE TITLE
Source Harvest: Invalid timeframe must not exceed 1 year

### ISSUE THREAD

**Issue by richard-sparq** [airbytehq/airbyte#27751]
### Connector Name

source-harvest

### Connector Version

0.1.18

### What step the error happened?

During the sync

### Revelant information

The sync fails with the following entry in the logs:
```
source > {"message":"Invalid timeframe: must not exceed 1 year"}
source > 400 Client Error: Bad Request for url: https://api.harvestapp.com/v2/reports/time/clients?per_page=50&from=20200101&to=20210101
```

If I query the same endpoint using curl I get a similar error. Changing the from parameter to 20200102 results in a successful response.

Anyone got any ideas please? Is this simply an issue with the Harvest Connector?

### Contribute

- [X] Yes, I want to contribute

**Comment by richardguinness** [comment]
Agreed, and thanks. But this requires modification to the Harvest connector which is something I can look at but I may not have the ability to modify.

**Comment by padioca** [comment]
I believe the issue is that the connector uses `end_date.subtract(years=1)` as opposed to `end_date.subtract(days=365)`. In looking at the Harvest API docs mentioned above, it states "The timeframe supplied cannot exceed 1 year (365 days)" which is fine most of the time, but will not work for leap years. I believe my solution above should solve for that, working on getting a PR put together.

**Comment by sajarin** [comment]
Solved thanks to @padioca!
