### ISSUE TITLE
Status page: custom connector status

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#27892]
When the stream view is used for custom source connectors, it seems it's following a different logic for the connection status.

Case 1: Reset does not influence the connection status
- Connection hasn't succeeded since 6/16 (has been trying to reset and it's been failing)
- Shows "On-time" on the status page but would not be On-time based on the 2x interval (set to refresh every 24 hours)

I would expect for the status of the connection to be delayed, because it has passed the expected interval for delayed. (Ideally actually this would show error, but I don't think we have handled failed refreshes in a good way yet)

Example: https://cloud.airbyte.com/workspaces/19f698e1-6472-4cbf-8ef1-b08f080daf75/connections/802bf041-ac18-4161-a8df-43a1c27813cc/job-history

Case 2: Disabled streams show as late
- Connection is disabled
- Enabled streams are late

I would expect to not see any streams in this view, since other disabled connections do not show any streams.

Example: https://cloud.airbyte.com/workspaces/bed3b473-1518-4461-a37f-730ea3d3a848/connections/d4119925-4ad2-4b28-806a-4bec53d6bfa2/status

cc @chandlerprall

**Comment by chandlerprall** [comment]
> Case 1: Reset does not influence the connection status

Agreed, except I believe that connection should be Pending from the reset, instead of Delayed; there's a couple other unimplemented cases for moving connection status into Pending: when a single stream has reset or when a stream is enabled and has no history

> Case 2: Disabled streams show as late

Looks like there's a distinction somewhere between connections with and without per-stream status, and that determines if a disabled connection's streams are listed or not. As described in the issue description the "Enabled streams" table should always be empty if the connection is disabled.

**Comment by nataliekwong** [comment]
Closed in favor of two new issues
