### ISSUE TITLE
Set Propagate schema changes through octavia cli

### ISSUE THREAD

**Issue by lucienfregosibodyguard** [airbytehq/airbyte#28191]
### Octavia CLI Version

0.50.4

### Revelant information

I want to set `Detect and propagate schema changes` to Propagate all changes through octavia CLI

I tried to set this in the octavia yaml connection

`non_breaking_change_preference: propagate_fully`

But it doesn't seem to have any effect/impact on the connection it stays at Ignore value

### Relevant log output

```shell
No
```

**Comment by nataliekwong** [comment]
Hi there, are you able to use Airbyte API rather than the Octavia CLI?

Here are the docs on it: https://reference.airbyte.com/reference/patchconnection

<img width="636" alt="Screen Shot 2023-09-28 at 4 31 04 PM" src="https://github.com/airbytehq/airbyte/assets/38087517/eca4c300-cf7b-4cdc-9dc9-12ed46d70ea9">
