### ISSUE TITLE
Bring Workspace settings to OSS

### ISSUE THREAD

**Issue by tealjulia** [airbytehq/airbyte#28276]
Bring workspace settings to OSS

Not all will be relevant in a non-cloud world (ie: data residency)

Unify them into a single page + feature flag them in as relevant

Small aside: remove the "change workspaces" button from the settings page on cloud.  We already allow users to do this from the picker.

**Comment by tealjulia** [comment]
@nataliekwong if you have some input!

**Comment by nataliekwong** [comment]
Hey! I have some ideas for this:
- Align the settings to be categories across the top rather than a column
- Combine "Account" and "Cookie Preferences" (if possible). I think at the time, the guidance was this was required to be one away from the top-level nav. However, I don't see that being the case in any other apps I use, so I'm not sure this is applicable still.
- Put data residency into the workspace settings, agreed with removing the "Change Workspace" CTA
- Users, Sources, and Destinations remain largely unchanged. I suggested we rename User Management to "Members", but not sure what to do with "Sources" & "Destinations"
- I prefer having the dbt cloud integration be more of a narrow width box so that eventually you see integrations in a horizontal order, but this isn't that important right now. 

I created a visual wireframe for the suggestions here: https://whimsical.com/workspace-settings-4L8PUfq2wTtEcytCkffBZz

**Comment by tealjulia** [comment]
Thanks for the visual!  Looks like a big improvement.  Left some thoughts.

**Comment by josephkmh** [comment]
This issue tracks general improvements to the settings page we can make. @nataliekwong is putting together a list of settings we want accessible across OSS, Enterprise and cloud https://docs.google.com/spreadsheets/d/1J9ovIiHaXRV7ewljV7sJphtYhX_UNyKLbh-FoCpTB1k/edit#gid=0

**Comment by nataliekwong** [comment]
Finished cleaning up the doc from my side! 👍

**Comment by tealjulia** [comment]
the general improvements outlined here have been done, so I'm marking this as closed

one item we did not address is the ability for users to delete an OSS workspace or organization.  I've split that out into https://github.com/airbytehq/airbyte/issues/29952
