### ISSUE TITLE
Publishing New Connectors fails on remote CI

### ISSUE THREAD

**Issue by bnchrch** [airbytehq/airbyte#28300]
## Problem

We've encountered issues with the publishing of two new connectors: `airbyte/source-gainsight-px:0.1.0` and `airbyte/destination-langchain:0.0.1`. Here are the key points:

- Both connectors failed to publish for the first time. See the related GitHub Actions run [here](https://github.com/airbytehq/airbyte/actions/runs/5534270427) and Docker Hub tags [here](https://hub.docker.com/r/airbyte/destination-langchain/tags).
- The same problem occurs when attempting to publish these via prerelease on CI.
- However, publishing them via `airbyte-ci` locally is successful.
- The remote CI logs indicate that the issue may lie with `crane ls`. See the related [source code here](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/publish.py#L26). The last line is a `NAME_UNKNOWN` error.
- Interestingly, we explicitly handle this error and mark it as successful because it indicates a new repository is added to Docker Hub, as expected for new connectors.
- Our current hypothesis is that the shared Docker instance setup [here](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/actions/environments.py#L377) causes the `crane_ls` instance to bring down the main pipeline when it exits unsuccessfully.
- We tried to test this here: https://github.com/airbytehq/airbyte/actions/runs/5537256263 it seems like that did occur

## Proposed Solution

To resolve this issue, we propose the following steps:

1. Rule out the `dockerd` theory: We need to ensure that the shared Docker instance setup is not causing the `crane_ls` instance to terminate the main pipeline when it fails.
2. Change `crane` to a library: Rather than being a separate Docker instance, `crane` should be a library installed in the existing pipeline.

**Comment by pedroslopez** [comment]
Copying over the update I shared on slack:

1. It doesn't seem like this is due to the global dockerd 
    - Adding logs all over the place, does not seem to indicate the parent dockerd service gets killed when crane non-0 exits.
2. The non-0 exit code is correctly detected, but the NAME_UNKNOWN error is not found in stdout
    - Logs [here](https://github.com/airbytehq/airbyte/actions/runs/5559403500/jobs/10155480143#step:5:570) show that both stderr and stdout are the same string, being process "/ko-app/crane ls airbyte/source-psl-test" did not complete successfully: exit code: 1 
    - Since this does not contain NAME_UNKNOWN, the successful check is not returned ([here](https://github.com/airbytehq/airbyte/blob/1c871756b31be55fc417e0df8f87f6ae9c842074/tools/ci_connector_ops/ci_connector_ops/pipelines/publish.py#L38))
    - Instead, we drop down to the else  where the failure status is returned ([here](https://github.com/airbytehq/airbyte/blob/1c871756b31be55fc417e0df8f87f6ae9c842074/tools/ci_connector_ops/ci_connector_ops/pipelines/publish.py#L40))
3. Locally, we also see that both stderr and stdout contain the same contents. HOWEVER, there are extra lines:
process "/ko-app/crane ls airbyte/source-psl-test-1" did not complete successfully: exit code: 1
Stdout:

Stderr:
Error: reading tags for index.docker.io/airbyte/source-psl-test-1: GET https://index.docker.io/v2/airbyte/source-psl-test-1/tags/list?n=1000: NAME_UNKNOWN: repository name not known to registry; map[name:airbyte/source-psl-test-1]

This seems to come down to a dagger version mismatch between local ci and github ci, and should be fixed by a version bump. The version bump has been issued, but we're pending confirmation of the fix which is blocked by other pipeline issues.

**Comment by evantahler** [comment]
It works now!
