### ISSUE TITLE
Show "Alpha" connectors when users search for a connector

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#28620]
Observations:
- Receiving connector requests for existing connectors (ex Postgres destination), even though we offer it. Fullstory: https://fsty.io/v/gLzmC47F, https://fsty.io/v/b9zkTHTK (requesting Google Sheets)
- Searching "Google" shows our GA / Beta connectors but misses the other Google alpha connectors, so the message that indicates those exist isn't seen. 

It seems that having both the search bar and filter is not necessarily intuitive (and if seen, the "hidden by filters" message is ignored as it isn't a noticeable CTA)

Suggestion: Automatically "check" the alpha connectors box if a user searches. Could also remove filters (Suggestion from Lake)

Slack thread: https://airbytehq-team.slack.com/archives/C03088BTMFC/p1689805550156599

**Comment by josephkmh** [comment]
Refining notes:

We should try fixing this by:
- Adding "show all connectors" button that selects all release stages to reveal all search matches 
- Making "hidden results" message more prominent
- Showing number of hidden connectors. (potentially show which release stages are hidden)

Other ideas:
- Disable filters entirely when searching
  - Kind of weird UX, makes it impossible to combine filter + search
- Move filters to left side of the screen to make them more prominent
  - Would be a pretty empty section, since we only have one facet
