### ISSUE TITLE
Internal Status Page

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#29055]
There are a ton of tools and services which Airbyte developers rely on to do to their jobs.  For both platform and connector developers, there are test and publish pipelines, internal services, etc which are hard to keep track of.  We should make an internal status page which shows the status for all of these in one place, so it is clear what is happening, who is fixing any problems, and if 'business as usual' can happen.

Tools to monitor:
* Connectors
    * Docker Hub
    * CI K8s
    * Dagster
    * Dagger
* Platform
    * TODO

Tools to consider for this status page:
* Notion
* StatusPage
* Uptime.com

**Comment by bnchrch** [comment]
Pagerduty has an internal status page as well https://airbyte.pagerduty.com/status-dashboard

**Comment by supertopher** [comment]
I think this is a good idea.  There is a pretty constant ebb and flow of internal tool uptime and downtime.  Just thinking about a few:

* is the build currently passing on master?
* is_code_free_active? and when does that code freeze end
* is the deploy pipeline in a working state?

I also think there may be an opportunity to message important changes to groups like oncall and TCS.  ie: Jimmy's changes to reduce CPU allocation for APIs is something I would like most of our devs to know about especially if they are looking at issues for an API connector.

**Comment by evantahler** [comment]
I'm infatuated with https://upptime.js.org - an entirely inside github status page engine.  Every issue is an incident, it has email and slack notifications, and it polls for HTTP status/success.

**Comment by bnchrch** [comment]
Good input @supertopher! Really like the code freeze announcements, build statuses and the idea of alerting "Hey oncall im reducing resources heads up"

Also like what you found @evantahler . At a cursory glace my only questions are
1. Its geared towards sites being down, whats the flow to automate the creation of one off issues (Dagster down?)
2. And announcements
2. Also an we cover tophers use case of ci build bad?

That being said im going to tinker because if its good enough im onboard.

I have some notes below on my exploration into PagerDuty (absolutely not) and OneUpTime.com (potentially yes but wed want to self host)

## Notes on oneuptime.com
At $22-$99/mo/seat I think paying them is a bad option

But running oneuptime locally we have
1. Public and Private status pages
2. Single Sign on
3. Notifications
4. One off announcement banners
5. Custom links to roadmaps and services
6. One off indicdent creation
7. Private and public status updates
8. Slack webhook notification
9. API Incident creation
10. Custom html, css, js (maybe we can insert a github status badge)
11. 

Id recommend you give it a try by cloning locally

### Notes on Pagerduty internal status page
Went down the rabbit hole of "can our existing tooling do this" by exploring pagerduty.

The answer is yes, but in the same way that a tomato is a fruit, if you bite into one expecting fruit like flavours, your gonna feel sick.

The critique comes down to, to properly set up a status page you need to
1. Create a technical service
2. Create a business service
3. Link them
4. Create a slack only team or slack only service
5. Create an incident
6. Attach it to the team, technical service, and business service
7. Write notes 

Even then its unclear if the slack notification really ever work properly.

**Comment by bnchrch** [comment]
Screenshot from oneuptime
![image.png](https://images.zenhubusercontent.com/63d02817d1857451994bd656/b5266406-26af-439a-8a1d-9391830f0cc9)

**Comment by alafanechere** [comment]
What about continuing using Instatus. It supports private status pages.

**Comment by bnchrch** [comment]
@alafanechere great suggestion! I didnt know thats what we used. Its 100% the right tool.
