### ISSUE TITLE
New Connector: Amazon SP API

### ISSUE THREAD

**Issue by harshithmullapudi** [airbytehq/airbyte#2935]
## Tell us about the problem you're trying to solve
Need to get the Amazon MWS orders data to the destination

## Describe the solution you’d like
Writing a connector for Amazon MWS and starting to support just orders features to get started

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368102017302) by [Unito](https://www.unito.io)

**Comment by sherifnada** [comment]
@harshithmullapudi should we instead support the [Sellers API ](https://developer.amazonservices.com/) as that seems to be the newer version of MWS?

**Comment by sherifnada** [comment]
Also @harshithmullapudi could you point to which [endpoints in the API ](https://github.com/amzn/selling-partner-api-docs/tree/main/references) you'd like support for?

**Comment by harshithmullapudi** [comment]
yeah I also think we should support `Sellers API`. Thinking of starting with `https://github.com/amzn/selling-partner-api-docs/blob/main/references/orders-api/ordersV0.md`. @sherifnada

**Comment by vitaliizazmic** [comment]
## Integration Vetting
The integration hasn't already been vetted. [Selling Partner API (SP-API)](https://developer.amazonservices.com/) is recommend to use for Source implementation. SP-API is the next generation suite of API-based automation functionality for Amazon's Selling Partners and is an evolution of Amazon Marketplace Web Service (Amazon MWS) APIs, which have been offering sellers programmatic access to critical Amazon features for more than 10 years

**[SP-API Documentation on GitHub](https://github.com/amzn/selling-partner-api-docs)**

**Please see the [Selling Partner API Developer Guide](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md) for instructions to get started.**

We must consider that there is difference for developing app for **sellers** and **vendors**.

**Webhook-based? (no/partially/yes)**
No

**Available authentication modes (API key/Oauth/other)**
The authorization model for the Selling Partner API is based on [Login with Amazon](https://developer.amazon.com/docs/login-with-amazon/documentation-overview.html), Amazon's implementation of **OAuth 2.0**. In this model the selling partner authorizes your application by interacting with pages displayed by Amazon and by your website. 

The way applications are authorized depends on the application type. We can use [self-authorization](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#Self-authorization) procedure. Before doing this we must [register as a developer](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#registering-as-a-developer) and [register our application](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#registering-your-application). 

In the end of process we will obtain refresh token. Generating a new refresh token does not invalidate previous refresh tokens.

An Login with Amazon (LWA) refresh token is a long-lived token that is exchanged for an LWA access token. An access token obtained through this token exchange must be included with calls to all Selling Partner API operations except restricted operations and grantless operations, which use somewhat different authorization models. After an access token is issued it is valid for one hour. The same access token can be used for multiple API calls, until it expires.

To manually exchange a refresh token for an access token, see [Connecting to the Selling Partner API](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#connecting-to-the-selling-partner-api).

**Creating an account**
We can use existing account. Also [free AWS account](https://aws.amazon.com/free) is available. We must [register as a developer](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#registering-as-a-developer)

**How to populate the account with data?**
We can use [Selling Partner API sandbox](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#the-selling-partner-api-sandbox)

**Available streams for sync**
The [references](https://github.com/amzn/selling-partner-api-docs/tree/main/references) directory on GitHub contains API references for all available Selling Partner APIs. In order to use these APIs we must be a registered developer. Not all APIs are accessible by all registered developers and we must have approval from Amazon before can access these APIs.

It's requested to start from 

- [Selling Partner API for Orders](https://github.com/amzn/selling-partner-api-docs/blob/main/references/orders-api/ordersV0.md)

Another APIs

- [Selling Partner API for A+ Content Management](https://github.com/amzn/selling-partner-api-docs/blob/main/references/aplus-content-api/aplusContent_2020-11-01.md)
- [Selling Partner API for Catalog Items](https://github.com/amzn/selling-partner-api-docs/blob/main/references/catalog-items-api/catalogItemsV0.md#selling-partner-api-for-catalog-items)
- [Selling Partner API for Finances](https://github.com/amzn/selling-partner-api-docs/blob/main/references/finances-api/financesV0.md#selling-partner-api-for-finances)
- [Selling Partner API for Messaging](https://github.com/amzn/selling-partner-api-docs/blob/main/references/messaging-api/messaging.md)
- [Selling Partner API for Notifications](https://github.com/amzn/selling-partner-api-docs/blob/main/references/notifications-api/notifications.md#selling-partner-api-for-notifications)
- [Selling Partner API for Product Fees](https://github.com/amzn/selling-partner-api-docs/blob/main/references/product-fees-api/productFeesV0.md)
- [Selling Partner API for Pricing](https://github.com/amzn/selling-partner-api-docs/blob/main/references/product-pricing-api/productPricingV0.md#selling-partner-api-for-pricing)
- [Selling Partner API for Reports](https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reports_2021-06-30.md)
- [Selling Partner API for Sales](https://github.com/amzn/selling-partner-api-docs/blob/main/references/sales-api/sales.md)
- [Selling Partner API for Sellers](https://github.com/amzn/selling-partner-api-docs/blob/main/references/sellers-api/sellers.md)
- [Selling Partner API for Services](https://github.com/amzn/selling-partner-api-docs/blob/main/references/services-api/services.md)
- [Selling Partner API for Shipping](https://github.com/amzn/selling-partner-api-docs/blob/main/references/shipping-api/shipping.md)
- [Selling Partner API for Solicitations](https://github.com/amzn/selling-partner-api-docs/blob/main/references/solicitations-api/solicitations.md)
- [Selling Partner API for Direct Fulfillment Orders](https://github.com/amzn/selling-partner-api-docs/blob/main/references/vendor-direct-fulfillment-orders-api/vendorDirectFulfillmentOrdersV1.md)
- [Selling Partner API for Direct Fulfillment Shipping](https://github.com/amzn/selling-partner-api-docs/blob/main/references/vendor-direct-fulfillment-shipping-api/vendorDirectFulfillmentShippingV1.md)
- [Selling Partner API for Retail Procurement Orders](https://github.com/amzn/selling-partner-api-docs/blob/main/references/vendor-orders-api/vendorOrders.md)
 
**Integration supports incremental sync?**
Partial

- Orders - CreatedAfter query parameter 

**Other information/blockers**
Singer Tap doesn't exist.
