### ISSUE TITLE
Destination BigQuery v2 - Array Column is null

### ISSUE THREAD

**Issue by jbfbell** [airbytehq/airbyte#29365]
More Context in [Slack Thread](https://airbytehq-team.slack.com/archives/C04VDANQN7P/p1691703836676929)
* Source: Google Ads
* Destination: BigQuery v2

The platform said this, which might be relevant and show a schema error:

```
2023-08-10 05:14:31 [46mreplication-orchestrator[0m > Schema validation errors found for stream _ad_history. Error messages: [$.ad_group_ad.ad.final_urls: array found, but [string, null] is required]
2023-08-10 05:14:31 [46mreplication-orchestrator[0m > publishing count, name: NUM_DISTINCT_SCHEMA_VALIDATION_ERRORS_IN_STREAMS, value: 1, attributes: [MetricAttribute[key=validation_error, value=$.ad_group_ad.ad.final_urls: array found but [string null] is required], MetricAttribute[key=docker_repo, value=airbyte/source-google-ads], MetricAttribute[key=docker_version, value=0.7.4], MetricAttribute[key=stream, value=_ad_history]]
```

Custom report stream containing the field `ad_group_ad.ad.final_urls` Source classifies it as a `string` however it is a comma separated list 
![image](https://github.com/airbytehq/airbyte/assets/104733644/3e661a4d-835b-4bcf-b7dd-3687b8a436c8)

The Final Table was delivered with `null` values for the entire field, however, the _raw tables contained the data.

Final Table
![image](https://github.com/airbytehq/airbyte/assets/104733644/60c40b35-385b-40d6-aa43-12522b3d5426)

Raw Table 
<img width="899" alt="Screenshot 2023-08-11 at 12 44 09 PM" src="https://github.com/airbytehq/airbyte/assets/104733644/18b885de-9eeb-46c3-aefc-c138691ea67a">

**Comment by evantahler** [comment]
Just a reminder, this may still prove to be a source bug, with an incorrect schema being returned

**Comment by jbfbell** [comment]
We will investigate this issue to get a better understanding of the root cause:
this will only be considered a blocker for v2 if its determined to be a v2 specific issue

**Comment by cynthiaxyin** [comment]
Investigation notes:

I assume the 1st screenshot is coming from the Google Ads source. The source field is typed as a string. Then, the 3rd screenshot shows the raw data that was passed through is actually an array (i.e., `{"field": ["string"]}`).

To me this is a clear indication it's a source problem in that there are non-string values in a string column, and Destinations V2 is correctly catching these type errors. Another way to see this is the most recent sync log shows this string-specific SQL:
```
  WHEN (JSON_QUERY(`_airbyte_data`, '$."ad_group_ad.ad.final_urls"') IS NOT NULL)
    AND (JSON_TYPE(JSON_QUERY(`_airbyte_data`, '$."ad_group_ad.ad.final_urls"')) != 'null')
    AND (SAFE_CAST(JSON_VALUE(`_airbyte_data`, '$."ad_group_ad.ad.final_urls"') as STRING) IS NULL)
    THEN ["Problem with `ad_group_ad.ad.final_urls`"]
```

In particular, the 3rd line would look different if we wanted to parse an array ([code area](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/destination-bigquery/src/main/java/io/airbyte/integrations/destination/bigquery/typing_deduping/BigQuerySqlGenerator.java#L151)). You can see the effect of this by running `JSON_VALUE` in BigQuery, an array value returns null whereas a string value returns the expected string value:
<img width="827" alt="Screenshot 2023-08-16 at 5 36 27 PM" src="https://github.com/airbytehq/airbyte/assets/22702693/3b885043-c162-4867-8ff5-819184cf4538">

I think the `replication-orchestrator` logs are saying the same thing; it expects a string or null value but finds an array value.

One interesting thing is the original connection this was reported on was deleted, but I can still see the schema under the Replication tab. It shows the type for the problematic field was actually discovered as Array. But I see several data resets so maybe this was String earlier and got fixed by the user later on?
<img width="990" alt="Screenshot 2023-08-16 at 5 41 30 PM" src="https://github.com/airbytehq/airbyte/assets/22702693/83e5528e-22af-41a3-b6f7-290cf2a8fe8c">

**Comment by cynthiaxyin** [comment]
I see this customer has a [new connection](https://cloud.airbyte.com/workspaces/523af30a-e425-4108-a4fb-74dcadcdfdca/connections/987a8e6f-64c5-45da-88a8-71c1c322783d/job-history) (with BigQuery on V2) and the schema shows array type for that field, as well as the correct array-related SQL + no `replication-orchestrator` errors in the sync logs.

**Comment by edgao** [comment]
+1 on not a blocker for release, but for the future - I think we should modify our sql to support converting arrays to string? submitted https://github.com/airbytehq/airbyte/issues/29524 for consideration
