### ISSUE TITLE
Concurrent Stripe: Measure the impact of resource and concurrency level allocation

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#29575]
## What
1. Tune the resource requirements and level of concurrency of the pre-release Stripe connector with concurrency to reach the limit of the test API (25 rps)

Suggestion: set really high limits so we can reach hit, then lower them to find the required specs.

2. Measure the impact of lowerering and increasing (memory, CPU, concurrency level) on the connector performance
3. Make an hypothesis on the required (memory, CPU, concurrency level) to reach 100 rps with a production account

We can monitor resource usage with the [kubernetes.memory.usage metric on datadog](https://app.datadoghq.com/metric/explorer?start=1692104073500&end=1692708873500&paused=false#N4Ig7glgJg5gpgFxALlAGwIYE8D2BXJVEADxQEYAaELcqyKBAC1pEbghkcLIF8qo4AMwgA7CAgg4RKUAiwAHOChASAtnADOcAE4RNIKtrgBHPJoQaUAbVBGN8qVoD6gnNtUZCKiOq279VKY6epbINiAiGOrKQdpYZAYgUJ4YThr42gDGSsgg6gi6mZaBZnHKGABuMMgA1ngARjoiiJoAdOqqbliteBoY8MAOUE6R6sjpeFlwALQaAMwAVDwgPAC6VK7ueJih4Zuq2xgxpfEr6yAacmg5oPIY1wgIOUk4ME6ZOxoQmYloonBOOSKZTpP5QX7-Jz0JjKERuDxoFb8CD2TBYQEKZ5-ZpnHh8C7yP4IADCUmEMBQIm2aB4QA).

- We should also add logs to the connector to track the number of requests per second.
- We should make sure to log a warning if we hit the Stripe rate limit

## Acceptance criteria
Either:
- [ ] The minimum (memory, CPU, concurrency level) to saturate the limit on a test account are identified
- [ ] We have a resource allocation matrix describing the expected throughput with various resource allocation (tracking mem, cpu, number of workers)
- [ ] We have an hypothesis for the minimum (memory, CPU, concurrency level) required to reach 100 rps on a production account
OR
- [ ] A follow up investigation issue is created to understand and resolve the bottlenecks in the concurrent Stripe connector
- [ ] A follow issue is created to decide on best resource allocation on cloud + document recommendations for OSS
- [ ] We should timebox this issue: if we cannot get all the information we wanted, we should still strive to make a call on how to move forward

**Comment by girarda** [comment]
Note: if the stripe connector is not already saturating the cpu its allocated, introducing concurrency should save costs

**Comment by maxi297** [comment]
**Witness**

_Description_
This is the current state before enabling concurrency. As we can see, the resource usage is very low compare to what is allocated.

![image](https://github.com/airbytehq/airbyte/assets/3360483/9b61870a-803e-4ce8-93ae-f982f1446d05)
[Image source](https://app.datadoghq.com/dashboard/b2x-7y7-izf/maxime-sandbox?refresh_mode=paused&tpl_var_ab_connection_id%5B0%5D=6aed3b3f-36b9-4fcf-abf9-4ceedc420f8d&from_ts=1698319184822&to_ts=1698324358585&live=false)

**Comment by maxi297** [comment]
**Enabling concurrency**

_Description_
We want to see the impact of enabling concurrency on the resources. In order to do that, we will set a connection full refresh streams and with i.e. `max_workers = 2`.

_Hypothesis_
We should see the resource usage up for both. With the little information we have, it's not clear of how much though.

_Results_

![image](https://github.com/airbytehq/airbyte/assets/3360483/96a28dcb-e907-40c9-9a2b-fd930e641121)
[Image source](https://app.datadoghq.com/dashboard/b2x-7y7-izf/maxime-sandbox?refresh_mode=paused&tpl_var_ab_connection_id%5B0%5D=bf6ede5c-e346-4489-a965-63a381eb3c30&from_ts=1698293899797&to_ts=1698302198102&live=false)

**Comment by maxi297** [comment]
**Cranking up concurrency**

_Description_
Even if we hit the max CPU using `max_workers = 2`, we could still be able to have some gain by increasing max_workers to 5.

_Hypothesis_
There a a little bit of gap between the CPU usage and the CPU limit of `max_workers = 2` so we might still get improved performances.

_Results_
Note: In order to run this test, our test account was not enough as the number of operations is much lower and we would hit the rate limit. As the rate limit issue is still not available for us to throttle properly, we switched to the prod account. We haven't seen any 429 with `max_workers = 5`
Note 2: Using `max_workers = 2` would trigger the log message `Main thread is sleeping because the task queue is full...` very often. Using `max_workers = 5`, this log is nowhere to be seen which might indicate that the main thread might become the bottleneck.

CPU doesn't seem to be utilized more. It seems like there are only two spikes where utilization is high. Correlating with the logs:
* The first spike aligns with the start of checkout_sessions_line_items but the spike peaked down before the end of the stream as it finished at 14:12:32 while the spike peaked down at ~14:08:20.
* The second spike aligns with the start of setup_attempts but as for checkout_sessions_line_items, it peaked before the end.


| Metric      | Change | Note  | 
|-----------|-----|---|
| CPU          | x25 | We are hitting the CPU limit already | 
| Memory    |  x5   | Memory was slowly creeping up  | 
| Sync time |  ?   | I have to set up a new witness sync to compare based on the prod account vs the test account | 

![image](https://github.com/airbytehq/airbyte/assets/3360483/0ade6049-d8ab-4e62-9a94-e3c2e48e5164)
[Image source](https://app.datadoghq.com/dashboard/b2x-7y7-izf/maxime-sandbox?refresh_mode=paused&tpl_var_ab_connection_id%5B0%5D=3d4de376-7f2a-4548-a92f-067c6fa81372&from_ts=1698343057525&to_ts=1698344521932&live=false)

**Comment by maxi297** [comment]
**More resources**

_Description_
Given there does not seem to be a lot of improvement in terms of time sync and that the CPU usage is reaching the limit, we can assume that more resources would mean faster syncs. Let's update the resource_requirements to `{"cpu_limit": "5", "cpu_request": "5", "memory_limit": "1000Mi", "memory_request": "1000Mi"}`

_Hypothesis_
CPU usage will go above 1 core and hence sync will be faster

_Results_


| Metric      | Change | Note  | 
|-----------|-----|---|
| CPU          | x25 | We are hitting the CPU limit already | 
| Memory    |  x5   | Memory was slowly creeping up  | 
| Sync time |  x1.85   | I changed from a test connection that had only streams with data to a connection that had all streams enabled hence why the change is not that notable compare to `max_workers = 2` | 

![image](https://github.com/airbytehq/airbyte/assets/3360483/0ade6049-d8ab-4e62-9a94-e3c2e48e5164)
[Image source](https://app.datadoghq.com/dashboard/b2x-7y7-izf/maxime-sandbox?refresh_mode=paused&tpl_var_ab_connection_id%5B0%5D=3d4de376-7f2a-4548-a92f-067c6fa81372&from_ts=1698343057525&to_ts=1698344521932&live=false)

**Comment by maxi297** [comment]
**Cranking up concurrency (again)**

_Description_
Even if we hit the max CPU using `max_workers = 2` we still had faster sync with `max_workers = 5`, so why not continue to crank up the number of workers? 

_Hypothesis_
We should get better performances with max_workers until we hit a plateau. This plateau seems to be only identifiable empirically. Let's arbitrarily use `max_workers = 20`.

_Results_
| max_workers  | sync time | cpu limit (assuming this doesn't change the performance much)
|----|---------|----|
| 1  | 43m 26s | 1 |
| 5  | 21m 27s | 5 |
| 20 | 17m 32s | 5 |

**Comment by maxi297** [comment]
**Trying to profile for more information**

_Profiling using 2 max_workers_
![austin-output_2-max-workers](https://github.com/airbytehq/airbyte/assets/3360483/2adce77f-89ea-483f-8505-0e77e1a6264d)

_Profiling using 5 max_workers_
![austin-output_5-max-workers](https://github.com/airbytehq/airbyte/assets/3360483/e54ebe0b-9416-448c-8e06-24fcbf756130)

We can see that we seem to lose a lot of time in thread that are not directly related to our code (9 blocks when max_workers = 2 and 12 blocks when max_workers = 5 which leads to believe that there would always be 7 blocks independently of the number of threads and one for each thread after). Those all link to [blocking on a queue](https://github.com/python/cpython/blob/43a6e4fa4934fcc0cbd83f7f3dc1b23a5f79f24b/Lib/concurrent/futures/thread.py#L81). Excluding idle using py-spy, we can see that those thread are idle.

![profile-with-idle](https://github.com/airbytehq/airbyte/assets/3360483/9082c7ce-8572-4714-ac95-ded510aa396f)
![profile-without-idle](https://github.com/airbytehq/airbyte/assets/3360483/88599b54-bc2d-47c0-a465-152707db8736)

We're not very clear as to if those idle threads impact sync time or not.

**Comment by maxi297** [comment]
Conclusions before first round of review
* There is no apparent bottleneck apart from the CPU that cap the limit of 1 core. This limit can't be increase because Python run single core because of the GIL. That being said, adding workers still improve the performance. This could make sense as there is more change of having at least one response when you have more workers processing requests.
* For the main thread `_wait_while_too_many_pending_futures` is taking most of the time. However, removing the call to this method gives a very small improvement i.e. ~2%. The longer/bigger the sync is, the bigger this improvement will be though. We should probably change how we manage our futures because the memory usage will grow indefinitely.
* We seem to be spending a lot of resource on idle threads. However, it's hard to understand that those threads are and what is the actual impact on the execution time.
* We could not have better performance above 10 workers as we would get the message `Connection pool is full, discarding connection: api.stripe.com. Connection pool size: 10`. [Increasing the pool size to 100 and removing the `_wait_while_too_many_pending_futures`](https://cloud.airbyte.com/workspaces/8ba9a84d-ef49-41fb-9aaa-9f75fb0f351e/connections/3d4de376-7f2a-4548-a92f-067c6fa81372/job-history#5551093::0), we did saturate the API rate limit during during stream `setup_attempts`. I killed the sync just in case this might impact prod but the sync didn't seem much faster that [with the pool size to 10](https://cloud.airbyte.com/workspaces/8ba9a84d-ef49-41fb-9aaa-9f75fb0f351e/connections/3d4de376-7f2a-4548-a92f-067c6fa81372/job-history#5546843::0)

**Comment by maxi297** [comment]
Closing the issue was a misclick

**Comment by maxi297** [comment]
Possible next steps (also documented [here](https://airbytehq-team.slack.com/archives/C02TL38U5L7/p1698859425518889):
- spike multi processes
- run multiple streams in parallel
- update the connection pools
- update the wait for pending future tasks
- use smaller slices
- make sure streams that can use stream slices use them
- measure how much time the main thread is spent waiting on the queue.get (it looks like a lot from Maxime's flamegraph)
- Could it help having better CPU? Like not increasing the limit (number of cores) but having a different type of CPU that is more performant

**Comment by maxi297** [comment]
Follow up link: 
* https://github.com/airbytehq/airbyte/issues/31590
* https://github.com/airbytehq/airbyte/issues/32070
* https://github.com/airbytehq/airbyte/issues/32072

**Comment by maxi297** [comment]
**More slices!!!**

_Description_
Creating more slices will create more partition to process. What would happen if we were to create one partition per 30 days instead of one per year? 

In order to do that, I used the max_workers=20 with the connection pool size that was limiting the previous execution from having 429.

_Hypothesis_
Having more partitions being generated would mean that there would be more chance for a worker to pick something up. This might reduce the sync time as worker would sleep less between run

_Results_
Surprisingly, we hit rate limiting on [this run](https://cloud.airbyte.com/workspaces/8ba9a84d-ef49-41fb-9aaa-9f75fb0f351e/connections/3d4de376-7f2a-4548-a92f-067c6fa81372/job-history#5677668::0) so it's hard to say if it would have been faster or not. What we can say is that we seem to be using more CPU. This is expected as we perform more requests (12x more to be precise). 

![image](https://github.com/airbytehq/airbyte/assets/3360483/c6c27e1d-d412-46d3-a29a-d4154100e0b1)
https://app.datadoghq.com/dashboard/b2x-7y7-izf/concurrent-cdk---stripe-resource-usage?refresh_mode=sliding&tpl_var_ab_connection_id%5B0%5D=3d4de376-7f2a-4548-a92f-067c6fa81372&from_ts=1698862763755&to_ts=1698866363753&live=true

_Conclusion_
* We can probably saturate the API with 10 max_workers
* Inconclusive to know if it would be faster but considering the logs around where it happen, it would have been 7min 26 seconds in for slices of one year while it would have been 8min 12 seconds for montly slices

**Comment by techieshark** [comment]
@maxi297 thanks for sharing your research here. I asked a question in Slack [here](https://airbytehq.slack.com/archives/C01AHCD885S/p1724216310118299) that took me here.

The AI support bot suggested that narrowing the time window from 365 days to e.g. 30 days (creating more slices) would speed things up.  

I'm not entirely convinced that's happening. 

In my test, I pulled all Stripe Charges from a test account:

| Data request time increment in days | Size | Records transferred | Time |
| ------------------------------------ | ---- | -------------------- | ----- |
| 365 | 153.18 MB | 54,780 records loaded | 36m 19s |
| 30 | 153.18 MB |  54,780 records loaded | 36m 17s |

**I would have expected the time slice option to be about 12x faster, but it was only 2 seconds faster.**

From below, you can see that there is 3-4 seconds between each request to Stripe:

![image](https://github.com/user-attachments/assets/8e89aad8-e4eb-4f77-bdb7-663053a5c4ba)
 
and these are the settings I used:
![image](https://github.com/user-attachments/assets/c261a3ba-d9ad-441b-8819-3432c6ec2476)

One might think each of the 10 workers would be assigned a time window to work with, but seems that's not happening (if it were, 10 subsequent requests in Stripe would each have a different time window, but that did not appear to be the case when I looked into them).

**Comment by girarda** [comment]
@maxi297 is there a reason to gate the concurrency to 
- Events
- CreatedCursorIncrementalStripeStream
?

the charges stream doesn't leverage concurrency today because it's an `IncrementalStripeStream`. Is the issue that it uses the Events stream in subsequent syncs?

If that's the case, I think the solution would be to use concurrency in the initial sync, but not in the follow up

**Comment by techieshark** [comment]
@girarda thanks for the follow up; not sure if this helps at all but I just googled `IncrementalStripeStream` (since I am still quite unfamiliar with the codebase) and ran across [this](https://github.com/airbytehq/airbyte/issues/32057):

> For now, we won't tackle:
> Stream using `IncrementalStripeStream` as they are affected by https://github.com/airbytehq/airbyte-internal-issues/issues/2368 which will change the cursor and hence incremental syncs

(but note that link is to an internal repo so it's a bit of a dead end in terms of my understanding of the issue)
