### ISSUE TITLE
New Source: Youtube Analytics

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#2970]
## Tell us about the new integration you’d like to have
https://developers.google.com/youtube/reporting/v1/reports 

## Describe the alternative you are considering or using

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368102600976) by [Unito](https://www.unito.io)

**Comment by vitaliizazmic** [comment]
## Integration Vetting
The integration hasn't already been vetted

**Webhook-based? (no/partially/yes)**
No

**Available authentication modes (API key/Oauth/other)**
The YouTube Reporting API and YouTube Analytics API support the [OAuth 2.0 protocol](https://developers.google.com/youtube/reporting/guides/authorization) for authorizing access to private user data. 

The YouTube Reporting API and YouTube Analytics API **do not support service account flow**. Since there is no way to link a Service Account to a YouTube account, attempts to authorize requests with this flow will generate an error.

The YouTube Reporting and YouTube Analytics APIs

- [server-side flow](https://developers.google.com/youtube/reporting/guides/authorization/server-side-web-apps)
- [client-side flow](https://developers.google.com/youtube/reporting/guides/authorization/client-side-web-apps)
- [installed application flow](https://developers.google.com/youtube/reporting/guides/authorization/installed-apps)

All available method require user's consent. 

**Creating an account**
We can use existing account. 

**How to populate the account with data?**
Youtube Data resources can be populated via UI. Youtube Reporting resources is analytics data for a channel or content owner. 

**Available streams for sync**

Youtube Reporting API resources

- [jobs](https://developers.google.com/youtube/reporting/v1/reference/rest/v1/jobs/list)
- [reports](https://developers.google.com/youtube/reporting/v1/reference/rest/v1/jobs.reports/list)
- [report_types](https://developers.google.com/youtube/reporting/v1/reference/rest/v1/reportTypes/list)
- [channel_reports](https://developers.google.com/youtube/reporting/v1/reports/channel_reports)
- [content_owner_reports](https://developers.google.com/youtube/reporting/v1/reports/content_owner_reports)

Youtube Data API resources

- [channels](https://developers.google.com/youtube/v3/docs/channels/list)
- [playlists](https://developers.google.com/youtube/v3/docs/playlists/list)
- [playlist_items](https://developers.google.com/youtube/v3/docs/playlistItems/list)
- [videos](https://developers.google.com/youtube/v3/docs/videos/list)

**Integration supports incremental sync?**
Yes

**Other information/blockers**
There is Singer [tap-youtube-analytics](https://developers.google.com/youtube/reporting/guides/authorization)

**Comment by rparrapy** [comment]
I'm interested in this connector. What's the status? If credentials are needed I have access to some accounts.
