### ISSUE TITLE
CDK: Let other streams run even if a stream fails

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#29882]
## What
The CDK already supports per-stream status.

We could leverage the feature to only sync a failing stream and let the others finish instead of failing the full stream.

## How
When iterating over the streams in the [AbstractSource](https://github.com/airbytehq/airbyte/blob/master/airbyte-cdk/python/airbyte_cdk/sources/abstract_source.py#L103), keep track of all exceptions raised in a list instead of raising them.

After running all the sync, check if there were any exceptions.
If any exception was an internal failure, raise a system failure
If all exceptions were config errors, raise a config error
If there were no exception, success!

## Acceptance Criteria
- [ ] CDK sources attempts to sync all streams even if one fails early
- [ ] A follow up issue is created to do the same in concurrent cdk
- [ ] Klavyio to be updated with this change

**Comment by girarda** [comment]
grooming notes:
- the platform already shows syncs as partial success if only some streams succeeded
- interesting cases:
  -  salesforce: bails on a 429
- we'll gate this solution and only enable it for klavyio as a first step
- idea: can we enable this for new connectors? @maxi297 to check how the source can access the metadata
- unclear what grouped errors will look like for sentry reporting
  - @girarda to run a test and see what grouped errors sent to sentry would look like 

plan:
- gate the feature for klavyio
- write a proposal for a longer-plan
  -  to flesh out: how to surface multiple exceptions from the connector

**Comment by maxi297** [comment]
Regarding using the metadata to enable this:
* Ben mentions there is no reliable "first release date" in the metadata. I didn't dig if it was because it wasn't maintain in the past of if even today the values are flaky (I suspect the former which wouldn't be a problem for us)
* Ben seemed very reluctant. I think is view is "is it worth the added complexity?" For the source developers, it seem nice to me to avoid breaking change while allowing other to benefit from the new nice feature

Conclusion: we would need to build a strong case and advocate for it. We should re-assess this in our team and push for it if it's what we want. [Discussion link](https://airbytehq-team.slack.com/archives/C03VDJ4FMJB/p1701441683937259)
