### ISSUE TITLE
OSS Settings page makes more sense with default versions [triage]

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#29907]
We are in traige - we are just correcting lies, we are not making the workflow better.  We are focusing on copy changes.

* Change "current version" to "default version"
* Add some copy under "manage your connectors" explaining that changes on this page will update non-breaking changes, but not breaking changes.  You need to update your syncs 1-by-1...
  * This should be a callout 
* "Version Changed" success message is hard to see - also make this a toast or modal.  Then, "upgrade all" could be "11 connectors are updated"
   * This an API update to return the number of effected connectors
   * 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaWRGIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1a900d13ae8ccec525d36fbdbcb2f27186068094/Screenshot%202023-08-28%20at%2012.12.39%20PM.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaVJGIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c3a9749c8ba60251aea5480de9b50efffee23e4c/Untitled.png)

**Comment by erohmensing** [comment]
That PR also added toasts on the upgrade like we wanted to add: 
> Gets rid of the covered-up error message and the weird Upgraded! button text by adding onSuccess and onError toasts to the useUpdateAllConnectors hook

**Comment by erohmensing** [comment]
I think what is left to implement is 
1. Change "current version" to "default version"
2. Add some copy under "manager your connectors" explaining that changes on this page will update non-breaking changes, but not breaking changes. You need to update your syncs 1-by-1...
  * This should be a callout
3. Then, "upgrade all" success toast should list number of updated connectors e.g. "11 connectors are updated"

**Comment by lmossman** [comment]
@erohmensing 
- My PR actually did add toasts for single connector upgrades as well - the screenshots in the PR were just a bit outdated from the behavior that was actually implemented in the end
- You can use the <Message> component for the callout under "Manage your connectors" - just make sure to put the text in the `en.json` file and point to that with react-intl like we do in other places!
- Yeah since upgrade all processes each connector individually, should be fairly straightforward to get the count of connectors being updated - you can pass that count into the string from the `en.json` by using an intl parameter and handle the plural/singular cases there. For example:
  - [Here](https://github.com/airbytehq/airbyte-platform-internal/blob/2687021b0f69dc2ad25bf90de98b6d6606283c26/oss/airbyte-webapp/src/locales/en.json#L843) is where we define the string in en.json, using the syntax `{count, plural, one {# connection} other {# connections}}`
  - The value for `count` is passed in [here](https://github.com/airbytehq/airbyte-platform-internal/blob/2687021b0f69dc2ad25bf90de98b6d6606283c26/oss/airbyte-webapp/src/components/connector/BreakingChangeBanner.tsx#L211)
  - This means if `count` is 1, then the string will insert `1 connection`. If it is anything else, it will insert `X connections`. So you can do something like this to properly communicate the number of connectors updated
