### ISSUE TITLE
URL-encode every special character in Query Parameter values

### ISSUE THREAD

**Issue by lmossman** [airbytehq/airbyte#29918]
## Context

A user reported [on slack](https://airbytehq-team.slack.com/archives/C027KKE4BCZ/p1692969191791459) that they need  to be able to fully URL-encode a JSON object into a query parameter value in order to integrate with their desired API (SAP Ariba)

Currently, if a query parameter value is set to a JSON object, low-code CDK seems to just pull out each of the keys of the top-level object and set those as an array of values on the query parameter.

For example, setting a query parameter `key` to `filters` and the `value` to `{"updatedDateFrom":"2023-08-20T00:00:00Z","updatedDateTo":"2023-08-20T23:59:59Z"}` results in the low-code CDK making a request with the following parameters:
```
 "parameters": {
    "filters": [
      "updatedDateFrom",
      "updatedDateTo"
    ]
  },
```
which translates to a url-encoded form of `filters=updatedDateFrom&filters=updatedDateTo`

Instead, the low-code CDK should url-encode every special character in the input value, and set that whole url-encoded string as the value on the query parameter. So the above example should be encoded to
```
filters=%7B%22updatedDateFrom%22:%222023-08-23T00:00:00Z%22,%22updatedDateTo%22:%222023-08-24T00:00:00Z%22%7D
```

## Acceptance Criteria
- For query parameters _or_ request_body_data in which the value is an object, apply the following logic to each of the parameter/object key-value pairs when url-encoding:
  - If a value is a list, the key should be duplicated for each element in the list, with the value set to that element. For example, if the parameter key is `test` and the value is `[a, b, c]`, then there should be 3 parameters set: `test=a&test=b&test=c`
  - Otherwise (i.e. value is an object, string, number, etc), just treat the value as a string and url-encode all [unsupported characters](https://www.freecodecamp.org/news/url-encoded-characters-reference) when setting it on the url. For example, if the key is `filters` and the value is `{"updatedDateFrom":"2023-08-20T00:00:00Z","updatedDateTo":"2023-08-20T23:59:59Z"}`, then the following should be set on the url: `filters=%7B%22updatedDateFrom%22:%222023-08-23T00:00:00Z%22,%22updatedDateTo%22:%222023-08-24T00:00:00Z%22%7D`
- For request headers:
  - If the value is a list, then set that list value directly as the header value. For example, if the header key is `test` and the value is `[a, b, c]`, then the header should look like `test: ["a", "b", "c"]` 
  - Otherwise (i.e. value is an object, string, number, etc), just treat the value as a string and set the raw string value as the header value. For example, if the header key is `filters` and the value is `{"updatedDateFrom":"2023-08-20T00:00:00Z","updatedDateTo":"2023-08-20T23:59:59Z"}`, then the header should look like `filters: "{\"updatedDateFrom\":\"2023-08-20T00:00:00Z\",\"updatedDateTo\":\"2023-08-20T23:59:59Z\"}"`

**Comment by lmossman** [comment]
Grooming notes:
- When we parse the manifest, we are doing something weird where we are just pulling the keys out of the object
  - Maybe caused by Jinja? 
- Behavior is unexpected
- The query params should not be treated as a Map of string -> anything, they should be Map of string -> string
- Leave list values as they are treated today, only treat anything else as a raw string which should be url-encoded
- @maxi297 to enumerate the cases of how list/dictionary values are url-encoded to inform how breaking this change is

**Comment by maxi297** [comment]
The issue is caused by [this line](https://github.com/airbytehq/airbyte/blob/53ddaaf2c26bac35eb0c6c627fba55606e2a4712/airbyte-cdk/python/airbyte_cdk/sources/declarative/interpolation/jinja.py#L77) were we interpret the result of interpolation as Python. This is useful in some cases like JSON body and `ListPartitionRouter.values = {{ config["pokemons"] }}` as Jinja interpolation would return strings and not the object type we expect. However, this is an issue where we would need the result to be a string (like this specific case)

Since the "clean" solution to update the interpolation interfaces which is costly, the proposed solution is to add this to the HttpRequester:
```
        for k, v in options.items():
            if not isinstance(v, [str, list]):
                options[k] = str(v)
```

This should be applied to header as well as the logic should be the same. Also update return type of `HttpRequester._request_headers` and `HttpRequester._request_params` to `Mapping[str, Union[str, List[str]]]`

**Comment by clnoll** [comment]
@lmossman after looking into this and discussing with @maxi297 I feel like the ideal course of action would be to have the user specify whether they want a value to be unpacked as separate query params or treated as a list. This would avoid the BE having to try to handle ambiguous situations that are unlikely to be accurate for all users. We'd probably want to offer something similar for the request body and headers.

If we didn't have to handle the interpolation cases like `{{ config["aaa"] }}`, the FE could disambiguate list values from unpacked-list values by allowing users to have multiple entries for the same key in the Query Parameters form field; the FE would send a list of `(k,v)` tuples to the BE instead of an object mapping k:v (in this case all v's would be treated as strings). This is aligned with how query parameters are handled, so feels like a good pattern.

But, we'd still have to decide how to handle cases like `{{ config["aaa"] }}`. As long as `config["aaa"]` is not a list we'd be fine to turn its value into a string on the BE for the purpose of query params, but if it is a list we'll need to handle it with the legacy behavior (unpacking the values as separate query params) for existing connections. To avoid any ambiguity going forward, we could add a checkbox (or macro?) in the UI which indicates whether the value should be unpacked as separate query params if the value is a list. And if we're adding that for the `{{ config["aaa"] }}` case, we might as well continue to allow users to input raw lists and use it for those, too.

**Comment by lmossman** [comment]
@clnoll @maxi297 We could add a checkbox if we must, but I'd like to avoid that if possible to avoid adding another decision on the user.

My feeling is that because arrays are natively supported in query params through the "unpacking" logic (i.e. `key=1&key=2&key=3`), and objects are _not_ natively supported, it feels fairly unambiguous to me to have our logic be:
- If the value of a query param has the structure of a list (i.e. starts with `[`, ends with `]`, and the elements are comma-separated), then we treat it as a list and unpack it
- Otherwise, we treat it as a string and url-encode it

When it comes to interpolated values, we should apply the interpolation logic _before_ we apply the above logic. So if `{{ config["aaa"] }} resolves to `[1, 2, 3]`, then we treat it as a list. If it resolves to some non-list value, we url-encode it.

This feels fairly unambiguous to me, and we could always add a note to the tooltip/docs explaining this behavior.

What do you think?

**Comment by clnoll** [comment]
@lmossman agree that the checkbox would be ugly - I think just having the convention that you describe documented in the tooltip should work!
