### ISSUE TITLE
TZ env variable is an inadvertent dependency of the Airbyte build

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#3010]
## Current Behavior
```
Hi
I am building Airbyte using " ./gradlew build " command but it gave me below error
"OracleSourceTest > testReadSuccess() FAILED
    java.sql.SQLException: Cannot create PoolableConnectionFactory (ORA-00604: error occurred at recursive SQL level 1
    ORA-01882: timezone region not found"
Any solution to resolve this error ?
```

* `./gradlew build` now depends on the host machine having `TZ=UTC` as an env variable. we should not require this and should have the build system handle setting this internally.
* `CORE_ONLY=1 ./gradlew build` seems to be running oracle tests. I haven't been able to reproduce this when running `--dry-run`

convo: https://airbytehq.slack.com/archives/C019WEENQRM/p1618931467288000

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368103202282) by [Unito](https://www.unito.io)

**Comment by blotouta2** [comment]
Thanks @cgardens for considering this issue on priority

**Comment by cgardens** [comment]
@marcosmarxm i was scanning back through this one. I'm a bit confused under which circumstance a user needs the `TZ` env variable to be set. for instance, I don't have it set on my machine. is it clear to you when this happens?

**Comment by marcosmarxm** [comment]
@cgardens the problem happened in the Github CI instance. Probably because how the instance use Java. 
Maybe adding this to the Oracle Source could solve the problem.
https://github.com/airbytehq/airbyte/blob/3dd14e2c882c04972df4da067efac406b830fbac/airbyte-integrations/connectors/destination-oracle/src/main/java/io/airbyte/integrations/destination/oracle/OracleDestination.java#L49

**Comment by evantahler** [comment]
Closing, as this doesn't seem to be an in-progress issue
