### ISSUE TITLE
New source: Square

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#3013]
## Tell us about the new integration you’d like to have
https://developer.squareup.com/us/en

## Describe the context around this new integration
* Which team in your company wants this integration, what for? This helps us understand the use case.
* How often do you want to run syncs?
* If this is an API source connector, which entities/endpoints do you need supported?

## Describe the alternative you are considering or using
What are you considering doing if you don’t have this integration through Airbyte?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368103250337) by [Unito](https://www.unito.io)

**Comment by yevhenii-ldv** [comment]
## Integration Vetting

**Webhook-based? (no/partially/yes)**

no

**Available authentication modes (API key/Oauth/other)**

[Application and Access Token (different for Sandbox and Production)](https://developer.squareup.com/docs/get-started)

**Creating an account**

I tried to register a new account using the company email, but I got the following error:
`The email address you entered is already in use.`
@sherifnada, I think that the account already exists, in which case it must be added to Lastpass.

**How to populate the account with data?**

Can be using API and UI to populate data in both the Sandbox and the Production account.

**Available streams for sync**

- Items
- Categories
- Discounts
- Taxes
- Employees
- Locations
- BankAccounts
- Refunds
- Payments
- ModifierLists
- Inventories
- Orders
- Roles
- Shifts
- CashDrawerShifts
- Settlements
- Customers

**Integration supports incremental sync?**

some

**Other information/blockers**

Python [SDK](https://developer.squareup.com/docs/sdks/python)
Singer [Tap](https://github.com/singer-io/tap-square)

**Comment by TymoshokDmytro** [comment]
### STREAMS DONE 

- Items -> [Incremental, Full_Refresh]
- Categories -> [Incremental, Full_Refresh]
- Discounts -> [Incremental, Full_Refresh]
- Taxes -> [Incremental, Full_Refresh]
- Locations -> [Full_Refresh]

### STREAMS IN PROGRESS

- Employees -> replaced with new V2 API [Team Members](https://developer.squareup.com/reference/square_2021-06-16/team-api/search-team-members)
- Roles -> replaced with new V2 API [List Team Member Wages](https://developer.squareup.com/explorer/square/labor-api/list-team-member-wages) 
- Orders -> Will take a little more time due to the hard data populating process
- Refunds 
- Payments
- ModifierLists
- Shifts
- Customers

### SKIPPING

- CashDrawerShifts - Unable to populate sandbox with data
- BankAccounts - Unable to populate sandbox with data
- CashDrawerShifts - Unable to populate sandbox with data
- Settlements - [Deprecated V1 API](https://developer.squareup.com/reference/square/settlements-api/v1-list-settlements)
- Inventories - Unable to list inventories. They can be accessed only for certain item by putting catalog_object_id in the url path ([Link](https://developer.squareup.com/explorer/square/inventory-api/retrieve-inventory-count))
