### ISSUE TITLE
Allow spec.jsons with no properties

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#3029]
A user reported wanting to create a source that doesn't have any configuration properties. However, his connector didn't function in the UI because the UI expected some properties in spec.json

He got the error 

```
{"message":"The received object did not pass validation","details":"property: webBackendCreateSource.arg0.connectionConfiguration message: must not be null invalid value: null"}
```

We should make it not required to have params in the spec.json

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368227056333) by [Unito](https://www.unito.io)

**Comment by cgardens** [comment]
I think this is just a FE thing. I think it's reasonable that for these fields the API does not accept null. It expects an empty object. My guess is the UI sometimes in these cases sends a null instead of an empty object.

@Jamakase can you double check that in the case where in `sources/create` that when `SourceConfiguration` is empty that we actually send an empty object from the FE instead of null? the same for `destinations/create` and `DestinationConfiguration`
