### ISSUE TITLE
Add another weekly run for 100 level connectors

### ISSUE THREAD

**Issue by bnchrch** [airbytehq/airbyte#30441]
## Question
Weeklys are now running successfully on ab_internal.ql > 100

Is it worth while to have another job testing ab_internal.ql = 100?

**Comment by evantahler** [comment]
Grooming:
* we want to know if connectors are failing and when that started when you work on them... but this is only useful if there is a high test frequency 
* Maybe knowing if the connector is green doesn't matter since you can now run all tests easily on master with airbyte-ci
* If community connectors aren't maintained by us... why care about the tests?

Decision: let us continue to not test `ql=100` connectors
