### ISSUE TITLE
Ability to update Workspace notification email from the UI

### ISSUE THREAD

**Issue by cpdeethree** [airbytehq/airbyte#30490]
### What area the feature impact?

Airbyte Platform

### Revelant Information

[Slack Context](https://airbytehq-team.slack.com/archives/C03GD9SV36E/p1694722132926739)

Currently there is no way to update the email recipient of notifications of workspaces from the UI. It must manually be done via a backend operation. This ticket is to expose the ability to do so via the front end.

According to @pmossman the appropriate PATCH style endpoint for this field should already be exposed in the backend to perform this operation.

The request is twofold:

1. Update the language on the notifications page to disambiguate workspace owner from workspace notification recipient. These are actually two different fields in the backend and saying it's always the owner (even though right now in practice it is, unless it's been changed manually in the backend) is not entirely correct.

2. Make the workspace notification email editable. This is separate field from the workspace user that owns the workspace, and unlike that user, which is an actual Airbyte user, this is just an arbitrary email string not tied to anything else.

![Screenshot 2023-09-15 at 12 07 09 PM](https://github.com/airbytehq/airbyte/assets/10550441/ec1b249f-0f48-43b4-9175-c2a27b98fa95)

**Comment by josephkmh** [comment]
Refining notes:
- `workspace.email` is used in some downstream data (e.g. associating workspaces with salesforce records), but this can probably be solved otherwise. @nataliekwong will check with data team
- OK to let users in a workspace change `workspace.email`
- Notification work is not planned for Q4, so larger backend changes will not be done (e.g. multiple recipients)
- @josephkmh to double check that changing a workspace email won't break credit purchasing somehow

**Comment by nataliekwong** [comment]
Just FYI, sharing for additional context.

We got an email from a Cloud user today thanking us for proactively emailing them about their connections being turned off, and they had no idea because the breaking change email went to the existing workspace email and they didn't get it. Since we use this email for breaking change notifications as well, it's important that we enable users to adjust it so they will be sure to get these notifications!
