### ISSUE TITLE
[destination-snowflake] length of synced columns are set to max-value

### ISSUE THREAD

**Issue by u-sahin** [airbytehq/airbyte#30825]
### Connector Name

destination-snowflake

### Connector Version

3.1.9

### What step the error happened?

During the sync

### Revelant information

Hi,

when synchronizing data to snowflake, the length of the variables are set to the maximum possible value
![image](https://github.com/airbytehq/airbyte/assets/16067962/c365a3a7-d00f-43bb-91d8-37db25a7e725)

As you can see the SESSION_SOURCE_DESC has a length of 1677216, which is the maximum for snowflake's varchar.
This happens for all of the tables which are synced to snowflake.

I can't seem to find an option to adjust this.
Also, it's irrelevant which source you have, as I have testet it with postgres and mssql.

### Contribute

- [ ] Yes, I want to contribute

**Comment by evantahler** [comment]
This is the expected behavior for now.  The [Airbyte type system](https://docs.airbyte.com/understanding-airbyte/supported-data-types) doesn't have string length as part of its properties - we just have 'string'.  So, in order not to loose/truncate any data, we create "TEXT" columns in Snowflake, which are varchar(max) under the hood.
