### ISSUE TITLE
Add support & test cases for connecting to Postgres via SSH tunnels

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#312]
## Tell us about the problem you're trying to solve
My Postgres Database lives in a different VPC than the one in which Airbyte is running. I'd like to connect to it via an SSH tunnel. 

## Proposed solution
Allow me to configure in the UI parameters for connecting to a database via an SSH tunnel

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368163354466) by [Unito](https://www.unito.io)

**Comment by hendrikjd** [comment]
Another use case for this - I wanted to try out Airbyte with a local deployment but am unable to connect to my postgres databases without the option for SSH tunnel connection.
If we do go with Airbyte it would likely run on the same VPC as our database so for us this isn't a "need to have" but would have been nice for testing.

**Comment by sherifnada** [comment]
@hendrikjd agreed -- we are working on this in July

**Comment by garrrychan** [comment]
+1 would be great so I can prototype from a local deployment of Airbyte and connect to a database on RDS.

**Comment by airbyte-jenny** [comment]
I'm currently working on this.  This comment is a list of subtasks involved in the code change, to make sure everything is covered and keep track of progress as I work.

Development
- [x] The spec.json for destination includes the ssh tunnel fields.
- [x] Set up the build to use apache mina sshd to support tunneling, and bouncycastle to support ssh keys.
- [x] Destination check() method can use ssh tunnel with both password auth and key auth.
- [ ] Modify tunneling code to be easily reusable.
- [ ] Destination write() method can use ssh tunnel.
- [ ] Data can move through to the destination while using an ssh tunnel.
- [ ] Test that destination write + normalization (separate ticket) is working.
- [ ] Source check() method can use ssh tunnel.
- [ ] Source read() method can use ssh tunnel.
- [ ] The spec.json for destination can be dynamically generated.
- [ ] The spec.json for source can be dynamically generated.
- [ ] Solve the bouncycastle jar version conflict with the kubernetes client-java.jar so that we don't have an invisible dependency conflict in the future.
- [ ] Do final adjustments to the bastion host sshd_config terraform to stabilize infra for long-term testing.

Testing
- [ ] Write integration test connectors and ensure they run well for postgresql.
- [ ] Document the pattern for testing these
- [ ] Create infra for mysql
- [ ] Create infra for MS SQL
- [ ] Write integration tests for mysql
- [ ] Write integration tests for MS SQL
- [ ] Identify any other databases we need to prioritize for tests and set them up likewise

Cleanup and Docs
- [ ] Write up docs on what the various parameters mean and how to configure a connector's ssh tunnel.
- [ ] Write up docs on how to create and configure a bastion host, at a conceptual level, so users can create them on-site.
- [ ] Write up docs on the list of touch points in the code that are affected by ssh tunneling, so other developers can handle upgrades, fixes, etc.
