### ISSUE TITLE
Update Connector OC Docs to improve the knowledge share of how to investiage and debug connectors

### ISSUE THREAD

**Issue by bnchrch** [airbytehq/airbyte#31318]
## Problem
Debugging Connectors is difficult, and there is no one place to learn how to debug connectors.

## Solution
Create the beginning of our "Debugging a Connector" Knowledge base by providing debugging tutorials for the most common questions a connector OC engineer might ask.

A WIP document can be found here:
https://www.notion.so/WIP-How-to-debug-connector-failures-as-an-Oncall-Engineer-9b68834912a24c72893bcbc4f01e8c95?pvs=4

A successful solution is a document you could hand a first time connector OC engineer and have them debug any common connector failure.

**Comment by brianjlai** [comment]
@bnchrch updating where I'm at since i'll be on PTO for our next checkin

Just updating you on the progress of the doc writing. I've been adding things directly onto the notion doc over the past week https://www.notion.so/WIP-How-to-debug-connector-failures-as-an-Oncall-Engineer-9b68834912a24c72893bcbc4f01e8c95

I've roughly broken the sections into:
- Prerequisite access requests and checks
- Standard workflow
- Useful operations
- Common database queries
- Connector Dashboards
- Common failure modes

There are still some rough edges, but I tried to get a standard workflow going as a good starting off point and I'll continue to try to add things as they come to me. I think it'll also be valuable to get another connector ops/extensibility eyes to contribute since my process might differ from others.

**Comment by bazarnov** [comment]
@brianjlai @bnchrch @oustynova 

Updated the Notion doc with the:
- validated the @brianjlai input, corrected and extended (thanks to @brianjlai for the initial input here):
   - Standard Workflow sections
   - Useful Operation
- added another section: [`Common Failure Troubleshooting Scenarios` ](https://www.notion.so/WIP-How-to-debug-connector-failures-as-an-Oncall-Engineer-9b68834912a24c72893bcbc4f01e8c95?pvs=4#45e3d38ef2464b60b51312891cf92309) and attempted to list the top-most scenarios to 
describe each category listed.

In order to maintain this doc as we expect it to be (useful and working doc for all on-call engineers) we need more questions asked from the part of TCS and the Airbyte OC:
- what are the common questions they face with typically when they see the on-call issue/request?
- what impacts them the most?
- what causing the problems when they are trying to troubleshoot?

All this info will help us to write meaningful guides for what to do with each category listed so far. 
the list of the categories will expand over time, the work is in progress.

**Comment by bnchrch** [comment]
Removing @brianjlai and adding @girarda as hes taking over finishing this issue.

Thanks to both of you

**Comment by girarda** [comment]
@bazarnov and I filled out the missing questions on the source side. Only remaining question to answer is how to connector to the temporal logs because I'm not able to authenticate to cloud.temporal.io

**Comment by girarda** [comment]
Filled out the missing pieces in the [docs](https://www.notion.so/How-to-debug-connector-failures-as-an-Oncall-Engineer-9b68834912a24c72893bcbc4f01e8c95).

The only lingering question I couldn't answer is how to access temporal logs because I wasn't able to access them
