### ISSUE TITLE
Sync on highlighting OC work

### ISSUE THREAD

**Issue by bnchrch** [airbytehq/airbyte#31313]

**Comment by evantahler** [comment]
Shared with managers:

:calendar: I want to share an observation and a request that came from this morning's [OC retro](https://docs.google.com/document/d/16yswZX4w480UQQB_1AQeE2UIXYBFhGfQAiy_5V75OW4/edit#heading=h.mr6ww4aepa6k).  As a reminder, the theory is that when folks are on call, they first help fix high-priority problems, [and then they work on making the OC tools and process better before doing sprint work](https://www.notion.so/On-Call-Handbook-cab412edc2e54941a0ce223ab909a43b#4a664c86c4184c5bafc7b353568a50be).  It turns out that this is [rarely happening](https://airbytehq-team.slack.com/archives/C03PLMF7UP5/p1697042619612459), and the cracks are starting to show in the OC process.  So, starting now, 
[@Ben Church (Airbyte)](https://airbytehq-team.slack.com/team/U04JXKJF19S)
 (our new OC Tzar) will be actively managing the OC epics ([1](https://app.zenhub.com/workspaces/retro-action-items-651457333272c6001c62b4fa/board), [2](https://app.zenhub.com/workspaces/connector-operations-6318ede5eda32e0010ef8566/board?epics=Z2lkOi8vcmFwdG9yL0VwaWMvMTAzNjEwMQ,Z2lkOi8vcmFwdG9yL0VwaWMvMTA3NjAxMw&filterLogic=any&repos=283046497,427539204,369021279,436587893,464581746,484145717,523319394,592970656,zh-Z2lkOi8vcmFwdG9yL1JlcG9zaXRvcnkvMTMzODY1MDY1&view=Z2lkOi8vcmFwdG9yL1NhdmVkVmlldy81NDA)) and assigning them to pairs of  OC engineers every 2 weeks.  There's a ton of low-hanging fruit we can do to make OC better (reports, sentry automations, templates and runbooks, etc).
As a reminder, that means that we EMs should account for this non-sprint-work time in our planning.  We should not pressure the folks on our team to do sprint work when they are on-call, and remind them of this expectation.  Tactically, when reviewing the[ quarterly roadmap](https://docs.google.com/spreadsheets/d/1ZLKxBX6Jo2t7Y1Q0H1M6nlZ8zATADC2HAYS4MqBbItE/edit#gid=802530690), I'd suggest that we turn weeks grey if there is one person working on an issue and they go-on call to hammer this expectation home.
We spend an inordinate amount of time on-call at this company... lets' make it suck a little less.
