### ISSUE TITLE
PoC support incremental for concurrent stripe

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#31401]
Goal: derisk the incremental part for concurrent CDK and the new interface

PoC on incremental using alex/stripe_concurrent_cdk. This should cover the following classes:
* IncrementalStripeStream
* LazySubStream
* UpdatedCursorIncrementalStripeLazySubStream

Identify risks and problem/potential solutions

**Comment by maxi297** [comment]
### Hypothesis
As the new stream interface does not require a different interface for full_refresh syncs and incremental syncs, we can keep `StreamFacade.supports_incremental` to false. This will avoid to change AbstractSource which currently manage the state (state management would have to be extracted from [here](https://github.com/airbytehq/airbyte/blob/2e7dfe8c408e34394522c1cf3b820999630fd306/airbyte-cdk/python/airbyte_cdk/sources/abstract_source.py#L256-L260) to avoid having the new code and AbstractSource handling states)

### Changes required
* `InMemoryMessageRepository` should allow for state messages as well
* Implement a ConcurrentCursor and call it in `ThreadBasedConcurrentStream` or `StreamPartition`

### Problems/Potential Solutions
* Calling `StreamFacade.supports_incremental` can be very confusing because even though it returns `False`, it can be incremental. Further changes to AbstractSource would need to consider this implementation detail when being updated which is very dangerous

### Conclusion
We prefer to have the implementations properly respecting the interface (i.e. if a Stream supports incremental, it should say so) than having less code change. We will therefore move the code that loops over slices from AbstractSource to core.Stream and have StreamFacade override this behavior

**Comment by maxi297** [comment]
### Hypothesis
Creating an object to manage state (called cursor) and having partition define cursor boundaries will allow us to simply call `self._cursor.close_partition(record_or_partition.partition)` when a partition is completely consumed.

### Changes required
* `InMemoryMessageRepository` should allow for state messages as well
* Have partition return cursor boundaries so that when the cursor wants to close the partition, we can update the state
* Implement a ConcurrentCursor.close_partition and call it in ThreadBasedConcurrentStream or StreamPartition

### Problems/Potential solutions
* For Stripe, this covers the full_refresh or first incremental sync just fine. However, during incremental syncs relying on a state, we have [this piece of code](https://github.com/airbytehq/airbyte/blob/c0a0b7930a8d88c64cef440cddced422d0409ca3/airbyte-integrations/connectors/source-stripe/source_stripe/streams.py#L363-L368) that explicitly disable the slices. This means that the state update does not always rely on the slices. In this case, it goes through [here in the AbstractSource](https://github.com/airbytehq/airbyte/blob/2e7dfe8c408e34394522c1cf3b820999630fd306/airbyte-cdk/python/airbyte_cdk/sources/abstract_source.py#L256-L260) and [here in Stripe](https://github.com/airbytehq/airbyte/blob/c0a0b7930a8d88c64cef440cddced422d0409ca3/airbyte-integrations/connectors/source-stripe/source_stripe/streams.py#L355-L361). This means that the state is updated based on the last record. 

### Conclusion
State can be manage in two ways:
* Using the slice upper boundary
* Using the latest record. This seems rather incomplete as the latest record might not be the most recent (logic that we will incorporate in the Concurrent CDK)

This leads to the following interface:
```
class Cursor(ABC):

    @abstractmethod
    def observe_record(self, record: Record, partition: Partition) -> None:
        raise NotImplementedError()

    @abstractmethod
    def close_partition(self, partition: Partition) -> None:
        raise NotImplementedError()
```

Given every records are in chronological order, checkpointing logic can be enabled and managed in the observe_record method. Else, the state will be updated in `close_partition`. There is [this code block](https://github.com/airbytehq/airbyte/blob/2e7dfe8c408e34394522c1cf3b820999630fd306/airbyte-cdk/python/airbyte_cdk/sources/abstract_source.py#L274-L277) that still needs to be figured out.
