### ISSUE TITLE
gradle: use cloudrepo proxies

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#31453]
We found that when gradle builds source-postgres, a significant amount of time is spend downloading jars and poms from random places on the internet, though mostly from Maven Central. Instead of doing this, let's instead connect to a proxy repo under our control. We'll see if this improves build times, at least it should make them more predictable.

**Comment by postamar** [comment]
I've experimented with the cloudrepo proxies and their performance and latency characteristics aren't suitable for our needs. The simple fact is that they slow down the build significantly instead of speeding it up. It's possible that the build just tries to download too many things. Whatever. Giving up on this for the time being.
