### ISSUE TITLE
Redshift V2 beta user testing

### ISSUE THREAD

**Issue by cynthiaxyin** [airbytehq/airbyte#31575]
Target 3 beta users and gather feedback before full rollout.

**Comment by pranasziaukas** [comment]
Expressing interest in participating.

**Comment by chrishronek** [comment]
Also interested in participating. We currently cannot ingest our HubSpot data into Redshift on the v1 destinations.

**Comment by cynthiaxyin** [comment]
@chrishronek Would you please fill out [this interest form](https://docs.google.com/forms/d/e/1FAIpQLSeb8OZDwwsNxqUwSItQvzgEXdaWG6_dDI4sS-avCHfCINkS3w/viewform)? We'll reach out in the coming weeks with more details. (@pranasziaukas I believe you've already filled this out - thanks!)

**Comment by chrishronek** [comment]
@cynthiaxyin, just filled it out. Thank you!

**Comment by cynthiaxyin** [comment]
@chrishronek Earlier you mentioned:
>We currently cannot ingest our HubSpot data into Redshift on the v1 destinations.

Curious if you could share more about what issues you were running into?

**Comment by chrishronek** [comment]
@cynthiaxyin I was getting an error related to [the limitations of the Redshift Destination](https://docs.airbyte.com/integrations/destinations/redshift?_gl=1*ec373o*_gcl_au*MTYzMTMyMzIwMi4xNjk5Mzk3OTUw#data-size-limitations), specifically around the SUPER data type. I had records that exceeded the size allowed by Redshift, so the sync was failing every time.

**Comment by evantahler** [comment]
Hi @chrishronek - 

Redshift Destinations V2 will not _immediately_ solve issues with records being to large to fit in a SUPER column (16mb).  Redshift, out of all the datawahouses, has the smallest size limitation on their JSON columns.  Airbyte always first writes all data as raw JSON to a single column (raw tables) and then expands and types that data into the final table.  We do this because this method is the most resilient when column data types changes via schema migrations.

Destinations V2 allows us to work on mitigating these size issues in a future project because now that our destination code manages the entire lifecycle of loading data (vs previously relying on dbt).  For example, we will be able to strip data from each record, add a "column was too big" error, and still include the primary key(s) and cursor in the upload for these problematic records.  We will be working on this project early next year.

**Comment by chrishronek** [comment]
@evantahler looks like AWS extended the SUPER data type column size from 1MB to 16MB. That might get me where I need to go, going to try implementing it.

https://aws.amazon.com//about-aws/whats-new/2023/12/amazon-redshift-super-data-column-size-16mb/

**Comment by cynthiaxyin** [comment]
@pranasziaukas @chrishronek Have you had a chance to try out the beta for Redshift Destinations V2 yet? I'd love to hear how your experience has gone and any feedback or questions you may have. Please let me know if you have any trouble joining the Slack channel for early access as well - I don't believe either of you are in there.

**Comment by chrishronek** [comment]
@cynthiaxyin, thanks for reaching out. 

Unfortunately, I cannot join the Slack channel because my organization doesn't use Slack 😞. 

I'm still facing the same issue even after attempting to use the V2 Redshift Destination:

```
-----------------------------------------------
error:  Value too long for character type
code:      8001
context:   Value too long for type character varying(256)
query:     208020314
location:  string.cpp:219
process:   query0_69_208020314 [pid=12062]
-----------------------------------------------
```

Based on @evantahler's feedback above, I'm guessing it's a separate issue that ya'll are looking to solve "early next year". So, the HubSpot &rarr; Redshift sync is useless for my org, and we must continue maintaining the extract we have in the form of an Airflow DAG (Airbyte would be much more maintainable for us). If you have other ideas for how I should troubleshoot, I'd love to hear them. Cheers 🍻

**Comment by evantahler** [comment]
@chrishronek - yep, I guess that's right.  Can you share more about what the data is that you are moving that is so big?  How do you solve it now with Airflow?  Do you truncate or null-out data that is too large for Redshift to hold?

**Comment by chrishronek** [comment]
@evantahler sure thing:

> Can you share more about what the data is that you are moving that is so big?

I don't think it's that big. My __theory__ is that Airbyte is trying to load *all* properties from the HubSpot API as one massive SUPER object instead of only specifying the properties that the user is interested in...therefore the group of properties is a massive field that Redshift doesn't quite know how to resolve.

> How do you solve it now with Airflow?

In Airflow, this is the general process:
1. We extract raw JSON from the HubSpot API to an S3 bucket. As part of the API call, we include a list of the HubSpot properties we are interested in (we don't return all object properties). For example, when loading contacts, [there's an API parameter called `properties`](https://developers.hubspot.com/docs/api/crm/contacts). That's where we request only the properties that we'd want
2. We then create a [JSON mapping](https://docs.aws.amazon.com/redshift/latest/dg/copy-usage_notes-copy-from-json.html) in S3 specifying how that JSON is structured
3. We then perform a copy command referencing that JSON mapping to load the JSON(s) from S3 and into Redshift. 

> Do you truncate or null-out data that is too large for Redshift to hold?

No, we just exclude the large properties form the initial API call to HubSpot (via the `properties` parameter).

**Comment by evantahler** [comment]
Github discussion for the Redshift V2 beta -> https://github.com/airbytehq/airbyte/discussions/33610

**Comment by evantahler** [comment]
@chrishronek thanks for the explanation!  You are correct that we do load all properties in the record first to one SUPER object, and then do the splitting and type-casting in SQL.  That said... if you are ignoring a large property in your custom pipeline... could you use [column selection](https://airbyte.com/blog/airbyte-column-selection-control-over-the-exact-data-to-sync) in the Airbyte UI to also ignore that column in the Airbyte sync?

**Comment by chrishronek** [comment]
@evantahler I tried doing that...but the entire payload with *all* properties is still being loaded in the `_airbyte` staging table (from what I can tell). Meaning when I toggle off a switch for a large property, it doesn't really matter because it still gets loaded into the raw table before the data is normalized.

**Comment by evantahler** [comment]
@chrishronek hmm... that's surprising.  The way that column selection works is that the Airbyte platform strips away / nulls out those columns as the records transit though Airbyte.  They really shouldn't be there in the destination / redshift, even in the raw table.  Can you share a screenshot of your connection setup, like this:

<img width="1706" alt="Screenshot 2023-12-18 at 3 41 32 PM" src="https://github.com/airbytehq/airbyte/assets/303226/b2ab1177-be1e-4c7b-842b-4c4f1e460103">
Here I've de-selected weight, age, and blood-type from this source, and I've confirmed those properties never make it to the destination.

**Comment by pranasziaukas** [comment]
> Have you had a chance to try out the beta for Redshift Destinations V2 yet?

@cynthiaxyin we haven't done hands on work with the Redshift Destination V2 yet. But it's on the radar.

Regarding the Slack channel, can you make it joinable w/o a paid account? I think https://slack.com/intl/en-gb/help/articles/4409350616467-Use-Slack-Connect-with-free-teams -- because Slack is not the main communication tool within our team we only have a free account.

**Comment by rohaldb** [comment]
Jumping in here @evantahler - in my case I can't strip out certain fields because airbyte treats an array of deeply nested objects as a single field on the stream. For example, the line_items field on the Shopify Orders stream. So what you are suggesting is not always possible. 
Having more flexibility in being able to control the subfields within each array item would definitely mitigate the super issues while you build out a more robust solution since I don't need many of those subfields and would just be able to disable them

**Comment by evantahler** [comment]
@pranasziaukas - you can join our [community slack free here](https://airbyte.com/community/community).  DM us when you get in and we'll add you to the proper channel

**Comment by cynthiaxyin** [comment]
We had 4 beta users in total give us feedback, summary: https://docs.google.com/spreadsheets/d/1KUX1O4TCDpHNuH7KGEy_0bo13s5jsNpxYqo401vncUA/edit#gid=0
