### ISSUE TITLE
Update snowflake async to use 200mb batches again

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#31741]
From [slack](https://airbytehq-team.slack.com/archives/C05H8UCNCK0/p1698082367311059)

* the new async framework defaults to [50 MiB](https://github.com/airbytehq/airbyte/blob/master/airbyte-cdk/java/airbyte-cdk/db-destinations/src/main/java/io/airbyte/cdk/integrations/destination/staging/AsyncFlush.java#L47) batches
  * bigquery is overriding this value to 25 MiB in GCS mode, and 20% of max memory in standard inserts mode
* the previous code was using [200 MiB](https://github.com/airbytehq/airbyte/blob/556e9adb0789671d5f644bff621848513355f684/airbyte-cdk/java/airbyte-cdk/core/src/main/java/io/airbyte/cdk/integrations/destination/record_buffer/FileBuffer.java#L27), and cites snowflake documentation for that number

Rollout
* Do a few test syncs in the perf workspace to make sure that (1) it works and (2) it didn't get slower

**Comment by evantahler** [comment]
Question for @perangel - do our container pods have "fast" (e.g. SSD) volumes?  We do write to disk a lot...

**Comment by perangel** [comment]
> Question for @perangel - do our container pods have "fast" (e.g. SSD) volumes?  We do write to disk a lot...

Yes, we use SSDs for all our volumes

**Comment by evantahler** [comment]
@edgao I think you've started this

**Comment by edgao** [comment]
yep, https://github.com/airbytehq/oncall/issues/3468 does this for bigquery. I can do the same for snowflake once it's merged.

**Comment by atxnyc** [comment]
This is great, will significantly reduce credit costs of running syncs with airbyte. These significantly increased on slow syncs when the batch size changed. 

Would it make sense to make the size of the buffer, and amount of times between flushes (I believe its 5 by default now), configurable in the destination settings so that users can tweak based based on their needs? That way they could keep them low to prioritize getting data sooner, or high to reduce snowflake costs

**Comment by edgao** [comment]
@atxnyc can you submit a separate issue for configurable batch size + flush frequency? seems like a potentially-valuable feature, trying to gauge overall interest
