### ISSUE TITLE
Investigate pip install race condition between cdk publish and connector publish

### ISSUE THREAD

**Issue by bnchrch** [airbytehq/airbyte#31793]
## Problem
A connector publish failed with error
> ExecError
> failed to solve: process "pip install --force-reinstall airbyte-cdk==0.52.0" did not complete successfully: exit code: 1

Suspiciously a CDK publish happened at the same time.

To resolve all we had to do was trigger a manual publish and everything was fine.

**Links**
* [Slack thread](https://airbytehq-team.slack.com/archives/C05KSGM8MNC/p1698154765551329)
* [Sentry error](https://airbytehq.sentry.io/issues/4570802530/?referrer=slack&notification_uuid=42d631a5-8e4e-4efe-a79a-abae24ffa342&alert_rule_id=14570850&alert_type=issue)
* [Related pipeline failure](https://github.com/airbytehq/airbyte/actions/runs/6627657036/job/18003033412)
* [Possibly related CDK publish](https://github.com/airbytehq/airbyte/actions/runs/6627514829)
* [Reran successfull pipeline](https://github.com/airbytehq/airbyte/actions/runs/6631834154)

## Theories
It could be related to the shared pip cache and pip automatically holding onto a stale version
https://stackoverflow.com/questions/14617136/why-is-pip-installing-an-old-version-of-my-package

**Comment by erohmensing** [comment]
One thing extra to note is that we didn't see a failure in the publish updates channel for this

**Comment by alafanechere** [comment]
Context:
In airbyte-ci publish or test we always pull and cache the latest CDK version in the `pip_cache` to make sure all connectors not pinning the CDK will install the freshest CDK.

To fetch the latest CDK version number I call the PyPi API.
If the version number change it will burst the cache [here](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/pipelines/hacks.py#L49-L55) and install the latest CDK:

```
    await (
        dagger_client.container()
        .from_("python:3.9-slim")
        .with_mounted_cache("/root/.cache/pip", dagger_client.cache_volume(pip_cache_volume_name))
        .with_exec(["pip", "install", "--force-reinstall", f"airbyte-cdk=={cdk_latest_version}"])
        .sync()
    )
``` 

This error occurs when the CDK is being published.
I think the problem is the same kind of problem we had with DockerHub API vs registry:
The PyPi API returns a new version number before it's actually available for download.

A "simple" workaround would be to introduce a retry logic.

**Comment by evantahler** [comment]
Grooming:
* Bust cache on failure OR wait 10 min?
* We chose to try without the pip cache (--no-cache-dir) if there's a failure rather than a 10min retry 
* Add a cache-buster ENV before with_exec when the CDK changes

We could get the list of images from pip via `pip index versions airbyte-cdk`.  
We could run pip upgrade to resolve this as well (`pip3 install --upgrade pip`)
