### ISSUE TITLE
Gradle format should only look at files that have changed.

### ISSUE THREAD

**Issue by davinchia** [airbytehq/airbyte#3229]
## Tell us about the problem you're trying to solve
Gradle format should only look at files that have changed. A common thing is forgetting to run format before pushing code and having the build fail before actually building code. Dev then lose 10 - 15 mins running format locally, and waiting for the build.

It would be nice if format runs only on files that are changed instead of the entire project as it does today.

## Describe the solution you’d like
Liren has proposed configuring the plugin to only run on modified files and adding this as a git pre hook so it integrates well with dev workflows.

## Are you willing to submit a PR?
Liren has promised to do this.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368106467916) by [Unito](https://www.unito.io)

**Comment by tuliren** [comment]
After looking into this issue, it looks like the root cause of the long `format` task is not that spotless checks the entire codebase, but that this task depends on the `generate` task, which is doing a whole bundle of things and therefore very slow. So this is not just a plugin configuration issue to make the `format` task faster. The `spotlessCheck` task actually takes less than 10 seconds to run for the entire codebase.

**Comment by tuliren** [comment]
Also I ran into an [NPE issue](https://github.com/diffplug/spotless/issues/700) when testing `ratchetFrom`.

**Comment by tuliren** [comment]
The spotless config is not always consistent with our Java code style setting in IntelliJ and TypeScript prettier config. Given the suboptimal support of checking only the changed files, the better option is probably to just replace spotless with something else.

**Comment by keu** [comment]
FYI in python world there is https://pre-commit.com/

**Comment by davinchia** [comment]
No longer relevant.
