### ISSUE TITLE
Update Sentry alerting for new OC rotation

### ISSUE THREAD

**Issue by cynthiaxyin** [airbytehq/airbyte#32335]
The [new schedule](https://airbyte.pagerduty.com/schedules#P86BIJX). See [Slack thread](https://airbytehq-team.slack.com/archives/C03C4AVJWG4/p1699398713763509?thread_ts=1699303914.231839&cid=C03C4AVJWG4) for pointers from Pedro. DB sources will probably be making similar updates too.

We should make the necessary changes and verify everything works as expected before the split on Dec 13.

**Comment by cynthiaxyin** [comment]
Sentry paged API connectors instead of destinations :( Wrote up a doc: https://docs.google.com/document/d/1MZ_2BS9jvYCHuV304nnRz6PjvEZyhs_ylG7LAODvylw/edit

**Comment by evantahler** [comment]
re-assigning to @edgao while @cynthiaxyin is out.

**Comment by edgao** [comment]
this works now! from [slack thread](https://airbytehq-team.slack.com/archives/C03C4AVJWG4/p1703053046863599):
* @pedroslopez updated sentry ownership rules to route pages to the right team
* then we muted the old dw/dw sentry alerts, so that only the new destinations alerts (+ sources alerts) are still active
* then we triggered a page and verified that I got paged, and nobody else got paged
