### ISSUE TITLE
SAT: should validate the data types of output records

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#3253]
## Tell us about the problem you're trying to solve
#3252 and #2927 are examples of problems that happened because the output data type does not match the type declared in the catalogt. We should update source acceptance tests so they assert the output data type matches the one declared in the catalog.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368165196504) by [Unito](https://www.unito.io)

**Comment by Zirochkaa** [comment]
- [ ] run tests locally for any connector in order to understand how the running process works (build docker, install this test package, etc) (8h)
- [ ] look through TestBasicRead and some examples of acceptance-test-config.yml files in order to decide where to add a new flag for type validation feature (3h)
- [ ] add new function to ConnectorRunner if needed, depends on above step (1h)
- [ ] came up with an idea about where to get schemas for streams (2h)
- [ ] update TestBasicRead.test_read function with code that will do type validation (4h)
- [ ] pick up any source and test this functionality on it (4h)
