### ISSUE TITLE
BaseSingerSource non-zero exit code 

### ISSUE THREAD

**Issue by vitaliizazmic** [airbytehq/airbyte#3266]
base_singer.BaseSingerSource check method always finish with exit code 0 even with wrong credentials. It should exit with non-zero code when connection fails.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368165390109) by [Unito](https://www.unito.io)

**Comment by sherifnada** [comment]
@vitaliizazmic I think I misunderstood your comment from the other PR. This is actually expected behavior. Exit code 0 means the `check` process completed successfully (no unexpected exceptions happened). It does not say anything about whether the _output_ of the check was that credentials were valid or not. So in this case I think this is not an issue? Why did this come up during the work on search console?

**Comment by vitaliizazmic** [comment]
@sherifnada this issue came up while acceptance tests. It uses wrong credentials and expects non-zero exit code.

**Comment by sherifnada** [comment]
This sounds like a bug in acceptance tests. They should expect the check to have status code 0 but the output message to have status=failed e.g: `{"type":"connection_status", "connectionStatus": {"status":"failed"}}`

**Comment by keu** [comment]
@sherifnada I don't think we can distinguish between connection errors and errors from the connector itself.
This behavior expected when connector crashed because its config is invalid, not because credentials are invalid.
So we have 3 possible responses, which we tests:
* connection ok
* connection failed
* connector failed to start (exception), exit status != 0
