### ISSUE TITLE
airbyte-ci: automated local format

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#32935]
We want to offer a simple and automated approach to automatically format their code before pushing it to our repo.
This will be implemented with a `pre-commit` hook.

**At the moment `airbyte-ci format check all` takes ~2mn to run.**

Suggested implementation:
* Add a `make format.check` and a `make format.fix` targets wrapping `airbyte-ci` respective format command.
* Modify our [pre-commit config](https://github.com/airbytehq/airbyte/blob/master/.pre-commit-config.yaml#L1) to run `format.fix` on push.
* If `format.fix` modified files the push can't happen until a formatting commit is addeed.
* Bypass the hook when the commit message is `format` to avoid a double run of `format`

Alternative:
Do not use `airbyte-ci` in pre-commit: only rely on "native" libs to format locally (pre-commit takes care of the installation of these libs with `pipx`) 

Questions:
* When should the git hook run: on push or on commit?
* Is it reasonable to make developers wait for 2mn before pushing?

Definition of done:
* Our developer can install a pre-commit hook to automatically fix formatting before pushing their code
* The process to install the pre-commit hook is clearly documented and socialized
* We document IDE-specific set up  / plugins to accomplish the same thing: in VSCode, IntelliJ, and Pycharm?
* `format fix all` is disabled on the CI

**Comment by erohmensing** [comment]
Thoughts after talking with Stephane: 
- base assumption was that a pre-commit hook would be running `check`, not `format` 
- if doing formatting, should definitely be a pre-push hook, not pre-commit (don't make changes within devs commits) 
- when running check, wants to know which files had errors 
- both commands are _very_ verbose: would like a quieter mode to run that doesn't wipe the whole console history (e.g. in intellij with default limited history)

**Comment by bnchrch** [comment]
@pedroslopez @bnchrch @erohmensing Async opinions needed!

**Comment by bnchrch** [comment]
> On the note of precommit vs prepush
Im team pre push. Makes it easier to just write code to get things working.

> On the note of fixing vs checking
I dont have a strong opinion. But given that linters cant autofix anyway (when we introduce them) I'd say we go with check

> On the note of precommit config
I did not know we had this already, nor that it existed.
https://github.com/airbytehq/airbyte/blob/master/.pre-commit-config.yaml#L1

I feel a bit silly we didnt look for a tool like this at the begining of the format endevours.

Is it possible to have it call all our gradle formatters/linters?

If so is the correct approach to 
1. Have airbyte-ci format check call 

If so does it make sense to have `airbyte-ci format check/fix` install `pre-commit` and run it instead of our current approach?

Then were free to have the makefile install the `pre-commit` hook and both our hook and ci check reference the same config?

**Comment by erohmensing** [comment]
> On the note of precommit vs prepush

Also team pre-push! When I work on platform, for example, i always format before I push, because I like the CI checks to be actually valuable. But I explicitly don't use any precommit hooks at the moment because committing to me should be pretty instantaneous so that I can make small commits. 

> On the note of fixing vs checking

Based on "If format.fix modified files the push can't happen until a formatting commit is added", I think i'd prefer fix. Then if something is wrong, dagger has already done the work to fix it for me, instead of me having to run another command to fix it. Also the modified files shows me what the problems were. 

I understand ben's thought on linting though. I'm still in the strong camp that "formatting is something that can be fixed automatically, linting is not" and that we should have separate checks that run formatting and linting. That means that in the future, on the prepush hook, we can run format fix and lint (check) -- essentially fixing everything that we can, and then making the user fix the rest. 

> Bypass the hook when the commit message is format to avoid a double run of format

This is interesting, and yep, makes sense. I was wondering, if the pre-push check doesn't autocommit, if we were gonna run it again after committing the fixes. This would help. I guess we have to make users aware of this though - probably should be a very visible log that comes out at the end of the check. I was going to suggest widening the regex match to only include "format" as part of the message (i often use "run formatter" as my message) but then that could also catch things like "change the format of x to y" so sticking to something concrete is probably best. 

> Is it reasonable to make developers wait for 2mn before pushing?

I think with --no-verify available to us it is probably okay. Also anything precommit is still opt-in, right? I'd prefer to wait when pushing, I think, as its still faster than waiting to see if it fails in CI. but i think I check the formatter/care about CI-greenness _during_ the PR iteration process more than other people probably do. This probably highly depends on different people's workflows - some people might like to push often to be able to look at their diff as they're working, while others commit almost exclusively locally without remote pushes in between


> format fix all is disabled on the CI

Should this be "is replaced with format check"? Or we do the fix all and check for a diff? Regardless of how well we encourage formatting via precommit, IDEs etc., I think we still need to make some assertions in CI. But i agree that removing the auto-committing in CI is a goal of this.

**Comment by alafanechere** [comment]
> On not knowing that we already had a precommit config that lints etc... same 

I'm using it and it's configured quite well for python.
I think we should reproduce the same behavior `pre-commit` as, but only run in pre-push.

The current behavior of pre-commit is:
* When you commit the formatter runs and fixes the format. If any file got modified by the formatter the commit is not created: you have to stage the modified files and you can then commit. If you did not change any file after your previous  commit attempt the formatter will not change any file and your commit will be created.

I like this flow. But considering the current duration of `airbyte-ci format fix all` I think it's more reasonable to run it pre-push. 

> I feel a bit silly we didnt look for a tool like this at the begining of the format endevours.

For unification of local / remote CI I prefer that pre-commit runs airbyte-ci.
But if we can't implement a nice DX we can fallback to the existing `pre-commit` configuration + make it format java.

**Comment by alafanechere** [comment]
> If so does it make sense to have airbyte-ci format check/fix install pre-commit and run it instead of our current approach?

IMO it should be different:
* `make tools.install` installs airbyte-ci, pre-commit + pre-commit config
* `make format` runs  `airbyte-ci format fix all`
* pre-commit calls `make format` on push
