### ISSUE TITLE
JOB_KUBE_BUSYBOX_IMAGE is not used by orchestrator pod

### ISSUE THREAD

**Issue by maver1ck** [airbytehq/airbyte#33007]
### What method are you using to run Airbyte?

Kubernetes

### Platform Version or Helm Chart Version

0.50.34

### What step the error happened?

During the Sync

### Revelant information

Hi,
I'm trying to overwrite orchestrator busybox image repository.
I used JOB_KUBE_BUSYBOX_IMAGE and orchestrator pod is not using this image.
What can I do ?

**Comment by maver1ck** [comment]
I think problem lays in 2 places:
https://github.com/airbytehq/airbyte-platform/blob/861008b2daeca2c4d8005afba558d6d5287b7968/airbyte-workload-launcher/src/main/kotlin/pods/OrchestratorPodLauncher.kt#L127
https://github.com/airbytehq/airbyte-platform/blob/861008b2daeca2c4d8005afba558d6d5287b7968/airbyte-commons-worker/src/main/java/io/airbyte/workers/process/AsyncOrchestratorPodProcess.java#L474

**Comment by maver1ck** [comment]
@tryangul Maybe you can help ?

**Comment by AronsonDan** [comment]
Well, Im facing the same exact issue.
Because we are using Karpenter on our cluster and nodes are pretty volatile, im getting a lot of: 
`Failed to pull image "busybox:1.35": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/library/busybox:1.35": failed to copy: httpReadSeeker: failed open: unexpected status code https://registry-1.docker.io/v2/library/busybox/manifests/sha256:0fac7d303b1d9c0b4f5a596b7bd95525c94578f72146393f7a2534bfe3e4b2c0: 429 Too Many Requests - Server message: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit`

I thought that changing `Values.global.jobs.kube.images` to a busybox image from my private ecr image would change the image pull source but it changes in any other pod that needs the busybox image other than the orchestrator.

BTW, any reason you guys are using mainly busybox:1.28 and only in the orchestrator image using busybox:1.35?

**Comment by gediminas-puksmys-nfq** [comment]
That is also relevant for our case as we're hitting limits while trying to fetch `busybox:1.35`.
We managed to change busybox image for other pods, but orchestrator does not take this as uses it's hardcoded value

**Comment by bruceoutdoors** [comment]
Seems this [OrchestratorPodLauncher.kt](https://github.com/airbytehq/airbyte-platform/blob/v0.50.44/airbyte-workload-launcher/src/main/kotlin/pods/OrchestratorPodLauncher.kt) to be introduced in `0.50.34`. It didn't exist in `0.50.33`

**Comment by VeeraswamyGatta** [comment]
if we have our container registry with different repository name then its failing , so please read it from environment variable or config instead of hardcoding the image name, so that we can pass our own repository and tag (https://github.com/airbytehq/airbyte-platform/blob/861008b2daeca2c4d8005afba558d6d5287b7968/airbyte-commons-worker/src/main/java/io/airbyte/workers/process/AsyncOrchestratorPodProcess.java#L474)

**Comment by tryangul** [comment]
@maver1ck I took a stab at fixing this. It should be out in the latest few releases. Let me know if you're able to override as expected.

**Comment by davinchia** [comment]
Closing as done. Please re-open if you still encounter this issue!

**Comment by vainkop** [comment]
In https://github.com/airbytehq/airbyte-platform/releases/tag/v1.4.0 I still see pods failing with the following env vars missing from airbyte-airbyte-env ConfigMap & adding them as extraEnv does't help cause pods are looking for them in airbyte-airbyte-env ConfigMap:
```
JOB_KUBE_BUSYBOX_IMAGE
JOB_KUBE_CURL_IMAGE
```
