### ISSUE TITLE
Update airbyte-ci install in CI to use the version defined in pyproject.toml

### ISSUE THREAD

**Issue by bnchrch** [airbytehq/airbyte#33066]
## Problem
We install airbyte-ci from latest.

This can lead to issues if the branch in behind master when running airbyte-ci

## Solution
We should be installing airbyte-ci via the version in pyproject.toml

## Notes
* This is how `airbyte-ci update` and `make tools.airbyte-ci.install` works today. So we just need to reuse that logic in our GHA action

**Comment by erohmensing** [comment]
Does this mean we need to make sure that the branch is up to date with master before pulling it in, if master is version-forward of the branch? 

E.g. connector/lib tests could be passing on airbyte ci version a.b.N (branch version) but failing on a.b.N+1 and CI would be green if it passes on a.b.N - we wouldn't know until it failed on master. Similar but opposite issue as to using the latest binary ("master branch" version) instead of the branch version (latest) when airbyte ci is version-forward on the branch.

**Comment by erohmensing** [comment]
I guess I am arguing that "branch is behind latest airbyte CI" is actually a reasonable fail case and the answer should be 'merge in master' - but maybe that is reductive to all the problem cases here

**Comment by evantahler** [comment]
Grooming:
* We decided to always use `latest` version of airbyte-ci.  If there are problems... rebase.  People do that anyway.
