### ISSUE TITLE
[Source MySQL] : Failure to get load schema history

### ISSUE THREAD

**Issue by akashkulk** [airbytehq/airbyte#33107]
There are 2 main groups of errors we are seeing : 

1. Unable to initialize and start connector's task class 'io.debezium.connector.mysql.MySqlConnectorTask' with config[Example](https://cloud.airbyte.com/workspaces/a6b434d5-760d-499c-82cd-e964ffdaa089/connections/d6f7d9e3-91e6-4091-aec6-bfae5828e00b/job-history#6157012::4)

> This happens when reading schema history is timing out and and we are sending an empty schema change file. Consequently, the debezium task fails to start. 

2. Source process exited with non-zero exit code 1 java.lang.RuntimeException: java.nio.file.NoSuchFileException: /tmp/cdc-db-history13989736358536046491/dbhistory.dat [Example](https://cloud.airbyte.com/workspaces/5f2293da-e1c1-4bd5-8ccf-8bf6d9f4dffb/connections/d25fe0bc-686f-4368-8607-3c2dfbeffa8a/job-history#6159825::3)

> This happens when reading schema history errors out. In this case, we cannot read the schema history file, and that is what the error is indicating 

In both cases the correct thing to do is : 
1. Fail loud and clear if we fail to get schema history or timeout. Perhaps prompting the user to increase timeout. 
2. Change default minimum timeout by default

**Comment by prateekmukhedkar** [comment]
Reopening because this is happening for https://cloud.airbyte.com/workspaces/2d1355e0-65c1-4cf9-ac57-0f3c16ae862e/connections/c9d31da3-5417-41c0-b521-9e09b57503a0/job-history#7164942::4 even with increasing the initial wait timeout to the max allowed of 20 minutes.

`java.lang.RuntimeException: java.lang.RuntimeException: Building schema history has timed out. Please consider increasing the debezium wait time in advanced options.
`

**Comment by akashkulk** [comment]
This is actually a manifestation of https://github.com/airbytehq/airbyte/issues/31290. (Invalid topic.prefix name). Closing here and looking into that
