### ISSUE TITLE
Add alerts for when either of the connection support state cron and the definitions updater cron have not run inside a window

### ISSUE THREAD

**Issue by bnchrch** [airbytehq/airbyte#33317]
## Problem
We currently do not know if the crons are running

## Solution
We do have the information is datadog: https://app.datadoghq.com/dashboard/wv8-id6-vsm/cloud-connection-support-state-cron?from_ts=1699732132554&to_ts=1702324132554&live=true

We need to setup an OC alert when an elevated levels of errors occur

## Appendix
[Slack convo](https://airbytehq-team.slack.com/archives/C03VDJ4FMJB/p1702324241519319)

**Comment by evantahler** [comment]
Can this be made a little more generically, e.g. "alert whenever a cron job hasn't run 2 times in a row"

**Comment by erohmensing** [comment]
@evantahler you can't assert how many times it doesn't run, since you only know when it does run. That being said: 

we now have 
* [ConnectionSupportStateValidator hasn't run in 8 hours](https://app.datadoghq.com/monitors/136710663)
* [The DefinitionsUpdater cron has not run in 2 hours](https://app.datadoghq.com/monitors/136711442)

I think @gosusnp was looking into a more generic monitor for all crons where you just define the cron, and the alert threshold

**Comment by bnchrch** [comment]
notes:
* OAuth alerts are back
* But who is responsible for them?
* Uptime alerts are back up
* We need to go back and Terraform these
*

**Comment by gosusnp** [comment]
Move is introducing some pretty strong constraints around crons for workload API.
We have a few crons that runs every minute. Currently we have one global monitor but I think I'll look soon into a pattern to be able to have indidivual monitors for each cron.
So far our approach is we expect at least X runs within the last N minutes. I also think we'll add a monitor on the duration of those runs to catch early if things are slowing down.
