### ISSUE TITLE
Failed add connector operation should display logs

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#3335]
## Tell us about the problem you're trying to solve
Same scenario as in #3333 but separate request: I can't see the logs of the failed job which makes it hard to debug. It would be very helpful to have these logs in the UI so users can very easily give us helpful debugging info.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368166205931) by [Unito](https://www.unito.io)

**Comment by cgardens** [comment]
Before FE can do this `/v1/source_definitions/create` needs to return logs.

**Comment by cgardens** [comment]
Suggesting this as a good first issue for george or jenny

**Comment by cgardens** [comment]
More context for Jenny.

We allow a user to add a custom connector in the admin portion of our UI. This allows users to add connectors that they create themselves (or that didn't ship with Airbyte for whatever reason).

![Screen Shot 2021-06-04 at 11 44 50 AM](https://user-images.githubusercontent.com/9092207/120849050-6cd30880-c52a-11eb-8bd5-779caa045963.png)

Sometimes when adding a new connector there are errors. The 2 most common are:
1. the docker image just doesn't exist (usually due to a typo) 
2. the specified image does not correctly implement the airbyte protocol (e.g. the [get spec call](https://docs.airbyte.io/understanding-airbyte/airbyte-specification#spec) fails for some reason)

The goal of this PR is in these failure cases expose to the user the logs associated with the failure so that they can take action to fix things. You will find that showing failure logs is a common pattern that we already have. Here's a screenshot example of when do it for the check connection call. You can find the declaration for the associated endpoint [here](https://github.com/airbytehq/airbyte/blob/master/airbyte-api/src/main/openapi/config.yaml#L480):

![Screen Shot 2021-06-04 at 11 50 21 AM](https://user-images.githubusercontent.com/9092207/120849593-2f22af80-c52b-11eb-8a98-edceef5caeb9.png)

The issue we have is that the endpoint that creates a new connector definition does _not_ include the logs in its [response](https://github.com/airbytehq/airbyte/blob/master/airbyte-api/src/main/openapi/config.yaml#L208). Thus the UI is not able to display them.

Our goal in this issue is to supplement the existing response with those logs so that our UI developer can than expose them in the UI. To be clear, the only part you need to worry about is everything from the API and back--you don't need to worry about UI work!

Here are some other things it might be helpful to look out for along the way:
* You'll notice that when returning logs we reuse a `SynchronousJobRead` which contains a log attribute. Reusing that struct here probably makes sense! Doing so will allow you to pattern match a bit off of existing code paths as well.

**Comment by cgardens** [comment]
This issue is code complete for the BE side. Waiting on FE work in this issue https://github.com/airbytehq/airbyte/issues/3809 before we can merge & clode.

**Comment by cgardens** [comment]
@timroes did we never do this? I thought it was done at some point, but I could be mistaken.

**Comment by timroes** [comment]
Yes this has been done by now. The log of the job will be shown as long as either the actual job failed (i.e. not just the check inside the job), or if the user has the "Advanced Mode" setting turned on, in which case we'll always show the job log (no matter the result).
