### ISSUE TITLE
Decide on path forward for our CI infrastructure

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#33914]

**Comment by alafanechere** [comment]
Conor started [an helm chart ](https://github.com/airbytehq/airbyte-infra/tree/main/helm/charts/airbyte-ci/templates )which reproduces in a templated fashion the existing CI cluster we have with barebone kubernetes [manifests](https://github.com/airbytehq/airbyte-infra/tree/main/manifests).

It is beneficial for the connector ops team to use this helm chart as we'd only have to [tweak helm values file, at a single place](https://github.com/airbytehq/airbyte-stacks/blob/main/ci/prod/aws/us-west-2/applications/airbyte-ci/airbyte-ci-values.yaml), to deploy new runners. 

Having said that, given the current stability of the existing cluster, I don't think it's worth migrating to a **new cluster with this helm chart now.** Instead of starting a migration now I would prefer first make this helm chart evolve to be based on top of a dagger-maintained helm chart. Why:
* It might reduce the maintenance burden: Dagger maintains an official helm chart, we "just" build an interface on top of it that matches connector ops needs.
* Using Dagger's helm chart simplifies support and communication with the Dagger team.

## Next steps:

1. @alafanechere shares our current helm chart with the Dagger team
2. @alafanechere asks the Dagger team where Dagger's WIP helm chart is.
3. @alafanechere @airbyte-prodeng review Dagger's helm chart and assess if using it is feasible
4.  @alafanechere @airbyte-prodeng and Dagger team meet to define a path forward.


### Ideal output:
* We have a new cluster running an internal helm chart based on dagger's helm chart
* The helm values interface matches Connector Ops need to declare  and size new runners
* We have automated the deployment of changes with argo-cd.

**Comment by evantahler** [comment]
cc @git-phu

**Comment by alafanechere** [comment]
Tech spec advocating for moving to Github hosted runner available [here](https://docs.google.com/document/d/1jdFR1sFXBIvMUNmA-cCL33B0uvvQjJc4dqF3Sx22c5U/edit#heading=h.2eis5nt22emc).

**Comment by alafanechere** [comment]
Migration to Github hosted runners PR: https://github.com/airbytehq/airbyte/pull/34316
