### ISSUE TITLE
Implement normalization for the MySql destination.

### ISSUE THREAD

**Issue by davinchia** [airbytehq/airbyte#3429]
## Tell us about the problem you're trying to solve
MySql currently does not support normalization. It should support it.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368197699942) by [Unito](https://www.unito.io)

**Comment by ChristopheDuong** [comment]
Quick checklist for implementing this:
(since this is the first time doing this, we don't have a proper docs to describe all steps yet so this might not cover all steps)

- Add MySql community adapters https://github.com/dbeatty10/dbt-mysql to the list of packages in the dbt-project-template: https://docs.getdbt.com/docs/building-a-dbt-project/package-management
- Add destination to list of destinations that support normalization
  - In Java: https://github.com/airbytehq/airbyte/blob/master/airbyte-workers/src/main/java/io/airbyte/workers/normalization/NormalizationRunnerFactory.java 
  - In Python: https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/bases/base-normalization/normalization/destination_type.py
- Make sure https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/bases/base-normalization/normalization/transform_config/transform.py can generate the proper `profiles.yml` file for MySQL dbt adapter
- Try running normalization for this destination: https://github.com/airbytehq/airbyte/tree/master/airbyte-integrations/bases/base-normalization
- Fix any missing dbt macros, for example: https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/bases/base-normalization/dbt-project-template/macros/cross_db_utils/json_operations.sql

**Comment by trev142** [comment]
Really appreciate the work on this one guys - been hanging out for it for ages!! Thank you so much!
I've just updated to 0.27.1-alpha but I can't see the normalization option on my connection with a MySQL destination.
My MySQL destination is on version 0.1.6 and my MySQL server is 8.0.23.
Is there a trick that I'm missing??
![image](https://user-images.githubusercontent.com/63149542/125072756-522e1980-e0fe-11eb-978a-bf08de9626a1.png)

**Comment by ChristopheDuong** [comment]
> I've just updated to 0.27.1-alpha but I can't see the normalization option on my connection with a MySQL destination.
> My MySQL destination is on version 0.1.6 and my MySQL server is 8.0.23.
> Is there a trick that I'm missing??

Yes, that trick is this PR that we need to finalize! sorry about that
https://github.com/airbytehq/airbyte/pull/4651
