### ISSUE TITLE
New Source: Google Ads API

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#3457]
## Tell us about the problem you're trying to solve
User comments that Google Adwords won't be more supported in 2022/04 and only the new Google Ads will be used.
https://developers.google.com/google-ads/api/docs/migration#python
Adding this to track and future sprints.

## Describe the solution you’d like
Deprecated the google-adwords-singer to a new connector using Airbyte CDK 

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

## Are you willing to submit a PR?

No at the moment

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368197058986) by [Unito](https://www.unito.io)

**Comment by sherifnada** [comment]
Context from a user about what he needs: 

```
The specific things we need are the ad campaign parameters (including targeting information) and the daily ad performance metrics.  In the AdWords API, this would be:
• AD_PERFORMANCE_REPORT
• accounts
• ads
• adgroups
• campaigns
• CampaignCriteria
In the Ads API, I need to research this a little more carefully, but I think the analogous parts would be:
• The [account hierarchy](https://developers.google.com/google-ads/api/docs/account-management/get-account-hierarchy) (ideally we'd just specify our manager account and Airbyte would fetch data for all of the subaccounts, so we wouldn't have to go into Airbyte and edit the source connector every time we add a subaccount)
• Reporting by ad_group_ad, segmented by segments.date, segments.device, age_range_view, gender_view, geographic_view.geo_target_postal_code
• Targeting details from campaign_criterion (I'll have to investigate to see exactly how we want to query them)
```

**Comment by po3na4skld** [comment]
## Integration Vetting

**Webhook-based? (no/partially/yes)**
no

**Available authentication modes (API key/Oauth/other)**
To enable your app to access the API, you need an OAuth2 client ID and client secret.

**Creating an account**

In case this new API will support old creds, yes and they are in the lastpass
Otherwise we need to create one, but I have issues with loging into google account from integration-test@airbyte.io @sherifnada 

**How to populate the account with data?**








@sherifnada Can't say whether we need it as this could be migrated from Adwords API
https://developers.google.com/google-ads/api/docs/migration#python

**Available streams for sync**

[Account Management](https://developers.google.com/google-ads/api/docs/account-management/overview)
The Google Ads API enables programmatically creating accounts, managing account hierarchies, and setting some account-level options.

[Add Management](https://developers.google.com/google-ads/api/docs/ads/overview)
A Google Ads Ad is the resource that represents an actual ad being served on one of the Google networks.

[Assets](https://developers.google.com/google-ads/api/docs/assets/overview)
Assets are individual pieces of typed content (text, images, videos, and HTML5 bundles) that can be uploaded into an advertiser’s account and then associated with specific types of ads. Google Ads can then mix and match groups of assets to build combinations of full ads automatically.

[Billing](https://developers.google.com/google-ads/api/docs/billing/overview)
The Google Ads API lets you programmatically manage end-to-end billing workflows, from initial billing setup and account-level budget management, to customer invoice reconciliation.

[Campaigns](https://developers.google.com/google-ads/api/docs/campaigns/overview)
A Google Ads campaign is a set of one or more ad groups (ads, keywords, and bids) that share a budget, location targeting, and other settings. Campaigns are typically used to organize categories of products or services offered by an advertiser.

[Conversions](https://developers.google.com/google-ads/api/docs/conversions/overview)
A conversion in Google Ads is when a user performs some specified action after clicking an ad or viewing a Display Network ad, such as purchasing a product, installing a mobile app, or signing up for an email list.
Conversion tracking provides key insights into users' actions after viewing or clicking an ad. You can keep track of users who call, buy a product, install a mobile app, and more.

[Ad Extensions](https://developers.google.com/google-ads/api/docs/extensions/overview)
Ad extensions are extra bits of information that you can show alongside your ads. They can contain links to specific subpages on your webpage, a call button, product pricing information, and more.

[Keyword Planning](https://developers.google.com/google-ads/api/docs/keyword-planning/overview)
Keyword Planning is a process for getting keyword metrics and forecasts as well as searching for new keywords to add to campaigns.

[Reach Forecasting](https://developers.google.com/google-ads/api/docs/reach-forecasting)
ReachPlanService enables media agencies and 3rd-party media planning software companies to accurately forecast the commercial reach of video campaigns on YouTube and Google Video Partners. Media planners can use the service to answer questions such as:
- How much investment on YouTube would it take to meet a campaign's reach goals?
- How much of a target audience could a campaign reach for a given budget?
- What is the optimal budget allocation between YouTube and other media channels if I have a campaign optimizing for reach?

[Remarketing and Audience Targeting](https://developers.google.com/google-ads/api/docs/remarketing/overview)
Remarketing lets you advertise to people who have previously visited your website, used your mobile app, or who are in your CRM databases, by showing them relevant ads when they visit other sites or search on Google.

[Reporting](https://developers.google.com/google-ads/api/docs/reporting/overview)
Reporting of performance data is an integral part of Google Ads API applications. With the API's flexible reporting options, you can obtain performance data for all resources. This includes everything from an entire campaign to a set of keywords that triggered your ad.

[Targeting](https://developers.google.com/google-ads/api/docs/targeting/overview)
The Google Ads API currently supports several targeting options at the campaign and ad group level. Depending on the criteria type, you can use the Google Ads API to:

- Target or exclude criteria at the campaign or ad group level.
- Set absolute bids for specific criteria at the ad group level.
- Modify bids for criteria at the campaign or ad group level. 

[API Structure](https://developers.google.com/google-ads/api/docs/concepts/api-structure)

![API Structure](https://user-images.githubusercontent.com/36486349/119970135-0a24be80-bfb8-11eb-8018-ed3eb8bf5d2b.png)

[Ad MODEL STRUCTURE](https://developers.google.com/google-ads/api/reference/rpc/v7/Ad)
[Campain MODEL STRUCTURE](https://developers.google.com/google-ads/api/reference/rpc/v7/Campaign)


<--Do any streams support incremental sync?-->

[Batch Processing](https://developers.google.com/google-ads/api/docs/batch-processing/overview)
While most services provide synchronous APIs, requiring you to make a request and then wait for a response, BatchJobService provides a way to perform batches of operations on multiple services without synchronously waiting for the operations to complete.

Unlike service-specific mutate operations, a single job in BatchJobService can operate against a mixed collection of campaigns, ad groups, ads, criteria, labels, and feed items. Submitted jobs run in parallel, and BatchJobService automatically retries operations that fail due to transient errors such as rate limit errors.

In addition, BatchJobService lets you use temporary IDs within your requests so you can submit dependent operations in a single job.
