### ISSUE TITLE
Source logs should provide any indicated for how many records are left.

### ISSUE THREAD

**Issue by davinchia** [airbytehq/airbyte#3465]
## Tell us about the problem you're trying to solve
Today our logs only indicate the amount of rows read or the amount of rows read so far. There are no logs showing how many records are left to be read.  We should have such logs to better give users a sense of how much more data is left.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368072824795) by [Unito](https://www.unito.io)

**Comment by keu** [comment]
I think this could be quite complicated, in the worse case will have to read all data twice (thinking about `count` in SQL as the biggest performance killer)

**Comment by davinchia** [comment]
agreed. We probably need to play around with retrieving the planned query, and get an estimated count from there.

**Comment by ajzo90** [comment]
I am proposing a new PROGRESS message in the protocol for this. This message can contain total rows and number of read rows so far. The source can emit the PROGRESS messages at any point (with or without total count). 

Another solution is that the source can emit some kind of STREAM message with useful information about the stream and let the worker be responsible for the counting. 

In case the source happens to know (or are efficient enough to calculate) it opt-in to emit this information, otherwise it falls back on count only.

**Comment by sherifnada** [comment]
Progress has been implemented in the protocol and now a matter of adding to individual connectors
