### ISSUE TITLE
Do not propagate all parameters to child nodes when using `InlineSchemaLoader` in low-code CDK

### ISSUE THREAD

**Issue by ambirdsall** [airbytehq/airbyte#34755]
### Relevant information

In [this line](https://github.com/airbytehq/airbyte/blob/dfec691232d32a18dc54903ec65e819dd4d8cf83/airbyte-cdk/python/airbyte_cdk/sources/declarative/parsers/manifest_component_transformer.py#L106), `manifest_component_transformer.py` propagates parameters in a way that is not valid for inline schemas; while this is not problem for manifests that are written to have inline schemas from the start (and thus, hopefully, don't use parameters to share schema data across multiple files), it is not a behavior that makes sense in this context and it complicates [migrating an existing manifest to use inline schemas](https://github.com/airbytehq/oncall/issues/4085), which is a requirement for compatibility with the Connector Builder. Airbyte employees can reference [this internal slack conversation](https://airbytehq-team.slack.com/archives/C02TL38U5L7/p1706796525567619?thread_ts=1706745262.499109&cid=C02TL38U5L7) for additional context.

**Comment by maxi297** [comment]
To add on the specific of source-activecampaign case, the issue is that there is a [property named `type`](https://github.com/airbytehq/airbyte/blob/5571fd00321a7646706d1ffffd532cbafbdf4196/airbyte-integrations/connectors/source-activecampaign/source_activecampaign/schemas/campaigns.json#L4-L6) which leads the propagation to continue as we don't hit [this condition](https://github.com/airbytehq/airbyte/blob/5571fd00321a7646706d1ffffd532cbafbdf4196/airbyte-cdk/python/airbyte_cdk/sources/declarative/parsers/manifest_component_transformer.py#L106). The schema then ends up being modified like this (simplified version) which is not valid because `properties.primary_key` is expected to be an object

```
{
    "type": "object",
    "properties": {
        "type": {
            "type": "string",
            "name": "campaigns",
            "primary_key": "id",
            "$parameters": {
                "name": "campaigns",
                "primary_key": "id",
            }
        },
        "primary_key": "id",
        "$parameters": {
            "primary_key": "id",
            "name": "campaigns"
        }
    },
    "required": [
        "type"
    ]
}
```
