### ISSUE TITLE
Documentation - Better rendering of JSON Schema ?

### ISSUE THREAD

**Issue by jy95** [airbytehq/airbyte#35393]
### Topic

Documentation - Better rendering of JSON Schema ?

### Relevant information

Hello,

I was exploring one page of your Docusaurus website ( https://docs.airbyte.com/connector-development/schema-reference  ) when I saw this : 

![image](https://github.com/airbytehq/airbyte/assets/9306961/a7998f5f-fb08-4501-b562-28137f222cd9)

Would your project be interested to show your JSON schema(s) to your users in a visual way ?

![image](https://github.com/airbytehq/airbyte/assets/9306961/fdfb289c-126f-48e5-b7cb-2ceb47353115)

It is coming from a Docusaurus plugin called [docusaurus-json-schema-plugin](https://jy95.github.io/docusaurus-json-schema-plugin/docs/quick-start) .

Obviously, just a suggestion ;)

**Comment by timroes** [comment]
Hi @jy95

We render schemas using our own parser already for airbyte-lib, e.g. see here: https://docs.airbyte.com/integrations/sources/activecampaign#reference

We can use that parser in other places of our documentation as well if we plan to render. We looked into the linked plugin as well, but due to the AGPL license didn't use it (and also the basic implementation wasn't too much and we could control rendering a bit better, but it was mainly the license).

I'll leave this issue open since we could/should still improve the doc page you linked, just using our current rendering for it.

**Comment by jy95** [comment]
Hello @timroes ,

Up to your choice. For info, AGPL is quite misunderstood like explained in this [medium](https://medium.com/swlh/understanding-the-agpl-the-most-misunderstood-license-86fd1fe91275) article. The goal of this license is to improve the existing solution, nothing more like. Airbyte has sure that concern as well no ?

I found that your parser is not dark friendly (whereas mine is) - for example :
![image](https://github.com/airbytehq/airbyte/assets/9306961/907a3ec1-9094-49ef-85cb-e9c75b97d0a0)

**Comment by timroes** [comment]
While the GPL licenses try to aim for that, their wording and specific terminology (e.g. static linked) makes it imho always a confusing factor and one of the only licenses where even after debating if for decades I feel people end up with different understanding. Thus I've seen several companies not allow-listing them for usage (not just Airbyte), due to the complexity and confusion around something compared to e.g. MIT. (Also this issue feels like the wrong place to have an elaborate pro/con GPL discussion - see you over at Reddit 😉).

The dark scheme rendering is indeed a bug. @aaronsteers could you have a look at that?

**Comment by aaronsteers** [comment]
@jy95 - It's very nice to e-meet you! I am not a front-end developer myself but I was very excited to discover your excellent JSON Schema renderer several weeks back when I was working with a colleague on our plans for the new auto-generated references sections mentioned above.

As @timroes mentions, we ultimately decided we needed to avoid AGPL - and for better or worse, this is a common thread. Your points are well taken though, and there have been arguments on both sides and we chose to go with an in-house solution because we had front-end engineering resources at the time which could invest in an in-house rendering solution.

Again, probably beyond the scope of this issue thread, but if you would consider a more permissive license on the software, we would be very open to re-evaluating our usage decision, but as of now, AGPL is unfortunately a non-started for us. 

I've logged this issue to resolve the dark-mode issue:

- https://github.com/airbytehq/airbyte/issues/35472

Very happy to continue discussion with you in other mediums. You can find me on slack as `AJ Steers` for instance. 😄 

Closing for now, with follow-up dark-mode resolution tracking in: #36472. Thanks very much for reporting, and for creating the very helpful docusaurus json-schema plugin. 🙏
