### ISSUE TITLE
install_airbyte_pro_on_helm.sh fails if deployment already exists

### ISSUE THREAD

**Issue by qbatten** [airbytehq/airbyte#35500]
### Platform Version

0.50.46

### What step the error happened?

Upgrading the Platform or Helm Chart

### Revelant information

Running `/airbyte-platform/tools/bin/install_airbyte_pro_on_helm.sh` ([this file](https://github.com/airbytehq/airbyte-platform/blob/main/tools/bin/install_airbyte_pro_on_helm.sh)) fails with the following error message (newlines inserted for readability; actual output is a single line)

```
Error: UPGRADE FAILED: cannot patch "airbyte-pro-keycloak-setup" with kind Pod: 
Pod "airbyte-pro-keycloak-setup" is invalid: spec: Forbidden: pod updates may not change fields other than
 `spec.containers[*].image`,`spec.initContainers[*].image`,`spec.activeDeadlineSeconds`,`spec.tolerations` 
(only additions to existing tolerations),`spec.terminationGracePeriodSeconds` (allow it to be set to 1 if it 
was previously negative)
```

Seems like at least one field needs to be patch-able and is not.

**Comment by perangel** [comment]
Hey @qbatten, thanks for filing the issue. 

The immediate workaround here is to delete the `airbyte-pro-keycloak-setup` pod and then re-run the install script. The underlying cause is the setup pod is an unmanaged workload (raw pod, not a Job or Deployment). This will be fixed in a future release, but this should only be an issue if you are upgrading from a version prior to [v0.50.50](https://github.com/airbytehq/airbyte-platform/releases/tag/v0.50.50) to anything after that.
