### ISSUE TITLE
New Source: Dynamo DB 

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#3561]
## Describe the context around this new integration
Docker image that can be used to run locally: https://hub.docker.com/r/amazon/dynamodb-local/

## Describe the alternative you are considering or using

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200368060087111/1200371289226414) by [Unito](https://www.unito.io)

**Comment by mikaelene** [comment]
Hi, I work as a consultant for a customer that wants to evaluate Airbyte. This connector is a must have for them. What is the chances of this to be a reality? In that time?

**Comment by sherifnada** [comment]
@mikaelene apologies - missed your comment. I'm anticipating ~2 months for a release depending on requests -- the main constraint is bandwidth. Would you be open to contributing this connector in Java? We can guide you through it if so.

**Comment by mikaelene** [comment]
Hi @sherifnada , I have quite a lot experience in Python but haven't work with Java since school. Let me see with my customer how urgent/important this is. If I have time to look into it I'll let you know.

**Comment by misteryeo** [comment]
Adding @kailashjoshi018's request here to clean up the backlog: #6342

**Comment by misteryeo** [comment]
**Issue was linked to Harvestr Discovery:**  [New Source: DynamoDB](https://app.harvestr.io/components/0/list/3OADHzBP0)

**Comment by mcfearsome** [comment]
Curious if there is any news here? Would really like to get `airbyte` into my org and this would be the ideal way for me.

**Comment by akshay-github-acc** [comment]
Workaround :
I am working on a Datapipeline and I am also reading data from DynamoDB and dumping it on my Data warehouse, which is snowflake in my case. Since Airbyte does not support DynamoDB as source, so the work around which I have opted is to dump data (using a python script) from DynamoDB to csv on a Datalake , which is S3 in my case, then use Airbyte to read data present in csv and then dump it to snowflake.
Kindly note: Since Airbyte is not keep track of any cursor (check-point till which data has been ingested) , so I am maintaining that part in my transformation using DBT.

I am using Airflow to orchestrate the whole process so I have written that python script in airflow itself. 

You can follow following link to under how to dump data from DynamoDB to S3.
https://medium.com/towards-data-engineering/scan-complete-dynamodb-table-python-9f61acce4a20
https://randomwits.com/blog/export-dynamodb-s3

Once you have done this then you can use Airflow.

**Comment by Tomperez98** [comment]
I just did the first commit to PR [#14555](https://github.com/airbytehq/airbyte/pull/14555). check() method implemented.
Working on the `describe()`, `read()`, and then I intend to work on the different required tests

**Comment by marcosmarxm** [comment]
Closed by https://github.com/airbytehq/airbyte/pull/18750
