### ISSUE TITLE
🎉 new source: Airbyte-native Shopify connector

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#3581]
## Tell us about the new integration you’d like to have
Our current shopify connector is based on Singer. This makes the iteration cycle longer as described in #3582 . We'd like to migrate our Shopify source connector off of the Singer-based one and onto an Airbyte-based package using the CDK. 

## Describe the alternative you are considering or using

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200368060087111/1200376844471650) by [Unito](https://www.unito.io)

**Comment by bazarnov** [comment]
#3576 https://github.com/airbytehq/airbyte/issues/3576#issuecomment-847596183
This issue should probably be covered with this implementation as well but I didn't test towards the Public App, since "Public App" with right permissions on data (read/write scopes) needs to be accessed first. We should listen to the customer's feedback on this, but this should work as is.
