### ISSUE TITLE
add retention policies for pod histories

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#3634]
see https://stackoverflow.com/questions/41385403/how-to-automatically-remove-completed-kubernetes-jobs-created-by-a-cronjob

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200368060087111/1200387298030973) by [Unito](https://www.unito.io)

**Comment by jrhizor** [comment]
We could switch to using `Job` instead of `Pod` to take advantage of https://kubernetes.io/docs/concepts/workloads/controllers/job/#ttl-mechanism-for-finished-jobs or we'll have to have a separate sweeping thread.

**Comment by davinchia** [comment]
I don't have the best experience with Kube jobs. If the underlying pod fails, the job will retry repeatedly until it hits some configured limit. Because the job -> pod lifecycle isn't integrated well, I suspect we are going to have to track both statuses, which will make our process handling more complicated, so I'd prefer not to use it.

The sweeper is simple enough that it seems an okay solution and not worth taking on the additional cost of the job abstraction. I'm thinking of a pod running `kubctl get pod | grep Compl | awk '{print $1}' | xargs kubectl delete pod' on some cadence. How does that sound?

**Comment by jrhizor** [comment]
I think we should do it with the Kubernetes API abstraction in some background task on the scheduler, and it should operate based off of our tags for what to sweep, but yes, I think the sweeping "cron" does seem much easier

**Comment by davinchia** [comment]
@jrhizor I think splitting the sweeper out into a separate deployment will be cleaner than having it run as part of the scheduler.  Kube can then manage the scheduling of the sweeper pod and make sure its always up.

Agree on using Java Kube api.

**Comment by davinchia** [comment]
@ChristopheDuong pointed out that if we have a separate deployment, using a bash command is easier and simpler.
