### ISSUE TITLE
[source-hubspot][destination-bigquery] Ignore Detect and propagate schema changes is NOT WORKING

### ISSUE THREAD

**Issue by nimuriel** [airbytehq/airbyte#36352]
### Connector Name

Hubspot-BigQuery

### Connector Version

0.2.33

### What step the error happened?

During the sync

### Relevant information

The connector is set up to avoid all the de-normalized "properties_field_name" for Deals, Companies, Contacts, Engagements, I only care about the "properties" json field, however, when new properties are created, the "IGNORE" Detect and Propagate changes doesn't work.  All new columns / properties are added to the synced stream, which makes a mess the end table.

### Contribute

- [ ] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
Hello @nimuriel the version you're reporting is not compatible with latest version for any connector you're reporting.
The issue is likely to be related to Bigquery destination. 
Make sure to use latest version of the Bigquery Destination Connector and the Airbyte Platform.
Please open a new issue reporting the problem to Bigquery and what version of the Platform you're using.
