### ISSUE TITLE
[cdk] Upgrade Airbyte and its dependencies to Pydantic V2

### ISSUE THREAD

**Issue by dtzeng** [airbytehq/airbyte#36475]
### Topic

Upgrade to pydantic v2

### Relevant information

It looks like Airbyte is still using Pydantic v1: https://github.com/airbytehq/airbyte/blob/1b99f1ab8963f66f063cfa6580b64e64c46d7d4c/airbyte-cdk/python/pyproject.toml#L38

Same with protocol models: https://github.com/airbytehq/airbyte-protocol/blob/f92b4afe7b9d2ca3f35ed152f9c3ae212235d472/protocol-models/python/setup.py#L61

Are there any plans to upgrade to V2? https://docs.pydantic.dev/latest/migration/

Creating a new connector that depends on Pydantic V2 is currently impossible because of this.

However, if Airbyte upgrades to V2, you can still use V1 libraries through `pydantic.v1`. See [here](https://docs.pydantic.dev/latest/migration/#continue-using-pydantic-v1-features).

**Comment by marcosmarxm** [comment]
@dtzeng I added the issue to the extensibility team which is responsible for the Airbyte CDK package.

**Comment by mn-mikke** [comment]
+1 The pyndatic upgrade would be helpful.

**Comment by marcosmarxm** [comment]
@mn-mikke can you give more details of your use case?

**Comment by mn-mikke** [comment]
I've created a custom destination connector that pushes data to [our app](https://docs.h2o.ai/enterprise-h2ogpte/). The connector utilises a [Python library](https://pypi.org/project/h2ogpte/) that has Pydantic V2 as a dependency. For now, I have to use really old version of library that still uses Pydantic V1, otherwise I'm not able to build the connector due to the collision with `airbyte-cdk`.

**Comment by sherifnada** [comment]
bumping this one as well, some libs in my project use pydantic v2 and `airbyte-cdk` doesn't allow it

Maybe a simple solution: pydantic v2 ships with the entire v1 lib for backwards compatibility, which can be used via `import pydantic.v1`. Maybe relax the `setup.py` constraint to allow `>=2.0.0` and replace all usages in `airbyte-cdk` with `pydantic.v1` as a stopgap?

**Comment by aaronsteers** [comment]
First of all - hi, @sherifnada! 👋 😄 

Second - this came up this week also on PyAirbyte. Since PyAirbyte depends on the CDK, this issue is a dependency for that one.

- https://github.com/airbytehq/PyAirbyte/issues/216

I've also logged an issue on the upstream `airbyte-protocol-models`, since I think that operation would need to come before this one:

Migration guide here:

https://docs.pydantic.dev/latest/migration/#code-transformation-tool

**Comment by aaronsteers** [comment]
@sherifnada, @dtzeng, @mn-mikke - We're happy to announce that the Python CDK v2.0 now uses Pydantic 2.0. Connector updates are coming soon. As each connector bumps its dependency on the latest CDK version, thereafter they'll each be compatible with Pydantic 2.x.

Closing as resolved. ✅ 🎉 

cc @marcosmarxm, @erohmensing, @natikgadzhi
