### ISSUE TITLE
container-orchestrator-java-opts feature flag not always consistent

### ISSUE THREAD

**Issue by subodh1810** [airbytehq/airbyte#36557]
The connection https://cloud.airbyte.com/workspaces/b61bc266-ef3c-460c-af2f-f70da4a2993c/connections/31331a3d-d8e5-4c9a-b243-e8b6b2a681dd/job-history uses the feature flag `container-orchestrator-java-opts` variation `Debug Logs`. Whats weird is that sometimes the flag seems to be active and we see logs in debug mode while other times we don't! 

[Sync](https://cloud.airbyte.com/workspaces/b61bc266-ef3c-460c-af2f-f70da4a2993c/connections/31331a3d-d8e5-4c9a-b243-e8b6b2a681dd/job-history#9789217::0) where feature flag was not active

[Sync](https://cloud.airbyte.com/workspaces/b61bc266-ef3c-460c-af2f-f70da4a2993c/connections/31331a3d-d8e5-4c9a-b243-e8b6b2a681dd/job-history#9793400::0) where feature flag seemed active

It's weird why sometimes the flag will be active and other times not active.

**Comment by tryangul** [comment]
Reproduced [here](https://cloud.airbyte.com/workspaces/b61bc266-ef3c-460c-af2f-f70da4a2993c/connections/31331a3d-d8e5-4c9a-b243-e8b6b2a681dd/job-history#9836047::0) and confirmed correct java opts were passed and thus feature flag behavior is working as expected. Thus the bug is likely downstream in the replication orchestrator itself.

Values passed match expected.
```      JAVA_OPTS:                                    -XX:+ExitOnOutOfMemoryError -XX:MaxRAMPercentage=75.0 -javaagent:/app/dd-java-agent.jar -Ddd.profiling.enabled=true -XX:FlightRecorderOptions=stackdepth=256 -Ddd.trace.sample.rate=0.5 -Ddd.trace.request_header.tags=User-Agent:http.useragent -DLOG_LEVEL=DEBUG
```

cc @subodh1810

**Comment by subodh1810** [comment]
Oh even I verified that! What I was curious about is why even after the JAVA_OPTS, we didnt see the debugging logs
