### ISSUE TITLE
BigQuery destination: make credentials json optional

### ISSUE THREAD

**Issue by akoshterek** [airbytehq/airbyte#3657]
## Tell us about the problem you're trying to solve
You don't need explicit authentication when a service is running inside Google Compute/Kubernetes engine with a proper service account

## Describe the solution you’d like
Make service account json field optional and don't try to authenticate when it's empty.

## Are you willing to submit a PR?
Yes

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200368060087111/1200389955059431) by [Unito](https://www.unito.io)

**Comment by sherifnada** [comment]
@akoshterek I'm trying to think of what the right UX/interface here should be. 

Maybe we should have something like a drop down list which asks you the kind of auth method you want. One is "no auth" for your case. Another is "Service Account JSON credentials". This is easier to understand as it makes the user think about it (instead of them forgetting to input JSON credentials for example)

**Comment by akoshterek** [comment]
@sherifnada  "No auth" would be misleading imho. It can use a service account attached to the VM or even your personal account when you're logged in GCP on your local machine.

So possibly
"Default auth" and "Service Account JSON credentials"?

With 1st option selected json field should be disabled or disappear, not sure what is possible with `spec.json`

Yes, I can handle it
