### ISSUE TITLE
Support composite cursors & Primary Keys

### ISSUE THREAD

**Issue by davinchia** [airbytehq/airbyte#3737]
## Tell us about the problem you're trying to solve
Just as we allow for primary keys to be composite, cursors should also be composite. This gives users more flexibility so is strictly better.

Change wise, this is pretty simple. All we would have to do is change the defined type. The more involved part is migrating all the relevant connectors today.

More importantly, we should align on whether this is a good decision (sounds like yes) before doing this.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200368060087111/1200399942952192) by [Unito](https://www.unito.io)

**Comment by sherifnada** [comment]
What's an example of a composite cursor?

**Comment by davinchia** [comment]
I'm thinking a paginated list HTTP call with two params, `date-created` and `offset`. We would need both fields to paginate.

I think in general the protocol should mirror what we allow for primary keys, as it's quite logical that they end up being the same field/fields.

**Comment by cgardens** [comment]
Is there a specific ask from a user here? Or just in general it would be good to support.

**Comment by davinchia** [comment]
There wasn't a specific ask. More in general good to support.

**Comment by ajzo90** [comment]
I brought it up in slack because I have stumbled upon this for iterators with limited number of items per call. Theoretically it is possible to get stuck unless you have a composite cursor (assuming at least once delivery). 
In most cases, if a source need a composite cursor, it's probably defined by the source itself. But in cases where the source is of generic character it would make sense to expose it to the user. 

Anther reason for this change is to be consistent with the primary key definition. 
A source should be able to decide whether it support composite cursors or not (basically limit the length to 1) in the spec or catalog.

**Comment by cgardens** [comment]
closed as stale
