### ISSUE TITLE
Appstore connector doesn't show schemas

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#3750]
## Expected Behavior
The connector should work.

## Current Behavior
User adds Appstore connector but no schema appears to be selected.
![image](https://user-images.githubusercontent.com/5154322/120123969-33944480-c188-11eb-8609-9be8383525d2.png)

## Logs
`2021-05-28 20:56:36 ERROR (/tmp/workspace/55/0) DefaultAirbyteStreamFactory(internalLog):108 - There were no sales for the date specified.`
[logs-55-0 (2).txt](https://github.com/airbytehq/airbyte/files/6567073/logs-55-0.2.txt)

## Steps to Reproduce
1. 
1. 

## Severity of the bug for you
Very low / Low / Medium / High / Critical

## Airbyte Version
0.23.0

## Connector Version (if applicable)
airbyte/source-appstore-singer:0.2.2

## Additional context
_Environment, version, integration..._

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200368060087111/1200401791774365) by [Unito](https://www.unito.io)

**Comment by jrhizor** [comment]
relevant: https://airbytehq.slack.com/archives/C01MFR03D5W/p1622235830377700

**Comment by htrueman** [comment]
**Scoping report:**

Found that the issue is in `base_singer/singer_helpers.py`, within `get_catalogs` method.
The string `singer_catalog = json.loads(completed_process.stdout)` produces the json parse exception, for we need to preformat it before parsing into python object.
So the changes are going to be in the appstore singer app. 

Suggested solution:
- Fork appstore singer app;
- Preformat `completed_process.stdout`, then load to python object.
Also appstore creds in LastPass are poorly formated, so need to be updated.
