### ISSUE TITLE
Update the refresh endpoint in order to support merge

### ISSUE THREAD

**Issue by benmoriceau** [airbytehq/airbyte#37636]
In order to support a different merge mode, we need to update the refresh endpoint in order to include the refresh mode.

In order to do that, we will need to add a new enum in the api, which will contain:
- truncate
- merge

The existing endpoint needs to be modified: It currently has a list of stream descriptor, that need to be change to a list of (refresh_type_enum, stream_descriptor).

We also need to handle the mode where no stream is specified (meaning that all the streams are supporting the same refresh mode). There is 2 options here that are up to the implementer:
- Split the endpoint into 2 endpoints: One with the refresh type only present in the list of streams, one without stream and a global refresh type
- Add an optional global refresh type in the same endpoint.
- 

DoD: the endpoint is added to the api.

This needs to be done in coordination with @teallarson

**Comment by teallarson** [comment]
FWIW in the UI we only support the user selecting one refresh type or the other, but two thoughts from my side:

Making refreshType a top-level property like:
```
{
    refreshType: "merge" | "truncate",
    streams: ConnectionStream[]
}
```
would work fine.

2. The frontend already knows all the streams that would be involved in a merge or truncate because we display them in the UI, so it would be straightforward enough for us to pass a list of every stream to refresh even for a full connection refresh.  That said... that may be a pain for API users.
