### ISSUE TITLE
Support horizontally scalable job execution

### ISSUE THREAD

**Issue by ChethanUK** [airbytehq/airbyte#3825]
## Tell us about the problem you're trying to solve
Run scheduling functionality should be horizontally scalable, able to handle running hundreds of thousands of tasks
Running scheduler in a horizontally scalable way: To be able to handle running hundreds of connectors without being limited single nodes computing capabilities

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200368060087111/1200417702501184) by [Unito](https://www.unito.io)

**Comment by jrhizor** [comment]
Note on implementation:
1. We'd need to move all `TemporalPool`-related code to a separate `airbyte-worker` container. Then we could freely scale up the number of `airbyte-workers`. (this is relatively easy to do)
2. The harder part is handling logs and making sure those are ultimately available in the UI. The work we're doing in https://github.com/airbytehq/airbyte/issues/3639 will likely be easy to port to this.

**Comment by cgardens** [comment]
@jrhizor is this a good first issue? it seems pretty complicated.

**Comment by tuliren** [comment]
Agree that this is not a good first issue even for an Airbyte employee. I would feel pretty nervous if this is the first issue assigned to me.

**Comment by jrhizor** [comment]
The 1) step is a minor refactor with adding a module. I'd be completely comfortable giving that to a new employee as a first issue with proper guidance because it gives a good intro into our build/project structure.

2) is very separate and completely unapproachable for newcomers.

Maybe I should have split it into multiple issues. For now I'll just mark as needs scoping.

**Comment by jrhizor** [comment]
This is basically the same issue as https://github.com/airbytehq/airbyte/issues/4232 since the body of the description is about scaling workers horizontally. I'm editing the title of the issue to make that clear what this is talking about and closing as a duplicate.

In the future, we'll need to have something separate for making the scheduler itself horizontally scalable and HA.

**Comment by jrhizor** [comment]
Turns out I misread the purpose of the other ticket. Reopening this.
