### ISSUE TITLE
New Source: Snapchat Marketing API

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#3916]
## Tell us about the new connector you’d like to have
I'd like to read data from the Snapchat Marketing API

https://marketingapi.snapchat.com/docs
https://businesshelp.snapchat.com/s/article/api-faq
https://businesshelp.snapchat.com/s/article/api-apply

**Comment by cheyura** [comment]
**Webhook-based? (no/partially/yes)**
No

**Available authentication modes (API key/Oauth/other)**
The Snapchat Marketing API uses access tokens to control access and authenticate requests, the access token will reflect the user permissions when used in API requests.

The access token should be included in all API requests to the server in the Authorization header in the following way:
Authorization: Bearer meowmeowmeow

To setup OAuth app follow these steps:

- To activate access to Snapchat’s Marketing API, make sure you have a business account set up. Then follow the steps below.
- Log in to Ads Manager.
- Click the menu in the top corner and select ‘Business Details.’ 
- Click '+OAuth App'
- Agree to the terms and conditions to activate access.
- Click 'Save.'
Depending on your objectives you may want the redirect_uri to simply display the code value so that you can copy it and use it in an app built elsewhere to generate tokens, or you may choose to build the entry point for your entire app on the redirect_uri so that it may read the code value automatically upon user authentication.

Creating an account
Self-Service free


How to populate the account with data?
It can be done through the UI, API.

Available streams for sync with limit per request
Creative | 10
Media | 10
Organization | 15
Ad Account | 15
Segments | 15
Campaign | 30
Ad Squad | 30
Ad | 30


Other information/blockers
Refresh tokens if use OAuth on behalf of other user

**Comment by cheyura** [comment]
@sherifnada min budget 5$ per day

**Comment by sherifnada** [comment]
@cheyura please go ahead with creating the campaign

**Comment by TymoshokDmytro** [comment]
## DONE
- Organization 
- Ad Account (Incremental)

## In progress
- Creative 
- Media 
- Segments 
- Campaign 
- Ad Squad 
- Ad
