### ISSUE TITLE
Release community-contributed Google Ads Connector

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#3940]
## Tell us about the problem you're trying to solve
#3842  introduced the Google Ads connector via contribution from the awesome @harshithmullapudi . There's a few loose ends we should tie up once that PR is merged: 

- Add docs to SUMMARY.md, public docs, build status pages. The instructions for getting the account credentials are the same as they are for google adwords. 
- update the contributor in #3869 since he is blocked on that PR
- Update the google adwords connector name in sourcedefinition YAML to add the `(Deprecated)` postfix. We should **not** remove the Google Adwords connector just yet. We still need to implement quite a number of reports and endpoints on Google Ads before we can move forward. 
- Add to source definition YAML/JSON

**Comment by yevhenii-ldv** [comment]
- [ ] Add docs to SUMMARY.md, public docs, build status pages. [1h 30m]
- [ ] update the contributor in #3869 since he is blocked on that PR [30m]
- [ ] Update the google adwords connector name in sourcedefinition YAML to add the `(Deprecated)` postfix. We should **not** remove the Google Adwords connector just yet. We still need to implement quite a number of reports and endpoints on Google Ads before we can move forward.  [30m]
- [ ] Add to source definition YAML/JSON [30m]

**Comment by sdabhi23** [comment]
Do we have any ETA for release?? Also any clues as to how I can test this new connector while am waiting for it to be released?

**Comment by yevhenii-ldv** [comment]
@sdabhi23 
Already released
