### ISSUE TITLE
Obfuscate secrets output in logs

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#4000]
## Tell us about the problem you're trying to solve
While no connectors should generally log secrets, it can sometimes happen due to implementation bugs. This is a security issue and very cumbersome to correct manually when users want to share logs with us for debugging. This is also a blocker for being able to report on 

## Describe the solution you’d like
I would like Airbyte core to obfuscate any secrets in log files such that any instance where the connector is not obfuscating logs is caught by Airbyte core. One implementation for this is to have a mapper which reads any LOG messages on stdout, and any messages on stderr, and for each message obfuscates any secrets based on the knowledge of the connector's config json.

**Comment by jrhizor** [comment]
related: https://github.com/airbytehq/airbyte/issues/3885

**Comment by Phlair** [comment]
Benching my work on this for now after discussing with @subodh1810 and discovering more complexity than initially thought...

First steps seem relatively straightforward:
- On worker start (or thereabouts), look at spec.json for connector to determine keys of airbyte_secret fields
- Map these keys to the config to obtain the actual values of the secrets for this connection
  - these are the values we want to redact 

Ideas for solutions:
- Override LoggerFactory so that every connector instantiates its Logger by doing something like AirbyteLoggerFactory.getLogger(...)
  - [+] This could then be implemented beyond just connectors
  - [-] Requires (small) change to every existing connector
  - [-] Secrets could still appear in logs if standard LoggerFactory is used by accident
- Directly replace secret strings in STDOUT / STDERR on worker
  - [+] More straightforward implementation
  - [-] Code repetition, with more repetition as any new 'steps' are added in the airbyte flow (e.g. source, destination, normalization, every new thing that gets added)
- Programmatically configure log4j2 during runtime to pattern mask secret values
  - [+] Once-implementation, will continue to catch logs on any new 'steps' added in the airbyte flow
  - [-] Requires solid understanding of log4j2... out-of-date docs don't help (we would need to configure at isolated level per connector rather than altering global log4j configuration so that our masks don't accidentally overlap incorrectly)

**Comment by cgardens** [comment]
done.
