### ISSUE TITLE
[source-instagram] Update Media Insights and Story Insights Streams

### ISSUE THREAD

**Issue by im-voracity** [airbytehq/airbyte#40610]
### Topic

Add new metrics

### Relevant information

Since API V18 (currently the connector is using V19) some metrics were deprecated and all the streams do not come with it anymore, but instagram introduced new metrics to replace the old ones, which Airbyte currently does not currently supports, so from these API version updates, we've only lost metrics.

**DEPRECATED METRICS:**
- exits
- taps_forward
- taps_back

**NEW METRICS**:
- follows
- profile_visits
- shares
- total_interactions

[Reference](https://developers.facebook.com/docs/instagram-api/reference/ig-media/insights)

**Comment by marcosmarxm** [comment]
Thanks @im-voracity for reporting the issue. Are you interested in contributing? You can contact me on Slack, and I will direct you what is needed to make the changes.

**Comment by im-voracity** [comment]
Updated issue title and description to better represent the new metrics I'm working on, since I figured some of those new metrics can also apply to media insights, so it's easier to deal with all of them at once.

**Comment by leonardocaloi** [comment]
I am experiencing an issue with the Instagram connector in Airbyte related to the 'video_views' metric. Although the connector is configured to use API version 19.0, I am unable to create a new app or generate an access token with version 19.0—only version 21.0 is available for new applications. In API version 21.0, the 'video_views' metric has been deprecated and is no longer supported.

When attempting to synchronize data using the Instagram connector, I receive the following error from the Graph API:

```
{
  "error": {
    "message": "(#100) Starting from version 21+, the following metric is no longer supported: video_views. Instead, please refer to the documentation at https://developers.facebook.com/docs/instagram-api/reference/ig-media/insights for a list of supported metrics.",
    "type": "OAuthException",
    "code": 100,
    "fbtrace_id": "[REDACTED]"
  }
}
```
Details:

- Issue: The 'video_views' metric is deprecated in API version 21.0, causing synchronization failures because it is still being requested by the connector.
- API Version Constraints: I cannot create an app or obtain an access token using API version 19.0, as only version 21.0 is available for new apps and tokens.
- Impact: The synchronization process fails due to the deprecated metric, preventing the retrieval of updated media insights.

Request:

Update the Instagram Connector: I kindly request that the 'video_views' metric be removed from the API requests made by the Instagram connector, specifically in the 'media_insights' stream, to align with the current API version and supported metrics.
