### ISSUE TITLE
Allow oracle destination to be created without create user privilege

### ISSUE THREAD

**Issue by walkabout21** [airbytehq/airbyte#4064]
# Oracle destination throws a null pointer exception if the login schema user does not have create user privileges. 

###  Create user is a dba level privilege in many organizations and not necessary for the destination to sync data when the destination schema already exists.  If the default schema already exists then the destination should be created even if the login user does not have create user.

**Comment by cgardens** [comment]
good point. I think this makes sense to do. The story around how we represent this in the configuration is going to be a little bit tricky. We have the concept of destinations that support namespaces (putting data in different schemas) and those that do not (only put it in whatever the default schema is), but we don't have a concept of a destination that supports namespaces if certain configuration conditions are met.

We can think about this 2 ways: Either just split out a second oracle connector that has the described behavior or add handling in our configuration model for optionally supporting namespaces based on certain configuration conditions (or at least fails in an obvious way if those conditions are not met). I'm not entirely sure which I'd prefer, both have kinda annoying tradeoffs.

**Comment by walkabout21** [comment]
If you catch the null pointer exception then you should be able to evaluate the state of the db at that time in order to proceed with creating the destination with a warning along the lines of "default user does not have create user privs, destination will only function for existing schemas"

**Comment by walkabout21** [comment]
@cgardens any idea if this is on the roadmap for a near term change?

**Comment by cgardens** [comment]
@walkabout21 thanks for being patient. will try to get you a timeline!

@sherifnada want to bring this area to your attention (sorry I had not labeled it properly previously). Are we in a place where GL could work on this?  would like to give @walkabout21 some idea of when we could get to this.

**Comment by sherifnada** [comment]
we can prioritize for this week or next week. Apologies for the radio silence @walkabout21 !

**Comment by DoNotPanicUA** [comment]
Hi @walkabout21,
I've reproduced the case with a user without CREATE USER privs, but I got a valid error for that:
`java.sql.SQLSyntaxErrorException: ORA-01031: insufficient privileges`
May I ask you to send your airbyte log, mb I missed something in my case.

@sherifnada 
Actually we are checking right now existing of the default schema before trying to create it. The local problem might be in using DBA_USERS table which is not available for a common Oracle user. It's correct to use ALL_USERS. We will see all visible users for us. 
But I think we should do more here. At this moment we are trying to create a user if we can't find it. But in Oracle, it's not enough to start working with this user. We also should provide a list of different grants to it like CREATE SESSION, CREATE TABLE and etc.
Shall I implement the missing user creation part?

**Comment by DoNotPanicUA** [comment]
@sherifnada,
Sorry for misleading you. We actually don't need these privs because we do all that stuff under another user :)
Looks like in this case I'm chasing my own tail :facepalm:

**Comment by marcosmarxm** [comment]
>But I think we should do more here. At this moment we are trying to create a user if we can't find it. But in Oracle, it's not enough to start working with this user. We also should provide a list of different grants to it like CREATE SESSION, CREATE TABLE and etc.
Shall I implement the missing user creation part?

You need to create the new "user"/"schema", grant permission and also after that give permission to the current user to access the new schema.

**Comment by DoNotPanicUA** [comment]
> 
> You need to create the new "user"/"schema", grant permission and also after that give permission to the current user to access the new schema.

I'm not sure that it's our case actually. We have two possible cases here:
1) We logged as a DBA user. - we can create any objects under any schemas so no additional privs are required.
2) We logged as a regular user but with Create user priv. - in this case we can create a new user but we would not create a table without CREATE ANY TABLE permission from this user. (as you actually said) But to get this grant we need to login as the created user and grant it to us. But here we have a problem, we can't login a new user because it requires CREATE SESSION privs and it can be granted only by DBA user.
I think we have a restriction here : "You can't use not existing default destination schema if your user doesn't have DBA role"
P.S. We can dive deeper and provide a list of exact privs required for managing other schemas but usually they are all system-level and rearly granted to a non-dba users.

**Comment by walkabout21** [comment]
I'm not sure I understand how this is closed?  Was a work around created so the destination can be loaded without create user?  The two use cases given require create user.  My use case was a data engineer without create user privs, which is pretty standard separation between engineer and dba.

**Comment by DoNotPanicUA** [comment]
@walkabout21,
If the default destination user is already created and you have enough permissions to create/drop/write there, you can do it without dba. The problem was that even if your destination user exists, we are trying to check it using a DBA view.
The ticket was closed by fix the PR merge.
Please, update your Oracle destination connector version to 0.15 and try your case one more time.
