### ISSUE TITLE
Oncall: Investigate Empty Catalog being sent.

### ISSUE THREAD

**Issue by davinchia** [airbytehq/airbyte#41957]
From https://airbytehq-team.slack.com/archives/C06H4LJRK1Q/p1720657791996809.

We have a Clear operation running for some time now. It seems like an empty catalog is being sent. Investigate if this is the case.

**Comment by tryangul** [comment]
If a reset is requested for streams that are no longer in the configured catalog for the connection, we will send an empty catalog to the source/dest.

**Comment by tryangul** [comment]
[Main discussion thread](https://airbytehq-team.slack.com/archives/C06H4LJRK1Q/p1720657791996809)

[What to do thread](https://airbytehq-team.slack.com/archives/C03AS1GAQV6/p1721081812239639)

**Comment by tryangul** [comment]
## General frequency and distribution
Saw this "stuck connection reset for streams not in the catalog" scenario for 3 connections in the past 30 days. 2 were scheduled postgres dest connections. 1 was snowflake dest and manually scheduled.
Non-postgres destinations should now error out with an explicit "no streams in configured catalog" error, which should prevent them from being stuck. Postgres connections should also start throwing this same error sometime next week. Going forward, we should only see syncs get stuck for destinations without the fix (older, uncertified or custom destinations)

## Root cause
It's unclear how we end up in this scenario, but given the low incidence rate and the pending fix to un-stuck postgres syncs, it doesn't seem pressing to investigate. Nonetheless, we are adding a metric (`sync_with_empty_catalog`) to count the occurrence of syncs started with an empty catalog to keep tabs on the issue.
