### ISSUE TITLE
turn off form autocomplete for configs in browser

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#420]
We shouldn't be allowing the browser to save most of this.

**Comment by cgardens** [comment]
yeah... 

MVP: err on the side of not saving anything. by default turn off for all configuation.
Premium: in configuration we can specify which fields are sensitive or not and the UI respects that.

**Comment by cgardens** [comment]
Let's say the goal for this issue is stop the browser from saving any of the info for configuration fields. @Jamakase is it possible to just completely turn off form auto complete for all of the integration configuration fields (other than the name one at the top)?

![Screen Shot 2020-09-24 at 3 27 09 PM](https://user-images.githubusercontent.com/9092207/94206528-8344a280-fe7a-11ea-89b2-5145f667e375.png)
