### ISSUE TITLE
New Source: Sharepoint

### ISSUE THREAD

**Issue by tokestermw** [airbytehq/airbyte#4254]
## Tell us about the new connector you’d like to have
* Which source and which destination?
Microsoft Sharepoint: https://www.microsoft.com/en-us/microsoft-365/sharepoint/collaboration

* Do you need a specific version of the underlying data source e.g: you specifically need support for an older version of the API or DB? 
No

## Describe the context around this new connector
* Which team in your company wants this integration, what for? This helps us understand the use case.
The machine learning team and the platform team, in order to integrate customer knowledge bases.

* How often do you want to run syncs?
Daily, weekly

* If this is an API source connector, which entities/endpoints do you need supported?
I think https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/get-to-know-the-sharepoint-rest-service?tabs=csom

## Describe the alternative you are considering or using
* What are you considering doing if you don’t have this integration through Airbyte?
Another vendor that has an integration with Sharepoint

**Comment by igrankova** [comment]
**"Webhook-based? (no/partially/yes)** 
partially: https://docs.microsoft.com/en-us/sharepoint/dev/apis/webhooks/overview-sharepoint-webhooks

**Available authentication modes (A key/Oauth/other)** 
API key: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/connect-to-sharepoint
OAuth: https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/authorization-code-oauth-flow-for-sharepoint-add-ins
Other: high-trust SharePoint Add-ins, Add-ins that use the cross-domain library

**Has Sandbox environment?** 
Yes: There are two types of Sandbox solutions:
Code-based sandbox solutions, which contain a custom assembly in the package.
Declarative sandbox solutions, which only contain XML-based configurations and related assets.
https://docs.microsoft.com/en-us/sharepoint/administration/create-test-and-developer-environments

**How to populate the account with data** 
UI
If your applications require more complex GET requests, POST requests or uses more advanced capabilities such as batching, you'll quickly notice that using the SPHttpClient is cumbersome and error-prone. In such cases, you should consider using an alternative such as the PnPjs library that offers you a fluent API that can be verified for correctness by TypeScript.

**Available streams for sync** 
User profiles and groups

**Integration supports incremental sync?** 
Yes: two kinds of synchronization: full and incremental.
Manual sync: On the Start Profile Synchronization page, select Start Incremental Synchronization to synchronize only information that has changed since the last time that you synchronized.
Maintain profile synchronization in SharePoint Server: https://docs.microsoft.com/en-us/sharepoint/administration/maintain-profile-synchronization

**Other information/blockers** 
Incremental sync additional info: https://www.simego.com/blog/2013/09/data-sync-incremental-sync-support"

**Comment by igrankova** [comment]
@sherifnada Ready for implementation

**Comment by igrankova** [comment]
@sherifnada Ready for implementation

**Comment by sherifnada** [comment]
thanks @igrankova !

**Comment by armsepehr** [comment]
@igrankova, Does the implementation of the sharepoint source connector is completed? You closed the issue.

**Comment by igrankova** [comment]
@armsepehr, I apologize, it was accidently closed during the migration to Zenhab.

**Comment by nickblitz** [comment]
Hey @igrankova , just checking if there has been updates made for this. I see it's in done status within the GL roadmap board? Thanks!

**Comment by timxieICN** [comment]
hi team - any update on this?

**Comment by oustynova** [comment]
Hi @timxieICN This Implementation is not in the roadmap right now. @bmcgilli @sherifnada tagging you also

**Comment by timxieICN** [comment]
Thanks for the quick response, @oustynova @sherifnada .
Happy to hop on a call to discuss this further.

TL/DR: We want to set up an ETL process between our internal Sharepoint site and our Cloud Infra (such as AWS S3, etc.). We want to have a way to sync up not only static files stored on Sharepoint (such as pdf, csv, word, etc.) but also the Sharepoint webpages.
We also would like to have a nice way to trigger the ETL sync, such as on-demand trigger, running on a schedule, or event based trigger when new files arrive.

**Comment by timxieICN** [comment]
@oustynova @sherifnada  - any thoughts? ^^

**Comment by nataliekwong** [comment]
This connector is now available as a part of the Airbyte Connector Catalog. 

You can read more about the connector here: https://docs.airbyte.com/integrations/sources/microsoft-sharepoint
