### ISSUE TITLE
[destination-postgres] Postgres Source to Postgres Destination Connector overrides TEXT columns to VARCHAR

### ISSUE THREAD

**Issue by walker-philips** [airbytehq/airbyte#42906]
### Connector Name

destination-postgres

### Connector Version

2.0.15

### What step the error happened?

Other

### Relevant information

A postgres to postgres connection changes source data types of TEXT to VARCHAR in the postgres Destination. While TEXT vs VARCHAR is a somewhat debated topic, I think Airbyte should respect the source systems decision on data typing when possible.

I think it would be beneficial for like to like connectors to have a means of passing their exact schema between each other rather than relying on the default Airbyte JSON typing protocol to guesstimate. Obviously this may introduce some difficulty with differing versions of systems. Perhaps during connection "checking", versions of the systems can be compared with old-to-new or same-to-same allowing "true" data typing pass-through given most people are adhering to backwards compatibility these days.

Why this is giving me problems, I have to alter data types retroactively in the destination database... which becomes increasingly hard as views get built on top of these airbyte tables and prevent data re-typing altogether.

### Contribute

- [ ] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
I think this is expected as Airbyte will transform the Source Postgres data/record to an AirbyteMessage and send to Postgres Destination. This is how Airbyte is designed to allow any source to any destination. If you need "data type parity" probably you need to choose a data migration tool to accomplish your project. 

@airbytehq/destinations maybe has more information about it.

**Comment by walker-philips** [comment]
Is there any intent to revisit the selection of varchar vs text? From the postgres docs: 
```
There is no performance difference among these three types, apart from increased storage space when using the blank-padded type, and a few extra CPU cycles to check the length when storing into a length-constrained column. While character(n) has performance advantages in some other database systems, there is no such advantage in PostgreSQL; in fact character(n) is usually the slowest of the three because of its additional storage costs. In most situations text or character varying should be used instead.
```

**Comment by evantahler** [comment]
This is not something we will support in the near future.  Airbyte's [type system](https://docs.airbyte.com/understanding-airbyte/supported-data-types/) is very limited to support maximum interoperability between different types databases, files, and APIs - at the expense of precision.  Most Airbyte syncs are not to and from the same database technology, so that's not what we optimize for.  

When writing to databases _in general_, we are optimizing to be the most able to store any data we get, so all incoming STRING (airbyte type) columns that the postgres destination gets will be stored as TEXT to fit the largest possible values.
