### ISSUE TITLE
Source Quickbooks: Number data types are being transformed to strings

### ISSUE THREAD

**Issue by maciej-nedza** [airbytehq/airbyte#4292]
## Expected Behavior
According to [docs](https://docs.airbyte.io/integrations/sources/quickbooks) supported streams should leave number fields types as numbers in output schema.

## Current Behavior
Most of number fields are being transformed to strings.
It's probably caused by these fields  in `quickbooks-tap` being defined as  
```
      "format": "singer.decimal",
      "type": [
        "null",
        "string"
]
```

## Steps to Reproduce
1. Create quickbooks source. Quickbooks lets you create free trial account with demo organisation already holding some test data.
2. Create connection between quickbooks source and any destination.
3. Check the source schema, e. g. `Invoices` stream and `TotalAmt` field. It's type is set to string, when it should be a number.

## Severity of the bug for you
Medium

## Airbyte Version
0.26.2-alpha

## Connector Version (if applicable)
0.1.1

**Comment by Zirochkaa** [comment]
@sherifnada login/password are not in Latspass, only test creds.

**Comment by Zirochkaa** [comment]
**Are the account test credentials available in Lastpass?** - yes

## Task breakdown
- [ ] Go through each stream's schema in `sample_files/configured_catalog.json` and update fields types according to [docs](https://docs.airbyte.io/integrations/sources/quickbooks) (~6-7h because streams have large schemas, file contains 4.5k+ rows)
- [ ] Add acceptance tests, at least `spec`, `connection`, `discovery` and `basic_read` tests (`basic_read` will check types of fields) (~4h)

**Comment by vitaliizazmic** [comment]
@Zirochkaa Quickbooks it's Intuit product. We can use its login and password, which is presented in Lastpass.
