### ISSUE TITLE
Allow configuring a sync_success webhook

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#4519]
## Tell us about the problem you're trying to solve
When a sync succeeds I want to receive a notification to a webhook, same as https://github.com/airbytehq/airbyte/pull/2706 but for success notifications.

**Comment by prasrvenkat** [comment]
Would it be ok for me to work on this? @sherifnada 
We have our own state of integrations in our side and internally going to use Airbyte and having this would help us track both success/failure better.
(Ideally we want to customize payloads, but we can work on that after once there is a channel for success with similar structure as failure now)

**Comment by marcosmarxm** [comment]
@prasrvenkat I assigned this to you. You can reach me on Slack if you had any issue =)

**Comment by prasrvenkat** [comment]
> @prasrvenkat I assigned this to you. You can reach me on Slack if you had any issue =)

Awesome, thanks. I will ping you shortly

**Comment by EDjur** [comment]
Hi!

I've been trying out the notifications webhook and it seems to me that there isn't a way of distinguishing which job succeeded/failed just from the webhook response? 

For example, if I have multiple connectors from BigQuery to BigQuery (for reasons), is there any way to know which one of these identical connectors (but with different projects / service accounts) actually succeeded or failed?

I saw you mentioned the ability to customise payloads @prasrvenkat missing currently. So that might be the issue I'm running into here. But wanted to check whether perhaps I'm missing something.

Essentially, I want to automatically perform some actions once a sync finishes. But I need to know which sync actually finished. But all I get currently is just this:

`Your connection from BigQuery version 0.1.4 to BigQuery version 0.5.0 succeeded\nThis was for sync started on Tuesday, November 23, 2021 at 4:23:00 PM Coordinated Universal Time, running for 31 seconds.\n\nYou can access its logs here:`
