### ISSUE TITLE
Source GA: DEADLINE_EXCEEDED exception

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#4536]
## Enviroment
- **Airbyte version**:  ???
- **OS Version / Instance**: ???
- **Deployment**: ???
- **Source Connector and version**: 0.2.6
- **Severity**: High
- **Step where error happened**:  Sync

## Current Behavior
GA connector fails with DEADLINE_EXCEEDED exception

## Expected Behavior
GA connector sync succeeds

## Logs
User to provide

<details>
<summary>LOG</summary> 

```

replace this with
your long log
output here

```

</details>

## Steps to Reproduce
1. Run GA 0.2.6 sync
2.
3.

**Comment by jaimefr** [comment]
I am the user who reported the bug.
Airbyte version: 0.25.0-alpha
OS Version / Instance: EC2 t3.large
Deployment: Docker

I attach the logs. They are quite large but the error happens at the end. This integration is trying to synch 6 tables and  5 of them work properly. I have also another (smaller) synch with those same 6 tables in another Google Analytics account and everything works perfectly. However, this one, it always fails at the same point.

[logs-1032-0.txt](https://github.com/airbytehq/airbyte/files/6762427/logs-1032-0.txt)

**Comment by davydov-d** [comment]
This issue is not about our current GA connector. The bug was reported on Jul 5 2021, version of the connector was 0.2.6, Airbyte version was 0.25.0.alpha. All these facts as well as log records point to `source-googleanalytics-singer`, which we do not have anymore. Now we have CDK version - `source-google-analytics-v4`, so the issue is irrelevant
