### ISSUE TITLE
[connector-request] Google Ad Manager

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#45993]
This is a **suggestion** to create a connector for **Google Ad Manager** using the UI Connector Builder.
The website for the connector is https://admanager.google.com.

If you want to try, claim this issue and start working on it following the steps below.

### Steps:
1. Comment in the issue and wait to be assigned to start working on it.
2. Map the API endpoints (get approval to move to 3 step)
3. Describe steps to get credentials.
4. Create the connector using the UI Builder

> [!IMPORTANT]
> Airbyte doesn't have sandbox credentials for this connector. You must have access/credentials to the service provider to create the connector.

> [!CAUTION]
> This is a **suggestion** and there may be cases where creating the connector using the Builder won't be possible. To minimize the risk of investing a lot of time directly in creating the connector, we strongly recommend to follow steps above.

**Comment by Harmaton** [comment]
Please assign this issue to.me @octavia-squidington-iii

**Comment by marcosmarxm** [comment]
One issue each time @Harmaton you can claim another connector after submit the pull request from the previous one.

**Comment by JoeyAzarAddbloom** [comment]
Hello. Please assign the issue to me

**Comment by JoeyAzarAddbloom** [comment]
Please untag us from this case, we had a confusion with the platform, we thought we were creating the connector for Google Ads not google Ad Manager.

**Comment by bbrewington** [comment]
I probably can't pick this one up, just thought I'd share some hopefully helpful links:

API docs
- As of Oct 20, 2024 the production API is SOAP: https://developers.google.com/ad-manager/api/start
- And there's a REST API in beta: https://developers.google.com/ad-manager/api/beta/getting-started

In case you need to set up an account to test the integration:
- I've seen several comments online saying you need Google AdSense set up in order to use Ad Manager - here's an example: https://lineardesign.com/blog/how-much-does-google-ad-manager-cost/
- Helpful page showing differences between Google Ad Manager & Google AdSense: https://support.google.com/admanager/answer/9234653?hl=en

**Comment by bala-ceg** [comment]
@marcosmarxm, can i try [Google Forms](https://developers.google.com/forms/api/reference/rest) instead of this, since setting up adsense account takes time
