### ISSUE TITLE
[Amplitude] Unable to set up source: Configuration check failed with implausible file size too large error

### ISSUE THREAD

**Issue by rasmuswissmann** [airbytehq/airbyte#46712]
### Connector Name

source-amplitude

### Connector Version

0.6.10

### What step the error happened?

Configuring a new connector

### Relevant information

I consistently get this error when trying to set up an Amplitude source in AirByte Cloud:

<img width="628" alt="Screenshot 2024-10-10 at 10 32 43 AM" src="https://github.com/user-attachments/assets/25b221a2-2842-4d0e-b0e5-ad95a8468f68">

Configuration check failed: "The file size of the exported data is too large. Shorten the time ranges and try again. The limit size is 4GB. Provide a shorter 'request_time_range' interval."

I have tested this against our production Amplitude project — with various start dates and time ranges, though it only has a few hundred events — and a new, empty project. Logs attached. I have also varied the secret to confirm that this changes the error to an access error.

Any ideas? Am I doing this wrong or is there a Connector issue?

### Relevant log output

```shell
2024-10-10 14:26:35 [46mplatform[0m > 
2024-10-10 14:26:35 [46mplatform[0m > Connector exited, processing output
2024-10-10 14:26:35 [46mplatform[0m > ----- START CHECK -----
2024-10-10 14:26:35 [46mplatform[0m > 
2024-10-10 14:26:35 [46mplatform[0m > Output file jobOutput.json found
2024-10-10 14:26:35 [46mplatform[0m > Connector exited with exit code 0
2024-10-10 14:26:35 [46mplatform[0m > Reading messages from protocol version 0.2.0
2024-10-10 14:26:35 [46mplatform[0m > MetricClient has not been initialized. Must call MetricClientFactory.CreateMetricClient before using MetricClient. Using a dummy client for now. Ignore this if Airbyte is configured to not publish any metrics.
2024-10-10 14:26:35 [46mplatform[0m > Check failed
2024-10-10 14:26:35 [46mplatform[0m > Checking for optional control message...
2024-10-10 14:26:35 [46mplatform[0m > Optional control message not found. Skipping...
2024-10-10 14:26:35 [46mplatform[0m > Writing output of fa9f58c6-2d03-4237-aaa4-07d75e0c1396_984ad848-2ee7-40ab-b698-60dc74aabc32_0_check to the doc store
2024-10-10 14:26:35 [46mplatform[0m > Marking workload fa9f58c6-2d03-4237-aaa4-07d75e0c1396_984ad848-2ee7-40ab-b698-60dc74aabc32_0_check as successful
2024-10-10 14:26:35 [46mplatform[0m > 
2024-10-10 14:26:35 [46mplatform[0m > Deliberately exiting process with code 0.
2024-10-10 14:26:35 [46mplatform[0m > ----- END CHECK -----
2024-10-10 14:26:35 [46mplatform[0m >
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by natikgadzhi** [comment]
👀 We haven't looked at this specifically yet, but I think I've seen something similar. 

@bazarnov I wonder if the async component thing is compatible with situations where there is a custom component transformation (like in amplitude) — could we try and move it over? Or could we post a guide here so @rasmuswissmann could try themselves?

**Comment by bazarnov** [comment]
@rasmuswissmann Have you tried to follow the recommendation from the error message?

@natikgadzhi I'll check the `AsyncRetriever` compatibility opportunity for the `source-amplitude` and what it takes to move the `Events` stream to use it.

Because we need to use the `generator` approach instead of having the complete list before we output something. Since the `active users` stream is marked as `stream for check connection`, it might be the case where for the first slice with the step of `P1M` (1 month) we receive more than 4Gb of data.

+ this code part could be moved to use the `generator` approach:
https://github.com/airbytehq/airbyte/blob/baz/source/shopify/track-parent-state-for-bulk-streams/airbyte-integrations/connectors/source-amplitude/source_amplitude/components.py#L52-L55

+ To control the `step size` (which is reasonable in this case), this line should accept the value from the config, or be overridden for the `check connection` specifically (not sure this is possible currently)

@rasmuswissmann Can we test an assumption and set the `Request time range` value for your input configuration to the smaller value of `5 or 6` (default is 24) and re-try to set up the source?

**Comment by rasmuswissmann** [comment]
@bazarnov  Yes — I have tried time ranges with values as low as 1 and 2. I have also tried various options for the start date.

What confused me is that the project has very little data — and that this error also happened on a newly set up, empty project. There should not be 4GB of data, unless Amplitude somehow sends over massive files with non-content data?

**Comment by bazarnov** [comment]
@rasmuswissmann I kindly ask you to run the following `curl` command in the Terminal, and provide the output result here, so we can directly check what's the error message you receive. 

```
curl -X GET 'https://amplitude.com/api/2/users?start=20241001&end=20241028&m=active&i=1&g=country' \
-H 'Authorization: Basic <YOUR_PROJECT_API_KEY>'
```

It's clear that the source receives the `HTTP-400`, which might be treated in a different way on our side, also.

**Comment by rasmuswissmann** [comment]
@bazarnov If I run the exact command, I get 

`{"error": {"http_code": 400, "type": "invalid", "message": "Invalid chart definition", "metadata": {"details": "Invalid user property country"}}}%`

Without the '&g=country' it returns successfully

`{"data": {"xValues": ["2024-10-01", "2024-10-02", "2024-10-03", "2024-10-04", "2024-10-05", "2024-10-06", "2024-10-07", "2024-10-08", "2024-10-09", "2024-10-10", "2024-10-11", "2024-10-12", "2024-10-13", "2024-10-14", "2024-10-15", "2024-10-16", "2024-10-17", "2024-10-18", "2024-10-19", "2024-10-20", "2024-10-21", "2024-10-22", "2024-10-23", "2024-10-24", "2024-10-25", "2024-10-26", "2024-10-27", "2024-10-28"], "series": [[7, 5, 4, 8, 7, 6, 10, 7, 3, 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], "seriesCollapsed": [[0]], "seriesLabels": [0], "seriesMeta": [{"segmentIndex": 0}]}}%`

**Comment by bazarnov** [comment]
@rasmuswissmann Based on the fact you have the non-successful API call we need either to `group by country` on the side of you Amplitude account or disable the `&g=country` (grouping by Country property) in the way we work with the Amplitude API.

We have to estimate the possible impact of the change on our side, before we move on with the change. 

In a meanwhile, could you please try to enable such grouping for the Users, Dashboard or similar and run the API call with `&g=country` again? 

@natikgadzhi I'm pretty sure we can handle the issue here, it's clear to me what's going on and we have options worth discussing.

**Comment by bazarnov** [comment]
The quick patch to unblock Customers setting up the source: https://github.com/airbytehq/airbyte/pull/46736

The long-term fix is to handle this dynamically by looking at the `error code + error message`, not `error code` only; thus raising the meaningful log message to `disable the Groupping by Country`, because it's not available for the authenticated user.

**Comment by bazarnov** [comment]
@rasmuswissmann The patch was merged, please try to set up the source again but now set the `Options > Active Users Group by Country` to `False`.

**Comment by rasmuswissmann** [comment]
@bazarnov This fixed it. The behavior just as you expected: Switching the optional grouping off = works. Switching it on = error. 

Thank you for debugging and merging a patch so quickly. Amazing!

**Comment by bazarnov** [comment]
Closing this one. @rasmuswissmann thank you for the bug, we couldn't catch before)
