### ISSUE TITLE
CDK: Allow setting request data on the outgoing HTTP requests

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#4764]
## Tell us about the problem you're trying to solve
A user writing a connector for a SOAP API needs to set the `data` param on the outgoing request. Currently the HTTPStream abstraction only allows setting `json` not `data` on the outgoing request. 

See slack convo for more info: https://airbytehq.slack.com/archives/C021JANJ6TY/p1626352477204300

## Describe the solution you’d like
Add a method `request_data` similar to `request_json` which allows setting this info.

**Comment by Zax337** [comment]
Hi, I'm the aforementioned user trying to make a SOAP API connector, to add a bit more details to this, here is how I offer to solve this problem:

1. add a new method `HttpStream::request_body_data` with the same purpose as `request_body_json`:
```    
def request_body_data(
        self,
        stream_state: Mapping[str, Any],
        stream_slice: Mapping[str, Any] = None,
        next_page_token: Mapping[str, Any] = None,
    ) -> Optional[Mapping]:
        """
        Override when creating POST requests to populate the body of the request with a non-JSON payload.
        """
        return None
```
2. Update HttpStream::`read_records` to also call this method
 ```
request = self._create_prepared_request(
                path=self.path(stream_state=stream_state, stream_slice=stream_slice, next_page_token=next_page_token),
                headers=dict(request_headers, **self.authenticator.get_auth_header()),
                params=self.request_params(stream_state=stream_state, stream_slice=stream_slice, next_page_token=next_page_token),
                json=self.`request_body_json(stream_state=stream_state, stream_slice=stream_slice, next_page_token=next_page_token),
                data=self.request_body_data(stream_state=stream_state, stream_slice=stream_slice, next_page_token=next_page_token),
            )
```
3. Update `HttpStream::_create_prepared_request` to take `data` into account:
```
def _create_prepared_request(
        self, path: str, headers: Mapping = None, params: Mapping = None, json: Any = None, data: Any = None
    ) -> requests.PreparedRequest:
        args = {"method": self.http_method, "url": self.url_base + path, "headers": headers, "params": params}

        if self.http_method.upper() == "POST":
            args["json"] = json
            args["data"] = data

        return self._session.prepare_request(requests.Request(**args))
```
Given that at no time the HttpStream class is parsing the actual content sent or received (because your code architecture is on point :heart: ), it should not matter which kind of body is provided except for when given to `requests`, so this should be sufficient. The user can then choose to implement `request_body_json` or `request_body_data` depending of their use case.


For now I just created a new connector based on the HTTP one and overwrote `_create_prepared_request` to put the `json` content (which is actually XML then) into `args["data"]` (ie., `args["data"] = json` instead of `args["json"] = json`) and it works. I need this connector ASAP so I'll use this for now, but I figured that could be useful for the community too. ;)


I'll be happy to discuss if you need further details. 
Thanks for the great tool in any case!

**Comment by sherifnada** [comment]
@Zax337 that's a good way of going about it! Thanks for the great writeup. Since you already basically scoped this out, would you want to contribute it to the CDK? No pressure, just thought I'd see if you're interested.

**Comment by Zax337** [comment]
@sherifnada I'd love to! I'm very busy at the moment though so I probably won't be able to focus on that before a week or two.
