### ISSUE TITLE
[source-stripe] Customer_Balance_Transaction records are occasionally getting missed

### ISSUE THREAD

**Issue by williamkaper** [airbytehq/airbyte#48857]
### Connector Name

source-stripe

### Connector Version

5.8.0

### What step the error happened?

None

### Relevant information

We are seeing CBT's that aren't getting picked up on created/updated. I would have assumed since there is a created event for customer_balance_transaction [(doc here)](https://docs.stripe.com/api/events/types#event_types-customer_cash_balance_transaction.created), the updated would catch it if the record was "created" after the last sync but with a created value that was before the last sync. [https://github.com/williamkaper/airbyte/blob/e1217e8c7e5ce8400dc7a0eb0c25e2426734c[…]e-integrations/connectors/source-stripe/source_stripe/source.py](https://github.com/williamkaper/airbyte/blob/e1217e8c7e5ce8400dc7a0eb0c25e2426734c80f/airbyte-integrations/connectors/source-stripe/source_stripe/source.py#L497)

If that is not the case, then I'm worried that I might need to change this sync so its more like a normal balance transaction where it only has a created date and can leverage a look-back window to pick it up. Is there anyway I could get someone on the team to take a quick peek at this and weigh in?

### Relevant log output

```shell

```

### Contribute

- [x] Yes, I want to contribute

**Comment by williamkaper** [comment]
@marcosmarxm @maxi297 I may have had an epiphany on what is going on, but I'd love for you to check my thinking to make sure it pencils out before I open up a PR fix for it. 

In [PR 46864](https://github.com/airbytehq/airbyte/pull/46864/files) I introduced support for customer balance transactions to pull incrementally instead of requiring a full resync each time. The previous implementation only tried pulling records when a customer's balance was zero, but that missed updated where offsetting CBT transactions occurred raising and then lowering the balance. It was also an intensive pull when a Stripe customer had a lot of `customer` records because unfortunately, Stripe doesn't offer a `list all` style operation to get all customer balance transactions for all customers. The API for customer balance transactions needs to be called per customer. (This itself is its own pain if you have millions of customers in your Stripe database due to Stripe not being willing to add a sensible batch retrieve method for all customers).  

When I coded this solution, I assumed the way UpdatedCursorIncrementalStripeSubStream would work is it would call it once per customer to pull any incremental updates on the event_type `customer_cash_balance_transaction`. However, I'm noticing for the customers that I'm seeing CBTs not getting captured, they have never been updated. That is making me wonder if CBT's are only getting checked if the customer first has been incrementally updated. 

If this is indeed what is happening, then I'd like to make the call to CBT for a customer ID anytime a customer stream record is updated OR a new `customer_cash_balance_transaction` is created.  I think one solution would be to add `customer_cash_balance_transaction` to the list of customer events https://github.com/williamkaper/airbyte/blob/e1217e8c7e5ce8400dc7a0eb0c25e2426734c80f/airbyte-integrations/connectors/source-stripe/source_stripe/source.py#L138 (Please check my thinking on this). Another is to have a different sub-stream method that did this type of logic. I don't have a strong enough understanding of how the events marry into the records to know the best way to try even to approach that.

**Comment by williamkaper** [comment]
I updated above to more accurately reflect my current research/troubleshooting

**Comment by marcosmarxm** [comment]
@maxi297 do you mind taking a look into this issue reported by William?

**Comment by williamkaper** [comment]
This is my first attempt at a fix - [](https://github.com/airbytehq/airbyte/commit/5395a98982678ce3b4bbd5bd93831bdf5b201d63
)

**Comment by maxi297** [comment]
Just to share my understanding:
* `customer_cash_balance_transaction` events return a `customer_cash_balance_transaction` objects
  * Those objects are different than `customer_balance_transaction`
  * They can be retrieved through `v1/customers/<customer id>/cash_balance_transactions` and not through `v1/customers/<customer id>/balance_transactions`
* I don't see any events for `customer_balance_transaction`
* Based on [this documentation](https://docs.stripe.com/billing/customer/balance), the customer balance transaction is immutable so we can probably retrieve it filtering on `created[gte]`: `Because the credit balance is computed from a ledger — an immutable list of debit and credit transactions — it provides an audit trail of transactions for the customer. These [Customer Balance Transactions](https://docs.stripe.com/api/customer_balance_transactions/object) can refer to the object related to the adjustment`

The change you are proposing would change it so that we do the following in incremental mode:
```
state = start_date
created_query_param = start_date
for each customer_id:
  for each transaction get customer_balance_transactions where created > created_query_param:
    emit transaction
    state = max(state, transaction.created)
```

That change makes sense to me in the short run but it seems like we could be at risk of losing transactions on the next incremental sync. The example would be if we have the following set of events:
* T0: Our connector does a request for customer ID `customer_id1`
* T1: A transaction is added for `customer_id1`
* T2: A transaction is added for `customer_id2`
* T3: Our connector does a request for customer ID `customer_id2` and a transaction with `created = T2` so we update the state to `T2`

In the case above on the next sync, we will query only for transactions where `created > T2` which means that the transaction that happened at T1 for `customer_id1` will never be emitted. I assume:
* All `ParentIncrementalStripeSubStream` streams can be affected by this issue
* Either the likelihood of such dataloss is low or we don't have enough users to have this bug being reported to us

Does that reasoning make sense to you? I've created [an issue](https://github.com/airbytehq/airbyte-internal-issues/issues/11066) for this problem. In the meanwhile, I think your change makes sense. If you think you might be affected by this dataloss, I suggest that you run things in full_refresh mode for now. We will refine this issue with the team next Tuesday and see what is the priority and how we will tackle this.

**Comment by williamkaper** [comment]
@maxi297 That makes sense. I agree, with this change, the risk of data loss is low but non-existent. Full Refresh on CBT is problematic, because of Stripe's bullshit API for CBTs where they don't emit an event on created nor do they have a list-all for all customers CBTs, either of which would solve this. 

We have a HubiFi customer with a Stripe Account with over 1.5M customer records. Doing a full refresh means we need make 1.5M calls every full refresh. No only does that take a good 6+ hours to complete, but it spikes Airbtyes memory consumption (I'm guessing all the customer records gets loaded into memory and the customers that are processed aren't being dereferenced thus are  getting held onto). 

If this change works, for now I'm going to run on a custom build of the stripe connector with the commit above cherry-picked.

**Comment by maxi297** [comment]
@williamkaper we will be looking at this change soon-ish. The expectation is that we will be working on moving source-stripe to our no-code framework in the coming weeks in order to simplify maintenance. It's not only for maintenance though. For example, the problem I mentioned above is already solved for free with this. So I think I would process in two steps:
* We can apply the changes from https://github.com/airbytehq/airbyte/commit/5395a98982678ce3b4bbd5bd93831bdf5b201d63 (very nit is I think we can remove the `legacy_cursor` but I'm fine with keeping it). Can you put up a PR for that?
* Our team will be looking that the dataloss issue while doing the migration to no-code in the following weeks

Let me know if you have concerns around this plan and we'll figure these out together 💪

**Comment by williamkaper** [comment]
I already removed Legacy_cursor. This change seems to have resolved the
issue, but I'm looking forward to seeing what the low code Stripe looks
like!

I'll put up a PR either tomorrow or next week as an interim solution.

*Bill Kaper*


*HubiFiCo-Founder | CTO*724.421.4888
***@***.***
Book an appointment <https://calendar.app.google/C9Ne6V53c7B41BJp8>

**Comment by williamkaper** [comment]
> [@williamkaper](https://github.com/williamkaper) we will be looking at this change soon-ish. The expectation is that we will be working on moving source-stripe to our no-code framework in the coming weeks in order to simplify maintenance. It's not only for maintenance though. For example, the problem I mentioned above is already solved for free with this. So I think I would process in two steps:
> 
> * We can apply the changes from [5395a98](https://github.com/airbytehq/airbyte/commit/5395a98982678ce3b4bbd5bd93831bdf5b201d63) (very nit is I think we can remove the `legacy_cursor` but I'm fine with keeping it). Can you put up a PR for that?
> * Our team will be looking that the dataloss issue while doing the migration to no-code in the following weeks
> 
> Let me know if you have concerns around this plan and we'll figure these out together 💪

PR up: https://github.com/airbytehq/airbyte/pull/49811
