### ISSUE TITLE
[EPIC] Apply snowflake recommended best practices to Snowflake destination connector

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#4904]
## Tell us about the problem you're trying to solve
Placeholder for following the directions [here](https://drive.google.com/file/d/1Ftb0AykACbspwFTdv498UC7DQELahmvh/view?usp=sharing)

- [x] #4371 
- [x] #10033
- [x] #9907

**Comment by jrhizor** [comment]
related: https://github.com/airbytehq/airbyte/issues/4370

**Comment by etsybaev** [comment]
1. JDBC driver is already used for connection.
2. The UI is already designed to select Snowflake from the drop-down menu as an option and contains usages guide.
3. A driver's version has been updated
4. The "application" parameter (partner names) is set to "airbyte"
5. ACTION_REQUIRED: Azure uploading method option is not implemented yet. Do we need it?
6. Username and password auth option is already implemented, OAuth would be done as part of https://github.com/airbytehq/airbyte/issues/6201
7. Not applicable. As we have multiple source connectors we can not identify DB's specific types but use generic ones. 
8. Default object names pattern is used.
9. Additional connection parameters are exposed  such as "role", "warehouse", "database","schema".
10. Metadata: Not used
11. ACTION_REQUIRED: Ensure you are escaping underscores in all metadata objects. Otherwise,
these will be treated as a wildcard characters resulting in the calls going
against the full account (for example, the database name FOO_BAR). In
addition to performance concerns, this can also lead to excessive Cloud
Services usage/cost.
For example, to avoid having the underscore character being
used as a wildcard which will retrieve metadata for all objects
via ODBC/JDBC, a backslash ("\") character needs to be used
in front of the underscore character to escape the underscore
and prevent it from being used as a wildcard character. The
drivers will then correctly identify the specific path for the
objects to perform the metadata call.
12. We already have an option with internal staging, the batch size is configurable, Azure Blob Storage support is missed, but this was already added as an action point earlier. We already use a single session for a stream. Error handling is added as part of centralized exception handling. OAuth will be added as part of another ticket. 
13. Direct query method is already used. OAuth will be added as part of another task. Materialized Views will not be used in the destination connector. "Awareness of Multiple Virtual Warehouses" is not applicable, User will have to set URL. Custom connection properties are already supported. 
14. Points either not applicable or already implemented.
