### ISSUE TITLE
Issue when running docker compose-up on Mac

### ISSUE THREAD

**Issue by johnlafleur** [airbytehq/airbyte#492]
Here is what the console returns:
```
docker-compose up
Starting airbyte_init_1 ... done
Starting airbyte-db        ... done
Starting airbyte-data-seed ... done
Starting airbyte-scheduler ... error
Starting airbyte-server    ...
ERROR: for airbyte-scheduler  Cannot start service scheduler: error while mounting volume '/var/lib/docker/volumes/local/_data': failed to mount local volume: mount /tmp/airbyte_local:/var/lib/docker/volumes/local/_data, flags: 0x1000: no sStarting airbyte-server    ... done
Starting airbyte-webapp    ... done
ERROR: for scheduler  Cannot start service scheduler: error while mounting volume '/var/lib/docker/volumes/local/_data': failed to mount local volume: mount /tmp/airbyte_local:/var/lib/docker/volumes/local/_data, flags: 0x1000: no such file or directory
ERROR: Encountered errors while bringing up the project.
```

**Comment by cgardens** [comment]
I think the issue here is that there is an old docker volume present that is colliding with the volume that the current app is trying to use. So far running `docker volume rm $(docker volume ls -q)` and then running compose up has fixed it. 

This does seem like it's gotten a little more brittle though as I'm getting it as I switch between branches which shouldn't be the case. Going to keep this open for now to see if I can't figure out why it has gotten more brittle.

**Comment by jrhizor** [comment]
We should rename to `airbyte_local` and `airbyte_workspace` in case `local` is being used by an actual volume in use by something else on Docker.

**Comment by cgardens** [comment]
We have moved way from using named volumes and just bind directories, so this issue should now be resolved.
