### ISSUE TITLE
oracle hyperion essbase

### ISSUE THREAD

**Issue by charlesmiao** [airbytehq/airbyte#4971]
## Tell us about the new connector you’d like to have
* Which source and which destination?
* Do you need a specific version of the underlying data source e.g: you specifically need support for an older version of the API or DB? 

## Describe the context around this new connector
* Which team in your company wants this integration, what for? This helps us understand the use case.
* How often do you want to run syncs?
* If this is an API source connector, which entities/endpoints do you need supported?

## Describe the alternative you are considering or using
What are you considering doing if you don’t have this integration through Airbyte?

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by karinakuz** [comment]
**Integration Vetting**

**Webhook-based?** (no/partially/yes) if partially, mention which endpoints are webhook-based
 **_no_**

**_Available authentication modes_** (API key/Oauth/other) 
**_You access Oracle Essbase REST resources over HTTPS, using HTTP Basic authentication. To use HTTP Basic authentication to validate users, you specify the user name and password for your Essbase account in the Authorization header._**  https://docs.oracle.com/en/database/other-databases/essbase/19.3/essrt/authenticate.html

**Connecting to the data source what kind of API is it?** (SOAP/GraphQL/REST/other) 
**_REST API_** https://docs.oracle.com/en/database/other-databases/essbase/19.3/essrt/index.html 

**is there an SDK available?** Can we connect with HTTP requests directly? 
_**yes**_

If this is a database/datalake/pubsub source, **does it have a JDBC driver or Java SDK?** 
_**Java SDK**_

**Creating an account** 
 Select one of the below options 
self-service free account available?
**_30-days are trial_**

**Comment by karinakuz** [comment]
Blocker: For creation Free Trial Oracle Cloud account Payment verification is required. I used billing data from LastPass, but verification failed. Sent letter to support.

**Comment by karinakuz** [comment]
We still have an issue with the card and no answer from  Oracle Customer Service https://signup.cloud.oracle.com/?verify_email=eyJhbGciOiJIUzI1NiJ9.eyJmaXJzdE5hbWUiOiJKZWFuIiwibGFzdE5hbWUiOiJMYWZsZXVyIiwiY291bnRyeSI6IlVTIiwic3ViIjoib2NpLXNpZ251cCIsImlzcyI6Imh0dHBzOlwvXC9zaWdudXAub3JhY2xlY2xvdWQuY29tIiwiaXNPcGF5T3V0YWdlIjpmYWxzZSwidXNlclNlc3Npb25JZCI6InNpZ251cF82NjRkNjI4MS01ODRiLTRiNTUtYmNhYi0wNDE2OTg2OTQ5OTYiLCJleHAiOjE2NDAwOTQzMDksImlhdCI6MTY0MDA5MjUwOSwiZW1haWwiOiJpbnRlZ3JhdGlvbi10ZXN0QGFpcmJ5dGUuaW8ifQ.YLiIT3ha9urdvw6FGemKXzkVdvMLDIVXBX8bIHv5p6Q&sourceType=:ow:o:h:nav:OHP0625ViewAccountsButton%20:ow:o:p:feb:0916FreePageBannerButton: 

**_Error processing transaction
We're unable to complete your sign up. Common sign up errors are due to: (a) Using prepaid cards. Oracle only accepts credit card and debit cards (b) Intentionally or unintentionally masking one's location or identity (c) Entering incomplete or inaccurate account details. Please try again if this applies to you. Otherwise, contact Oracle Customer Service._**

@sherifnada could we use another card for the Payment verification?
