### ISSUE TITLE
Support basic normalization for MySQL 5.x

### ISSUE THREAD

**Issue by tuliren** [airbytehq/airbyte#4989]
## Tell us about the problem you're trying to solve
- Currently MySQL basic normalization relies on the `WITH` keyword, which is only available for 8.0 or later versions.
- But we have seen a few requests about supporting basic normalization for older MySQL versions.

## Describe the solution you’d like
- Replace `WITH` with something else.

## Describe the alternative you’ve considered or used
- N/A

## Additional context
- N/A

## Are you willing to submit a PR?
- No.

**Comment by ChristopheDuong** [comment]
the `WITH` keyword is used when dbt materialization is in `ephemeral` mode.

I looked over the files we generate and we don't use `WITH` keywords explicitly anymore so it should be possible to do normalization without `WITH` keywords as it is shown in the generated SQL here:
https://github.com/airbytehq/airbyte/tree/master/airbyte-integrations/bases/base-normalization/integration_tests/normalization_test_output/postgres/test_primary_key_streams/final/airbyte_tables/test_normalization

maybe we just need to make sure to disable the ephemeral settings for MySQL not in version 8+?

**Comment by philippeboyd** [comment]
@ChristopheDuong any news on this? This prevents us to do sync with normalization in MySql 5.7 as per issue #5117 

Is there an easy way to disable `ephemeral ` mode when the destination is less than MySQL 8 ?

**Comment by ChristopheDuong** [comment]
You can also export the generated "normalize" folder, change the materialization setting in the `dbt_project.yml` file, and re-import them as a custom dbt transformation step to be applied after your sync (disable the basic normalization step then)

This is described in the series of tutorials here: https://docs.airbyte.io/operator-guides/transformation-and-normalization/transformations-with-sql 

I think one of the issues with running normalization on MySQL < v8 is that there is still some usage of the `WITH` keyword when unnesting tables. But if you don't this case, you could work around it (otherwise I can also give you pointers on how to unnest without the with keyword too)

**Comment by ChristopheDuong** [comment]
> I think one of the issues with running normalization on MySQL < v8 is that there is still some usage of the WITH keyword when unnesting tables. 

@tuliren mentioned that the `WITH` keyword is still being referenced in normalization here:

https://github.com/airbytehq/airbyte/blob/5a0d7afcc88c2514b08128bdc1aa0ee675d87df6/airbyte-integrations/bases/base-normalization/dbt-project-template/macros/cross_db_utils/array.sql#L115

Instead of having a MySQL macro to unnest using CTE (ie with keyword queries), we could create _ab5, _ab6 model files instead and disable ephemeral settings for that destination (if version is < v8)

**Comment by marcosmarxm** [comment]
Normalization and custom dbt are deprecated features and will be removed soon from the project. For that reason I'm closing the issue as it won't be implemented anymore.
