### ISSUE TITLE
Research/POC: Using xmin in PostgreSQL-connector to do incremental updates without CDC

### ISSUE THREAD

**Issue by esenilsson** [airbytehq/airbyte#5022]
## Tell us about the problem you're trying to solve
I want to do incremental updates from Postgresql to Snowflake, but struggle to do so. I have a postgresql database where I am not able to use CDC or any type of replication. In addition I have no "updated_at" column or similar.

## Describe the solution you’d like
I suggest a solution that Fivetran also has. As I understand it, the idea is to do a full table-scan on the system column XMIN to see which entries were added since last. [Fivetran documentation](https://fivetran.com/docs/databases/postgresql#updatingdata)

## Describe the alternative you’ve considered or used
I have used a bash script where I execute a SQL selecting entries that has change since last time (by checking 4 different columns for a newer date since last). Could potentially also use xmin here.

## Are you willing to submit a PR?
Currently do not have the competencies

**Comment by grishick** [comment]
Setting a timebox to 13 points (about a half of a 2 week sprint)

**Comment by edgao** [comment]
some WIP notes:
* need to figure out how to handle xmin wraparound. Fivetran docs have a few cases where they force a full resync, and I suspect we'll need to support those as well
* need to check if normalization needs the cursor values, or if we can filter out xmin entirely. IIRC incremental+deduphistory uses the cursor (which makes sense) so might need to add special handling for it

**Comment by edgao** [comment]
@cgardens replying to your comment https://github.com/airbytehq/airbyte/issues/14732#issuecomment-1216898759

I think that protocol could be made to work, with a few caveats.

In its current form, it will _always_ generate duplicated records after a wraparound: Imagine an append-only source table; eventually there will be two rows with `xmin=0`. Postgres _does_ provide a way to distinguish between those rows, but (I think?) it requires installing the `pageinspect` server extension, and I'm not sure that's a thing we want to require.

Specifically: Postgres periodically "freezes" old xmin values ("frozen" xids are treated as older than any other xid value; this is necessary to maintain transaction semantics) - this happens at least once every 2 billion transactions (i.e. a bit less than `2^31`). Prior to postgres 9.4, this was accomplished by setting them to the value `2` (which is easy to detect), but in >=9.4 they just set a flag bit on the tuple header, which we can't read without the extension.

The pre-9.4 behavior is also kind of problematic, in that we would need to check if `oldest unfrozen xmin in table <= xmin in cursor`. If that's not the case, then we have no way to find the records after `xmin in cursor` but before `oldest unfrozen xmin in table`, which forces us to do a full refresh. (though 9.4 came out in 2014, so maybe not worth worrying about?)

We'd also need to handle xmin values in normalization, which requires strictly orderd cursors. This is maybe workaraoundable by using `(txid_current() >> 32 << 32) + xmin` as the cursor (`txid_current()` is a 64-bit int representing the current transaction ID, and it does _not_ wrap around). But this is getting pretty deep into postgres guts and I'm still trying to convince myself that this is actually correct.

**Comment by cgardens** [comment]
@edgao got it! I guess if we can get a handle on how often the edge case that is mentioned in this issue https://github.com/airbytehq/airbyte/issues/14732 , from there we can decide if we want to explore this approach or not.

**Comment by edgao** [comment]
Shelving this issue for now - this is unfortunately somewhat niche, and requires a pretty hefty set of changes. Summarizing those here for future people:
* Require users to install the pageinspect server extension if they want to use xmin (this is required for querying whether a row is frozen https://stackoverflow.com/a/69319339 )
* Use the algorithm described in https://github.com/airbytehq/airbyte/issues/14732#issuecomment-1216898759, but filter out [frozen rows](https://www.postgresql.org/docs/current/routine-vacuuming.html#VACUUM-FOR-WRAPAROUND) during incremental syncs
  * Also, for pre-9.4 postgres, check if `oldest xmin in table <= xmin in cursor WHERE xmin NOT IN (1, 2)` - if this is not the case, then we must do a full refresh (see https://github.com/airbytehq/airbyte/issues/5022#issuecomment-1217187056)
  * This requires a very different approach to handling state from our current implementation (currently StateDecoratingIterator is reused across all DB sources; we'd need to extend it to also track the min cursor value in a sync)
* In incremental syncs, select `txid_current() >> 32 << 32 + (xmin :: text :: int) AS source_xmin` - this produces an epoch-extended int64 XID (i.e. never wraps around); this non-wraparound behavior is required for normalization
* In snapshot/full refresh syncs, select frozen rows using `xmin :: text :: bigint AS source_xmin` (i.e. use 0 as their epoch) - this is guaranteed to be lower than any non-frozen XID value. (non-frozen rows should still use the txid_current thing)
  * This means that the source_xmin column won't be particularly useful to end users (i.e. the values will be different between full refresh and incremental syncs)
* In normalization, add logic to keep the `source_xmin` column in the SCD table, but remove it from the final table

---

I'd love to understand how Fivetran accomplishes their xmin syncs without using pageinspect - fundamentally the problem is that after an xid wraparound, there are two rows with `xmin=0`; how can we tell which one is new or old? (maybe hyperminhash :P )

**Comment by igrayson** [comment]
@edgao What if we just sync both `xmin=0`s? 🤔

The connector docs might then provide guidance against using xmin on very large tables — primarily because of the full table scans, but also the inefficiency of unnecessarily re-syncing xmin dupes. I suspect if dupes are a real problem, the user will have hit more serious scaling problems with basic throughput.

Fivetran's [docs](https://fivetran.com/docs/databases/postgresql) suggest they might trigger mandatory full refreshes when xmin duplications are detected:

> In high-volume transactional databases, freezing and wraparound events may occur with XMIN because of the loss of the state in some circumstances, resulting in [automatic re-syncs](https://fivetran.com/docs/databases#automaticresync) that may increase your sync time.

This would make the implementation pretty simple — similar to `updated_at` where multiple rows may have the exact same updated_at, with additional logic to keep going past xmin=2^31, until `txid_current()` (or the equivalent lookup that works on read replicas). `xmin` can be read from the default-configured`airbyte` user.

**Comment by edgao** [comment]
oh yeah, that could work. My understanding is that xmin values are shared across tables, so any sufficiently high-traffic database would probably still struggle with xmin, even if the specific table(s) being synced are low-volume.

Some more concrete thoughts: there's probably some nuance in the initial sync (e.g. what happens if the DB is old enough that we're catching it in the middle of a wraparound, and how do we detect that + use the previous epoch for the older records). And maybe we need to modify the state message? (to store the oldest-synced xmin value, so that we can detect wraparound). But I agree that if we're ok with occasional full resyncs, this looks feasible.

(cc @bleonard )

**Comment by cgardens** [comment]
Cross-posting a note on performance of xmin since it's come up a few times.

> have we tested this performance impact? i've heard it referenced a few times. i think we're treating it lik e a boogey man, and i suspect it's not real.
>
> right now there is no guarantee that our customers happen to index updated_at column, so we are likely doing full table scans anyway. in fact there's probably a pretty low probability that that column is ever indexed by a user.

[link](https://airbytehq-team.slack.com/archives/C043JHEEYKG/p1678719294541349?thread_ts=1678679717.071059&cid=C043JHEEYKG) to original message
