### ISSUE TITLE
[source-postgres] CDC Not Working. Successful syncs with 0 records for incremental tables

### ISSUE THREAD

**Issue by jimmc2** [airbytehq/airbyte#50435]
### Connector Name

source-postgres

### Connector Version

3.6.21

### What step the error happened?

During the sync

### Relevant information

We are getting successful syncs and no noticeable errors in our logs but our CDC Postgres -> snowflake jobs just began outputting no records with no discernible reason why. I've seen a few other Postgres CDC issues from other people within the last two weeks as well but they seem to have different logging output than we do.

This began on 2024-12-23. I can provide additional configuration details but don't really have logs with errors to provide as it appears that everything is working properly.

### Relevant log output

```shell

```

### Contribute

- [ ] Yes, I want to contribute

**Comment by jimmc2** [comment]
https://github.com/airbytehq/airbyte/issues/49802

After setting the Invalid CDC position behavior (Advanced) field we began receiving the same error as the above issue and believe they are related so closing my issue.

**Comment by christinecommm** [comment]
We hit the exact same error as the one described above on 2025-01-13. 

We received the following support from Airbyte: "The reason your incremental syncs are not succeeding is because the Postgres Source Connector is timing out looking for the WAL resume position. The amount of time allowed for this search is set on the Connector Settings page as Initial Waiting Time in Seconds (Advanced)." 

In our case, increasing the Initial Waiting Time in Seconds (Advanced) to 2400 resolved our issue. We also increase our WAL size to 1TB, but we're unclear if this was required for resolution.
