### ISSUE TITLE
Source Hubspot: migrate to CDK

### ISSUE THREAD

**Issue by gaart** [airbytehq/airbyte#5114]
## Tell us about the problem you're trying to solve
In order to keep the code consistent across the connectors and to be able to test this connector the same way we do for the rest we need to move it to the new base.

## Describe the solution you’d like
Remove all of the `base-python` and `airbyte-protocol` references and replace then with `airbyte-cdk`.  Refactor the codebase to fit the current best practices. See https://docs.airbyte.io/connector-development/cdk-python, https://docs.airbyte.io/connector-development/best-practices and other `airbyte-cdk` sources for the refs (such as `Harvest`, `Braintree` etc.).

## Describe the alternative you’ve considered or used
We may just left the connector as it for now. But still at some point we'll need to rebuild this connector.

## Additional context
Description updated after the https://github.com/airbytehq/airbyte/pull/6465.

## Are you willing to submit a PR?

I can do it.

**Comment by augan-rymkhan** [comment]
**Make SourceHubspot inherits AbstractSource**
- [ ] Implement `check_connection`, we can use [client.health_check](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-hubspot/source_hubspot/client.py#L115) in this method
- [ ] Fix `stream.name` property so `AbstractSource's` `discover` command can find the related schemas.
- [ ] Implement `streams` method, we can use `Client._apis`, because this property already has instantiated stream instances.
