### ISSUE TITLE
New source: quickbooks (airbyte-native) 

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#5238]
## Tell us about the new connector you’d like to have
As part of the migration away from Singer based connectors in #3582 we want to rewrite this connector using the Airbyte CDK. We should perform vetting as normal and treat this as a brand new connector rather than copy all features the Singer connector supports. 

The new connector should also support oauth authentication out of the box

**Comment by Zirochkaa** [comment]
## Scoping summary

### 1. What is the “ideal end state” for the features offered by this connector?
 - Quickbooks REST entities (subentities) map to Airbyte streams
 - We will use `client_id`, `client_secret `and `refresh_token` to obtain `access_token`, and use it to send HTTP requests. We also need `user_agent` and `realm_id`.
 
### 2. What is the release roadmap for this connector?
 - #### Which features are absolutely necessary for the MVP release? 
   I believe that all 28 streams which were in singer version of quickbooks source can be realized in MVP, since there are no particular problems to get each of them.
  
 - #### Which features can be released as follow ups? 
   Other streams (there are more then 28 streams).



  - #### Task breakdown
  
    - [ ] Create source scaffolding
    - [ ] Populate schemas folder (they can be obtained from [singer version](https://github.com/airbytehq/tap-quickbooks) of this source)
    - [ ] Implement `spec`, `check`, and `discover` commands
    - [ ] Implement `read` command
        - [ ] Create API base abstract class 
	- [ ] Implement Full Refresh for all streams
	- [ ] Implement Incremental for streams, that support this feature (based on singer version on this source I can say that all 28 streams support incremental)
    - [ ] Handle rate limiting
    - [ ] Implement SAT

### 3. Check if and how [Fivetran](https://fivetran.com/connectors/lever) or [Stitch Data](https://www.stitchdata.com/integrations/lever/) support this connector 
  - #### Do they do something better than our proposed implementation?
    Stitch supports same 28 streams.
  - #### Is there something we can/should do better?
    We can support more streams (there are more then 28 streams).

### Sheet with all streams [here](https://docs.google.com/spreadsheets/d/1s-MAwI5d3eBlBOD8II_sZM7pw5FmZtAJsx1KJjVRFNU/edit#gid=135870899)

**Comment by akvadrako** [comment]
FYI this requires https://github.com/airbytehq/airbyte/issues/3990 since the refresh tokens expire when used if they are over 24 hours old.

**Comment by sherifnada** [comment]
@RickRen7575 this issue is unfortunately not prioritized at the moment due to #3990 being a blocker. Please upvote that issue to indicate interest
