### ISSUE TITLE
Document (and maybe improve) how we inject "runtime" environment variables in the webapp

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#5447]
## Tell us about the problem you're trying to solve
* We have a way of injecting runtime environment variables into the webapp using nginx. It is a little hard to do though. We want to _at least_ document it to make it easy. This is really important because right now, we are setting env variables at build time. This is bad because it is easy to forget to set them properly at build time (as opposed to having the infrastructure inject the properly at runtime). Also it requires rebuilding the webapp 4 times to do a release (OSS, dev, staging, prod).
* Potentially we want to update how we do this injection to be easier. @Jamakase suggested injecting a json object via docker compose into nginx, instead of doing one env variable at a time. If he can do that cleanly via docker compose that would be great. Some open question of how to make that look good in docker compose.

## Question for the future
* We will want to host the webapp in a static bucket / CDN soon. That means we will _not_ have an nginx server sitting in front of it. How will we inject the env variables in that scenario. @davinchia @Jamakase wdyt? We can close this issue once we solve the bullet points above but I want to start this conversation now since it may be relevant to how we think about the implementation.

**Comment by davinchia** [comment]
ah yes I forgot about:
```
  sub_filter </head>
                '</head><script language="javascript"\>
                window.TRACKING_STRATEGY = "$TRACKING_STRATEGY";
                window.PAPERCUPS_STORYTIME = "$PAPERCUPS_STORYTIME";
                window.FULLSTORY = "$FULLSTORY";
                window.OPENREPLAY = "$OPENREPLAY";
                window.AIRBYTE_VERSION = "$AIRBYTE_VERSION";
                window.API_URL = "$API_URL";
                window.IS_DEMO = "$IS_DEMO";
                </script>';
        sub_filter_once on;
```

To make sure I understand this means that as long as these env vars are defined in the Nginx environment (e.g. `$FULLSTORY`), they will be loaded in and used by the webapp?

A JSON config map would also work on K8s so that sounds like a good idea.

W.r.t to the CDN question, this might be a simple question but is it possible to compile React in a way so that it points to some sort of external file (similiar to `.env`) that we can swap in/out for various envs without running `npm run build`?

**Comment by Jamakase** [comment]
@cgardens 

1. Actually this problem is solved by having correct CI/CD, where oss version and cloud version **should** be built separately, as they are different apps and in future releases env variable won't switch cloud and oss version anymore.
2. As discussed, we could support different type of variables and just providing all the json is one of the options.

As for setting env variables in cdn - there is no other option to inject env variables into statically build bundle, except providing them in build time. Even if we point it to some external file as @davinchia supposed, then we should somehow set which env file should be used. To possible options here:
1. Add logic to always pick 
  - .env.prod from s3 prod bucket, if webapp URL is prod-cloud.airbyte.io
  - .env.dev from s3 dev bucket, if webapp URL is dev-cloud.airbyte.io
  - .env.stage from s3 stage bucket, if webapp URL is stage-cloud.airbyte.io
2. set up which file to pick during build time

All these limitations are due to the fact, that we can't change variables in a statically hosted app if there is no server in front of it ( or nginx in our case )

Also as another option, we could consider adjusting our app to SSR ( server side rendering ). In this case, we could inject variables on the fly when we want and pick them during container run. Main advantage here over nginx is that webapp will be displayed much faster as user will receive page with all data prefilled instead of waiting for data fetch. But it is totally separate feature.

**Comment by Jamakase** [comment]
> 1. I do not want to have run `npm build` for every environment. It really takes too long.

Well as this step should be never run manually, I do not think it's a big deal to have as many envs as necessary.

As it is going to be a file stored somewhere next to the app in the bucket, let's refer to it as `config.json`. Have I got it right, that we just want to store config next to the app and retrieve it as `/config.json` by default, so we won't need to configure URL where to get this file from? It is clear how we want to handle it for cloud, but we still need to decide how to handle oss version in this case.

I suppose we may want to test/apply different config strategies for oss and cloud, so we may need to make common `ConfigService` and inject it depending on our needs. I am going to add such concept and we will decide what logic we should have there.

**Comment by cgardens** [comment]
> Have I got it right, that we just want to store config next to the app and retrieve it as /config.json by default, so we won't need to configure URL where to get this file from?

yes! that is how i was thinking about it.

> It is clear how we want to handle it for cloud, but we still need to decide how to handle oss version in this case.

fair enough. it would definitely be nice if it could just be the same for OSS. given it's just a static file could we just treat it the same?
