### ISSUE TITLE
Source Shopify: native airbyte is slower than singer tap

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#5469]
## Tell us about the problem you're trying to solve
From user [slack convo](https://airbytehq.slack.com/archives/C01MFR03D5W/p1628600395445900):
> Hi all, the Shopify native connector takes a very long time to sync even in incremental mode due to it getting stuck on a retry loop. I’m attaching logs as a reply to this message
> hmm I have been running the singer-based connector for a few months without facing similar issues. Is it because it implements some of the enhancements you mentioned? Unfortunately I might not be able to adopt the native connector (I really want to) if it’s not at least on par with the Singer-based one.

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by bazarnov** [comment]
This issue should be fixed in `0.1.13`, with implemented Rate-Limits balancer.

**Comment by bazarnov** [comment]
@sherifnada @marcosmarxm 
This issue is fixed with `0.1.13`. As far as i can see it's no longer present during the sync. Probably we can close this for now, and re-open if there would be a customer's request. 
WDYT?

**Comment by marcosmarxm** [comment]
@rparrapy could you test version `0.1.13`?

**Comment by rparrapy** [comment]
@marcosmarxm I am actually on `0.1.14` currently. Although the rate-limit errors are gone, the native connector is still much slower than the Singer one.

As an example, for one of my Shopify connections:

- A full refresh takes ~24 hours for singer-based, ~60 hours for native.
- Even worse, incremental appends take minutes with singer-based, several hours for the Native connector.

I am attaching logs for my latest incremental append sync in case it helps. The connector (or at least the logs) have been stuck at the same place for hours.

[logs-shopify-slow.txt](https://github.com/airbytehq/airbyte/files/7117817/logs-shopify-slow.txt)

**Comment by bazarnov** [comment]
Hi, there is a logical explanation of such a behaviour - the singer tap  uses the `id` for incremental fetch of each stream, which is standard behaviour for the Shopify records filtering. We migrated from this solution to the use of `date-time` filtering.

According to their REST API documentation: all the streams has the `id` and this property could be used for incremental data fetch, but not all the streams we have in Native Shopify connector could be  filtered using the updated_at / created_at filtering. Plus, the singer tap doesn't have streams like: order risks, discounts, pages. (correct me if I'm wrong)

We use the date-time filtering for incremental refresh, which much more understandable for the end-user, but requires fetch all the data and then filter the oldest and leave only the records after the saved state. 

This potentially could be fixed by using the `cache` for the frequently used streams like `orders`. 

@sherifnada WDYT of implementing the `cache` for this connector?

**Comment by rparrapy** [comment]
Understood, thanks for the explanation. If possible, I would prioritize caching since at its current state the connector speed is just too slow. For my current use case, it is unfortunately not acceptable for an incremental append to take more than  18 hours (the sync for which I uploaded the logs yesterday still has not finished).
