### ISSUE TITLE
Select SRE Ticketing Platform for Airbyte Cloud

### ISSUE THREAD

**Issue by davinchia** [airbytehq/airbyte#5487]
## Tell us about the problem you're trying to solve
We need a ticketing platform for Airbyte Cloud.

This issue is to evaluate various options and pick one with @nataliekwong's input.

Working document here: https://docs.google.com/document/d/1V2Lt3eylNyYUt_FGa-hnNppyAPnkNwGgX-7xDylmHwM/edit?usp=sharing

**Comment by davinchia** [comment]
@nataliekwong made the executive decision and we are going with FreshDesk!

**Comment by nataliekwong** [comment]
@davinchia To make sure we are on the same page, we haven't made the decision to use FreshDesk. I have not yet started actually testing anything against our requirements doc, so I don't know if it will be what we go with. From a surface level it appears to do what we need, but we won't know until we thoroughly test our flows.

It's worth starting a trial with a different tool to be able to compare and make a more informed decision. I haven't yet gotten to HappyFox and Zoho, but those are on the list next to start trials for, since those were also at the top of the list for the GL team.

Expected timeline for making a decision would be end of next week.

**Comment by davinchia** [comment]
Got it. I didn't realise we would be trialing different ticketing systems in parallel. I thought it was a more concrete decision.

In that case, I'll keep this issue open.

**Comment by davinchia** [comment]
@nataliekwong we have settled on Intercom yes?

**Comment by nataliekwong** [comment]
@davinchia Yep, Intercom - can close this!
