### ISSUE TITLE
Redshift Connector successful sync but result in retry

### ISSUE THREAD

**Issue by Zirochkaa** [airbytehq/airbyte#5623]
This is a follow-up ticket for #5569 for specifically Redshift connector.

## Enviroment
* **Airbyte version**:  0.29.11-alpha
* **OS Version / Instance**: Linux EC2 m5.2xlarge
* **Deployment**: Docker
* **Source Connector and version**: Redshift 0.3.12
* **Destination Connector and version**: Snowflake 0.3.12
* **Severity**: Critical
* **Step where error happened**: Sync

## Current Behavior
Successful job ends with retry

## Expected Behavior
Successful job should end with success and no retry

## Logs
*If applicable, please upload the logs from the failing operation. 
For sync jobs, you can download the full logs from the UI by going to the sync attempt page and 
clicking the download logs button at the top right of the logs display window.*

<details>
<summary>LOG</summary> 

```

replace this with
your long log
output here

```

</details>

## Steps to Reproduce
1. 
1. 
1. 

## Are you willing to submit a PR?

No.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202102171868563/1202126626966585) by [Unito](https://www.unito.io)

**Comment by yurii-bidiuk** [comment]
Hi @Zirochkaa 
This issue was created a long time ago and is not reproducible anymore. I made some data syncs and got successful messages (screen below). Could you please verify if it's reproducible for you?
![1111](https://user-images.githubusercontent.com/35812734/172572313-d6c3a071-2af0-41ce-88d2-04159020b20d.png)
![2222](https://user-images.githubusercontent.com/35812734/172572330-f92577ee-9640-4a11-b792-e16e93bf4cfa.png)
![333](https://user-images.githubusercontent.com/35812734/172572345-420d175f-0dde-4119-8cef-2ecf73db6a95.png)
