### ISSUE TITLE
Basic normalization problems with Shopify->Snowflake

### ISSUE THREAD

**Issue by rparrapy** [airbytehq/airbyte#5739]
Enviroment

• Airbyte version: example is 0.29.11-alpha
• OS Version / Instance: t2.xlarge
• Deployment: Docker
• Source Connector and version: Shopify 0.1.13
• Destination Connector and version: Snowflake 0.3.12
• Severity: Critical
• Step where error happened: Basic normalization

Current Behavior
The basic JSON blobs sitting in _AIRBYTE_RAW tables is ok.
However, after basic normalization some tables don't have the right columns and some tables are missing. For example:

- ORDERS_LINE_ITEMS_DISCOUNT_ALLOCATIONS is not created, the DISCOUNT_ALLOCATIONS column exists in the - ORDER_LINE_ITEMS table.

Expected Behavior
Normalization is done succesfully.
ORDERS_LINE_ITEMS_DISCOUNT_ALLOCATIONS is created. 

Additional information: I am using S3 as staging for Snowflake.
[logs-shopify-native-2908.txt](https://github.com/airbytehq/airbyte/files/7078262/logs-shopify-native-2908.txt)

**Comment by bazarnov** [comment]
From this thread:
https://airbytehq.slack.com/archives/C01MFR03D5W/p1630270571144600?thread_ts=1628600395.445900&cid=C01MFR03D5W

Tried to reproduce using `postgres` destination, no issues with the normalisation, 
Products are properly normalised into smaller tables according to the name of entity, like `product_variables`
Entities like `title` and `vendor` are inside the main table `products`

**Comment by bazarnov** [comment]
> • Step where error happened: Sync job

@rparrapy could you please be more specific with this? As far As I understand the sync job is completed ok, but normalisation isn't?

**Comment by rparrapy** [comment]
Correct. Edited the issue description accordingly.

**Comment by sherifnada** [comment]
@rparrapy does resetting the schema help?

**Comment by bazarnov** [comment]
@rparrapy @sherifnada 

Based on logs above:
`WARN: Unknown type for column total_tax_set at products` means that destination expects the products with old schema, back to the times when the products schema was equal to the orders schema. 
The resetting of the schema should be enough to fix the normalisation process. 

Also, in order to reproduce the 🐛 , I replicate the test data to Destination Snowflake (v. 0.3.12), all the data was normilised as expected. 

Recommendations here are:
 1. Update / refresh the schema in connection settings + save down bellow.
 2. Use another destination table in the Snowflake.
 3. Create new connection between `Shopify > Snowflake`.

**Comment by rparrapy** [comment]
Resetting the schema does not help. I'm following the recommendations now, I'll keep you posted.

**Comment by rparrapy** [comment]
The recommendations worked (at least on a small subset of data). Running the full sync now, will keep you posted. Thanks!
