### ISSUE TITLE
Source Google DBM/DV360

### ISSUE THREAD

**Issue by darian-heede** [airbytehq/airbyte#6049]
## Tell us about the new connector you’d like to have
* A source connector for Google [Display & Video 360 / DoubleClick Bid Manager (DBM)](https://developers.google.com/bid-manager/v1.1)

## Describe the context around this new connector
* This integration is required by our business intelligence team. This implies reporting and visualization and especially data analytics.
* The snycs should run at least once per day. It would be great if I could specify a date range for the fetch, i.e. `start_date` and `end_date`.
* I require all available reports and dimensions and metrics from this API. The [service endpoint](https://developers.google.com/display-video/api/reference/rest#service-endpoint) is https://displayvideo.googleapis.com

## Describe the alternative you are considering or using
As of now we're using a third party API connector service, which currently has issues.

## Are you willing to submit a PR?
No.

**Comment by darian-heede** [comment]
Might be a duplicate of #2984. Not sure...

**Comment by sherifnada** [comment]
@darian-heede We would love to support this connector but it seems like the 360 suite of products is pretty expensive to get access to. We would love to get a sandbox account from Google in order to support integrating with this API. would you be able to give us any pointers on how to get a sandbox account/account that doesn't cost a fortune?

**Comment by darian-heede** [comment]
Solved by #11828.
