### ISSUE TITLE
source stripe: fix test failures

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#6168]
the connector's build [is failing](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/builds.md). This issue tracks fixing it.

**Comment by yevhenii-ldv** [comment]
I investigated the state of the [builds](https://dnsgjos7lj2fu.cloudfront.net/tests/summary/source-stripe/) of this connector. It looks like this defect has been fixed since Sep 15.
Having looked at it, I found that Sep 14 the [PR](https://github.com/airbytehq/airbyte/pull/6004) were merged into the master branch by @Zirochkaa, who probably fixed the bug with the assembly.
