### ISSUE TITLE
source facebook-marketing: fix test failures

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#6170]
the connector's build [is failing](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/builds.md). This issue tracks fixing it.

**Comment by Zirochkaa** [comment]
Looks like it's an issue with new transform function:

<img width="1599" alt="image" src="https://user-images.githubusercontent.com/19872253/134025349-66c5cee8-dd68-43e9-98cb-99f89827c3fe.png">

Need to gebug this function and find out why it's failing (on which record, for example).

**Comment by vitaliizazmic** [comment]
There are two types of error in logs.  First error connected to test failing while merging solution for #5190 TestFullRefresh fails because records from two different syncing aren't  identical. Another error is caused by recent changes in source. TestBasicRead fails for AdsInsights streams. It finish with KeyError: 'type' [in convert_to_schema_types](https://github.com/airbytehq/airbyte/blob/31820f9ccc8cc6fb9217542e016d82672692d82b/airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/streams.py#L168).
