### ISSUE TITLE
Obtain public developer application for the Shopify source connector

### ISSUE THREAD

**Issue by cheyura** [airbytehq/airbyte#6204]
## Tell us about the problem you're trying to solve
Obtain a public developer application for the Shopify connector like specified in #6070

###Requirements to obtain public developer application
TBD

**Comment by ycherniaiev** [comment]
still in progress due to recent review of app

**Comment by bazarnov** [comment]
Please update this issue with the latest information and/or close it with comment, thanks.

**Comment by YowanR** [comment]
@ycherniaiev @igrankova we should plan to re-engage with Shopify. Let's chat more offline.

**Comment by igrankova** [comment]
Shopify accepted our form: Apps are currently being reviewed within two weeks of submission.

**Comment by bazarnov** [comment]
Great news! Fingers crossed!

**Comment by igrankova** [comment]
We have 2 blockers:
1. The application must not request permissions for unused scopes: For the read_checkout permissions, this is only allowed when building an app with the Sales Channel SDK.
2. Must use Shopify Billing API. At this time all public apps are required to use the Billing API to issue charges to merchants.
Why do we have this requirement?
•	The Billing API is designed to optimize the merchants experience by reducing the number of invoices they have to keep track of and pay each month.
•	This also benefits partners by reducing the number of steps their customer is required to do to onboard with the app.
•	This creates a fair exchange of value between Shopify and our app developers, who in turn are gaining valuable access to our merchant base through the Shopify App Store.
Below are a few resources for getting setup with the Billing API and to assist choosing a billing model:
•	[How app billing cycles work for merchant and partners](https://protect-us.mimecast.com/s/6174Co2lP6tYMvvoU1v2w3?domain=shopify.ca) - Partner Blog
•	[How to setup your apps billing](https://protect-us.mimecast.com/s/2Z_6CpYmPXcoGAAlHDyxOk?domain=shopify.ca) - Partner Guide
•	[The Benefits of billing with GraphQL](https://protect-us.mimecast.com/s/BwecCqxn9MiNDXX4tQBvMf?domain=shopify.ca) - Partner Guide
For any charges that you manage, you must use the Billing API. If you are connecting Shopify to a service where you don’t own the billing process, we understand that you cannot charge that service on the Billing API. However, all new customers that install your Shopify app must be charged through the Billing API. You are not required to switch the billing method for merchants that already have their Billing set up with you. While we understand partners may already have a billing system in place, in order to be a public Shopify app, partners are required to also connect to the Billing API for customers who install the Shopify App.
The Billing API requirement exists to ensure a consistent merchant experience and to be completely honest, it is quite rare that we would make an exception where it doesn't need to be used. The Billing API is designed to optimize the merchants experience by reducing the number of invoices they have to keep track of and pay each month. This also benefits partners by reducing the number of steps their customer is required to do to onboard with the app, which creates a fair exchange of value between Shopify and our app developers, who in turn are gaining valuable access to our merchant base through the Shopify App Store.
@YowanR

**Comment by YowanR** [comment]
@igrankova where did we get the update for the billing API? I want to follow-up on that myself

**Comment by igrankova** [comment]
@YowanR, the [docs](https://shopify.dev/apps/store/requirements#b-billing), the email from the support (help center ticket number - 33878509) forwarded to you.

**Comment by igrankova** [comment]
We have received an exemption from Shopify for our public app. We can get a public unlisted app on the Shopify app store, which should unblock us for OAuth. 
Resuming the process for submitting the app for approval from Shopify.
We should keep it unlisted.

**Comment by bazarnov** [comment]
We should revert this PR https://github.com/airbytehq/airbyte-platform-internal/pull/4085 changes to enable `OAuth` for Cloud back. Just leave it here, for quick movements.

**Comment by igrankova** [comment]
The UNLISTED App is submitted for review. Apps are currently being reviewed within two weeks of submission.

**Comment by igrankova** [comment]
![image](https://github.com/airbytehq/airbyte/assets/87977540/9c6cdf31-64c9-402d-9f40-d1e874c8d3a0)
