### ISSUE TITLE
QA Signup / Signin / Password reset flows

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#6485]
Historically there has been some instability here and we have recently torn up a lot of this stuff, so we need to make triple sure it is good shape.

As part of this process, we should write down exactly the steps we take as part of this QA so that we can synthesize it into a cypress test in Q4.

## QA Checklist
- [ ] - can create a new user with a new email address. (should only create one record in the db)
- [ ] - cannot create a new user with an email address that is already used
- [ ] - i cannot access the app until i have verified my email
- [ ] - if i have not yet verified my email, i can request another verification be sent
- [ ] - i can reset my password (when logged in)
- [ ] - i can reset my password (when logged out)
- [ ] - on sign in, if i have one workspace, i am brought it directly.
- [ ] - on sign up, if i have one workspace, i am brought it directly.
- [ ] - on sign in, if i have multiple workspaces, do i go to an arbitrary on of them or to the workspace list? either is fine.
- [ ] - on sign up, if i have multiple workspaces, do i go to an arbitrary on of them or to the workspace list? either is fine.

**Comment by ChristopheDuong** [comment]
## QA Checklist
- [ ] - can create a new user with a new email address. (should only create one record in the db)
- [ ] - cannot create a new user with an email address that is already used
- [ ] - i cannot access the app until i have verified my email
- [ ] - if i have not yet verified my email, i can request another verification be sent
- [ ] - i can reset my password
- [ ] - on sign in, if i have one workspace, i am brought it directly.
- [ ] - on sign up, if i have one workspace, i am brought it directly.
- [ ] - on sign in, if i have multiple workspaces, do i go to an arbitrary on of them or to the workspace list? either is fine.
- [ ] - on sign up, if i have multiple workspaces, do i go to an arbitrary on of them or to the workspace list? either is fine.

**Comment by airbyte-jenny** [comment]
## QA Checklist
 * [x]  - can create a new user with a new email address. (should only create one record in the db)
 * [x]  - cannot create a new user with an email address that is already used
 * [x]  - i cannot access the app until i have verified my email
 * [x]  - if i have not yet verified my email, i can request another verification be sent
 * [x]  - i can change my password (when logged in)
 * [ ]  - i can reset my password (when logged out)
Issues remain with this one, noted in another ticket.

 * [x]  - on sign in, if i have one workspace, i am brought to it directly.
 * [x]  - on sign up, if i have one workspace, i am brought to it directly. (This isn't what we actually want. User is taken to a workspace creation page, which is fine). It's slightly unclear to the user that they should click on the workspace name to go there, since there isn't a Go button.

 * [x]  - on sign in, if i have multiple workspaces, do i go to an arbitrary on of them or to the workspace list? either is fine.
 * [x]  - on sign up, if i have multiple workspaces, do i go to an arbitrary on of them or to the workspace list? either is fine.
