### ISSUE TITLE
QA Invite Users

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#6486]
This feature has never worked properly. We need to figure out its current state and get it to a working state before the launch.

## QA Checklist
- [ ] - ~~invite to a workspace a user that does _not_ yet have an Airbyte account.~~
- [x] - invite to a workspace a user that does _not_ yet have an Airbyte account should alert that the user does not exist and they first must create an account.
- [x] - invite to a workspace a user that _does_ already have an Airbyte account.
- [x] - should not be able to add a user multiple times (@tuliren to do this)
  - https://github.com/airbytehq/airbyte-cloud/pull/318
- [x] - hide role in UI when inviting a user
  - This field is now disabled.

**Comment by cgardens** [comment]
related issues: 
https://github.com/airbytehq/airbyte/issues/5455
https://github.com/airbytehq/airbyte/issues/5449

**Comment by tuliren** [comment]
Here is my QA summary without knowing what is the expected user flow.

## Invite to a workspace a user that does *NOT* yet have an Airbyte account.

Issues:
- It is unclear if I must select a role or not.
  - This is probably not a required field, since I can click the submission button without selecting a role.
- There is only an `admin` role. Should we also have a `user` role?
  - Since role is not required, I guess not selecting any role is equivalent to a `user` role. But it's better to make this explicit.
- Once a role is selected, there is no way to unselect it.
  - This is a problem if not selecting a role is equivalent to a `user` role.

<img width="688" alt="Screen Shot 2021-09-28 at 12 25 40" src="https://user-images.githubusercontent.com/1933157/135152810-6c531ce0-1738-4b0f-9b18-8bc3dcbe46c6.png">

- When adding a new user, I cannot submit the form. A warning only shows up in the browser console:
```
console.js:107 Warning: An unhandled error was caught from submitForm() Error: Object not found. User liren+user1@airbyte.io does not exist yet. Please sign-up manually and add to workspace once user is created
    at AirbyteRequestService.ts:75
    at l (runtime.js:63)
    at Generator._invoke (runtime.js:293)
    at Generator.next (runtime.js:118)
    at r (asyncToGenerator.js:3)
    at s (asyncToGenerator.js:25)
```

## Invite to a workspace a user that *does* already have an Airbyte account.

Adding a registered user for the first time works.

Issues:
- Users are automatically added as `admin`, even if `admin` role is not selected.
- The same user can be added multiple times.

<img width="995" alt="Screen Shot 2021-09-28 at 12 36 03" src="https://user-images.githubusercontent.com/1933157/135154302-46ff2b31-f8c3-445c-8021-361bf7083199.png"> 

## Additionally issues related to account management
- The `remove` button is clickable but does not actually remove the user.
- The `remove` button is clickable even for the currently logged in user.
  - Because this button currently does not work, so I cannot test what will happen if the last user is removed from the workspace.
  - A user probably should not be able to remove herself? Or at least the super admin, if there is such a role, should not be able to remove herself. Otherwise, all users can be removed from the workspace, and the workspace becomes a phantom one.

**Comment by jrhizor** [comment]
Which environment are you testing on (and which version of core/cloud)?

**Comment by tuliren** [comment]
> Which environment are you testing on (and which version of core/cloud)?

I tested on the production site. Should I do it on the dev site?

**Comment by jrhizor** [comment]
Prod is good. I looked up the version of core and cloud from Kubernetes on the cloud console.

**Comment by ChristopheDuong** [comment]
> When adding a new user, I cannot submit the form. A warning only shows up in the browser console:

From past discussions, we had mentioned about a pop-up (not just a warning in console) when this happens as a workaround:

![Screenshot 2021-09-29 at 10 22 04](https://user-images.githubusercontent.com/7718175/135231306-459ec7ba-fbdf-441a-a0f9-3aa3d970b3d4.png)

**Comment by davinchia** [comment]
QA for current prod deployment. Looks like it's working:

invited a user:
<img width="1524" alt="Screen Shot 2021-10-06 at 8 19 50 AM" src="https://user-images.githubusercontent.com/9772859/136122108-135f7bb5-7894-470c-be1c-d818830d98ab.png">

verified email:
<img width="1528" alt="Screen Shot 2021-10-06 at 8 20 50 AM" src="https://user-images.githubusercontent.com/9772859/136122188-585687d2-db6d-411d-a54c-1ac8d63f8754.png">

logged in to new user and saw new workspace:
<img width="2039" alt="Screen Shot 2021-10-06 at 8 21 09 AM" src="https://user-images.githubusercontent.com/9772859/136122129-c053b78d-c4fb-4c95-9308-3daa10b77016.png">

revoke the user:

(disappears from inviter)
<img width="1176" alt="Screen Shot 2021-10-06 at 8 22 24 AM" src="https://user-images.githubusercontent.com/9772859/136122218-8cbf2b59-37a7-4863-918d-93eadeb4b289.png">

(disappears from invitee)
<img width="2045" alt="Screen Shot 2021-10-06 at 8 22 28 AM" src="https://user-images.githubusercontent.com/9772859/136122264-b49c73d8-f760-4cb7-a2b1-2db610cb3700.png">

**Comment by davinchia** [comment]
@cgardens this looks good on prod. think we can close it
