### ISSUE TITLE
Server won't start - Invalid version string: latest

### ISSUE THREAD

**Issue by harshithmullapudi** [airbytehq/airbyte#6560]
## Enviroment
- **Airbyte version**:  example is 0.22.0-alpha
Is this your first time deploying Airbyte: No
OS Version / Instance:  EC2 t2.medium
Memory / Disk: 16Gb
Deployment: Docker
 Airbyte Version: 0.29.17-alpha
Step: Upgrading

## Current Behavior
 Server won't start, stuck with error: "Exception in thread "main" java.lang.IllegalArgumentException: Invalid version string: latest", see attachments for full server logs.

```
Refer to this slack conversation
https://airbytehq.slack.com/archives/C01MFR03D5W/p1632824081402300
```

## Steps to Reproduce
1.
2.
3.

## Are you willing to submit a PR?

Remove this with your answer.

**Comment by Zax337** [comment]
Steps to reproduce:
1. Create a new connector whose version doesn't follow the pattern major.minor.patch (for instance, 1.0 or latest)
2. [Create a connection using this connector.]
3. [Change this connector so that it requires an additional field]
4. Update the connector to use this latest implementation, use again the "wrong" format.
5. Stop and restart Airbyte. The DB should contain multiple version of the source and will try to determine which version is the newest by parsing their version. The code expect a major.minor.patch format and will throw an exception, preventing the server to start.

I'm not certain of the two steps in [ ], the important thing here is that you have to make sure the source is duplicated in DB.

I guess a solution would be to rely on `create_at` and / or `updated_at` in case the version is "wrong", but it depends on how those fields are actually filled in. If this works for you, I don't mind submitting a PR. You could also enforce the right format for custom connectors, but the problem will still exist for current images.

**Comment by davinchia** [comment]
@Zax337 I've put this in the backlog. The team will be looking at this appropriately.

**Comment by cgardens** [comment]
For now we are going to insist on strict semvar for connector versions. Everything else is not valid.
