### ISSUE TITLE
Source Stripe: upgrade connector doesn't allow save new config

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#6791]
## Enviroment
- **Airbyte version**:  0.30.3-alpha
- **OS Version / Instance**: macOS
- **Deployment**: Docker
- **Source Connector and version**: Stripe 0.1.19
- **Destination Connector and version**: ~
- **Severity**: Very Low / Low / **Medium** / High / Critical
- **Step where error happened**: Update Config from existing connector

## Current Behavior
I have a Stripe 0.1.19 connector and want to update to 0.1.20 where there is a new config field.
After upgrading the connector version and entered the connector config page I couldnt save the new config.

Stripe 0.1.19
![image](https://user-images.githubusercontent.com/5154322/136083393-225ec814-8da1-4a08-b0bf-276ca149ed01.png)

Stripe 0.1.20 after change lookback windows variable to 30 doesnt allow me save!
![image](https://user-images.githubusercontent.com/5154322/136083465-19d8722c-3647-452c-a19d-968989f20b45.png)

## Expected Behavior
*Tell us what should happen.*

## Logs
*If applicable, please upload the logs from the failing operation. 
For sync jobs, you can download the full logs from the UI by going to the sync attempt page and 
clicking the download logs button at the top right of the logs display window.*

<details>
<summary>LOG</summary> 

```

replace this with
your long log
output here

```

</details>

## Steps to Reproduce
1.
2.
3.

## Are you willing to submit a PR?

Remove this with your answer.

**Comment by antixar** [comment]
I guess it is not relevant issue. We will check

**Comment by bazarnov** [comment]
This issue is related to UI/UX. Once you've updated the `source-stripe` version from `0.1.19` to `0.1.20`, the `Save changes and test` button is not active unless you `Edit` the `Client_secret` value. If you copy/paste the same secret value as it was before, the UI allows you to save the changes. 
See the screenshots:

Before the update:
version = `0.1.19`, no `Lookback window` field
<img width="930" alt="Screenshot 2022-02-07 at 12 51 25" src="https://user-images.githubusercontent.com/22987674/152774485-ed13b276-98a8-470a-a915-07b53171b1f2.png">

After the update:
version = `0.1.20`, `Lookback window` appeared, but `Save changes and test` button is not active
<img width="941" alt="Screenshot 2022-02-07 at 12 54 13" src="https://user-images.githubusercontent.com/22987674/152774994-664dc9af-b8a3-4ea2-8a8d-27952ad74fd1.png">

Once you re-edit the `Client_secret` with the same value as it was before the update (the same secret value), the `Save changes and test` button is active. Check the screen capture for more details.
https://user-images.githubusercontent.com/22987674/152775584-979e6b4b-8ad7-4fd1-a035-b257c35f63e4.mov

**Comment by misteryeo** [comment]
Tagging you in @timroes since this looks like a UI/UX issue

**Comment by Jamakase** [comment]
We disable buttons only in a few cases: when the form is submitting, when there is some error, and when values don't differ from the initial one ( are not dirty ).

In this particular case, `lookback_window_days` has a default value, as a result, we assume that form values are the same as we apply `0` value by default here.

If some connector in the new version was upgraded and a new field was added, doesn't it mean that connector config value should be upgraded based on default values? So if we add `lookback_window_days` in new version and user upgrades connector - doesn't it mean that this property should be already applied? If yes - then it means we can't indeed update the form, as UI assumes it to be deeply equal.
