### ISSUE TITLE
OAuth Flow: new authSpecifications supporting field references from connector config as dependency

### ISSUE THREAD

**Issue by bazarnov** [airbytehq/airbyte#6971]
## Tell us about the problem you're trying to solve
We need a way to pass the user input config parameters into the OAuthFlow 2.0.

**Use-case:**
We have Source Shopify with implemented Oauth2.0 connection method.
The `url base` for the `consent` and the `access token url` should include the `Shop Name` which user can input on the stage of connection setup (see screenshot, for `shop`). 
So the final link for the consent screen should look like this:

FORMAT: `"https://{shop}.myshopify.com/admin/oauth/access_token"`, where {shop} is the Shop Name of the user's Shop.

## Describe the solution you’d like
1. Probably to extend the OAuth Specification to have something like: 
`"oauthFlowConfigParameters"` or `"oauthFlowCustomParameters"` and pass the config-required fields there, and as the result to the `<connector>OauthFlow.java` 
2. The button of `Authenticate your Shopify account` in this case should be active only after the `Shop` field is populated.

## Describe the alternative you’ve considered or used
Other way to pass the config-required parameters into the OAuthFlow.

## Additional context
<img width="1669" alt="Screenshot 2021-10-12 at 14 50 27" src="https://user-images.githubusercontent.com/22987674/136955291-9e3f72d4-37c1-4a8c-8797-a46dfd355910.png">

**Comment by sherifnada** [comment]
I would prefer that we don’t hardcode special rules in the UI/server for each connector. As it is, hardcoding the oauth flow in the server couples the connector lifecycle with the server lifecycle. Because their versions are released totally separately, it’s not a good experience for the user.

I propose that we add the following struct to the oauth specification:
// represents a list of pointers to the fields required to launch the oauth flow.
// For example, to authenticate a shopify user, we need to embed the shop ID in the consentgrant URL,
// shop ID is a separate parameter in the spec
// Therefore this array would contain a list of pointers (a pointer is a string array denoting a path in the config)
// pointing to the required fields
oauth_flow_required_fields: Array<Array<String>>
```

In the shopify case this would be something like:



---- spec.json
{
"properties": {
  shop_id: {type: string},
  refresh_token: {type: string}
  client_id: // etc...
 ,
 authSpecification: {
  type: oauth2
  oauth2Specification:
   {
    oauth_flow_input_fields: [["shop_id"]]
    // remaining fields
    }
 }
}
