### ISSUE TITLE
Source Google ads: connector doesn't pull data for today

### ISSUE THREAD

**Issue by harshithmullapudi** [airbytehq/airbyte#7047]
## Current Behavior
Data is not pulled for today. https://github.com/airbytehq/airbyte/blob/3b32a091ff6e9fc502ffeb284e8550b05ca8f300/airbyte-integrations/connectors/source-google-ads/source_google_ads/streams.py#L88 

## Expected Behavior
It should also pull for the same date

## Logs
*If applicable, please upload the logs from the failing operation. 
For sync jobs, you can download the full logs from the UI by going to the sync attempt page and 
clicking the download logs button at the top right of the logs display window.*

<details>
<summary>LOG</summary> 

```

replace this with
your long log
output here

```

</details>

## Steps to Reproduce
1.
2.
3.

## Are you willing to submit a PR?

Remove this with your answer.

**Comment by bigdatawonders** [comment]
Any news on this one?
Is there a way to also have this yesterday depend on account timezone that could be pulled from Google Ads API accounts?

**Comment by annalvova05** [comment]
Hy, @bigdatawonders, @harshithmullapudi ! 
For incremental streams data is synced up to the previous day using your Google Ads account time zone. The reason is that Google Ads can filter data only by [date](https://developers.google.com/google-ads/api/fields/v8/ad_group_ad#segments.date) without time. Also, some reports cannot load data in real-time due to Google Ads [limitations](https://support.google.com/google-ads/answer/2544985?hl=en). New connector version with updated docs just been published.
