### ISSUE TITLE
Shopify Connector: Support Mandatory Webhooks

### ISSUE THREAD

**Issue by cheyura** [airbytehq/airbyte#7122]
## Tell us about the problem you're trying to solve
To comply with the General Data Protection Regulation (GDPR), public apps must set up mandatory webhooks. These webhooks help you manage the user data that an app collects.

## Describe the solution you’d like
The following webhooks must be added to every public app:

customers/data_request: Requests to view stored customer data
customers/redact: Requests deletion of customer data
shop/redact: Requests deletion of shop data

When you receive one of the mandatory webhooks, you must confirm your receipt of the redaction request by responding with a 200 series status code. You must also complete the action within 30 days of receipt, unless you're legally required to retain the data

## Additional context
We are an ETL platform and store no data. For this problem the answer from Shopify : "If your app doesn't hold any customer data just make sure your app returns a response status code 200 for those webhooks.'

Please refer to this link https://shopify.dev/apps/webhooks/mandatory

**Comment by davinchia** [comment]
is it important for this endpoint to be hosted at our cloud.airbyte.io/be affiliated with airbyte.io? can we get away with a randomly generated endpoint entirely serviced by Google Functions (Functions can be configured to exposed automatically assign a public url to the function) and not tied to airbyte dns at all?

asking because tying it airbyte.io is one additional step and wondering if we need to do that if this is 'one-off' work.

**Comment by bazarnov** [comment]
Part of this epic closed the question around mandatory webhook for `Shopify`, closing this issue. 

https://github.com/airbytehq/airbyte-platform-internal/issues/7392
