### ISSUE TITLE
MongoDB: Support SSL connection and allow paste SSL PEM file content

### ISSUE THREAD

**Issue by lorriexingfang86** [airbytehq/airbyte#7379]
## Tell us about the problem you're trying to solve
For my mongo db i need a pem file to establish the ssl connection and get access to it. I need a place to upload this file or paste content of this file in airbyte mongoDB

currently in my application i am using a command like this:

`mongodb://USER_NAME:PASSWORD@MONGO_HOST_URL:27017/?ssl=true&ssl_ca_certs=mongo_certificate.pem&retryWrites=false
`
to get access to my mongodb on cloud.

## Describe the solution you’d like
I noticed that for Oracle DB as a source connector, airbyte allows user to paste the ssl pem file content. How abt also adding it to the mongodb connector?

## Describe the alternative you’ve considered or used
may use a proxy to get access to mongo db so i don't need the pem file.

**Comment by ecylmz** [comment]
Hi,

In addition, for the replica set option, there should be an input where we can enter ca-certificate.

Do you have any workaround suggestions until this feature is implemented?

**Comment by rock2799** [comment]
When will this feature be added. I am setting up CDC with source MongoDB community edition. But the following error is being thrown.

---------------------------------------
Timed out after 30000 ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference=primary}. Client view of cluster state is {type=REPLICA_SET, servers=[{address=192.168.10.251:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketWriteException: Exception sending message}, caused by {javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target}, caused by {sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target}, caused by {sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target}}]
---------------------------------------

**Comment by shubhshah01** [comment]
Is there any update on this issue ? Any workaround ?

**Comment by muthuk94** [comment]
Is there any update on this issue ? Any workaround ?

**Comment by evantahler** [comment]
Closing as duplicate of https://github.com/airbytehq/airbyte/issues/33452 - join us over there!
