### ISSUE TITLE
Mixpanel Source Connector Doesn't allow for start_date to be Older Than 1 Year

### ISSUE THREAD

**Issue by lucasdurrant** [airbytehq/airbyte#7451]
https://github.com/airbytehq/airbyte/blob/03732dfcca129b57df3a85e79456ed6f70acb9bc/airbyte-integrations/connectors/source-mixpanel/source_mixpanel/source.py#L826

Would Like to be able to sync data in mixpanel that is older than 1 year, but selecting a start_date older than 1 year will always default to y year ago

**Comment by lucasdurrant** [comment]
@sherifnada I have tested the mixpanel APIby querying events from 2019, and the query worked successfully, so I don't believe this is a mixpanel API related constraint

**Comment by sherifnada** [comment]
@lucasdurrant thank you for the answer! pulled into our current sprint

**Comment by Zirochkaa** [comment]
## Scoping summary

### 1. What is the “ideal end state” for the features offered by this connector?
 - Quickbooks REST entities (subentities) map to Airbyte streams
 - We will use `client_id`, `client_secret `and `refresh_token` to obtain `access_token`, and use it to send HTTP requests. We also need `user_agent` and `realm_id`.
 
### 2. What is the release roadmap for this connector?
 - #### Which features are absolutely necessary for the MVP release? 
   I believe that all 28 streams which were in singer version of quickbooks source can be realized in MVP, since there are no particular problems to get each of them.
  
 - #### Which features can be released as follow ups? 
   Other streams (there are more then 28 streams).



  - #### Task breakdown
  
    - [ ] Create source scaffolding
    - [ ] Populate schemas folder (they can be obtained from [singer version](https://github.com/airbytehq/tap-quickbooks) of this source)
    - [ ] Implement `spec`, `check`, and `discover` commands
    - [ ] Implement `read` command
        - [ ] Create API base abstract class 
	- [ ] Implement Full Refresh for all streams
	- [ ] Implement Incremental for streams, that support this feature (based on singer version on this source I can say that all 28 streams support incremental)
    - [ ] Handle rate limiting
    - [ ] Implement SAT

### 3. Check if and how [Fivetran](https://fivetran.com/connectors/lever) or [Stitch Data](https://www.stitchdata.com/integrations/lever/) support this connector 
  - #### Do they do something better than our proposed implementation?
    Stitch supports same 28 streams.
  - #### Is there something we can/should do better?
    We can support more streams (there are more then 28 streams).

### Sheet with all streams [here](https://docs.google.com/spreadsheets/d/1s-MAwI5d3eBlBOD8II_sZM7pw5FmZtAJsx1KJjVRFNU/edit#gid=135870899)
