### ISSUE TITLE
destination-csv seems to fail to write file

### ISSUE THREAD

**Issue by ChristopheDuong** [airbytehq/airbyte#772]
## Expected Behavior
I've been testng a CSV in both Source and Destination to download a CSV from a remote/public URL from Google Cloud Storage and save it locally in a csv file where Airbyte is running

## Current Behavior
I've noticed an error and exceptions when using the destination-csv to save local files while using the source-csv to input data:

```
INFO[m i.a.i.b.IntegrationRunner(run):66 - {} - Integration config: IntegrationConfig{command=WRITE, configPath='target_config.json', catalogPath='catalog.json', statePath='null'}
ERROR (/tmp/workspace/8/1) LineGobbler(voidCall):69 - Exception in thread "main" java.io.FileNotFoundException: /local/epicovid/storage.googleapis.com/covid19-open-data/v2/latest/epidemiology.csv_1604176654030.csv (No such file or directory)
```
However if i go and manually create a directory:
`sudo mkdir -p /tmp/airbyte_local/epicovid/storage.googleapis.com/covid19-open-data/v2/latest/`

Then the destination can finally succeed and output the file properly.
So the bug makes it a little harder to use the destination-csv integration since i have to manually create the output folder...

## Steps to Reproduce
1. Set up source CSV to pull data from https://storage.googleapis.com/covid19-open-data/v2/latest/epidemiology.csv
1. Set up destination CSV to store data locally at /local/epicovid/
1. Run the integration manually

## Severity of the bug for you
Low

**Comment by cgardens** [comment]
What does your configuration for csv-destination look like? are you just setting ` /local/epicovid/`? is youre local mount just `/tmp/airbyte_local`? i'm asking because i'm a little unsure why it's trying to write `epicovid/storage.googleapis.com/covid19-open-data/v2/latest/` if you're using the the configuration i described above, shouldn't it be writing to just `/tmp/airbyte_local/epicovid/<name of stream>`? It seems like there's a lot deeper nesting going on. from what you've describe it sounds like it's trying to write the file to a weird spot. 

the other possibility is that this is it not working well with a linux machine, which is possible. though the integration tests do run on linux (but i think it's one less layer of docker, so it could behave slightly differently) would have to think through this one a bit more.

**Comment by ChristopheDuong** [comment]
Maybe then it's the Source-CSV that is not defining "name of stream" properly?

The configuration files as seen in the dev_root/workplace are:

```
cat target_config.json 
{"destination_path":"/local/epicovid"}
```

```
cat tap_config.json 
{"url":"storage.googleapis.com/covid19-open-data/v2/latest/epidemiology.csv","format":"csv","storage":"https://","reader_options":"{}"}
```

**Comment by cgardens** [comment]
yeah. if the name of the stream looks like a path it's possible something gets messed up there. that seems likely. could you at least try to confirm this theory? then we can workout what to do from there. maybe just hardcode a simple stream name that doesn't have any `/` to see what we get as a tesT?

**Comment by ChristopheDuong** [comment]
I will change the Airbyte Stream Name from the Source File connector so that it contains only simple characters then!

Thanks!
