### ISSUE TITLE
Python linter fails on files with no imports

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#776]
## Current Behavior
* spotless python fails on python files with no imports.

## Steps to Reproduce
1. user template generate to create a new source in python
1. ./gradlew build
1. the build will fail with the linter dying in the unit_test.py file which has no imports.

<img width="831" alt="Screen Shot 2020-11-01 at 3 38 55 PM" src="https://user-images.githubusercontent.com/9092207/97818670-8d677700-1c58-11eb-81b2-742125c5479e.png">
<img width="715" alt="Screen Shot 2020-11-01 at 3 39 07 PM" src="https://user-images.githubusercontent.com/9092207/97818672-8f313a80-1c58-11eb-9aae-9b30746b80ca.png">

## Workaround
* adding an import fixes the problem.

**Comment by cgardens** [comment]
grrrrrrr. i hate this.

**Comment by michel-tricot** [comment]
I am suprised to see that we are specifying a separator in spotless, we didn't do it for java.

I'll take a look at it as I am working on the incremental spotless

**Comment by cgardens** [comment]
@michel-tricot was this completed as part of this issue https://github.com/airbytehq/airbyte/issues/754 or is it still open?

**Comment by michel-tricot** [comment]
It is unfortunately still open and there are no real solution. I spent some time looking at it: spotless needs some kind of a marker in the file to detect if the header is already there or if it it needs to update it or add it.

For java it is easy since you can use the `package` keyword but for python there isn't really a solution. The only work around would be to add more keyword as markers

**Comment by michel-tricot** [comment]
should I close it as wont fix?
