### ISSUE TITLE
Cloud users often create a second workspace instead of renaming

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#7845]
## Tell us about the problem you're trying to solve
The majority of Cloud users have more than one workspace, but only one is actually used.

When a user is created in Cloud, a workspace is automatically created for them. The workspace is named using the email of the user. The user doesn't understand that the workspace name can be changed by going to Configuration. Instead, the user creates a new workspace and names it to their liking, and leaves the original workspace empty. This causes many empty workspaces to exist, making it difficult to understand in Sales/CS which is the active or best workspace.

## Describe the solution you’d like
Allow the user to rename the workspace when it is created. We should provide a default name based on the email, but it should be obvious to the user that the workspace name can be changed on that screen. 

The default workspace name should ideally be the entire email (like natalie@airbyte.io-default), rather than using the first part of the email or the last. This prevents workspaces from being created with the same name (e.g. david-default or gmail-default)

**Comment by nataliekwong** [comment]
fyi @cgardens created this issue from our conversation today on renaming workspaces so that we can reduce workspace bloat

**Comment by cgardens** [comment]
@jrhizor what do you think about this one? the conversation started with what it would look like to add an Organization concept in addition to Workspace. I think that's something we'll definitely want to do, but in the short term it sounded like we could get quite a bit of value by just allowing the user to set the workspace name when they signed up. I was thinking down this path since it sounds relatively trivial, while adding Organization will certainly not be something we think about until Q1
