### ISSUE TITLE
Entering start date before data in Google analytics gives error

### ISSUE THREAD

**Issue by milo157** [airbytehq/airbyte#7901]
## Enviroment
- **Airbyte version**: 0.30.38-alpha
- **OS Version / Instance**: AWS EC2
- **Deployment**: Docker
- **Source Connector and version**: Google Analytics 0.1.9
- **Destination Connector and version**: Postgress
- **Severity**: Medium
- **Step where error happened**: Setup new connection

## Current Behavior
When setting up the Google analytics behaviour and I specify a start date before the date my Google analytics account had data or was even created) it gives the error "TypeError('cannot unpack non-iterable NoneType object')" which is not intuitive of what is causing the error.

## Expected Behavior
If the user enters a start date before the account has any data it should automatically sync from the earliest possible date

## Logs

[logs-2affa2d1-bc55-4511-826d-de9af3c5fefa-.txt](https://github.com/airbytehq/airbyte/files/7525912/logs-2affa2d1-bc55-4511-826d-de9af3c5fefa-.txt)

<details>

## Steps to Reproduce
1. Create a Google analytics source
2. Enter a start date that is before a date you had any data in your account

## Are you willing to submit a PR?
Potentially

**Comment by augan-rymkhan** [comment]
This error happens If a user enters `start_date` before the date when Google analytics account had the first data.
In `check_connection` method the current implementation tries to get only one the first date-slice to check the reading permissions.

For example: 
1. Google Analytics account is created on 2021-02-10
2. User enters 2021-01-01 as `start_date`, and `windows_in_date = 30`
3.` check_connection` method sends a request only for the first slice (2021-01-01 - 2021-02-31)
    [read_check](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-google-analytics-v4/source_google_analytics_v4/source.py#L491) list is empty because there is no data for that slice. Also there no exception is raised, so `check_connection`  methods returns `None`
[self.check](https://github.com/airbytehq/airbyte/blob/master/airbyte-cdk/python/airbyte_cdk/sources/abstract_source.py#L74) could not unpack `None`

**Comment by augan-rymkhan** [comment]
@milo157
We merged fix for this issue into master and released a new version of the connector.

Upgrade your connector to version **0.1.10** and get started. To upgrade your connector version, go to the admin panel in the left hand side of the UI, find this connector in the list, and input the latest connector version.

Please let us know if you have any further questions.

Enjoy!
