### ISSUE TITLE
Find ways to accelerate Klaviyo connector

### ISSUE THREAD

**Issue by tuliren** [airbytehq/airbyte#8002]
## Tell us about the problem you're trying to solve
- The Klavyio source connector runs slowly (e.g. https://github.com/airbytehq/airbyte-cloud/issues/588).
- One potential reason is that some of the APIs only allows full refresh (with pagination), and we cannot query from a specific date. Consequently we iterate through all pages, and consume the content if it is after a certain date.
- This is O(N) iteration. In theory we can do a binary search and greatly reduce the number of API calls to O(lgN) during the searching stage.

## Describe the solution you’d like
- Check which streams are ordered by the start date timestamp.
- Perform a binary search to find the page to pull data from.
- For now, just implement it for this API source. In the future, this could be generalized to other APIs as well.

## Describe the alternative you’ve considered or used
N/A

## Additional context
N/A

**Comment by sherifnada** [comment]
cc @keu

**Comment by keu** [comment]
I like this idea, but Klaviyo is a really bad example, as the list stream doesn't have a reliable cursor column (ts_update always == ts_created) and records ordered by creation time. So unfortunately there is no way we can just read some pages instead of the full read.

**Comment by keu** [comment]
Another possible use of pagination that supports random access:
we can save the last page that was read and continue reading from the place near it

**Comment by tuliren** [comment]
@keu, it looks like the global exclusion API does support reading a specific page, and the result is ordered:
https://apidocs.klaviyo.com/reference/lists-segments#get-global-exclusions

```sh
curl --request GET \
     --url 'https://a.klaviyo.com/api/v1/people/exclusions?api_key=PRIVATE_KEY&sort=asc&count=500&page=0' \
     --header 'Accept: application/json'
```

It has the `page` and `sort` parameter in the request URL.

Also the response does tell us the current and total page:

```
{
"object":"string"
"start":0
"end":0
"page":0
"page_size":0
"total":0
"data":[...]
}
```

Those seem sufficient to perform binary search.

**Comment by tuliren** [comment]
Oh, you are talking about the list stream, not the global exclusion stream. That stream also return the total page. Since the data is ordered by creation timestamp, that's also sufficient, right?

**Comment by sherifnada** [comment]
if we take the problem as: "make klaviyo faster" then I think potentially a trivial/low hanging fruit improvement we can make is to launch multiple async HTTP requests to the API, and reading their outputs as they arrive (respecting rate limiting)

To make it concrete, let's say a full sync from klaviyo entails making 10 http requests. the sequence of events would be: 

```
request 1
read response 1
request 2
read response 2
...
read response 10
```

Alternatively, we can do: 

```
request 1
request 2
request 3
request 4
request 5
read response 1
read response 2
read response 3
read response 4
read response 5
...
```

I think it might be worthwhile to try something like that first, because all users must first do a full refresh before an incremental sync would be useful, and right now users aren't even able to make a full refresh sync because of how long the connector takes. My order of priorities on making this connector faster (arguably on any connector) would be: 
1. make first-time experience as fast as possible (if it's sufficiently bad, users will just churn)
2. make incremental syncs better

**Comment by sherifnada** [comment]
@keu is this something you're able to look at?

**Comment by keu** [comment]
> Oh, you are talking about the list stream, not the global exclusion stream. That stream also return the total page. Since the data is ordered by creation timestamp, that's also sufficient, right?

I'm afraid not, because it is not an append-only stream, so we don't get updates.
So far the following list attributes can be updated: name, person_count
(Also we are using "deprecated" v1 API, the v2 doesn't have any order)

global_exclusions as I mentioned in the https://github.com/airbytehq/airbyte-cloud/issues/588 can be converted to incremental because it supports desc order.

**Comment by keu** [comment]
> @keu, it looks like the global exclusion API does support reading a specific page. Based on the documentation here: https://apidocs.klaviyo.com/reference/lists-segments#get-global-exclusions
my comment about requirements is a general requirements for all cases. not just Klaviyo, these are requirements to for the stream.

> I am not sure what you mean by "if it is descending we don't need this technic because it is simply incremental". If we know the total number of pages, and the data is sorted, whether they are sorted asc or desc only affects the direction of the binary search.
I mean that if we can sort stream desc we can fetch updates only, so we don't need binary search here, it would be more efficient to just read until the initial cursor value from the state.

**Comment by keu** [comment]
@sherifnada I think not only particular first sync is important, because let be honest there are data volumes that can sync in days. What is more important is to make any sync incremental. So eventually we will get there. Thinking about I can imagine another scenario when binary search or similar use of random access pagination can be useful:

Let's say we have 100k records and can sort ASC or DESC by updated.
We do initial sync and fail or stop after 1k of records.
Next time we will read from the tail (desc, the rest of 99k), but we can't save our progress before we read all data.
Instead, we can save metadata (to the state probably??) something about how many records there are, how many records we sync, how many pages, next pages, etc...
So next time we sync we can decide from which tail we will read (ASC or DESC). If it is ascending we can use binary search to find a precise page (if last page from meta data doesn't match).
