### ISSUE TITLE
SAT: Add incremental test to verify backward compatibility of the state files

### ISSUE THREAD

**Issue by keu** [airbytehq/airbyte#8057]
## Tell us about the problem you're trying to solve
One of the most important things, when you upgrade the connector, is to be sure that your sync progress will not be reset.
To ensure this new version of the connector still should be able to read any previously created STATE file.

## Describe the solution you’d like
SAT should have a test that checks if the connector correctly processes and use any STATE file generated by prev versions.

Solution 1:
Run incremental read with the latest image and save STATE file.
Run incremental on the testing branch with saved STATE file.
Check that none or only `state_value  < records` are produced.

Solution 2:
Maintain STATE file under `integration_tests` folder for each version of state file.
Have SAT to check incremental read with each STATE file

Solution 3:
None of the above solutions is perfect, so there is a space for a better one... TBD

## Describe the alternative you’ve considered or used
Do this manually.

## Are you willing to submit a PR?
yes

**Comment by alafanechere** [comment]
grooming note:
* check if state key changed
* running a sync with the previous state seems the most robust approach (solution 1)

**Comment by alafanechere** [comment]
## What can make a `STATE` not backward compatible:
If the developer changed the cursor field or the logic to update the cursor value this can break the post-upgrade sync in the following manner:
1. The current connector version loads a state generated with the previous connector version
2. The new cursor field is not present in the previous connector state
3. Past data, potentially already synced to a destination, get backfill, leading to duplicates on the destination and unexpected load on the source.

Because `STATE` objects are freeform objects, any key it contains might be used to alter a sync logic, so for safety, we can consider changes on all keys potentially breaking changes.  

## Potential **syntactic** tests: 
1. **Check that the cursor paths did not change:**
   * Run `discover` on both versions
   * Assert that the cursor field on each stream did not change

2. **Check that the previous STATE keys are a subset of the current STATE keys**:
    *  Run `read` on both connector versions, retrieve STATE messages
    *  `assert set(previous_state.keys()).issubset(set(current_state.keys()))`
    * Risk: performing `read` with the same config on both versions asserts that backward compatibility tests for spec passed.

## Potential **semantic** tests:
1. **Check that the current connector version can run with a previous connector STATE file**
    * Run `read` on previous connector version without state file.
    * Store that last state message in a file, keep track of the cursor value.
    * Run `read` on the current connector version with the previously stored state file.
    * Retrieve the STATE message and make sure the cursor value increases compared to the old state.
    * Risk: performing `read` with the same config on both versions asserts that backward compatibility tests for spec passed.

**Comment by alafanechere** [comment]
closing in favor of: 
* https://github.com/airbytehq/airbyte/issues/15439
* https://github.com/airbytehq/airbyte/issues/15440
