### ISSUE TITLE
Can't delete a connector which has a secret property containing a `pattern` in spec.json

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#8244]
## Current Behavior
I can't delete a stripe connector via the UI. I suspect it's because the spec for the connector describes the field: 

```
 "client_secret": {
        "type": "string",
        "pattern": "^(s|r)k_(live|test)_[a-zA-Z0-9]+$. ",
         "airbyte_secret": true
}
```

I suspect that because this field is **both** a secret and a pattern, when we go to delete it, the secret value is replaced with a secret mask `*******`. But this causes the pattern validation to fail. 

## Expected Behavior
I should be able to delete the connector. 

## Steps to Reproduce
1. Use Stripe connector version 0.1.23
2. Create a stripe connector in airbyte
3. try to delete it
4. fail

**Comment by cgardens** [comment]
Will be a "first" issue for parker.

**Comment by haoranyu** [comment]
The pattern attribute is already removed by https://github.com/airbytehq/airbyte/commit/dae0d77cbbf03cee08de92736c66d3cc1efce4cd

The issue can be closed I guess.

**Comment by sherifnada** [comment]
the problem is fixed for stripe but still present for any connector following the same pattern, so we should keep it open imo

**Comment by cgardens** [comment]
I was able to recreate this on OSS locally by using version 0.1.23 of the Stripe source. I used the integration test credentials in last pass. 

I think this is a 1 or maybe 2 line fix. 

https://github.com/airbytehq/airbyte/blob/master/airbyte-server/src/main/java/io/airbyte/server/handlers/SourceHandler.java#L172-L176
```
    final ConnectorSpecification spec = getSpecFromSourceId(source.getSourceId());
    validateSource(spec, source.getConnectionConfiguration());

    final var fullConfig = configRepository.getSourceConnectionWithSecrets(source.getSourceId()).getConfiguration();
    validateSource(spec, fullConfig);
```
I think the first `validateSource` is probably just an artifact left over from an before the secrets handling process. That is the line that is throwing the exception and it isn't surprising since the secrets aren't present in the object that it is trying to validate. The next line then gets the actual secrets and then validates again. I would expect the second validate to work. In testing it out it looks like it does. So I think all we need to do here is remove the first `validateSource`. 

After that, it's not super clear to me that the second validate is needed either. I think one use case we might have here is if we make a mistake and the spec for a connector evolves in a backwards incompatible way such that the config can't validate anymore, we still want to be able to delete it (because deleting is our escape hatch to just start from scratch).
