### ISSUE TITLE
Source Postgres: views are not listed during schema discovery

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#8254]
## Enviroment
- **Airbyte version**:  example is 0.32.5-alpha
- **OS Version / Instance**: macOS
- **Deployment**: example are Docker
- **Source Connector and version**: Postgres 0.3.14
- **Severity**: High

## Current Behavior
Postgres views are not listed in streams anymore. It's a regression from prior version `0.3.13` with which views are properly listed in the stream list.

## Expected Behavior
Postgres views should be replicable streams

## Steps to Reproduce
1. Create a view on your postgres sandbox
2. Set up a connection with a postgres source (version 0.3.14)
3. Listed stream does not contain postgres views

I think that the implementation of  `getPrivilegesTableForCurrentUser` function for Postgres source (introduced in https://github.com/airbytehq/airbyte/pull/8010) filters view out. @alexandertsukanov do you confirm my intuition?

**Comment by haithem-souala** [comment]
Hi,

### Current Behavior
When i click on **Update latest source schema**, i cannot see all tables in the database, but only ones created after the creation of the first airbyte Connection.
 
### Expected Behavior
Fetch all tables and views in the Postgres source database.

### Steps to Reproduce

1. Airbyte - Create a new source:  Postgres / 0.3.14
2. Airbyte - Created a new destination: BigQuery / 0.5.0
3. Airbyte - Create a new Connection, and select only ONE TABLE to sync.
4. Airbyte - Wait for the first sync. _(i'am not sure if this step is necessary)_
5. Postgres - Create a new table(s) in the source database
6. Airbyte - in the Settings tab of Connection, try to select other tables
7. Airbyte - it will only fetch the newly created tables in the **step 5**.
