### ISSUE TITLE
Source Iterable: Increase batch size for iterable from 1000 to 10000

### ISSUE THREAD

**Issue by danieldiamond** [airbytehq/airbyte#8262]
## Tell us about the problem you're trying to solve
Iterable connector is too slow to migrate all the data

## Describe the solution you’d like
A bulk API  e.g. similar to salesforce bulk api: 
https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-salesforce/source_salesforce/streams.py#L101

## Describe the alternative you’ve considered or used
None

## Are you willing to submit a PR?
unfortunately not

**Comment by avida** [comment]
@danieldiamond Could you please elaborate what problem you faced with Iterable and what connector's version? There is no such thing as batch size for Iterable API.  They are using [exports](https://api.iterable.com/api/docs#export_exportDataJson) endpoint to transfer large data over http chunked stream and only parameter we could modify is to adjust datetime range of data we want to extract. 

Since this endpoint has limit of 4 request per minute there could be a lot of 429 "try again later" error response. On other hand we cant specify datetime range too big cause Iterable server could close connection so we have to retry request (and worst thing that data are not sorted by datetime parameter so we have to start request over again to not lose some records).  Recently Ive added adjustable stream algorithm (#8091) so it could guess datetime range for optimal performance. Not a perfect solution though but should work.  

Could you please provide full logs and what connector version you are using?
