### ISSUE TITLE
DX: visualize code coverage in PR

### ISSUE THREAD

**Issue by keu** [airbytehq/airbyte#8271]
## Tell us about the problem you're trying to solve
Currently, we get an only percentage of coverage. This makes it hard to understand if changed lines were covered.

## Describe the solution you’d like
The desired solution should look this (https://stackoverflow.com/questions/67482906/show-coverage-in-github-pr)

![image](https://user-images.githubusercontent.com/1619536/143599665-3760d804-c3bc-4904-ba84-08138e97b85a.png)

## Describe the alternative you’ve considered or used
generate a coverage HTML report and download it.

## Are you willing to submit a PR?
yes

**Comment by yevhenii-ldv** [comment]
Hi @sherifnada!
I would like to describe the progress of work on this issue:

- To solve this issue, we can use such a service as Codecov(I will attach a link not to him [here](https://docs.codecov.com/docs/commit-status)). This service analyzes the results of testing our code and makes very handy diagrams for visualizing code coverage. Also, this service can be used not only for connections based on Python, but also for other programming languages (it is suitable for us for visualizing testing of all connectors, as well as destinations, SAT and airbyte_cdk). The list of supported languages can be found [here](https://docs.codecov.com/docs/supported-languages#below-is-a-list-of-supported-languages-linking-to-their-example-repositories).
- This solution has the following [pricing](https://about.codecov.io/pricing/). I have investigated it, and according to it, we can use the Free version, because `airbytehq/airbyte` is an Open Source (public) repository. According to this plan, we can use Codecov for free with an unlimited users.
- Directly for the issue that was pursued in this ticket, we also need to install the application in the settings of Airbyte personal account on GitHub - for the `airbytehq/airbyte` repository. You can read more about this [here](https://docs.codecov.com/docs/github-checks).
- I tried to test this and created an absolutely basic project with a couple of functions and several tests that cover some of the functionality (you can see it [here](https://github.com/yevhenii-ldv/test-coverage/pull/4)). If you open the `Files changed` tab in this Pull Request, you can see the annotations that display lines not covered by tests (for example, [here](https://github.com/yevhenii-ldv/test-coverage/pull/4/files#diff-ea564ae7a4d58a58dce33caa3ec9920f5cf7cf43aad43aedf85b95ecd276e889))
- I tried to do the same for the airbytehq / airbyte repository and make some changes with it, and I got something ([link](https://github.com/yevhenii-ldv/airbyte/pull/11)) however I used hardcode to run tests only for the Braintree connector.

On this I stalled, bacause I wanted to check if we can use this functionality for our project, but I cannot run test commands for connectors using a forked project. And unfortunately, I could not test this feature, and I cannot be 100% sure that this service will be able to satisfy our requests according to the current issue, since Airbyte project is quite large and complex, and it even looks a bit like we have many repositories in one repository. And this can all be seen in the way we use Github Actions to test our connectors independently of each other.

Based on this, as far as I understand, the next step is to connect Codecov to the main project and continue working directly with it (not with fork), then we can check in more detail how it can interact with Github Actions to test connectors (and not only).

And from this follows the next problem, I tried to study how this Github Action works and found that we use the `ci_integration_test.sh` command sequentially, which then launches the `Gradle` command, which subsequently runs the tests. And, unfortunately, I could not understand how it all connects and works with each other, and therefore connecting Codecov there turned out to be quite a difficult moment for me.

**Comment by sherifnada** [comment]
@yevhenii-ldv thanks for the report. This looks great. I think we should shoot to merge this sprint if possible. If you have any technical questions please reach out in the connectors org slack channel and prefix your message with `Airbyte team:` so it is clear you're asking one of us for assistance
