### ISSUE TITLE
Hubspot: Support incremental sync on all possible streams

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#8344]
## Tell us about the problem you're trying to solve
The Hubspot API supports incremental sync for many more objects than we currently offer via our connector. Many streams (e.g: `products`) are using full refresh sync when they could be doing incremental. 

## Describe the solution you’d like
1. Find which streams can support incremental sync
2. Support incremental sync for as many as possible

**Comment by lgomezm** [comment]
Hello! I've been exercising this solution as we need incremental updates to handle one of our use cases, but I think the current solution won't scale for big Hubspot accounts. That is because it iterates over the the complete dataset (say `contacts`) and outputs only those that were created/updated after the given state.

I would be more than happy to take on the task of updating this connector and, in fact, I already have a branch in which I am applying a different approach on some of the available streams. If that's okay with you guys, I can create a draft PR (will add tests shortly and update all other necessary files).

**Comment by sherifnada** [comment]
@lgomezm nothing we love more than a contribution! let us know how we can be helpful, @lazebnyi can work with you to get it into master :)
