### ISSUE TITLE
Persist normalized in the same schema as unnormalized tables

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#845]
## Tell us about the problem you're trying to solve
It is unintuitive that when a user requests data to be replicated into schema (or dataset in BQ) `X` that we replicate it into schema `X_NORMALIZED`. We should replicate the normalized table into `X`.

**Comment by ChristopheDuong** [comment]
DBT is not able to overwrite the destination table that contains the JSON blob data with a new table with the proper schema since it is using that JSON BLOB as input. (Same table is simultaneously used as input and output)

So the destination connectors should write into a different table name instead (with a _raw suffix?) so that DBT can actually output the final destination table name with the proper normalized schema.

Currently to bypass this problem, DBT is writing in a different schema that has a `_NORMALIZED` suffix

**Comment by michel-tricot** [comment]
I like the idea of writing to a table with the _raw suffix

**Comment by sherifnada** [comment]
complete with #874
