### ISSUE TITLE
Source Shopify: PoC performance improvement from using the GraphQL API. 

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#8503]
## Tell us about the problem you're trying to solve
Context is available in #8487 . TL;DR the shopify source is incredibly slow when syncing transactions, which is a resource nested under `orders`. The current sync strategy is to read an order, then make another API class specifically to get the orders. This is incredibly slow. I expect we can get a literal 100x speedup on the transactions stream by using the GraphQL API. 

## Describe the solution you’d like
1. validate the assumption that using the GraphQL API will make the sync faster
2. if yes, investigate how we can rewrite the connector (or certain portions of it) to use the graphQL API. 

There is a blocking issue in the CDK that will first need to be resolved before we can do this well. The CDK today assumes that each stream is read sequentially i.e: read orders, then order transactions, etc.. and manages state based on this assumption. We will need to change the CDK to allow the concept of a "composite" stream i.e: one which outputs records from multiple streams and manage state appropriately. 

## Describe the alternative you’ve considered or used
Patience of the strongest kind

**Comment by sherifnada** [comment]
wrote a quick PoC. Pulling orders seems to be much faster

```
import requests

token = '<>'
def form_query(cursor=""):
    pagination_clause = f", after:\"{cursor}\"" if cursor else ""
    query = '''
    {
      orders(first: 250, sortKey: UPDATED_AT''' +  pagination_clause +'''){
        pageInfo {
          hasNextPage
        }
        edges {
          cursor
          node {
            id
          }
        }
      }
    }'''
    return query

def req(query):
    url = 'https://airbyte-integration-test.myshopify.com/admin/api/2021-07/graphql.json'
    headers = {'Content-Type': 'application/graphql', 'X-Shopify-Access-Token': token}
    r = requests.post(url, headers=headers, data=query)
    return r

has_next = True
cursor = ''
while has_next:
    query = form_query(cursor)
    print(query)
    r = req(query)
    print(r.status_code)
    json_response = r.json()
    print(json_response)
    has_next = json_response['data']['orders']['pageInfo']['hasNextPage']
    cursor = json_response['data']['orders']['edges'][-1]['cursor']
    print(cursor)
```

**Comment by bazarnov** [comment]
Hello, polling the `orders` stream is not the issue of the performance, the `orders` are pulled fast and easy using REST API + pagination. Example, we have 122 orders inside of our integration-test account for shopify, we can pull them easily with REST API Call, took 1 sec for this operation. 

The biggest issue here is the polling the others dependent on `orders` stream, like `order_refund`, the REST API call accepts only the order_id, as input, so we need to run through each order id to find the information about the refund.
Same situation with `transactions`, `order_risks`, `fulfillment_orders`, `fulfillments` - those streams are iterating foe each order_id to fetch their relevant information from API.

Basically, we can use the GraphQl API instead of REST API here, however this bring us more problems than solutions.
1) The GraphQL is much more limited than REST in terms of performance. more info here: https://shopify.dev/api/usage/bulk-operations/queries#operation-restrictions
2) When we pull the data out using GraphQL we need to pass the whole amount of fields inside the `node {...}` structure before the query executed. The names are different from those are coming using REST API. Basically we need to have the ready-to-go gQL query, which is equally to "have another Json schema" for each stream.
3) We would need to deal with more throttling than expected, the details are covered here in article by Shopify themselves, using simple `metafields` nested structure. I assume the more nested structures we have inside the stream, the more we wait until we can go on with data fetch for each and every stream. 
https://www.shopify.com/partners/blog/shopify-metafields

I don't believe the GraphQL approach will resolve the performance issues, just because it exists as an option to use, even though we can use the BulkOperation on it and pull the whole object at once (nice try, but no) we are still limited with this:
https://shopify.dev/api/usage/bulk-operations/queries#operation-restrictions

The GraphQL approach is good when you need some sort of specific information we know exists, we will face a bunch of issues while working on different user account with different amount and data-structure (like we have fields 1,2,3. User have fields: 1,2,3,4. the difference is field 4, it will not be included inside of the ready-query, so we miss this data) On the other hand there is no method to retrieve the list of available nodes for each object, which is super sad.

LMK WDYT.

**Comment by sherifnada** [comment]
notes from convo: 
1. shopify does not accept time when filtering by `updated_at`, only by day
2. bulk operations only accept two levels of nesting, if we ever need to do it for multiple levels of nesting then we are SOL

this plus the points made by baz above indicate that the graphql API is not really a good fit for our usecase

**Comment by sherifnada** [comment]
closing the issue as the PoC is now complete

**Comment by philippeboyd** [comment]
@sherifnada will this PoC be implemented for Shopify? 

I'm not seeing anything GraphQL related in the changelog https://docs.airbyte.com/integrations/sources/shopify#changelog

Shopify as a Source is still super slow...

**Comment by sherifnada** [comment]
@philippeboyd due to the reasons explained above, we found that the GraphQL API does not offer reliable improvements for this connector unfortunately, so GQL is not a feasible path forward.

**Comment by zds97** [comment]
Just wanted to follow up to see if this might be reconsidered due to the additional fields provided by the GraphQL API. https://github.com/airbytehq/airbyte/issues/8503

**Comment by sherifnada** [comment]
@zds97 it would be considered in the scope of that ticket. Follow there for updates!
