### ISSUE TITLE
Source Google Analytics: Improve sampling awareness

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#8570]
## Problem
The `window_in_days` parameters was removed from source Google Analytics specification to simplify configuration, it now defaults to 90 days. This decision comes from this issue https://github.com/airbytehq/airbyte/issues/7850 and was implemented in this PR https://github.com/airbytehq/airbyte/pull/8175.

This parameters could be used as a workaround to avoid Google Analytics API sampling that can lead to return inconsistent results according to user expectation. Google Analytics samples results when reports has > 500000 records. Downsizing reports with a custom `window_in_days` parameters allow the avoidance sampling while increasing the sync duration. 

Moreover it's not currently explicit for users that a report they ingest is sampled or not. This information is returned by Google Analytics API so we should be able to display warning logs / automatically reduce the report size to solve this sampling problem.

## Solution
I'd suggest the following:
* Display warning logs that a report was sampled during read operation 
* Re-add `windows_in_day` parameters (or rename in to `batch_size`) + document its impact in the specification description field.
* Or make the connector smart enough to adapt the batch size if the consumed reports appears to be sampled.

## Reference
I opened this issue following a Slack [thread](https://airbytehq.slack.com/archives/C01MFR03D5W/p1638643722342600?thread_ts=1637860057.477300&cid=C01MFR03D5W) with @folusoogunlana

**Comment by alafanechere** [comment]
@nataliekwong what's your opinion on this?

**Comment by foogunlana** [comment]
@nataliekwong @alafanechere FYI the documentation says that it samples when there are more than 500k "sessions" in the data, not "records". See [the doc I'm talking about here](https://support.google.com/analytics/answer/2637192?hl=en#thresholds&zippy=%2Cin-this-article).

The documentation might be wrong (or just not specific enough) though. If it's correct it's worth noting that it complicates the implementation of any self-correcting connector, because the custom report would have to always fetch for sessions.

As for self-correcting, here's a suggestion:

Check the response for each report for the `sampleReadsCounts` and `samplingSpaceSizes` fields - see the `ReportData` type [here](https://developers.google.com/analytics/devguides/reporting/core/v4/rest/v4/reports/batchGet), and if they're present and `(sampleReadsCounts[i] / samplingSpaceSizes[i]) < 1`, then it's being sampled. Otherwise, it's not being sampled. If it's sampled, we could then halve the batch size and try again starting from the stream slice that failed.

I could give this a go if you all think it's a good idea

**Comment by foogunlana** [comment]
Actually, instead of halving the batch size, we could `updated_batch_size = current_batch_size * sampleReadsCounts[i] / samplingSpaceSizes[i]`

**Comment by alafanechere** [comment]
Yes great suggestion @foogunlana , you're contribution is welcomed of course 😄

**Comment by sherifnada** [comment]
I would love to explore self-correcting behavior which is toggled perhaps with a "prevent sampling" boolean flag. @foogunlana would setting `window_in_days` to 1 basically solve this issue? 

If that's the case, is there any reason not to set this number to 1 by default instead of 90?

**Comment by alafanechere** [comment]
Settings `window_in_days` to `1` will probably reduce sampling but increase read duration. I find it a legit workaround but it does not guarantee no sampling for high traffic websites that have > 500k session / day.

**Comment by foogunlana** [comment]
Good point @alafanechere. There might be users for whom 1 day is still too large a window size. Though, that problem can't be solved without changing the `cursor_field` from `ga:date`, which has a granularity of 1 day, to something more granular - e.g. `ga:dateHourMinute`. Perhaps that could be another improvement to make here.

**Comment by foogunlana** [comment]
Couple of updates here.

1. The best we can do is `ga:date` not `ga:dateMinuteHour`. Judging from the documentation, you can only use `startDate and `endDate` which has a format of `YYYY-MM-DD` - https://developers.google.com/analytics/devguides/reporting/data/v1/rest/v1beta/DateRange

2. Another reason that sampling can occur in ga's API is due to high cardinality of custom dimensions. e.g. if you add a custom dimension "user_id" and there are over X users in a single time period, GA will sample the report instead of fetching all the unique user_ids.

I also suspect a better way to tell if the data is sampled is to check the `isDataGolden` field, which is a boolean telling you whether or not the query will always return the exact same data. If the report is sampled, I doubt that can be `true`. See [here](https://developers.google.com/analytics/devguides/reporting/core/v4/rest/v4/reports/batchGet#OrderBy).

I now like the suggestion of setting `window_in_days` to 1 since we can't get under 1 day. It might be the best we can do. Is there any way to warn users when `isDataGolden` is `False`? I'm also worried the first sync will be quite huge if we have to sync a few years with `window_in_days` set to 1. 🤷

**Comment by alafanechere** [comment]
@foogunlana Let's go for the `window_in_days = 1`. We can make the connector log warnings when `isDataGolden = false`.
