### ISSUE TITLE
Make it possible to opt-out from cloud logging

### ISSUE THREAD

**Issue by TSkrebe** [airbytehq/airbyte#8581]
## Tell us about the problem you're trying to solve
It's not possible to opt-out from cloud logging.

## Describe the solution you’d like
I'd like to have configuration (through helm charts) to opt-out from cloud logging i.e. minio/gcp/aws when using k8s.

## Describe the alternative you’ve considered or used
There is no alternative at the moment. 

## Additional context
When running k8s, all logs can be collected by tailing logs from _/var/log/pods_, therefore there is no need too use cloud loggers.

## Are you willing to submit a PR?
maybe

**Comment by jrhizor** [comment]
There are a couple issues that we face with logging that made us go in the current direction:
1. Users usually want log histories for jobs longer than they want the pods around. If we're pulling the logs from k8s logging, we won't have the backed up history.
2. Connector pods output both records and logs to stdout. Our current wrapping of the source images reroutes all stdout to another pod that's responsible for deciding whether a line should be logged or if the line should be treated as a record and passed to a destination. Right now this other pod runs multiple source/destination pairs, so we still need to write the logs to some persistent location if we want to read it per-sync in the UI.

Even if you discount 1), for 2) the vast majority of users don't want their data records to be sent to k8s logging. However, if we made the wrapper for connector pods smarter, we could differentiate logs from data on the connector pod instead of the pod orchestrating them. I can definitely imagine a version where we do this (so all logs end up in k8s pod logs as expected) and then the logs are collected by some other async process (either Stackdriver/similar or a process that reads from k8s logging and writes to cloud storage) before the completed pods are deleted.

@davinchia any thoughts?

**Comment by davinchia** [comment]
@TSkrebe logging to Cloud storage powers the Airbyte webapp UI, especially the live log stream in the Jobs panel. Are you planning to use the Webapp? If you are Cloud storage is required. There is no good way to pull logs from general logging solutions otherwise. Does that make sense?

**Comment by TSkrebe** [comment]
@davinchia yes, I somehow missed that you use Cloud for webapp UI.. Thanks for explaining guys. 

It might be a controversial idea but what if it was configurable to put log to postgres? These logs don't to be indexed, so it could be dumped to TEXT or whatever. The reason i raised this ticket was purely from operational perspective. I'd rather maintain a single postgres than postgress + minio. I totally understand your approach from architectural pov, so this is more of a wishlist-type-of ticket.

**Comment by alafanechere** [comment]
I'm adding the area/documentation tag as @jrhizor and @davinchia comment are valuable and might help adding details to the [Cloud logging section](https://github.com/airbytehq/airbyte/issues/8581)

**Comment by davinchia** [comment]
@TSkrebe my main concern with using postgres is the scalability. Iirc, the columns (or rows) are limited to 1GB size so we would need to use some sort of rotation for the server and scheduler logs. I don't want to say no, but it seems slightly strange to me. Will discuss more with Jared.

Operationally would it be easier to use a proper Cloud storage option e.g. AWS or S3? All you would need to set up is a bucket and credentials.

**Comment by TSkrebe** [comment]
Sometimes using cloud is not an option due to circumstances. 

So if i understand correctly, it's possible for a single attempt to produce 1GB of logs?

**Comment by jrhizor** [comment]
We operate under the worst case assumption that attempts can produce a lot of log data. In theory, someone could have a custom connector that logs 100 lines per record and end up with a multi-gb log file. While we would strongly discourage implementing a connector like that, the platform needs to be robust to cases like this so any connector-level bugs don't take down the rest of the system by taking down the shared db or some other shared and limited resource.

**Comment by TSkrebe** [comment]
I agree with all your points. I'm not suggesting to change the default behavior, but rather make it possible to opt-in. Again, this is more of a wish than some make-or-break feature. Thanks for explaining current architectural design decisions!

**Comment by davinchia** [comment]
I'm going to close this since we are not going to work on this.
