### ISSUE TITLE
Source CockroachDB: Do not list tables in the connection settings if user do not have access to them #5172

### ISSUE THREAD

**Issue by sashaNeshcheret** [airbytehq/airbyte#8868]
## Environment
- **Airbyte version**:  example is 0.34.4-alpha
- **OS Version / Instance**: Ubuntu 20.04
- **Deployment**: Docker
- **Source Connector and version**: source-cockroachdb 0.1.3
- **Destination Connector and version**: source-cockroachdb 0.1.3
- **Severity**: High
- **Step where error happened**: Sync job / Setup new connection

## Current Behavior
User can see all tables even he does not have select grants for some of them during discovery.

## Expected Behavior
User can see only tables where he have select grants during discovery.

## Steps to Reproduce
1. Start Airbyte
2. Set CockroachDB as the source
3. Set any destination
4. Proceed to Setup new connection, verify schemas and tables where the connected user doesn't have privileges appear on Airbyte UI

**Comment by lshrinivas** [comment]
@sashaNeshcheret I think the PR that fixes this should take into account the `public` role as well [here](https://github.com/airbytehq/airbyte/pull/9004/files#diff-32e498a181faa29ce368c0c6336f574789749c5a1f3cd98772d63599e303ec4cR113). I was bitten by this when using v0.1.5 of the CockroachDB connector, where I couldn't see any tables, whereas I could with v0.1.4. When connecting to CockroachDB via another tool (like DBeaver), and the same credentials, I could see all the tables. Upon digging deeper, I found this is so because the tables had SELECT grants given to PUBLIC, and not explicitly to the db user I connected with. 

I can work around this issue by providing explicit GRANTs to the db user I use, but judging from the intent of this ticket (and PR), I think any tables that are accessible to the PUBLIC role should be visible in the Airbyte UI.
