### ISSUE TITLE
🐛  Source Postgres: JSONB Postgres field shows as string

### ISSUE THREAD

**Issue by joshuataylor** [airbytehq/airbyte#9028]
## Environment
- **Airbyte version**:  v0.35.0-alpha
- **OS Version / Instance**: Ubuntu
- **Deployment**: Docker
- **Source Connector and version**: 0.4.0
- **Severity**: Medium
- **Step where error happened**: Connection

## Current Behavior
In Postgres, I have a JSONB field. This shows as string in airbyte, where as I want this to be JSONB so I can have the field as VARIANT in Snowflake.

## Expected Behavior
It shows as variant.

## Steps to Reproduce
1. Create a postgres table with a JSONB column
2. It shows as string
3. It exports as string

**Comment by harshithmullapudi** [comment]
Hey @joshuataylor can you help us understand this more. If your question is the column type JSONB is not reflecting back in the connection schema then yeah this is done to keep the schema generic across all the destinations.

Being said that you can do the needy in the Custom DBT and transform it the way you want.

**Comment by bleonard** [comment]
Note: I assume jsonb can be either Object or Array

**Comment by bleonard** [comment]
Quick google search suggests that JSONB is always an object (and not a string or array, etc). Validate that.
In `discover, return the JSON SChema as `object` and not `string`.
Validate that GA destinations handle that as expected. For example, `VARIANT` in Snowflake. @edgao says he thinks it should work.

**Comment by edgao** [comment]
jsonb can be any valid json value, including object, array, string, etc:
```
postgres=> select '[1, 2, 3]' :: jsonb;
   jsonb
-----------
 [1, 2, 3]
(1 row)

postgres=> select 'true' :: jsonb;
 jsonb
-------
 true
(1 row)
```

de facto, normalization will map a `{type: object}` schema to `jsonb`, so this will work fine for normalized destinations. But I'm less sure this plays nicely with Avro (and by extension, destination-bigquery-denormalized) - it's not obvious what we're supposed to write in this case.

**Comment by VitaliiMaltsev** [comment]
i have created draft [PR](https://github.com/airbytehq/airbyte/pull/19971) with mapping of jsonb datatype to {"type":"object"} in jSON schema and tested it with different destinations

Here is my test table
![Screenshot 2022-11-29 at 19.00.06.png](https://images.zenhubusercontent.com/627269d854eb270caf3b5686/ac524bc9-3e1d-4c7d-8a64-6cb1d625d7fa)
All of these values are valid for JSONB
Results:

**Redshift** JSONB ----> SUPER
Standart inserts - ok
S3 staging - ok

**Bigquery** JSONB ----> STRING
Standart inserts - ok
GCS Staging - ok

BigQuery denormalized 
Standart inserts - failed
`BigQueryError{reason=invalid, location=null, message=Error while reading data, error message: JSON parsing error in row starting at position 0: Flat value specified for record field. Field: test_column; Value: [1, 2, 3]}:`
GCS Staging(AVRO)- failed
`Caused by: org.apache.avro.AvroTypeException: Could not evaluate union, field test_column is expected to be one of these: NULL, RECORD. If this is a complex type, check if offending field (path: test_column) adheres to schema: [1, 2, 3]`

**S3** 
CSV - ok
JSONL -ok
AVRO - failed
Parquet - failed

**Snowflake** JSONB ----> VARIANT
Internal Staging  - ok
AWS S3 Staging (CSV) - ok
GCS Staging (CSV) - ok
Azure blob Staging (CSV) -ok

Summary of all these fails - currently we can not map all of JSONB values into avro record and BigQuery Denormalized can not map it also - all that you mentioned above

AFAIK in airbyte protocol V1 removed _airbyte_type_ from json schema and we should not use it anymore so schema mapping like _{"type": "object","airbyte_type": "jsonb"}_ will not be valid. Is it correct?

I'm not sure how to handle all of valid Jsonb values on the destination side for AVRO records and BigQuery Denormalized. Seems like json schema mapping like {"type":"object"} is not enough to cover all the cases for different destinations
@edgao do you have any ideas?

**Comment by edgao** [comment]
nice research!

> AFAIK in airbyte protocol V1 removed airbyte_type from json schema and we should not use it anymore so schema mapping like {"type": "object","airbyte_type": "jsonb"} will not be valid. Is it correct?

correct. (tbf, adding arbitrary new values to airbyte_type in protocol v0 was probably also not the right approach, since there was no guarantee that all destinations/normalization would handle it correctly )

> how to handle all of valid Jsonb values

It sounds like this doesn't fit into any of the existing types. Therefore, we should:
1. Add a new WellKnownTypes.yaml entry for "arbitrary json" (this should resolve to the `{}` schema, i.e. accept anything)
    1. This needs to go through the protocol change process, and maybe (?) requires a protocol major version bump
2. Update normalization to handle that new type correctly
3. Figure out what the correct avro type is (I don't think avro has a good "any value at all" type, so this might need to just be a `string` - but we should do the research to confirm/deny that)
4. Update avro + bigquery-denormalized to convert the new type to that avro type
5. Update sources to discover + read the new type

So this has a dependency on the ongoing data types protocol project. (cc @grishick )

**Comment by VitaliiMaltsev** [comment]
> * Add a new WellKnownTypes.yaml entry for "arbitrary json" (this should resolve to the `{}` schema, i.e. accept anything)
>   
>   1. This needs to go through the protocol change process, and maybe (?) requires a protocol major version bump
> * Update normalization to handle that new type correctly
> * Figure out what the correct avro type is (I don't think avro has a good "any value at all" type, so this might need to just be a `string` - but we should do the research to confirm/deny that)
> * Update avro + bigquery-denormalized to convert the new type to that avro type
> * Update sources to discover + read the new type

@edgao 
1. I have updated [PR](https://github.com/airbytehq/airbyte/pull/19971) with V1 protocol requirements. Please take a look
2. Regarding the normalization -  @etsybaev is working on [normalization update ](https://github.com/airbytehq/airbyte/pull/19721) and also i created a separate task to handle new datatype https://github.com/airbytehq/airbyte/issues/20130
3. I tried different ways to create correct avro record from the valid values of jsonb but have no luck, so yes String type in Avro schema is an ideal candidate 
@suhomud is working on avro schema conversion for V1 protocol [here](https://github.com/airbytehq/airbyte/pull/20088) so probably we could add the new datatype handling in his PR
4. Bigquery-denormalized update is more complex due to json schema conversion in connector. Here is an [issue](https://app.zenhub.com/workspaces/destinations-6332532d6893ce001c7a56a7/issues/airbytehq/airbyte/17647) to handle it  
5.  discover + read updated in my [PR](https://github.com/airbytehq/airbyte/pull/19971)
  cc @grishick @bleonard

**Comment by bleonard** [comment]
This is definitely something we should be very careful about with the ongoing data types work and issues we've seen.
