### ISSUE TITLE
Make generated DBT models downloadable from the UI

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#9123]
Enabling a _Download DBT models_ button in the UI could help users that want to implement their own custom transformation and make the debugging normalization easier.

The current flow requires the user to have access to the docker containers, and Airbyte UI users might not be the same team that is operating Airbyte.

The current flow is described in this [tutorial](https://docs.airbyte.io/operator-guides/transformation-and-normalization/transformations-with-dbt) and can be a bit cumbersome for some non-technical users:
```
#!/usr/bin/env bash

TUTORIAL_DIR="$(pwd)/tutorial/"
rm -rf $TUTORIAL_DIR/normalization-files
mkdir -p $TUTORIAL_DIR/normalization-files

docker cp airbyte-server:/tmp/workspace/$NORMALIZE_WORKSPACE/normalize/ $TUTORIAL_DIR/normalization-files

NORMALIZE_DIR=$TUTORIAL_DIR/normalization-files/normalize
cd $NORMALIZE_DIR
cat $NORMALIZE_DIR/models/generated/**/*.sql
```

**Comment by sethsaperstein** [comment]
As a follow up, this would greatly improve the development lifecycle of dbt + airbyte + warehouse configuration, by making it self-service for non-engineers. In other words, I would like to build a data platform with these technologies, then enable another team to act as users. They consist mainly of non-technical data modelers that take tickets to bring data into our warehouse and model the data properly via dbt. The development lifecycle I'm looking for that does not involve an engineer to exec into the airbyte container ad hoc to get the dbt staging model is as follows:

New connection:
- Configure the source
- Configure the destination (most likely already configured as your warehouse)
- Configure the connection
- Run the connection (default normalization enabled)
- Grab the generated dbt model (the difficult bit)
- Go to dbt cloud, paste in the staging model
- Build, test, and modify downstream models in dbt cloud
- Kick off your model deployment in dbt cloud


Scheduled updates to the connection:
- Turn the connection to a scheduled update
- Select a custom dbt transformation (as configured above)
- Have the custom dbt transformation trigger all downstream models with command dbt run <model>+
- Optional: Have the dbt command trigger via a hook into your dbt cloud deployment rather than the github repo (so that dbt run history is in a unified view and dbt cloud alerting benefits are realized)

**Comment by marcosmarxm** [comment]
This also would help users on Kubernetes where volumes are ephemeral.

**Comment by grishick** [comment]
This would also greatly help Airbyte engineers when troubleshooting normalization errors.

**Comment by cgardens** [comment]
We are no longer generating these dbt models and have [deprecated this feature](https://github.com/airbytehq/airbyte/discussions/34860).
