### ISSUE TITLE
Source Google Ads: Support the new campaign type "Performance Max"

### ISSUE THREAD

**Issue by julienBovet** [airbytehq/airbyte#9313]
## Tell us about the problem you're trying to solve
As of today, data about Performance Max campaigns in Google Ads Source connector are not pulled properly.

## Describe the solution you’d like
Manage this campaign type correctly like the others and upgrade API to Google Ads API V9 (that has this new support)

## Describe the alternative you’ve considered or used
Neither Google Ads Data Transfer OR Fivetran support this. Airbyte would get a nice advantage here ;)

## Additional context
Looks like the data is pulled with a campaign type = Unknown according to that slack discussion
https://airbytehq.slack.com/archives/C021JANJ6TY/p1641385198058300

## Are you willing to submit a PR?
Nope

Thanks a lot !

**Comment by augan-rymkhan** [comment]
Campaign type "Performance Max" was added in Google Ads api version V9. To support this type in the connector we need to upgrade google-ads python package to the latest version [14.1.0](https://github.com/googleads/google-ads-python/blob/main/ChangeLog)
After upgrading locally, some SAT test cases failed. 

- `use_proto_plus` mandatory field was added.
- Some fields in `ad_group_ads` were deprecated.

Currently, I am working on the how to fix the root cause of the failed tests.

**Comment by VasylLazebnyk** [comment]
@sherifnada please take a look at the scoping report, Auganbay also created a PR according to it.

**Comment by Bart97coder** [comment]
This type of advertising is quite interesting. In my opinion, it is worth looking into this. If anyone wants to expand their knowledge, I recommend [this post](https://gamerseo.com/blog/performance-max-google-ads-specs-optimizing-your-campaigns-for-success/) on optimization.
