### ISSUE TITLE
Variable Input Fields UI Component Buggy

### ISSUE THREAD

**Issue by misteryeo** [airbytehq/airbyte#9417]
## Current Behavior
1. When adding a new item to the variable input fields component, it creates a non-descriptive ascending numerical list.
2. If a user goes in to edit any item within a created list of fields and clicks 'Cancel' instead of 'Save' - all previously created fields disappear and the 'Add' button freezes.

## Expected Behavior
1. Each new item added should expose the value that's been included in the field, not a numerical list.
2. Clicking 'Cancel' should return user to the existing list of fields they already setup and not reset + freeze them out of that screen requiring them to refresh the screen and start from scratch.

Recorded a Loom to illustrate this: https://www.loom.com/share/0bb7add7e488469eb97ec97fa73b684d

**Comment by Jamakase** [comment]
@misteryeo Thanks for your report. There is indeed an issue with cancel button.

However `When adding a new item to the variable input fields component, it creates a non-descriptive ascending numerical list.` is done this way by design.

The problem is that in case there is no name field, we are not sure what value to actually display for such object, so we display an index. 

@jrhizor if we are going to display some other info instead of just index, we need to decide what exactly we would like to display ( some field / combination of fields / json )

**Comment by Jamakase** [comment]
Added a fix for `Clicking cancel when editing one of the filter criteria causes a failure.` case. If we are going to change behavior for naming - let's open a separate issue.

**Comment by timroes** [comment]
I've created https://github.com/airbytehq/airbyte/issues/10858 to follow up on the outstanding issue with indexes in the list + the redesign of the component.
