### ISSUE TITLE
[EPIC] Update schemas in source connector source-pinterest

### ISSUE THREAD

**Issue by rfortmann-ewolff** [airbytehq/airbyte#9568]
## Summary
- [ ] Update existing schemas

## TODOs
- [ ] Review following PR : https://github.com/airbytehq/airbyte/pull/9537

**Comment by misteryeo** [comment]
@rfortmann-ewolff assigning this to you as I see you're working on a PR for this.

cc: @marcosmarxm

**Comment by philipherrmann** [comment]
This issue is about a pretty trivial bug/typo, where "AD_ACCOUNT_IDAD_ID" was accidentially written to schema json, instead of "AD_ACCOUNT_ID", and "AD_ID". It makes the normalization for the stream "ad_analytics" quite unusable. Ronald and me were trying to get the integrations tests to pass, but we struggle because we quickly run into rate limits in our account despite of having "Standard" Pinterest v5 API access. Think we need some help to get this PR ready.

**Comment by alafanechere** [comment]
Fixed by https://github.com/airbytehq/airbyte/pull/10223
