### ISSUE TITLE
Support WAL replication

### ISSUE THREAD

**Issue by michel-tricot** [airbytehq/airbyte#957]
## Tell us about the new integration you’d like to have
I would like airbyte to sync mysql & postgres using WAL

**Comment by rubenssoto** [comment]
Great idea, so airbyte will be a CDC tool

**Comment by michel-tricot** [comment]
You got it! :)

**Comment by nicor88** [comment]
Wow, looking forward to that.

**Comment by jrhizor** [comment]
I'm closing this issue and splitting it into other issues:
- Postgres (https://github.com/airbytehq/airbyte/issues/2156) - released!
- MySQL (https://github.com/airbytehq/airbyte/issues/2847)
- SQL Server (https://github.com/airbytehq/airbyte/issues/2848)
- Oracle (https://github.com/airbytehq/airbyte/issues/2849)

If you need CDC for a different source than what's listed here please create a feature request ticket if the non-CDC version of the integration already exists and an integration request otherwise.
