### ISSUE TITLE
Tech spec for staging in all cloud destinations 

### ISSUE THREAD

**Issue by subodh1810** [airbytehq/airbyte#9617]
Write a tech spec for issue https://github.com/airbytehq/airbyte/issues/7555

**Comment by ChristopheDuong** [comment]
Please note that today we have a class `OAuthConfigSupplier` that is injecting OAuth instance wide parameters into connector config at the last minute by the scheduler before passing the final configuration to a worker starting a sync/check_connection/discover operation.

The instance-wide parameters for OAuth are meant to be kept secrets and not shared with end-users, which is why they are not persisted inside the connector config to avoid leaking them out.

This ticket for staging by default in all cloud destinations should be behaving in a similar way as a fallback mechanism where default staging bucket credentials (meant to be kept secret from users too) could be injected into destination connector configurations. They could be configured in a similar way as an "instance-wide" parameter.

As a result, we should take this into consideration when speccing out this feature in order to re-work both the OAuth injection and the default staging option for destinations and make a more generic "injection" functionality.

**Comment by subodh1810** [comment]
https://docs.google.com/document/d/18_Ezbl7Z1aSpHBdFFUy6BHMlDfYTktI4Yp8h2DbX4RE/edit#heading=h.fa72b39y2m99
