### ISSUE TITLE
Namespace Airbyte metadata columns

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#966]
## Tell us about the problem you're trying to solve
* Airbyte injects various metadata columns into my data.

## Describe the solution you’d like
* The names are not consistent and sometimes it is hard to tell what is my data and what is airbyte metadata.

**Comment by ChristopheDuong** [comment]
Indeed, this would be helpful!

In Fivetran, `fivetran_` prefix is used:
https://fivetran.com/docs/getting-started/system-columns-and-tables

In Stitch, `_sdc_` prefix is used:
https://www.stitchdata.com/docs/data-structure/system-tables-and-columns

**Comment by ChristopheDuong** [comment]
While testing replications from different schemas from a jdbc source:
- I used the new multiple destination feature to replicate data from a source-file to a destination-postgres in a specific schema.
- I built another pipeline to replicate data from that schema  with source-postgres to a destination-bigquery

Unfortunately, normalization process in the second sync failed because of ambiguous columns (metadata columns) that were created from the first sync...

We should namespace airbyte metadata columns and handle them properly in the normalization too

**Comment by cgardens** [comment]
If we are going to do this, we might really want to do it before the hard launch because this will be painful to migrate.
