### ISSUE TITLE
Do not run normalization if no records are committed or pending records from a previous partial  sync

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#9672]
## Tell us about the problem you're trying to solve
Now that we have access to the number of records actually [committed to the destination](https://github.com/airbytehq/airbyte/issues/3247), we can be smarter about when run normalization. Our logic so far has been always run normalization, because even if replication failed, we should normalize whatever data that we can. This is wasteful if there's nothing to normalize. 

## Describe the solution you’d like
Now we can skip running normalization if the following condition if no records were committed to the source or destination.

There is one more case that we need to handle before we implement this. If in the previous replication job, records _were_ synced but normalization failed, we likely still want to run normalization on the next run, even if no records are synced. I'm not sure a) if this is the behavior we want or a slightly different behavior and b) if this is the right behavior how we would do it sensibly.

@pmossman for visibilty, since this feature is unlocked by your change.

### Acceptance Criteria
- Normalization is skipped when it is known that no records were committed
- Normalization is never skipped when it should have run (edge case around failed normalization from a previous job)

**Comment by tq-tien** [comment]
I got the same issue. We are using "full refresh | overwrite" sync mode, and every time Airbyte cannot connect to source database, normalization still run, clear all table data. Hope this change will occur asap.

**Comment by cgardens** [comment]
Split out @tq-tien's comment into a separate issue: https://github.com/airbytehq/airbyte/issues/12782

**Comment by grishick** [comment]
Feedback from a customer that I heard today is that they have several dozen tables in a CDC connection. When the sync produces zero records, the job still takes 30 minutes. Some of that time is attributed to Debezium timeout (5 minutes), but I suspect the bulk of the time is normalization.

**Comment by evantahler** [comment]
Closing https://github.com/airbytehq/airbyte/issues/13807 in favor of this story, and updating the title to reflect the edge case

**Comment by mid** [comment]
I have the same issue. 0 bytes synced, but ~11 minutes spent on building dbt incremental models.

**Comment by evantahler** [comment]
To complete this story, we may need to add additional information to the attempts or jobs table to record if normalization ran.  We do already store how many records were moved in the StandardSyncSummary.  We can also retrieve if normalization run from Temporal, but that data isn't guaranteed to persist, while data in the DB does as long as the sync is active.

**Comment by cgardens** [comment]
I'm trying to think through what info we need here. 

Goal: We attempt to run normalization anytime there is data in the raw table that has not yet been normalized. 
Note: This is regardless of whether that data happened in the current sync or some past sync.

In order to make that guarantee, I think we need the following piece of information for _each attempt_:
* Total number of records _committed_.
* Did normalization run successfully.

Given those pieces of information we can in force the invariant described in the goal. The logic would be run normalization if a non-zero number of records have been committed since the last time normalization was run successfully.

pseudocode
```
attempts = fetch all attempts for a connection in descending order by time until you find one where normalization succeeded == true.

// sum is total number of committed records since last successful normalization run
sum = attempts.map(Attempt::getNumCommittedRecords).sum();

if(sum > 0) {
  runNormalization();
}
```

Anyone want to sanity check this approach? Or suggest something that might be easier?

**Comment by evantahler** [comment]
Notes from grooming:
* it would be more accurate just to COUNT * from _airbyte_raw_* to determine if we need to normalize.  Why can't we just read from the destination?
  * The act of normalization requires READ and WRITE Access... so... we can probably read?
  * Normalization itself should start with a COUNT and then determine if there's something to do.
  * we probably can't rely on the COUNT method because we keep _raw* tables and data round from previous successful runs --> DOESN'T WORK

* do we want to store just that normalization ran, or do we want to more robustly store each step of the sync and some status about it (ran, times, etc)

Add normalization stats to syncStats blob.  
* But that's hard to query if the data is in JSON if the data isn't normalized... is this our excuse to normalize agree. 
* We only need to consider the attempts since the most recent success attempt (or limit to the most recent 1000) 

---
internals of normalization

1) READ -> _airbyte_raw_tables
2) NORMALIZE -> dbt things (include normalize / dedupe phases)
  _airbyte_raw_users (keep)
  users (drop, and recreate each time)
---

**Comment by salima-airbyte** [comment]
There is a separate normalization worker. AB **raw tables are never deleted**.  (per Evan's discussion w. Charles)
Need to add column that indicates normalization has ran. Use timestamp as column type.

**Comment by alovew** [comment]
Some notes as I'm thinking about this:

- the recordsCommitted field is not reliable. Don't currently have stats on how often it is not populated, but a null value does not mean that no records were committed.
- do we populate recordsCommitted with 0 when there is not an unreliable committed count and there are actually no records committed? or is this field null? If it is null, we should change this to record 0, so we can distinguish between an unknown # of records committed and a known 0 records committed. 
- In the case where records committed is null (i.e. the number is unreliable, and so is unknown), we should default to running normalization.

**Comment by evantahler** [comment]
If `recordsCommitted` is unknown, it makes sense to do the safer thing and normalize 👍.  But... why is `recordsCommitted` unreliable?  Does "committed" mean ACKed by the destination, and we are lacking a `recordsEmitted` perhaps?

**Comment by alovew** [comment]
recordsCommitted can be unreliable because in order to keep track of records committed, we are accumulating state messages in order to match destination state messages to source state messages (see `StateDeltaTracker.java`) and this has a memory limit. If we hit that memory limit, we stop being able to track how many records have been committed.
