### ISSUE TITLE
Prefix table names in destinations with the source name

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#973]
## Tell us about the problem you're trying to solve
If I'm sync'ing the `User` stream from salesforce and the `User` stream from stripe into the same dataset in bigquery, they may overwrite each other. To get around this, I'd like for Airbyte to namespace my streams in the destination based on the source they came from.

**Comment by ChristopheDuong** [comment]
Instead of having all sources tables written to the same schema (using prefix to differentiate), what do you think about having one schema per source?

It would allow easier switching between vendors too...

If i have a replication process using vendor A and switch to vendor B, i just need to change the schema of my tables in my downstream transformation process and everything should still work the same. 
Instead of having to change every table names because Airbyte chose to rename my source tables (when others providers only change the schema but keep the same table names)

**Comment by cgardens** [comment]
In each of these cases how would the be supported in the warehouses we support (and want to support)? What would be the limitations.

**Prepending Source Name**
What are relevant table names lengths?

**Using Different Schemas**
Do all of the warehouses we use support multiple schemas within a database? (BQ comes to mind as one I'm not sure about. Within the dataset abstraction, I'm not aware of multi-schema supports. But I could definitely be wrong).

**Comment by cgardens** [comment]
How common is using separate schemas for this use case @ChristopheDuong? I have never used schemas for this type of use case. But that doesn't mean it's not commonly done.

**Comment by ChristopheDuong** [comment]
> In each of these cases how would the be supported in the warehouses we support (and want to support)? What would be the limitations.
> 
> **Prepending Source Name**
> What are relevant table names lengths?
> 
> **Using Different Schemas**
> Do all of the warehouses we use support multiple schemas within a database? (BQ comes to mind as one I'm not sure about. Within the dataset abstraction, I'm not aware of multi-schema supports. But I could definitely be wrong).

In BigQuery, you have:
- Projects
- Datasets
- Tables

In other databases/warehouses, you have:
- Database
- Schemas
- Tables

So Datasets from BigQuery are equivalent to Schemas in Snowflake/Redshift.
It is for example noted like that here:
https://docs.getdbt.com/reference/resource-configs/schema/#warehouse-specific-information

**Comment by ChristopheDuong** [comment]
> How common is using separate schemas for this use case @ChristopheDuong? I have never used schemas for this type of use case. But that doesn't mean it's not commonly done.

I had a use case for example where we had a Hubspot instance for dev and one for prod (same for other sources too)
We would replicate both to our data warehouse and each would get its own schema hubspot_dev and hubspot_prod

Our DBT transformation was run on all tables from both schemas so that we could validate changes made to configurations of entities in hubspot before applying them to the prod version.
Switching from dev to prod data sources with DBT was effortless as it was just about changing the schema name (not the table names)

Fivetran: `the schema name becomes the name of your connector and must be unique because each connector name must be unique.`
https://fivetran.com/docs/getting-started/core-concepts#namingconventions
Stitch: `For each integration that you add to Stitch, a schema specific to that integration will be created in your data warehouse. The integration’s schema is where all the data Stitch replicates from the data source will be stored.`
https://www.stitchdata.com/docs/data-structure/integration-schemas

**Comment by ChristopheDuong** [comment]
Gitlab docs also describes this usage:

> These raw tables are referred to as source tables or raw tables. They are typically stored in a schema that indicates its original data source, e.g. netsuite
> - Zuora data stored in raw.zuora
> - GitLab.com data with tables stored in raw.tap_postgres.gitlab_db_*
> - Customers.gitlab.com data with tables stored in raw.tap_postgres.customers_db_*
https://about.gitlab.com/handbook/business-ops/data-team/platform/dbt-guide/#sources

**Comment by cgardens** [comment]
This is done, right @ChristopheDuong  going to close. reopen if i am wrong.

**Comment by ChristopheDuong** [comment]
No this is not done and could still be an issue but if we could work on this related issue, it would fix it: https://github.com/airbytehq/airbyte/issues/1119

we don't need to reopen this one if we are going to treat it in #1119
