### ISSUE TITLE
Source Facebook Marketing: add new fields

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#9836]
## Tell us about the problem you're trying to solve

Requested by Adriel from Cart.com

Add new fields to **ads_insights** stream:
- landing pagesviews
- website url
- url parameters
- customer conversions
- website leads

## Describe the solution you’d like
Add the fields to improve reports details.

## Describe the alternative you’ve considered or used
None

## Additional context
None

## Are you willing to submit a PR?
No

**Comment by lazebnyi** [comment]
On hold
Waiting for clarification from @misteryeo and @marcosmarxm

**Comment by marcosmarxm** [comment]
sorry @lazebnyi @misteryeo updated the stream name.

**Comment by misteryeo** [comment]
@lazebnyi leaving this with you

**Comment by marcosmarxm** [comment]
@lazebnyi do you need any additional info from me here?

**Comment by misteryeo** [comment]
This has been deprioritized until we see more requests from users.

**Comment by midavadim** [comment]
We already support insights streams with a lot of attributes.

I close this issue because the mentioned attributes are not present in insights streams.

https://developers.facebook.com/docs/marketing-api/insights

https://developers.facebook.com/docs/marketing-api/reference/adgroup/insights/
https://developers.facebook.com/docs/marketing-api/reference/ad-account/insights
