### ISSUE TITLE
Source Google Ads: not possible edit config connector already created

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#9886]
## Environment
- **Airbyte version**:  0.35.12-alpha
- **OS Version / Instance**: macOS
- **Deployment**: Docker
- **Source Connector and version**: Google Ads 0.1.23
- **Destination Connector and version**: NA
- **Severity**: Very Low / Low / **Medium** / High / Critical
- **Step where error happened**: Edit connector already created

## Current Behavior
After creating a Google Ads connector I can't edit the config.
![image](https://user-images.githubusercontent.com/5154322/151632417-c7ac819c-96f6-442a-b7ce-205444701fd4.png)

## Expected Behavior
*Tell us what should happen.*

## Logs
```
{
    "status": "failed",
    "message": "RefreshError('invalid_client: Unauthorized', {'error': 'invalid_client', 'error_description': 'Unauthorized'})",
    "jobInfo": {
        "id": "f4c415a6-f3ed-4094-bd4e-a2b03914fe7c",
        "configType": "check_connection_source",
        "configId": "Optional[253487c0-2246-43ba-a21f-5116b20a2c50]",
        "createdAt": 1643409954527,
        "endedAt": 1643409956226,
        "succeeded": true,
        "logs": {
            "logLines": [
                "2022-01-28 22:45:54 \u001B[32mINFO\u001B[m i.a.w.t.TemporalAttemptExecution(get):115 - Docker volume job log path: /tmp/workspace/394df574-5b6f-4412-b98f-787e1890b3ba/0/logs.log",
                "2022-01-28 22:45:54 \u001B[32mINFO\u001B[m i.a.w.t.TemporalAttemptExecution(get):120 - Executing worker wrapper. Airbyte version: 0.35.12-alpha",
                "2022-01-28 22:45:54 \u001B[32mINFO\u001B[m i.a.c.i.LineGobbler(voidCall):82 - Checking if airbyte/source-google-ads:0.1.23 exists...",
                "2022-01-28 22:45:54 \u001B[32mINFO\u001B[m i.a.c.i.LineGobbler(voidCall):82 - airbyte/source-google-ads:0.1.23 was found locally.",
                "2022-01-28 22:45:54 \u001B[32mINFO\u001B[m i.a.w.p.DockerProcessFactory(create):157 - Preparing command: docker run --rm --init -i -w /data/394df574-5b6f-4412-b98f-787e1890b3ba/0 --log-driver none --network host -v airbyte_workspace:/data -v /tmp/airbyte_local:/local airbyte/source-google-ads:0.1.23 check --config source_config.json",
                "2022-01-28 22:45:55 \u001B[32mINFO\u001B[m i.a.w.p.a.DefaultAirbyteStreamFactory(internalLog):97 - Checking the config",
                "2022-01-28 22:45:55 \u001B[1;31mERROR\u001B[m i.a.w.p.a.DefaultAirbyteStreamFactory(internalLog):95 - Check failed",
                "2022-01-28 22:45:56 \u001B[32mINFO\u001B[m i.a.w.t.TemporalAttemptExecution(get):141 - Stopping cancellation check scheduling..."
            ]
        }
    }
}
```

## Steps to Reproduce
1. create Google Ads connector using Integration Account credentials
2. try to edit the start date
3. boom

**Comment by r-rob** [comment]
I noticed this issue as well and found that re-entering all of the secrets is required in order to retest or save.

**Comment by sherifnada** [comment]
@edgao this strikes me as a UI or backend server error. It is probably wise to ask @timroes and/or someone on platform for pointers if needed

**Comment by edgao** [comment]
update: When I stuffed the `credentials` entry in the source-google-ads spec inside a `oneOf`, I was able to run airbyte locally and update the connector without needing to reenter all the secrets. The diff:
![Screen Shot 2022-03-04 at 4 05 50 PM](https://user-images.githubusercontent.com/5741425/156858351-ed9f7a39-2191-4f0f-a571-55079bc11417.png)

This is because `JsonSecretsProcessor#copySecrets` only handles nested objects when their schema is a `oneOf`/`allOf`/`anyOf`. If there's a bare object inside another object, it won't even try to resolve secrets in the nested object.

A root cause fix is being tracked in https://github.com/airbytehq/airbyte/issues/6393, but I'll try to implement slightly better handling for now.

---

The super quick and dirty fix would be to just use the oneOf, but (a) it looks weird (because the UI shows a dropdown with only one option) and (b) I don't think it's a huuuge lift to support non-oneOf objects.
