### ISSUE TITLE
Add connectionId as an Intercom custom attribute

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#9936]
## Tell us about the problem you're trying to solve
I would like to use Intercom to launch a [product tour](https://www.loom.com/share/3c29aaa5a4714f4c822994f6410fb8db) on the connection settings page in Airbyte Cloud.  Intercom requires a specific page URL rule that the product tour can be seen on. Because we place the connection_id in the URL of the connection settings (e.g. https://cloud.airbyte.io/workspaces/bed3b473-1518-4461-a37f-730ea3d3a848/connections/2fc0c3d9-b479-4597-aa70-bbd776a378e8), we cannot show the product tour unless we add the connectionId as a custom attribute. 

## Describe the solution you’d like
Add the connectionId as an Intercom custom attribute.

A similar PR was pushed to send the workspace Id to Intercom as a custom attribute: https://github.com/airbytehq/airbyte/pull/9489

**Comment by timroes** [comment]
@nataliekwong If the tour should just show automatically on the connections setting page, I don't think you'll need the `connectionid` as a user parameter. You should be able to tell it to just appear on URLs that have `/connections/` in it and end on `/settings`, like the following:

![screenshot-20220201-165258](https://user-images.githubusercontent.com/877229/152002776-113dc075-e051-4f6d-b088-d312e1d4d16b.png)

I think you'd only need the parameter if you'd actually want to send people to this tour while they are on another page (i.e. the "User tour everywhere" setting). I am not sure if that's actually what you want to do, since it would also bring up the question, to which connection should the user be lead in this case?

Please let me know if the above solution might already solve what you were trying to do. If not, we'll need to figure out which connection id we should push to Intercom, since we'll only have one, once the user is anyway on the connections page (i.e. the "Use tour everywhere", would anyway just work while being on the connection page :thinking: )

**Comment by nataliekwong** [comment]
Oh, I didn't realize that would work instead of using the the URL! You're
right, I just tested it with the settings you set up above, and it shows up
for me successfully. I think this should work and we can close this. Thanks
for the tip!

**Comment by nataliekwong** [comment]
Hey @timroes , no users have been able to see the product tour since it launched two weeks ago. I thought it was due to low activations, but realized the onboarding flow does not fit the URL strings defined in the filtering logic, since it's a generic URL like this: https://cloud.airbyte.io/workspaces/{{workspace id}}/onboarding. This only happens if the user is going through the onboarding flow.

An example screenshot: 
<img width="965" alt="Screen Shot 2022-02-17 at 8 50 08 PM" src="https://user-images.githubusercontent.com/38087517/154560127-2765c4fd-19e8-42f1-8f34-259f47638ac3.png">

Since the entire onboarding flow is on the same URL (from source setup, destination setup, to connection settings), I don't believe Intercom can use URL rules to define when it is shown.  Instead of a URL rule, they also offer an event-based rule, which triggers the product tour to show up when it receives an event. In this case, could we use a frontend Segment event to trigger the product tour? 

Very open to other ideas!

**Comment by timroes** [comment]
I played around with this today. And as soon as we enable GTM (via Segment) we can actually trigger that tour via GTM even without needing a custom event triggered from the code (into Segment/Intercom).

Drop me a message in Slack whenever your available, I am happy to get this up and running with you.
