### ISSUE TITLE
Support Manual Refresh of Catalog

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#996]
## Tell us about the problem you're trying to solve
* Once the catalog has been discovered the first time, it is never discovered again. This means Airbyte can never detect changes in the source.

## Describe the solution you’d like
* At any time a new catalog can be fetched from the source and a new selection from that catalog can be made.
* If this process is done and there is a change in the catalog at all, a full refresh is required.

**Comment by sherifnada** [comment]
## Definitions
**Catalog expansion**: a new stream is added to the catalog, or a new field in an existing stream is added (or both). 
**Catalog contraction**: an existing stream is removed from the catalog, or an existing field in an existing stream is removed (or both).
**Catalog amendment**: an existing stream has been renamed, or an existing field has been either renamed or its type has changed. 

**Discovered Catalog Refresh**:   A process which runs discovery then performs one of the following actions: 
* If the catalog was amended: move the connection to a new state `DEFUNCT_CATALOG_AMENDED` in the backend. Connections whose source is in this state do not sync data. 
* If the catalog has expanded/contracted and not amended, we update the source's catalog selection by adding any new streams/fields without selecting them. If any streams/fields were removed by the contraction, remove them from the catalog (even if they were selected). 

## Scope
Catalog amendment is out of scope for this issue. The currently supported recourse for an amendment is to recreate the source and perform a full refresh sync. 

## Acceptance criteria
* document that expansion & contraction can be remedied on an existing source, but amendment requires a full refresh from a new source. 
* Add a method in the scheduler `refresh_discovered_catalog` which preforms Discovered Catalog Refresh. 
* Before running any sync in the scheduler, perform Discovered Catalog Refresh. 
* Change scheduler so that `DEFUNCT_CATALOG_AMENDED` connections do not sync data. 
* In the UI, if a connection is in `DEFUNCT_CATALOG_AMENDED` show it as greyed out in the UI. When the user clicks through to the connection display a message like "Airbyte can not sync data for this connection because its schema has changed in a backwards incompatible way. Please create a new connection to sync your data. See more information on the [docs](https://www.youtube.com/watch?v=dQw4w9WgXcQ)" 

I'll create separate issues for this once we're happy with the direction. 

## Future considerations
points in this section should have issues created for them but are not required to close this issue. 
* The ideal solution here is to run Discovered catalog refresh before every sync. The problem is that this creates a circular dependency between the server and the scheduler. For scheduled syncs, the scheduler would find a sync to run
* Technically speaking, if all selected streams are full refresh, the connection shouldn't go to a `DEFUNCT_CATALOG_AMENDED` state since they always overwrite data in the destination. But we do this for simplicity.

**Comment by sherifnada** [comment]
We're going to punt this out of the v0.6 milestone to minimize delivery risk. Will replace with a bugfix on the UI that prevents connections from getting into this state. 

@cgardens could you create an issue to describe the problem to Artem?

**Comment by cgardens** [comment]
yessir!

**Comment by cgardens** [comment]
now duplicate of https://github.com/airbytehq/airbyte/issues/1401
